import type { QuarterlyPropertyNavItem, QuarterlyQualityGateView } from "./types";

const completionLabels = { "required-incomplete": "Povinné údaje neúplné", "editorial-sparse": "Volitelný obsah je řídký", complete: "Kompletní" } as const;

export function QuarterlyReportReviewExport({ status, admin, properties, quality, warningsAcknowledged, transitionAction, groupId, reportId, publishedAssetId, persistentStorageAvailable }: { status: string; admin: boolean; properties: QuarterlyPropertyNavItem[]; quality: QuarterlyQualityGateView; warningsAcknowledged: boolean; transitionAction: string; groupId: string; reportId: string; publishedAssetId: string | null; persistentStorageAvailable: boolean }) {
  return <div className="quarterly-workspace-content"><div className="card"><span className="quarterly-eyebrow">Finální interní kontrola dávky</span><h2>Kontrola a export</h2><p className="muted-copy">Každá nemovitost představuje samostatně připravovaný kvartální report. Současné PDF akce dočasně zachovávají stávající společnou architekturu; budoucí náhled a export budou umístěny u konkrétní nemovitosti.</p></div>
    <div className="card"><h2>Úplnost nemovitostí</h2><div className="quarterly-completion-list">{properties.map((property) => <div key={property.propertyId}><div><strong>{property.propertyName}</strong><small>{completionLabels[property.completion]}</small></div><span>{property.warningCount > 0 && `WARNING ${property.warningCount} `}{property.blockerCount > 0 && `BLOCKER ${property.blockerCount}`}</span></div>)}</div><p className="muted-copy">Řídký volitelný obsah je pouze redakční informace a nezavádí nový publikační blokátor.</p></div>
    <div className="card"><h2>Datová kvalita</h2><p><strong>INFO {quality.infoCount} · WARNING {quality.warningCount} · BLOCKER {quality.blockerCount}</strong></p>{quality.invalidQualityCount > 0 && <p className="muted-copy">U {quality.invalidQualityCount} snapshotů se metadata kvality nepodařilo ověřit; publikace je blokována.</p>}{quality.issues.length ? <ul className="quarterly-quality-list">{quality.issues.map((issue, index) => <li className={issue.severity} key={`${issue.code}-${issue.propertyId || "all"}-${index}`}><strong>{issue.severity}</strong><span>{properties.find((property) => property.propertyId === issue.propertyId)?.propertyName || "Report"}</span><p>{issue.message}</p></li>)}</ul> : quality.invalidQualityCount === 0 && <p className="muted-copy">Bez problémů kvality dat.</p>}
      {status === "REVIEW" && quality.warningCount > 0 && <p className="muted-copy">{warningsAcknowledged ? "Warningy byly potvrzeny pro aktuální kontrolní cyklus." : "Warningy musí před publikací potvrdit administrátor."}</p>}
      {status === "REVIEW" && admin && quality.blockerCount === 0 && quality.warningCount > 0 && !warningsAcknowledged && <form action={transitionAction} method="post"><button className="secondary" name="action" value="acknowledge-warnings">Potvrdit warningy</button></form>}
    </div>
    <div className="card quarterly-workflow-actions"><h2>Lifecycle a export</h2>{status === "DRAFT" && <form action={transitionAction} method="post"><button className="primary" name="action" value="submit-review">Odeslat ke kontrole</button></form>}{status === "REVIEW" && admin && <><form action={transitionAction} method="post"><button className="secondary" name="action" value="return-draft">Vrátit do konceptu</button></form>{quality.blockerCount === 0 && warningsAcknowledged && <form action={transitionAction} method="post"><button className="primary" name="action" value="publish">Publikovat</button></form>}</>}
      {status === "PUBLISHED" && <div className="quarterly-published-actions"><a className="button secondary" href={`/api/reporting-groups/${groupId}/quarterly-reports/${reportId}/assets/preview`}>Stáhnout náhled PDF</a>{publishedAssetId ? <a className="button secondary" href={`/api/reporting-groups/${groupId}/quarterly-reports/${reportId}/assets/download`}>Stáhnout PDF</a> : admin && persistentStorageAvailable ? <form action={`/api/reporting-groups/${groupId}/quarterly-reports/${reportId}/assets/generate`} method="post"><button className="primary" type="submit">Vygenerovat PDF</button></form> : admin ? <p className="muted-copy">Trvalé úložiště souborů není nakonfigurováno. Pro kontrolu vzhledu použijte náhled PDF.</p> : <p className="muted-copy">PDF zatím nebylo vygenerováno.</p>}<form action={transitionAction} method="post"><button className="secondary" name="action" value="create-correction">Vytvořit opravnou revizi</button></form></div>}
    </div>
  </div>;
}
