import {DistributionOpportunityStage} from "@prisma/client";
import {canSeeAll} from "@/lib/auth";
import {prisma} from "@/lib/db";

export const distributionOpportunityStages:Record<DistributionOpportunityStage,string>={NEW:"Nový",CONTACTED:"Kontaktován",QUALIFIED:"Kvalifikován",VIEWING:"Prohlídka",OFFER:"Nabídka",RESERVED:"Rezervace",WON:"Uzavřeno",LOST:"Ztraceno"};
type Actor={id:string;role:string;allProperties?:boolean};
function assertInternal(actor:Actor){if(!canSeeAll(actor.role))throw new Error("Distribuční CRM je dostupné pouze interním správcům FlatCloud.")}
function validPrice(value:number|null){return value==null||(Number.isSafeInteger(value)&&value>0)}
export async function createDistributionProspect(actor:Actor,input:{name:string;email?:string|null;phone?:string|null;source?:string|null;note?:string|null}){assertInternal(actor);if(input.name.trim().length<2)throw new Error("Doplňte jméno zájemce.");if(!input.email&&!input.phone)throw new Error("Doplňte alespoň e-mail nebo telefon zájemce.");return prisma.$transaction(async(tx)=>{const prospect=await tx.distributionProspect.create({data:{name:input.name.trim(),email:input.email||null,phone:input.phone||null,source:input.source||null,note:input.note||null,createdById:actor.id}});await tx.auditLog.create({data:{userId:actor.id,action:"DISTRIBUTION_PROSPECT_CREATED",entityType:"DistributionProspect",entityId:prospect.id,details:{name:prospect.name,source:prospect.source,hasEmail:Boolean(prospect.email),hasPhone:Boolean(prospect.phone)}}});return prospect})}
export async function createDistributionOpportunity(actor:Actor,input:{prospectId:string;unitId:string;stage:DistributionOpportunityStage;askingPriceCents:number|null;offeredPriceCents:number|null;nextActionAt:Date|null;note?:string|null}){assertInternal(actor);if(!Object.values(DistributionOpportunityStage).includes(input.stage))throw new Error("Vyberte platnou fázi příležitosti.");if(!validPrice(input.askingPriceCents)||!validPrice(input.offeredPriceCents))throw new Error("Cena musí být vyšší než nula.");return prisma.$transaction(async(tx)=>{const[prospect,unit]=await Promise.all([tx.distributionProspect.findFirst({where:{id:input.prospectId,active:true},select:{id:true}}),tx.unit.findFirst({where:{id:input.unitId,property:{active:true,flatcloudConsolidationBasisPoints:{gt:0}}},select:{id:true,propertyId:true}})]);if(!prospect)throw new Error("Aktivní zájemce nebyl nalezen.");if(!unit)throw new Error("Jednotka není součástí potvrzeného aktiva FlatCloud.");const opportunity=await tx.distributionOpportunity.create({data:{...input,askingPriceCents:input.askingPriceCents==null?null:BigInt(input.askingPriceCents),offeredPriceCents:input.offeredPriceCents==null?null:BigInt(input.offeredPriceCents),note:input.note||null,createdById:actor.id}});await tx.auditLog.create({data:{userId:actor.id,propertyId:unit.propertyId,action:"DISTRIBUTION_OPPORTUNITY_CREATED",entityType:"DistributionOpportunity",entityId:opportunity.id,details:{prospectId:input.prospectId,unitId:input.unitId,stage:input.stage,askingPriceCents:input.askingPriceCents,offeredPriceCents:input.offeredPriceCents,nextActionAt:input.nextActionAt?.toISOString()||null}}});return opportunity})}
export async function updateDistributionOpportunity(actor:Actor,id:string,input:{stage:DistributionOpportunityStage;askingPriceCents:number|null;offeredPriceCents:number|null;nextActionAt:Date|null;note?:string|null}){assertInternal(actor);if(!Object.values(DistributionOpportunityStage).includes(input.stage))throw new Error("Vyberte platnou fázi příležitosti.");if(!validPrice(input.askingPriceCents)||!validPrice(input.offeredPriceCents))throw new Error("Cena musí být vyšší než nula.");return prisma.$transaction(async(tx)=>{const current=await tx.distributionOpportunity.findFirst({where:{id,unit:{property:{active:true,flatcloudConsolidationBasisPoints:{gt:0}}}},select:{id:true,stage:true,askingPriceCents:true,offeredPriceCents:true,nextActionAt:true,note:true,unit:{select:{propertyId:true}}}});if(!current)throw new Error("Příležitost nebyla nalezena v interním rozsahu FlatCloud.");const updated=await tx.distributionOpportunity.update({where:{id},data:{stage:input.stage,askingPriceCents:input.askingPriceCents==null?null:BigInt(input.askingPriceCents),offeredPriceCents:input.offeredPriceCents==null?null:BigInt(input.offeredPriceCents),nextActionAt:input.nextActionAt,note:input.note||null}});await tx.auditLog.create({data:{userId:actor.id,propertyId:current.unit.propertyId,action:"DISTRIBUTION_OPPORTUNITY_UPDATED",entityType:"DistributionOpportunity",entityId:id,details:{before:{stage:current.stage,askingPriceCents:current.askingPriceCents?.toString()||null,offeredPriceCents:current.offeredPriceCents?.toString()||null,nextActionAt:current.nextActionAt?.toISOString()||null},after:{stage:input.stage,askingPriceCents:input.askingPriceCents,offeredPriceCents:input.offeredPriceCents,nextActionAt:input.nextActionAt?.toISOString()||null}}}});return updated})}
