import {canSeeAll} from "@/lib/auth";
import {businessDateEndInstant,businessDateKeyToInstant,type BusinessDateKey} from "@/lib/calendar";
import {prisma} from "@/lib/db";
import {distributionOpportunityStages} from "@/lib/distribution/crm";

export function parseDistributionReportPeriod(value:string|undefined,now=new Date()){const fallback=`${now.getUTCFullYear()}-Q${Math.floor(now.getUTCMonth()/3)+1}`;const period=value&&/^\d{4}(?:-Q[1-4])?$/.test(value)?value:fallback;const year=Number(period.slice(0,4)),quarter=period.includes("-Q")?Number(period.at(-1)):null,startMonth=quarter?(quarter-1)*3+1:1,endMonth=quarter?quarter*3:12;const pad=(n:number)=>String(n).padStart(2,"0"),lastDay=new Date(Date.UTC(year,endMonth,0)).getUTCDate(),fromKey=`${year}-${pad(startMonth)}-01` as BusinessDateKey,toKey=`${year}-${pad(endMonth)}-${pad(lastDay)}` as BusinessDateKey;return {key:period,label:quarter?`Q${quarter} ${year}`:`Rok ${year}`,year,quarter,from:businessDateKeyToInstant(fromKey),to:businessDateEndInstant(toKey)}}
export async function loadDistributionReport(actor:{id:string;role:string;allProperties?:boolean},periodValue?:string){if(!canSeeAll(actor.role))throw new Error("Distribuční reporting je dostupný pouze interním správcům FlatCloud.");const period=parseDistributionReportPeriod(periodValue),properties=await prisma.property.findMany({where:{active:true,flatcloudConsolidationBasisPoints:{gt:0}},select:{id:true,name:true,units:{select:{id:true,assetAssessments:{orderBy:[{assessedAt:"desc"},{createdAt:"desc"}],take:1},valuationSnapshots:{orderBy:[{valuationDate:"desc"},{createdAt:"desc"}],take:1},distributionOpportunities:{select:{id:true,stage:true,askingPriceCents:true,offeredPriceCents:true,createdAt:true,updatedAt:true}}}}},orderBy:{name:"asc"}}),stageEntries=Object.entries(distributionOpportunityStages);
  const rows=properties.map((property)=>{const assessments=property.units.map((unit)=>unit.assetAssessments[0]).filter(Boolean),valuations=property.units.map((unit)=>unit.valuationSnapshots[0]).filter(Boolean),opportunities=property.units.flatMap((unit)=>unit.distributionOpportunities),activity=opportunities.filter((item)=>item.createdAt>=period.from&&item.createdAt<=period.to),stageCounts=Object.fromEntries(stageEntries.map(([stage])=>[stage,opportunities.filter((item)=>item.stage===stage).length]));return {propertyId:property.id,propertyName:property.name,unitCount:property.units.length,assessedCount:assessments.length,valuedCount:valuations.length,readyCount:assessments.filter((item)=>item.distributionReady).length,urgentCount:assessments.filter((item)=>item.investmentUrgency==="IMMEDIATE").length,estimatedCapexCents:assessments.reduce((sum,item)=>sum+item.estimatedCapexCents,0),marketValueCents:valuations.reduce((sum,item)=>sum+Number(item.marketValueCents),0),openOpportunityCount:opportunities.filter((item)=>!['WON','LOST'].includes(item.stage)).length,newOpportunityCount:activity.length,offeredValueCents:opportunities.filter((item)=>item.stage==="OFFER"||item.stage==="RESERVED").reduce((sum,item)=>sum+Number(item.offeredPriceCents||0),0),stageCounts,issues:property.units.flatMap((unit)=>[...(!unit.assetAssessments.length?["Chybí rating"]:[]),...(!unit.valuationSnapshots.length?["Chybí valuace"]:[]),...(unit.assetAssessments[0]?.distributionReady&&!unit.valuationSnapshots.length?["Připraveno bez valuace"]:[])])}});
  const totals={unitCount:rows.reduce((sum,row)=>sum+row.unitCount,0),assessedCount:rows.reduce((sum,row)=>sum+row.assessedCount,0),valuedCount:rows.reduce((sum,row)=>sum+row.valuedCount,0),readyCount:rows.reduce((sum,row)=>sum+row.readyCount,0),urgentCount:rows.reduce((sum,row)=>sum+row.urgentCount,0),estimatedCapexCents:rows.reduce((sum,row)=>sum+row.estimatedCapexCents,0),marketValueCents:rows.reduce((sum,row)=>sum+row.marketValueCents,0),openOpportunityCount:rows.reduce((sum,row)=>sum+row.openOpportunityCount,0),newOpportunityCount:rows.reduce((sum,row)=>sum+row.newOpportunityCount,0),offeredValueCents:rows.reduce((sum,row)=>sum+row.offeredValueCents,0),stageCounts:Object.fromEntries(stageEntries.map(([stage])=>[stage,rows.reduce((sum,row)=>sum+(row.stageCounts[stage]||0),0)])),issueCount:rows.reduce((sum,row)=>sum+row.issues.length,0)};
  return {period,rows,totals,generatedAt:new Date(),scopeLabel:"Potvrzená aktiva FlatCloud · LIVE stav",stageLabels:distributionOpportunityStages};
}
