import type { DocumentCategory, DocumentPhotoStage } from "@prisma/client";
import { hasAllPropertyAccess } from "../auth";
import { prisma } from "../db";
import { createFileStorage } from "../storage";
import type { FileStorage } from "../storage/types";
import { requireDocumentEditAccess } from "./access";
import { randomStorageKey, validateFile } from "./file-validation";
import { createImageVariants } from "./image-processing";
type Actor = { id: string; role: string; allProperties?: boolean };
export type DocumentContext = { propertyId: string; unitId?: string; leaseId?: string; taskId?: string; taskEntryId?: string; complianceRecordId?: string };
export type ResolvedDocumentContext = { unit?: { propertyId: string } | null; lease?: { unitId: string; unit: { propertyId: string } } | null; task?: { id: string; propertyId: string; unitId: string | null; leaseId: string | null; lease: { unitId: string } | null } | null; entry?: { taskId: string; task: { id: string; propertyId: string; unitId: string | null; leaseId: string | null; lease: { unitId: string } | null } } | null; record?: { complianceItem: { propertyId: string } } | null };
function taskUnitId(task: NonNullable<ResolvedDocumentContext["task"]>) { return task.unitId || task.lease?.unitId || null; }
export function assertDocumentContextConsistency(context: DocumentContext, resolved: ResolvedDocumentContext) { if ((context.unitId && !resolved.unit) || (context.leaseId && !resolved.lease) || (context.taskId && !resolved.task) || (context.taskEntryId && !resolved.entry) || (context.complianceRecordId && !resolved.record)) throw new Error("Document context entity was not found."); const properties = [resolved.unit?.propertyId, resolved.lease?.unit.propertyId, resolved.task?.propertyId, resolved.entry?.task.propertyId, resolved.record?.complianceItem.propertyId].filter(Boolean); if (properties.some((propertyId) => propertyId !== context.propertyId)) throw new Error("Document context does not belong to the selected property."); if (context.unitId && resolved.lease && resolved.lease.unitId !== context.unitId) throw new Error("Document lease does not belong to the selected unit."); if (context.taskId && resolved.entry && resolved.entry.taskId !== context.taskId) throw new Error("Document task entry does not belong to the selected task."); const tasks = [resolved.task, resolved.entry?.task].filter(Boolean) as NonNullable<ResolvedDocumentContext["task"]>[]; for (const task of tasks) { const linkedUnitId = taskUnitId(task); if (context.leaseId && task.leaseId && task.leaseId !== context.leaseId) throw new Error("Document task does not belong to the selected lease."); if (context.unitId && linkedUnitId && linkedUnitId !== context.unitId) throw new Error("Document task does not belong to the selected unit."); if (resolved.lease && linkedUnitId && resolved.lease.unitId !== linkedUnitId) throw new Error("Document lease and task do not belong to the same unit."); } return context; }
async function resolveDocumentContext(context: DocumentContext): Promise<ResolvedDocumentContext> { const [unit, lease, task, entry, record] = await Promise.all([context.unitId ? prisma.unit.findUnique({ where: { id: context.unitId }, select: { propertyId: true } }) : null, context.leaseId ? prisma.lease.findUnique({ where: { id: context.leaseId }, select: { unitId: true, unit: { select: { propertyId: true } } } }) : null, context.taskId ? prisma.task.findUnique({ where: { id: context.taskId }, select: { id: true, propertyId: true, unitId: true, leaseId: true, lease: { select: { unitId: true } } } }) : null, context.taskEntryId ? prisma.taskEntry.findUnique({ where: { id: context.taskEntryId }, select: { taskId: true, task: { select: { id: true, propertyId: true, unitId: true, leaseId: true, lease: { select: { unitId: true } } } } } }) : null, context.complianceRecordId ? prisma.complianceRecord.findUnique({ where: { id: context.complianceRecordId }, select: { complianceItem: { select: { propertyId: true } } } }) : null]); return { unit, lease, task, entry, record }; }
export async function validateDocumentContext(context: DocumentContext) { return assertDocumentContextConsistency(context, await resolveDocumentContext(context)); }
function contextualUnitIds(context: DocumentContext, resolved: ResolvedDocumentContext) { return [...new Set([context.unitId, resolved.lease?.unitId, resolved.task ? taskUnitId(resolved.task) : null, resolved.entry ? taskUnitId(resolved.entry.task) : null].filter(Boolean) as string[])]; }
async function requireDocumentCreateAccess(actor: Actor, context: DocumentContext, resolved: ResolvedDocumentContext) { if (hasAllPropertyAccess(actor)) return; const propertyGrant = await prisma.userProperty.findFirst({ where: { propertyId: context.propertyId, userId: actor.id, permission: { in: ["EDIT", "ADMIN"] } }, select: { userId: true } }); if (propertyGrant) return; const unitIds = contextualUnitIds(context, resolved); if (!unitIds.length) throw new Error("Document edit access denied."); const unitGrant = await prisma.userUnit.findFirst({ where: { userId: actor.id, unitId: { in: unitIds }, permission: { in: ["EDIT", "ADMIN"] } }, select: { userId: true } }); if (!unitGrant) throw new Error("Document edit access denied."); }
export async function createDocumentFromUpload(input: DocumentContext & { actor: Actor; bytes: Uint8Array; mimeType: string; originalName: string; category: DocumentCategory; photoStage?: DocumentPhotoStage; title: string; description?: string; documentDate?: Date }, storage: FileStorage = createFileStorage()) { const resolved = await resolveDocumentContext(input); assertDocumentContextConsistency(input, resolved); await requireDocumentCreateAccess(input.actor, input, resolved); const metadata = validateFile(input); const key = randomStorageKey(), stored: string[] = []; try { await storage.putObject({ key, body: input.bytes, contentType: input.mimeType }); stored.push(key); let previewStorageKey: string | undefined, thumbnailStorageKey: string | undefined; if (input.mimeType.startsWith("image/")) { const variants = await createImageVariants(input.bytes); previewStorageKey = `${key}.preview.webp`; thumbnailStorageKey = `${key}.thumbnail.webp`; await storage.putObject({ key: previewStorageKey, body: variants.preview, contentType: "image/webp" }); stored.push(previewStorageKey); await storage.putObject({ key: thumbnailStorageKey, body: variants.thumbnail, contentType: "image/webp" }); stored.push(thumbnailStorageKey); } return await prisma.$transaction(async (tx) => { const asset = await tx.fileAsset.create({ data: { storageKey: key, previewStorageKey, thumbnailStorageKey, uploadedById: input.actor.id, ...metadata } }); return tx.document.create({ data: { propertyId: input.propertyId, fileAssetId: asset.id, category: input.category, photoStage: input.photoStage, title: input.title, description: input.description, documentDate: input.documentDate, unitId: input.unitId, leaseId: input.leaseId, taskId: input.taskId, taskEntryId: input.taskEntryId, complianceRecordId: input.complianceRecordId, createdById: input.actor.id } }); }); } catch (error) { await Promise.allSettled(stored.map((storedKey) => storage.deleteObject(storedKey))); throw error; } }
export async function softDeleteDocument(actor: Actor, id: string) { const document = await requireDocumentEditAccess(actor, id); if (!document) throw new Error("Document edit access denied."); return prisma.document.update({ where: { id: document.id }, data: { deletedAt: new Date() } }); }
