export function AnnualReportReviewExport({ status, admin, missingFields, previewApproved, transitionAction, previewHref, publishedAssetId, persistentStorageAvailable, periodOpen, reportId, groupId }: { status: string; admin: boolean; missingFields: string[]; previewApproved: boolean; transitionAction: string; previewHref: string; publishedAssetId: string | null; persistentStorageAvailable: boolean; periodOpen: boolean; reportId: string; groupId: string }) {
  const complete = missingFields.length === 0;
  return <div className="annual-report-editor-stack">
    <section className="card annual-report-editor-intro"><span className="annual-report-kicker">Interní akcionářský výstup</span><h2>Kontrola, PDF a publikace</h2><p>PDF vzniká deterministicky ze zmrazených Q4 snapshotů a výroční redakční vrstvy. Veřejná distribuce není součástí tohoto workflow.</p></section>
    <section className="card"><h2>Úplnost reportu</h2>{complete ? <p className="status ok">Povinné korporátní údaje i kapitoly nemovitostí jsou kompletní.</p> : <><p className="muted-copy">Před odesláním ke kontrole doplňte:</p><ul className="annual-missing-list">{missingFields.map((field) => <li key={field}>{field}</li>)}</ul></>}{periodOpen && <p className="muted-copy">Rok ještě není uzavřený. Editor i PDF náhled jsou dostupné, stav REVIEW se odemkne po 31. prosinci.</p>}</section>
    <section className="card annual-review-preview"><div><h2>PDF náhled</h2><p className="muted-copy">Náhled je interní kontrolní dokument. Stejný renderer a stejná zmrazená data se použijí pro finální soubor této revize.</p></div><a className="button secondary" href={previewHref} target="_blank" rel="noreferrer">Stáhnout PDF náhled</a>{status === "REVIEW" && <p className="muted-copy">{previewApproved ? "Kontrola PDF náhledu byla v aktuálním review cyklu potvrzena." : "Administrátor musí po otevření náhledu potvrdit jeho kontrolu."}</p>}{status === "REVIEW" && admin && !previewApproved && <form action={transitionAction} method="post"><button className="secondary" name="action" value="approve-preview">Potvrdit kontrolu PDF</button></form>}</section>
    <section className="card quarterly-workflow-actions"><h2>Lifecycle a interní publikace</h2>
      {status === "DRAFT" && (periodOpen || !complete ? <button className="primary" disabled>{periodOpen ? "Rok ještě není uzavřený" : "Report není kompletní"}</button> : <form action={transitionAction} method="post"><button className="primary" name="action" value="submit-review">Odeslat ke kontrole</button></form>)}
      {status === "REVIEW" && admin && <><form action={transitionAction} method="post"><button className="secondary" name="action" value="return-draft">Vrátit do konceptu</button></form>{previewApproved && <form action={transitionAction} method="post"><button className="primary" name="action" value="publish">Interně publikovat revizi</button></form>}</>}
      {status === "PUBLISHED" && <div className="quarterly-published-actions"><a className="button secondary" href={previewHref}>Stáhnout reprodukovaný PDF náhled</a>{publishedAssetId ? <a className="button secondary" href={`/api/reporting-groups/${groupId}/annual-reports/${reportId}/assets/download`}>Stáhnout finální PDF</a> : admin && persistentStorageAvailable ? <form action={`/api/reporting-groups/${groupId}/annual-reports/${reportId}/assets/generate`} method="post"><button className="primary" type="submit">Vygenerovat finální PDF</button></form> : admin ? <p className="muted-copy">Trvalé úložiště není nakonfigurováno. Náhled zůstává dostupný pro interní kontrolu.</p> : <p className="muted-copy">Finální PDF zatím nebylo vygenerováno.</p>}<form action={transitionAction} method="post"><button className="secondary" name="action" value="create-correction">Vytvořit opravnou revizi</button></form></div>}
    </section>
  </div>;
}
