import type { AnnualContact, AnnualGroupEntity, AnnualGroupStructure, AnnualTeamMember } from "@/lib/reporting/annual-corporate-sections";

type UserOption = { isTestIdentity?: boolean; id: string; name: string; email: string; title: string | null; avatarMimeType: string | null; role?: string };
const emptyTeam = (): AnnualTeamMember => ({ sourceUserId: null, name: "", role: "", email: "", photoDataUrl: null });
const emptyEntity = (): AnnualGroupEntity => ({ name: "", type: "", ico: "", address: "", leadership: "" });

export function AnnualCorporateSectionsEditor({ action, team, users, structure, contact, editable }: { action: string; team: AnnualTeamMember[]; users: UserOption[]; structure: AnnualGroupStructure; contact: AnnualContact; editable: boolean }) {
  const teamRows = [...team, ...Array.from({ length: Math.max(0, 8 - team.length) }, emptyTeam)].slice(0, 8);
  const entityRows = [...structure.subsidiaries, ...Array.from({ length: Math.max(0, 8 - structure.subsidiaries.length) }, emptyEntity)].slice(0, 8);
  return <form className="annual-report-editor-stack" action={action} method="post">
    <section className="card annual-report-editor"><div className="annual-editor-section"><span className="annual-section-number">07</span><div><h2>Tým</h2><p className="muted-copy">Vyberte osoby pro akcionářský report. Jméno, role a e-mail lze proti uživatelskému účtu redakčně upravit; při uložení se zmrazí jeho aktuální avatar.</p></div></div><div className="annual-team-editor-grid">{teamRows.map((member, index) => <fieldset className="annual-repeat-card" key={index}><legend>Osoba {index + 1}</legend><label className="field"><span>Uživatelský profil / avatar</span><select name={`team.${index}.sourceUserId`} defaultValue={member.sourceUserId || ""} disabled={!editable}><option value="">Bez propojení</option>{users.map((user) => <option value={user.id} key={user.id}>{user.name}{user.isTestIdentity ? " · TEST" : ""}</option>)}</select></label><label className="field"><span>Jméno</span><input name={`team.${index}.name`} defaultValue={member.name} disabled={!editable}/></label><label className="field"><span>Role a odpovědnost</span><input name={`team.${index}.role`} defaultValue={member.role} disabled={!editable}/></label><label className="field"><span>E-mail</span><input name={`team.${index}.email`} type="email" defaultValue={member.email} disabled={!editable}/></label></fieldset>)}</div></section>
    <section className="card annual-report-editor"><div className="annual-editor-section"><span className="annual-section-number">08</span><div><h2>Struktura skupiny</h2><p className="muted-copy">Korporátní schéma je výroční snapshot. Změny v evidenci vlastníků již publikovanou revizi nepřepíší.</p></div></div><h3>Mateřská společnost</h3><div className="annual-money-grid">{entityFields("parent", structure.parent, editable)}</div><h3>Dceřiné společnosti a SPV</h3><div className="annual-entity-editor-grid">{entityRows.map((entity, index) => <fieldset className="annual-repeat-card" key={index}><legend>Entita {index + 1}</legend>{entityFields(`entity.${index}`, entity, editable)}</fieldset>)}</div></section>
    <section className="card annual-report-editor"><div className="annual-editor-section"><span className="annual-section-number">09</span><div><h2>Kontakty a poučení</h2><p className="muted-copy">Všechna pole včetně právního poučení jsou editovatelná pro konkrétní revizi reportu.</p></div></div><div className="annual-money-grid"><Field name="companyName" label="Společnost" value={contact.companyName} editable={editable}/><Field name="registeredAddress" label="Adresa sídla" value={contact.registeredAddress} editable={editable}/><Field name="officeAddress" label="Adresa kanceláře" value={contact.officeAddress} editable={editable}/><Field name="phone" label="Telefon" value={contact.phone} editable={editable}/><Field name="email" label="E-mail" value={contact.email} editable={editable} type="email"/><Field name="dataBox" label="Datová schránka" value={contact.dataBox} editable={editable}/></div><label className="field"><span>Správní rada a způsob jednání</span><textarea name="boardMembers" rows={5} defaultValue={contact.boardMembers} disabled={!editable}/></label><label className="field"><span>Investiční výbor</span><textarea name="investmentCommittee" rows={3} defaultValue={contact.investmentCommittee} disabled={!editable}/></label><label className="field"><span>Poučení o důvěrnosti</span><textarea name="confidentialityNotice" rows={7} defaultValue={contact.confidentialityNotice} disabled={!editable} required/></label><label className="field"><span>Investiční upozornění</span><textarea name="investmentDisclaimer" rows={3} defaultValue={contact.investmentDisclaimer} disabled={!editable} required/></label></section>
    {editable && <button className="primary" type="submit">Uložit tým, strukturu a kontakty</button>}
  </form>;
}

function Field({ name, label, value, editable, type }: { name: string; label: string; value: string; editable: boolean; type?: string }) { return <label className="field"><span>{label}</span><input name={name} type={type} defaultValue={value} disabled={!editable}/></label>; }
function entityFields(prefix: string, entity: AnnualGroupEntity, editable: boolean) { return <><Field name={`${prefix}.name`} label="Název" value={entity.name} editable={editable}/><Field name={`${prefix}.type`} label="Typ společnosti" value={entity.type} editable={editable}/><Field name={`${prefix}.ico`} label="IČO" value={entity.ico} editable={editable}/><Field name={`${prefix}.address`} label="Sídlo" value={entity.address} editable={editable}/><Field name={`${prefix}.leadership`} label="Statutární orgán / jednatelé" value={entity.leadership} editable={editable}/></>; }
