import { redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { requireUser, canSeeAll } from "@/lib/auth";
import { Shell } from "@/components/Shell";
import { Checkbox, Field, Flash, FormCard, FormPage, Select, Textarea } from "@/components/FormUi";
import { buildingTypeOptions } from "@/lib/property-technical";
import { MethodologyCallout } from "@/components/MethodologyCallout";
import { propertyManagementScopeLabels } from "@/lib/ownership-scope";
export const dynamic="force-dynamic";
export default async function NewProperty({searchParams}:{searchParams:Promise<{ok?:string;error?:string}>}){const user=await requireUser();if(!canSeeAll(user.role))redirect("/portfolio");const[owners,managers,query]=await Promise.all([prisma.owner.findMany({where:{active:true},orderBy:{name:"asc"}}),prisma.user.findMany({where:{active:true,role:{in:["PROPERTY_MANAGER","MANAGER","SUPER_ADMIN"]}},select:{id:true,name:true,title:true},orderBy:{name:"asc"}}),searchParams]);if(!owners.length)redirect("/vlastnici?error="+encodeURIComponent("Nejprve přidejte vlastníka nebo SVJ."));return <Shell user={user}><FormPage title="Přidat nemovitost" description="Zvolte vlastnickou strukturu, hlavní kontaktní subjekt a správce objektu." backHref="/portfolio"><Flash ok={query.ok} error={query.error}/><MethodologyCallout slug="zalozeni-nemovitosti"/><FormCard action="/api/properties" cancelHref="/portfolio" submitLabel="Vytvořit a pokračovat"><Field label="Interní název objektu" name="name" required placeholder="např. Moskevská"/><Field label="Ulice a číslo" name="address" required/><Field label="Město" name="city" required/><Field label="PSČ" name="postalCode"/><Select label="Typ objektu" name="buildingType" options={buildingTypeOptions}/><Select label="Hlavní vlastník / SVJ" name="ownerId" required options={owners.map(o=>[o.id,o.name])}/><Select label="Vlastnická struktura" name="ownershipMode" defaultValue="WHOLE_OBJECT" options={[["WHOLE_OBJECT","Jeden vlastník celého objektu"],["UNIT_BASED","Různí vlastníci jednotlivých jednotek"],["SVJ","SVJ – vlastníci po jednotkách"]]}/><Checkbox label="Vybraný hlavní vlastník vlastní celý objekt" name="wholeObjectOwner" defaultChecked={true}/><Select label="Hlavní komunikační vlastník / SVJ" name="communicationOwnerId" options={[["","Stejný jako hlavní vlastník"],...owners.map(o=>[o.id,o.name] as [string,string])]}/><Select label="Správce nemovitosti" name="managerId" options={[["","Bez přiřazeného správce"],...managers.map(m=>[m.id,`${m.name}${m.title?` – ${m.title}`:""}`] as [string,string])]}/><h2 className="form-section-title field-full">Rozsah správy a KPI</h2><Select label="Rozsah správy" name="managementScope" defaultValue="FULL_MANAGEMENT" options={Object.entries(propertyManagementScopeLabels)}/><Field label="Podíl v KPI FlatCloud (%)" name="flatcloudConsolidationPercent" type="number" step="0.01" min={0} max={100}/><p className="field-full classification-help">Nechte prázdné, dokud není konsolidace potvrzena. Externí správa má 0 %, plně konsolidované aktivum 100 %. Tento údaj nemění uživatelská oprávnění.</p><Textarea label="Interní poznámka" name="note"/></FormCard></FormPage></Shell>}
