import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Shell } from "@/components/Shell";
import { Flash } from "@/components/FormUi";
import { requireUser } from "@/lib/auth";
import { businessDateKey } from "@/lib/calendar";
import { prisma } from "@/lib/db";
import { backofficePermissionForGroup, canAdminReportingBackoffice, canReadReportingBackoffice } from "@/lib/reporting/backoffice-access";

export const dynamic = "force-dynamic";
const permissionLabels: Record<string, string> = { VIEW: "Pouze čtení", EDIT: "Příprava reportů", ADMIN: "Administrace skupiny" };
const reportStatus: Record<string, string> = { DRAFT: "Koncept", REVIEW: "Ke kontrole", PUBLISHED: "Publikováno" };
export default async function ReportingGroupPage({ params, searchParams }: { params: Promise<{ groupId: string }>; searchParams: Promise<{ ok?: string; error?: string }> }) {
  const [{ groupId }, user, query] = await Promise.all([params, requireUser(), searchParams]); const permission = await backofficePermissionForGroup(user, groupId); if (!canReadReportingBackoffice(permission)) redirect("/reporty");
  const group = await prisma.reportingGroup.findUnique({ where: { id: groupId }, select: { id: true, name: true, description: true, active: true, properties: { select: { id: true, propertyId: true, effectiveFrom: true, effectiveTo: true, property: { select: { name: true, address: true, active: true } } }, orderBy: [{ property: { name: "asc" } }, { effectiveFrom: "asc" }] }, members: { select: { userId: true, permission: true, user: { select: { name: true, email: true, active: true } } }, orderBy: { user: { name: "asc" } } }, quarterlyReports: { select: { id: true, year: true, quarter: true, revision: true, status: true, createdAt: true }, orderBy: [{ year: "desc" }, { quarter: "desc" }, { revision: "desc" }], take: 20 } } }); if (!group) notFound();
  const admin = canAdminReportingBackoffice(permission); const [users, properties] = admin ? await Promise.all([prisma.user.findMany({ where: { active: true }, select: { id: true, name: true, email: true }, orderBy: { name: "asc" } }), prisma.property.findMany({ select: { id: true, name: true, address: true, active: true }, orderBy: { name: "asc" } })]) : [[], []]; const memberIds = new Set(group.members.map((row) => row.userId));
  return <Shell user={user}><div className="page"><div className="breadcrumb"><Link href="/reporty/kvartalni">← Kvartální reporty</Link></div><div className="page-title"><div><h1>{group.name}</h1><p>{group.description || "Bez popisu"}</p><span className={`status ${group.active ? "ok" : "bad"}`}>{group.active ? "Aktivní" : "Neaktivní"}</span> <span className="status">{permission === "SUPER_ADMIN" ? "Globální administrace" : permissionLabels[permission]}</span></div></div><Flash ok={query.ok} error={query.error}/>
    {admin && <div className="card"><h2>Základní údaje</h2><form className="compact-form" action={`/api/reporting-groups/${group.id}`} method="post"><label className="field"><span>Název</span><input name="name" defaultValue={group.name} required/></label><label className="field"><span>Popis</span><textarea name="description" defaultValue={group.description || ""}/></label><label className="checkbox-field"><input type="checkbox" name="active" defaultChecked={group.active}/><span>Aktivní skupina</span></label><button className="primary">Uložit skupinu</button></form></div>}
    <div className="detail-grid" style={{ marginTop: 16 }}><div className="card col-12"><h2>Členové skupiny</h2>{group.members.length ? group.members.map((member) => <div className="rule-summary" key={member.userId}><div><strong>{member.user.name}</strong><small>{member.user.email} · {member.user.active ? "aktivní" : "neaktivní"}</small></div>{admin ? <form className="compact-form" action={`/api/reporting-groups/${group.id}/members/${member.userId}`} method="post"><select name="permission" defaultValue={member.permission}>{Object.entries(permissionLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button className="secondary" name="action" value="update">Uložit</button><button className="danger-button" name="action" value="remove">Odebrat</button></form> : <span>{permissionLabels[member.permission]}</span>}</div>) : <p className="muted-copy">Skupina zatím nemá členy.</p>}{admin && <form className="compact-form" action={`/api/reporting-groups/${group.id}/members`} method="post"><label className="field"><span>Aktivní uživatel</span><select name="userId" required><option value="">Vyberte uživatele</option>{users.filter((row) => !memberIds.has(row.id)).map((row) => <option value={row.id} key={row.id}>{row.name} · {row.email}</option>)}</select></label><label className="field"><span>Oprávnění</span><select name="permission" defaultValue="VIEW">{Object.entries(permissionLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><button className="primary">Přidat člena</button></form>}</div></div>
    <div className="card portfolio-table-card" style={{ marginTop: 16 }}><div className="table-toolbar"><div><h2>Efektivní intervaly nemovitostí</h2><p>Intervaly jsou inkluzivní a pracují s pražskými kalendářními dny.</p></div></div><div className="table-wrap"><table><thead><tr><th>Nemovitost</th><th>Od</th><th>Do</th><th>Stav katalogu</th><th></th></tr></thead><tbody>{group.properties.length ? group.properties.map((interval) => <tr key={interval.id}><td><strong>{interval.property.name}</strong><span className="owner-sub">{interval.property.address}</span></td><td>{businessDateKey(interval.effectiveFrom)}</td><td>{interval.effectiveTo ? businessDateKey(interval.effectiveTo) : "Bez konce"}</td><td>{interval.property.active ? "Aktivní" : "Neaktivní"}</td><td>{admin && <form className="compact-form" action={`/api/reporting-groups/${group.id}/properties/${interval.id}`} method="post"><input type="date" name="effectiveFrom" defaultValue={businessDateKey(interval.effectiveFrom)} required/><input type="date" name="effectiveTo" defaultValue={interval.effectiveTo ? businessDateKey(interval.effectiveTo) : ""}/><button className="secondary" name="action" value="update">Uložit</button><button className="secondary" name="action" value="end">Ukončit k datu</button></form>}</td></tr>) : <tr><td colSpan={5} className="table-empty">Bez intervalů nemovitostí</td></tr>}</tbody></table></div>{admin && <form className="compact-form" action={`/api/reporting-groups/${group.id}/properties`} method="post"><label className="field"><span>Nemovitost</span><select name="propertyId" required><option value="">Vyberte nemovitost</option>{properties.map((property) => <option value={property.id} key={property.id}>{property.name} · {property.address}{property.active ? "" : " · neaktivní"}</option>)}</select></label><label className="field"><span>Platnost od</span><input type="date" name="effectiveFrom" required/></label><label className="field"><span>Platnost do</span><input type="date" name="effectiveTo"/></label><button className="primary">Přidat interval</button></form>}</div>
    <div className="card portfolio-table-card" style={{ marginTop: 16 }}><div className="table-toolbar"><h2>Poslední kvartální revize</h2></div><div className="table-wrap"><table><thead><tr><th>Období</th><th>Revize</th><th>Stav</th><th>Vytvořeno</th></tr></thead><tbody>{group.quarterlyReports.length ? group.quarterlyReports.map((report) => <tr key={report.id}><td>{report.year} Q{report.quarter}</td><td>{report.revision}</td><td>{reportStatus[report.status]}</td><td>{report.createdAt.toLocaleDateString("cs-CZ")}</td></tr>) : <tr><td colSpan={4} className="table-empty">Zatím bez reportů</td></tr>}</tbody></table></div></div>
  </div></Shell>;
}
