import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser, canSeeAll } from "@/lib/auth";
import { bankTransactionAccessWhere, requirePropertyAccess } from "@/lib/access";
import { prisma } from "@/lib/db";
import { money, date } from "@/lib/format";
import { moneyInput } from "@/lib/forms";
import { paymentStatuses } from "@/lib/labels";
import { Shell } from "@/components/Shell";
import { Flash, FormPage } from "@/components/FormUi";
import { outstandingCents, paidCents } from "@/lib/charges";
import { canCorrectTransaction, hasPropertyCorrectionAccess, transactionCorrectionUnitIds } from "@/lib/payment-corrections";
import { loadEditablePaymentLeases, paymentLeaseOptionLabel } from "@/lib/payment-lease-options";
import { bankNameForCode } from "@/lib/inbound-bank/bank-email";

export const dynamic = "force-dynamic";

export default async function TransactionDetail({ params, searchParams }: { params: Promise<{ id: string; transactionId: string }>; searchParams: Promise<{ ok?: string; error?: string }> }) {
  const user = await requireUser();
  const { id, transactionId } = await params;
  const [property, transaction, query] = await Promise.all([
    requirePropertyAccess(user, id),
    prisma.bankTransaction.findFirst({
      where: { AND: [{ id: transactionId, bankAccount: { propertyId: id } }, bankTransactionAccessWhere(user)] },
      include: {
        bankAccount: true,
        matchedRule: true,
        suggestedLease: { include: { unit: true, tenant: true } },
        allocations: { include: { charge: { include: { lease: { include: { unit: true, tenant: true } } } } } },
        securityDepositReceipts: { where: { type: "RECEIVED" }, include: { lease: { include: { unit: true, tenant: true } } } },
        inboxPayment: true,
      },
    }),
    searchParams,
  ]);
  if (!property || !transaction) notFound();
  const membership = property.memberships.find((row) => row.userId === user.id);
  const canManage = transaction.status!=="IGNORED"&&(canSeeAll(user.role) || membership?.permission === "EDIT" || membership?.permission === "ADMIN");
  const leases = property.units.flatMap((unit) => unit.leases.map((lease) => ({ ...lease, unit })));
  const editableLeases=await loadEditablePaymentLeases(user,transaction.source==="manual"?undefined:id);
  const [canCorrect,hasPropertyCorrection]=await Promise.all([canCorrectTransaction(user,id,transactionCorrectionUnitIds(transaction)),hasPropertyCorrectionAccess(user,id)]);
  const cancelledManual=transaction.source==="manual"&&transaction.status==="IGNORED"&&transaction.matchNote==="Ruční platba stornována správcem.";
  const depositLinked=transaction.securityDepositReceipts.length>0;
  const openCharges = leases.flatMap((lease) => lease.charges.map((charge) => ({ lease, charge, paid: paidCents(charge) }))).filter((row) => row.charge.active && outstandingCents(row.charge)>0).sort((a, b) => a.charge.dueDate.getTime() - b.charge.dueDate.getTime());
  const allocated = transaction.allocations.reduce((sum, allocation) => sum + allocation.amountCents, 0) + transaction.securityDepositReceipts.reduce((sum, movement) => sum + movement.amountCents, 0);
  const remaining = Math.max(0, transaction.amountCents - allocated);
  const rentAllocated = transaction.allocations.reduce((sum, allocation) => sum + allocation.amountCents, 0);
  const depositAllocated = transaction.securityDepositReceipts.reduce((sum, movement) => sum + movement.amountCents, 0);
  const hasCorrections = canCorrect && !cancelledManual && transaction.status !== "IGNORED";

  return <Shell user={user}><FormPage title="Bankovní platba" description={`${property.name} · ${transaction.bankAccount.bankName}`} backHref={`/nemovitosti/${id}/platby`}>
    <Flash ok={query.ok} error={query.error}/>
    <div className="detail-grid">
      <div className="card col-12"><div className="card-head"><div><span className="eyebrow">Bankovní transakce</span><h2>{money(transaction.amountCents)}</h2><p className="muted-copy">{date(transaction.bookedAt)} · {property.name} / {transaction.bankAccount.ibanMasked}</p></div><span className={`status ${transaction.status === "MATCHED" ? "ok" : transaction.status === "UNMATCHED" ? "bad" : transaction.status === "IGNORED" ? "" : "warn"}`}>{paymentStatuses[transaction.status]}</span></div><div className="summary-list"><div><span>Plátce / protistrana</span><strong>{transaction.counterpartyName || "Plátce neuveden"}</strong></div><div><span>Účet plátce</span><strong>{transaction.counterpartyIban || "—"}</strong></div><div><span>Variabilní symbol</span><strong>{transaction.variableSymbol || "—"}</strong></div><div><span>Zbývá přiřadit</span><strong>{money(remaining)}</strong></div></div></div>

      <div className="card col-5"><h2>Údaje z platby</h2><div className="summary-list"><div><span>Plátce / protistrana</span><strong>{transaction.counterpartyName || "Plátce neuveden"}</strong></div><div><span>Účet plátce</span><strong>{transaction.counterpartyIban || "—"}</strong></div><div><span>VS</span><strong>{transaction.variableSymbol || "—"}</strong></div><div><span>Zpráva z banky</span><strong>{transaction.message || "—"}</strong></div><div><span>Cílový účet</span><strong>{transaction.bankAccount.ibanMasked}</strong></div><div><span>Datum zaúčtování</span><strong>{date(transaction.bookedAt)}</strong></div><div><span>Zdroj</span><strong>{transaction.source === "manual" ? "Ruční platba" : "Bankovní notifikace"}</strong></div><div><span>Výsledek párování</span><strong>{transaction.matchNote || "—"}</strong></div></div></div>

      <div className="card col-7"><div className="card-head"><div><h2>Zaúčtování platby</h2><p className="muted-copy">Jak je přijatá bankovní částka využita v účetní evidenci FlatCloud.</p></div></div>{transaction.allocations.length || depositLinked ? <div className="stack-list">{transaction.allocations.map((allocation) => <div className="simple-row" key={allocation.id}><div className="round-icon">✓</div><div><strong>{allocation.charge.lease.unit.label} · {allocation.charge.lease.tenant.name}</strong><small>Úhrada předpisu · {allocation.charge.period}</small></div><div className="right"><strong>{money(allocation.amountCents)}</strong></div></div>)}{transaction.securityDepositReceipts.map((movement) => <div className="simple-row" key={movement.id}><div className="round-icon">✓</div><div><strong>{movement.lease.unit.label} · {movement.lease.tenant.name}</strong><small>Kauce</small></div><div className="right"><strong>{money(movement.amountCents)}</strong></div></div>)}</div> : <p className="muted-copy">Platba zatím není zaúčtována k předpisu ani jako kauce.</p>}<div className="summary-list" style={{marginTop:16}}><div><span>Bankovní transakce</span><strong>{money(transaction.amountCents)}</strong></div><div><span>Nájem</span><strong>{money(rentAllocated)}</strong></div><div><span>Kauce</span><strong>{money(depositAllocated)}</strong></div><div><span>Zbývá přiřadit</span><strong>{money(remaining)}</strong></div></div></div>

      {transaction.suggestedLease && <div className="card col-12"><h2>Návrh systému</h2><div className="notice"><strong>{transaction.suggestedLease.unit.label} · {transaction.suggestedLease.tenant.name}</strong><span>Návrh není zaúčtování.</span></div></div>}

      {cancelledManual&&<div className="card col-12"><h2>Ruční platba byla stornována</h2><p className="muted-copy">Transakce zůstává zachována v historii a její původní přiřazení bylo zrušeno.</p></div>}

      {canManage && remaining > 0 && transaction.amountCents > 0 && <div className="card col-12"><div className="card-head"><div><h2>Co chcete s platbou udělat?</h2><p className="muted-copy">Zaúčtujte pouze dosud nepřiřazenou částku {money(remaining)}.</p></div></div><div className="detail-grid"><div className="col-7"><h3>Přiřadit k předpisu</h3><form className="compact-form" action={`/api/properties/${id}/transactions/${transaction.id}/allocate`} method="post"><label className="field"><span>Otevřený předpis</span><select name="chargeId" required>{openCharges.map((row) => <option value={row.charge.id} key={row.charge.id}>{row.lease.unit.label} · {row.lease.tenant.name} · {row.charge.period} · zbývá {money(row.charge.amountCents - row.paid)}</option>)}</select></label><label className="field"><span>Částka (prázdné = maximální možná)</span><input name="amount" type="number" step="0.01" max={moneyInput(remaining)}/></label><button className="primary" type="submit">Přiřadit k předpisu</button></form></div><div className="col-5"><details><summary>Zaúčtovat jako kauci</summary><p className="muted-copy">Použitelná nealokovaná část transakce: {money(remaining)}.</p><form className="compact-form" action={`/api/properties/${id}/transactions/${transaction.id}/deposit`} method="post"><label className="field"><span>Smlouva</span><select name="leaseId" defaultValue={transaction.suggestedLeaseId || ""} required><option value="">Vyberte smlouvu</option>{leases.map((lease)=><option key={lease.id} value={lease.id}>{lease.unit.label} · {lease.tenant.name}</option>)}</select></label><label className="field"><span>Částka Kč</span><input name="amount" type="number" min="0.01" max={moneyInput(remaining)} step="0.01" required/></label><label className="field"><span>Datum přijetí</span><input name="effectiveAt" type="date" defaultValue={transaction.bookedAt.toISOString().slice(0,10)} required/></label><label className="field"><span>Poznámka</span><input name="note" placeholder="Kauce z bankovní transakce"/></label><button className="secondary" type="submit">Zaúčtovat jako kauci</button></form></details></div></div></div>}

      {hasCorrections && <div className="card col-12"><details open={!transaction.allocations.length && transaction.source === "manual"}><summary>Opravy zaúčtování</summary><div className="detail-grid" style={{marginTop:14}}>{transaction.allocations.length > 0 && <div className="col-7"><h3>Přiřazení nájemného</h3><div className="stack-list">{transaction.allocations.map((allocation) => <div className="simple-row" key={allocation.id}><div><strong>{allocation.charge.lease.unit.label} · {allocation.charge.lease.tenant.name}</strong><small>Předpis {allocation.charge.period}</small></div><div className="right"><strong>{money(allocation.amountCents)}</strong>{(hasPropertyCorrection||depositLinked||transaction.allocations.length>1)&&<form action={`/api/properties/${id}/transactions/${transaction.id}/allocations/${allocation.id}/remove`} method="post"><button className="text-button" type="submit">Odpárovat</button></form>}</div></div>)}</div>{(hasPropertyCorrection||depositLinked)&&<form action={`/api/properties/${id}/transactions/${transaction.id}/unallocate-all`} method="post"><button className="secondary" type="submit">Odpárovat všechna přiřazení nájemného</button>{depositLinked&&<p className="muted-copy">Odstranění přiřazení nájemného nemění zaúčtovanou kauci.</p>}</form>}</div>}<div className="col-5"><h3>Přepárovat celou platbu</h3>{depositLinked?<div className="notice">Část platby je zaúčtována jako kauce. Lze opravit jednotlivé alokace nájemného, ale celou platbu nelze přepárovat.</div>:<form className="compact-form" action={`/api/properties/${id}/transactions/${transaction.id}/reassign`} method="post"><label className="field"><span>Nový nájemní vztah</span><select name="targetLeaseId" required><option value="">Vyberte smlouvu</option>{editableLeases.map(lease=><option key={lease.id} value={lease.id}>{paymentLeaseOptionLabel(lease)}</option>)}</select></label><button className="secondary" type="submit">Přepárovat platbu</button></form>}{hasPropertyCorrection&&transaction.source==="manual"&&<div style={{marginTop:18}}><h3>Stornovat ruční platbu</h3>{depositLinked?<div className="notice">Platbu nelze stornovat, protože její část byla zaúčtována jako kauce. Nejprve je nutné opravit evidenci kauce.</div>:<form action={`/api/properties/${id}/transactions/${transaction.id}/cancel-manual`} method="post"><p className="muted-copy">Ruční platba zůstane zachována v historii a její přiřazení bude zrušeno.</p><label className="checkbox-field"><input type="checkbox" required/><span>Rozumím dopadu storna</span></label><button className="danger-button" type="submit">Stornovat ruční platbu</button></form>}</div>}</div></div></details></div>}

      {canManage && !transaction.allocations.length && !depositLinked && transaction.amountCents > 0 && <div className="card col-12"><details><summary>Pravidla pro budoucí platby</summary><p className="muted-copy">Pravidlo ovlivní i další odpovídající příchozí platby.</p><form className="compact-form" action={`/api/properties/${id}/transactions/${transaction.id}/rule`} method="post"><label className="field"><span>Název pravidla</span><input name="ruleName" placeholder="např. Nájem Byt 3"/></label><label className="field"><span>Cílová smlouva</span><select name="targetLeaseId" defaultValue={transaction.suggestedLeaseId || ""} required><option value="">Vyberte smlouvu</option>{leases.map((lease) => <option value={lease.id} key={lease.id}>{lease.unit.label} · {lease.tenant.name} · VS {lease.variableSymbol}</option>)}</select></label><label className="field"><span>Akce</span><select name="action"><option value="MATCH_LEASE">Automaticky párovat</option><option value="SUGGEST_LEASE">Pouze navrhnout</option></select></label><RuleChecks transaction={transaction}/><button className="secondary" type="submit">Uložit pravidlo</button></form></details></div>}

      {canManage && transaction.source!=="manual" && !transaction.allocations.length && !depositLinked && <div className="card col-12"><details><summary>Ignorovat platbu</summary><p className="muted-copy"><strong>Ignorovat pouze tuto platbu.</strong> Budoucí platby zůstanou beze změny, pokud výslovně nezvolíte vytvoření pravidla.</p><form className="ignore-form" action={`/api/properties/${id}/transactions/${transaction.id}/ignore`} method="post"><label className="field"><span>Název budoucího pravidla</span><input name="ruleName" placeholder="např. Převod rezervního fondu"/></label><label className="checkbox-field"><input type="checkbox" name="future"/><span>Ignorovat také budoucí odpovídající platby</span></label><RuleChecks transaction={transaction}/><div className="form-actions"><button className="danger-button" type="submit">Ignorovat pouze tuto platbu</button></div></form></details></div>}

      {transaction.inboxPayment && <div className="card col-12"><details><summary>Údaje z bankovní notifikace</summary><div className="summary-list" style={{marginTop:14}}><div><span>Banka</span><strong>{bankNameForCode(transaction.inboxPayment.bank)}{transaction.inboxPayment.bank !== "UNKNOWN" ? ` · ${transaction.inboxPayment.bank}` : ""}</strong></div><div><span>Důvěryhodnost zdroje</span><strong>{transaction.inboxPayment.sourceTrusted ? "Ověřený bankovní zdroj" : "Vyžadoval ruční kontrolu"}</strong></div><div><span>E-mail přijat</span><strong>{date(transaction.inboxPayment.receivedAt)}</strong></div><div><span>Datum platby</span><strong>{transaction.inboxPayment.bookedAt ? date(transaction.inboxPayment.bookedAt) : "—"}</strong></div><div><span>Cílový účet</span><strong>{transaction.inboxPayment.recipientAccount || "—"}</strong></div><div><span>Plátce / protistrana</span><strong>{transaction.inboxPayment.counterpartyName || "Plátce neuveden"}</strong></div><div><span>Účet plátce</span><strong>{transaction.inboxPayment.counterpartyAccount || "—"}</strong></div><div><span>VS / SS / KS</span><strong>{[transaction.inboxPayment.variableSymbol && `VS ${transaction.inboxPayment.variableSymbol}`, transaction.inboxPayment.specificSymbol && `SS ${transaction.inboxPayment.specificSymbol}`, transaction.inboxPayment.constantSymbol && `KS ${transaction.inboxPayment.constantSymbol}`].filter(Boolean).join(" · ") || "—"}</strong></div><div><span>Zpráva pro příjemce</span><strong>{transaction.inboxPayment.message || "—"}</strong></div><div><span>Odesílatel notifikačního e-mailu</span><strong>{transaction.inboxPayment.sender || "—"}</strong></div><div><span>Předmět e-mailu</span><strong>{transaction.inboxPayment.subject || "—"}</strong></div><div><span>Výsledek parseru</span><strong>{transaction.inboxPayment.parseNote || "—"}</strong></div></div>{transaction.inboxPayment.rawExcerpt && <details style={{marginTop:14}}><summary>Původní obsah bankovní notifikace</summary><pre className="email-raw">{transaction.inboxPayment.rawExcerpt}</pre></details>}</details></div>}
    </div>
  </FormPage></Shell>;
}

function RuleChecks({ transaction }: { transaction: { counterpartyIban: string | null; counterpartyName: string | null; variableSymbol: string | null; message: string | null; amountCents: number } }) {
  return <div className="rule-checks"><strong>Podmínky pravidla</strong>{transaction.counterpartyIban && <label className="checkbox-field"><input type="checkbox" name="useIban" defaultChecked/><span>Účet plátce: {transaction.counterpartyIban}</span></label>}{transaction.counterpartyName && <label className="checkbox-field"><input type="checkbox" name="useName"/><span>Jméno obsahuje: {transaction.counterpartyName}</span></label>}{transaction.variableSymbol && <label className="checkbox-field"><input type="checkbox" name="useVs"/><span>Variabilní symbol: {transaction.variableSymbol}</span></label>}{transaction.message && <label className="checkbox-field"><input type="checkbox" name="useMessage"/><span>Zpráva obsahuje: {transaction.message}</span></label>}<label className="checkbox-field"><input type="checkbox" name="useAmount"/><span>Přesná částka: {money(transaction.amountCents)}</span></label></div>;
}
