import Link from "next/link";
import { requireUser, hasAllPropertyAccess } from "@/lib/auth";
import { accessibleProperties } from "@/lib/access";
import { prisma } from "@/lib/db";
import { date } from "@/lib/format";
import { complianceState } from "@/lib/operations";
import { Shell } from "@/components/Shell";
import { NavigableTableRow } from "@/components/NavigableTableRow";
import { PortfolioScopePicker } from "@/components/PortfolioScopePicker";
import { parsePortfolioSelection, portfolioSelectionLabel, selectedPropertyIds } from "@/lib/portfolio-selection";

export const dynamic="force-dynamic";
export default async function CompliancePage({searchParams}:{searchParams:Promise<{properties?:string;propertyId?:string}>}){
 const [user,query]=await Promise.all([requireUser(),searchParams]); const availableProperties=await accessibleProperties(user); const selection=parsePortfolioSelection(query); const selectedIds=selectedPropertyIds(selection,availableProperties.map((p)=>p.id)); const properties=availableProperties.filter((p)=>selectedIds.includes(p.id)); const fullAccess=hasAllPropertyAccess(user); const ids=fullAccess?properties.map((p)=>p.id):properties.filter((p)=>p.memberships.some((m)=>m.userId===user.id)).map((p)=>p.id); const items=ids.length?await prisma.complianceItem.findMany({where:{propertyId:{in:ids},active:true},include:{property:true,assignedContact:true},orderBy:{nextDueAt:"asc"}}):[]; const states=items.map((item)=>({item,state:complianceState(item)})); const overdue=states.filter((row)=>row.state.key==="overdue"||row.state.key==="today").length; const soon=states.filter((row)=>row.state.key==="soon"||row.state.key==="upcoming").length;
 return <Shell user={user}><div className="page"><div className="page-title"><div><h1>Revize a povinné kontroly</h1><p>Termíny, odpovědné kontakty a historie pravidelných kontrol napříč portfoliem.</p><span className="scope-context-badge">{portfolioSelectionLabel(selection,properties.length,availableProperties.length)}</span></div><PortfolioScopePicker availableProperties={availableProperties.map((property)=>({id:property.id,name:property.name,address:property.address,city:property.city,active:property.active,ownerId:property.communicationOwner?.id||property.owner.id,ownerName:property.communicationOwner?.name||property.owner.name,scopeKind:property.flatcloudConsolidationBasisPoints==null?"UNCLASSIFIED" as const:property.flatcloudConsolidationBasisPoints>0?"FLATCLOUD" as const:"EXTERNAL" as const}))} selection={selection.mode==="ALL"?selection:{mode:"SELECTED",propertyIds:selectedIds}}/></div><div className="stat-grid compact-stats"><MiniStat label="Aktivní kontroly" value={String(items.length)} note="ve zvoleném rozsahu"/><MiniStat label="Do 60 dní" value={String(soon)} note="blížící se termín" bad={soon>0}/><MiniStat label="Po termínu" value={String(overdue)} note="vyžaduje zásah" bad={overdue>0}/></div><div className="card portfolio-table-card"><div className="table-toolbar"><div><h2>Kalendář revizí</h2><p>Nejbližší termíny jsou řazeny jako první.</p></div></div><div className="table-wrap"><table><thead><tr><th>Termín</th><th>Kontrola</th><th>Nemovitost</th><th>Periodicita</th><th>Dodavatel / technik</th><th>Stav</th><th></th></tr></thead><tbody>{states.length?states.map(({item,state})=><NavigableTableRow href={`/nemovitosti/${item.propertyId}/provoz#revize`} ariaLabel={`Otevřít revizi ${item.name}`} key={item.id}><td><strong>{date(item.nextDueAt)}</strong></td><td>{item.name}<span className="owner-sub">{item.category}</span></td><td><Link className="entity-link" href={`/nemovitosti/${item.propertyId}/provoz`}>{item.property.name}</Link></td><td>{item.frequencyMonths?`${item.frequencyMonths} měs.`:"Ruční termín"}</td><td>{item.assignedContact?.name||"Nepřiřazen"}</td><td><span className={`status ${state.tone}`}>{state.label}</span></td><td><Link className="table-link" href={`/nemovitosti/${item.propertyId}/provoz#revize`}>Detail</Link></td></NavigableTableRow>):<tr><td colSpan={7} className="table-empty">Zatím nejsou evidovány žádné povinné kontroly ve zvoleném rozsahu.</td></tr>}</tbody></table></div></div></div></Shell>
}
function MiniStat({label,value,note,bad=false}:{label:string;value:string;note:string;bad?:boolean}){return <div className="card stat"><div><span>{label}</span><strong className={bad?"negative":""}>{value}</strong><small className={bad?"bad":""}>{note}</small></div></div>}
