import Link from "next/link";
import { requireUser, hasAllPropertyAccess } from "@/lib/auth";
import { accessibleProperties } from "@/lib/access";
import { prisma } from "@/lib/db";
import { date } from "@/lib/format";
import { complianceState } from "@/lib/operations";
import { Shell } from "@/components/Shell";

export const dynamic="force-dynamic";
export default async function CompliancePage(){
 const user=await requireUser(); const properties=await accessibleProperties(user); const fullAccess=hasAllPropertyAccess(user); const ids=fullAccess?properties.map((p)=>p.id):properties.filter((p)=>p.memberships.some((m)=>m.userId===user.id)).map((p)=>p.id); const items=ids.length?await prisma.complianceItem.findMany({where:{propertyId:{in:ids},active:true},include:{property:true,assignedContact:true},orderBy:{nextDueAt:"asc"}}):[]; const states=items.map((item)=>({item,state:complianceState(item)})); const overdue=states.filter((row)=>row.state.key==="overdue"||row.state.key==="today").length; const soon=states.filter((row)=>row.state.key==="soon"||row.state.key==="upcoming").length;
 return <Shell user={user}><div className="page"><div className="page-title"><div><h1>Revize a povinné kontroly</h1><p>Termíny, odpovědné kontakty a historie pravidelných kontrol napříč portfoliem.</p></div></div><div className="stat-grid compact-stats"><MiniStat label="Aktivní kontroly" value={String(items.length)} note="v portfoliu"/><MiniStat label="Do 60 dní" value={String(soon)} note="blížící se termín" bad={soon>0}/><MiniStat label="Po termínu" value={String(overdue)} note="vyžaduje zásah" bad={overdue>0}/></div><div className="card portfolio-table-card"><div className="table-toolbar"><div><h2>Kalendář revizí</h2><p>Nejbližší termíny jsou řazeny jako první.</p></div></div><div className="table-wrap"><table><thead><tr><th>Termín</th><th>Kontrola</th><th>Nemovitost</th><th>Periodicita</th><th>Dodavatel / technik</th><th>Stav</th><th></th></tr></thead><tbody>{states.length?states.map(({item,state})=><tr key={item.id}><td><strong>{date(item.nextDueAt)}</strong></td><td>{item.name}<span className="owner-sub">{item.category}</span></td><td><Link className="entity-link" href={`/nemovitosti/${item.propertyId}/provoz`}>{item.property.name}</Link></td><td>{item.frequencyMonths?`${item.frequencyMonths} měs.`:"Ruční termín"}</td><td>{item.assignedContact?.name||"Nepřiřazen"}</td><td><span className={`status ${state.tone}`}>{state.label}</span></td><td><Link className="table-link" href={`/nemovitosti/${item.propertyId}/provoz#revize`}>Detail</Link></td></tr>):<tr><td colSpan={7} className="table-empty">Zatím nejsou evidovány žádné povinné kontroly.</td></tr>}</tbody></table></div></div></div></Shell>
}
function MiniStat({label,value,note,bad=false}:{label:string;value:string;note:string;bad?:boolean}){return <div className="card stat"><div><span>{label}</span><strong className={bad?"negative":""}>{value}</strong><small className={bad?"bad":""}>{note}</small></div></div>}
