import type { ReportDesignTemplateConfig } from "@/lib/reporting/design-template-schema";
import { ReportDesignGeneratedBackground } from "@/components/reporting/ReportDesignGeneratedBackground";
import { contentLogoRect, coverNarrativeRect } from "@/lib/reporting/presentation/report-design-parity";

const pct = (value: number) => `${value * 100}%`;
const rectStyle = (rect: { x: number; y: number; width: number; height: number }) => ({ left: pct(rect.x), top: pct(rect.y), width: pct(rect.width), height: pct(rect.height) });

export function ReportDesignCoverPreview({ config }: { config: ReportDesignTemplateConfig }) {
  return <div className="design-preview design-cover" data-page-format={config.page.format} style={{ background: config.brand.primary, aspectRatio: config.page.format === "FLATCLOUD_13X9" ? "13 / 9" : "297 / 210" }}><div className="design-hero-placeholder" style={rectStyle(config.cover.imageRect)}><span>MAIN · PRIMARY / 0</span></div><div className="design-logo" style={rectStyle(config.cover.logoRect)}><img src="/flatcloud-logo-white.png" alt="FlatCloud"/></div><div className="design-cover-stack" style={rectStyle(coverNarrativeRect(config.cover.titleRect))}><strong className="design-cover-title">Název nemovitosti</strong><span className="design-cover-period">Kvartální report - 3Q / 2026</span></div></div>;
}

export function ReportDesignContentPreview({ config, backgroundUrl, overview = false }: { config: ReportDesignTemplateConfig; backgroundUrl?: string; overview?: boolean }) {
  return <div className="design-preview design-content" data-page-format={config.page.format} style={{ ...(backgroundUrl ? { backgroundImage: `url(${backgroundUrl})`, backgroundSize: "cover", backgroundPosition: "center" } : {}), aspectRatio: config.page.format === "FLATCLOUD_13X9" ? "13 / 9" : "297 / 210" }}>{!backgroundUrl && <ReportDesignGeneratedBackground config={config} className="design-generated-background"/>}<span className="design-report-label" style={rectStyle(config.contentHeader.reportLabelRect)}>FlatCloud | Kvartální report | 3Q 2026</span><strong className="design-property-title" style={rectStyle(config.contentHeader.propertyTitleRect)}>Název nemovitosti</strong><div className="design-logo content-logo" style={rectStyle(contentLogoRect(config.contentHeader.logoRect))}><img src="/flatcloud-logo-report.png" alt="FlatCloud"/></div><div className="design-safe-area" style={rectStyle(config.contentSafeArea)}>{overview ? <><div className="design-supportive" style={rectStyle({ x: 0, y: 0, width: 0.593, height: 0.915 })}>SUPPORTIVE<br/>SECONDARY / 0</div><div className="design-commentary" style={rectStyle({ x: 0.643, y: 0.06, width: 0.356, height: 0.82 })}><strong>Komentář</strong><span>Management commentary</span></div></> : <span>Bezpečná obsahová plocha</span>}</div></div>;
}
