import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { FileText, LockKeyhole, Send } from "lucide-react";
import { Shell } from "@/components/Shell";
import { Flash } from "@/components/FormUi";
import { MethodologyCallout } from "@/components/MethodologyCallout";
import { canSeeAll, requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { date } from "@/lib/format";
import { dateInput } from "@/lib/forms";
import { renderWelcomeLetter, welcomeLetterStatuses, welcomeSectionFields, type WelcomeLetterStatus } from "@/lib/distribution/welcome-letters";

export const dynamic = "force-dynamic";
export default async function WelcomeLetterDetail({ params, searchParams }: { params: Promise<{ letterId: string }>; searchParams: Promise<{ ok?: string; error?: string }> }) {
  const [user, { letterId }, query] = await Promise.all([requireUser(), params, searchParams]); if (!canSeeAll(user.role)) redirect("/portfolio");
  const letter = await prisma.distributionWelcomeLetter.findUnique({ where: { id: letterId }, include: { createdBy: { select: { name: true } }, updatedBy: { select: { name: true } }, readyBy: { select: { name: true } }, sentBy: { select: { name: true } }, attachments: { orderBy: { sortOrder: "asc" }, include: { document: { include: { fileAsset: true } } } } } }); if (!letter) notFound();
  const documents = await prisma.document.findMany({ where: { propertyId: letter.propertyId, deletedAt: null }, include: { fileAsset: true }, orderBy: { createdAt: "desc" }, take: 80 });
  const selected = new Set(letter.attachments.map((item) => item.documentId)), preview = renderWelcomeLetter(letter), editable = letter.status === "DRAFT", ready = letter.status === "READY", due = letter.ownershipRegisteredAt <= new Date();
  return <Shell user={user}><div className="page distribution-welcome-detail"><div className="breadcrumb"><Link href="/distribuce">Distribuce</Link><span>›</span><Link href="/distribuce/uvitaci-dopisy">Uvítací dopisy</Link><span>›</span><span>{letter.recipientNameSnapshot}</span></div><div className="page-title"><div><h1>{letter.recipientNameSnapshot}</h1><p>{letter.propertyNameSnapshot} · {letter.unitLabelSnapshot} · revize {letter.revision}</p></div><span className={`status ${letter.status === "SENT" ? "ok" : ready ? "warn" : ""}`}>{welcomeLetterStatuses[letter.status as WelcomeLetterStatus]}</span></div><Flash ok={query.ok} error={query.error}/>
    <MethodologyCallout slug="uvitaci-dopis-vlastnikovi" compact/>
    <div className="welcome-letter-layout"><section className="card welcome-editor"><div className="card-head"><div><h2>Obsah a přílohy</h2><p className="muted-copy">Šablona FlatCloud · údaje kupujícího, jednotky, domu a prodávajícího jsou zmrazené v této revizi.</p></div></div>{editable ? <form action={`/api/distribution/welcome-letters/${letter.id}`} method="post" className="welcome-letter-form"><input type="hidden" name="mode" value="save"/><div className="form-grid"><label className="field"><span>E-mail nového vlastníka *</span><input name="recipientEmail" type="email" defaultValue={letter.recipientEmail} required/></label><label className="field"><span>Datum nabytí podle katastru *</span><input name="ownershipRegisteredAt" type="date" defaultValue={dateInput(letter.ownershipRegisteredAt)} required/></label><label className="field field-full"><span>Předmět e-mailu *</span><input name="subject" defaultValue={letter.subject} required/></label><label className="field field-full"><span>Úvod a obchodní shrnutí *</span><textarea name="introduction" rows={7} defaultValue={letter.introduction} required/></label>{welcomeSectionFields.map(([field, label]) => <label className="field field-full" key={field}><span>{label}</span><textarea name={field} rows={6} defaultValue={letter[field]}/></label>)}<label className="field field-full"><span>Závěr *</span><textarea name="closingText" rows={6} defaultValue={letter.closingText} required/></label><label className="field field-full"><span>Kontakty *</span><textarea name="contactText" rows={6} defaultValue={letter.contactText} required/></label></div><fieldset className="welcome-attachments"><legend>Přílohy z dokumentů domu</legend>{documents.length ? <div className="attachment-picker">{documents.map((document) => <label className="checkbox-field" key={document.id}><input type="checkbox" name="documentId" value={document.id} defaultChecked={selected.has(document.id)}/><span><strong>{document.title}</strong><small>{document.fileAsset.originalName}</small></span></label>)}</div> : <p className="muted-copy">Dům zatím nemá dostupné dokumenty. Přílohy lze nejprve nahrát v dokumentech nemovitosti.</p>}</fieldset><button className="primary" type="submit">Uložit koncept</button></form> : <ReadOnlySummary letter={letter}/>}</section>
      <aside className="card welcome-preview"><div className="card-head"><div><h2>Náhled e-mailu</h2><p className="muted-copy">Předmět: {letter.subject}</p></div></div><div className="welcome-email-preview" dangerouslySetInnerHTML={{ __html: preview.html }}/></aside></div>
    <div className="card welcome-gate"><div><h2>Kontrola a odeslání</h2><p className="muted-copy">Datum nabytí: {date(letter.ownershipRegisteredAt)} · prodávající: {letter.sellerNameSnapshot} · příloh: {letter.attachments.length}</p></div>{editable && <form action={`/api/distribution/welcome-letters/${letter.id}`} method="post"><button className="secondary" name="mode" value="ready" type="submit"><LockKeyhole size={15}/> Předat ke kontrole</button></form>}{ready && <><form action={`/api/distribution/welcome-letters/${letter.id}`} method="post"><button className="secondary" name="mode" value="reopen" type="submit">Vrátit k úpravám</button></form><form action={`/api/distribution/welcome-letters/${letter.id}`} method="post" className="welcome-send-confirm"><input type="hidden" name="mode" value="send"/><label className="checkbox-field"><input type="checkbox" name="confirmSend" value="yes" required/><span>Potvrzuji příjemce, datum nabytí, obsah a všechny přílohy.</span></label><button className="primary" type="submit" disabled={!due}><Send size={15}/> Odeslat uvítací e-mail</button>{!due && <small>Odeslání se zpřístupní v den nabytí podle katastru.</small>}</form></>}{letter.status === "SENT" && <div className="status ok"><FileText size={14}/> Odesláno {letter.sentAt ? date(letter.sentAt) : "—"} · {letter.sentBy?.name || "—"}</div>}</div>
  </div></Shell>;
}
function ReadOnlySummary({ letter }: { letter: Record<string, any> }) { return <div className="welcome-readonly"><div><span>Příjemce</span><strong>{letter.recipientEmail}</strong></div><div><span>Datum nabytí</span><strong>{date(letter.ownershipRegisteredAt)}</strong></div><div><span>Kontrolu připravil</span><strong>{letter.readyBy?.name || "—"}</strong></div><div><span>Poslední úprava</span><strong>{letter.updatedBy.name} · {date(letter.updatedAt)}</strong></div>{letter.attachments.length > 0 && <div className="field-full"><span>Přílohy</span>{letter.attachments.map((item: any) => <Link href={`/api/documents/${item.document.id}/download`} key={item.document.id}>{item.document.title} · {item.document.fileAsset.originalName}</Link>)}</div>}</div>; }
