import Link from "next/link";
import { BarChart3, Building2, CalendarClock, Home, ShieldCheck, TrendingUp, WalletCards } from "lucide-react";
import { Shell } from "@/components/Shell";
import { PortfolioScopePicker } from "@/components/PortfolioScopePicker";
import { CollectionChart, OccupancyChart } from "@/components/ReportChart";
import { ReportPeriodPicker } from "@/components/ReportPeriodPicker";
import { requireUser } from "@/lib/auth";
import { date, money } from "@/lib/format";
import { parsePortfolioSelection, portfolioSelectionLabel, selectedPropertyIds, serializePortfolioSelection } from "@/lib/portfolio-selection";
import { loadLiveReport } from "@/lib/reporting/live-service";
import { groupReportingQualityIssues, reportingQualityIssueTarget } from "@/lib/reporting/data-quality";
import { NavigableTableRow } from "@/components/NavigableTableRow";
import { MfBenchmarkTable } from "@/components/MfBenchmarkTable";
import { leaseStatuses, securityDepositStatuses } from "@/lib/labels";
import { parseLiveReportPeriodRange } from "@/lib/reporting/live-period";

export const dynamic = "force-dynamic";
const views = { overview: "Přehled", occupancy: "Obsazenost", collections: "Inkaso", tenancy: "Tenancy", benchmark: "MF benchmark", deposits: "Kauce", contracts: "Smlouvy" } as const;
type View = keyof typeof views;
export default async function ReportCenter({ searchParams }: { searchParams: Promise<{ view?: string; properties?: string; propertyId?: string; range?: string; from?: string; to?: string }> }) {
  const [user, query] = await Promise.all([requireUser(), searchParams]);
  const asOf = new Date(), range = parseLiveReportPeriodRange(query, asOf);
  const requestedSelection = parsePortfolioSelection(query), data = await loadLiveReport(user, requestedSelection, asOf, range.periods);
  const allowedIds = selectedPropertyIds(requestedSelection, data.availableProperties.map((property)=>property.id));
  const selection = requestedSelection.mode === "ALL" ? requestedSelection : { mode: "SELECTED" as const, propertyIds: allowedIds };
  const view: View = query.view && query.view in views ? query.view as View : "overview";
  const selectionValue = serializePortfolioSelection(selection), selectionSuffix = selectionValue === null ? "" : `&properties=${encodeURIComponent(selectionValue)}`;
  const rangeSuffix = range.mode === "rolling12" ? "" : range.mode === "ytd" ? "&range=ytd" : `&range=custom&from=${range.from}&to=${range.to}`;
  const a = data.aggregate;
  return <Shell user={user}><div className="page"><div className="page-title"><div><h1>Reporty</h1><p>{portfolioSelectionLabel(selection,allowedIds.length,data.availableProperties.length,data.availableProperties.filter(property=>property.active).length)}.</p><span className="live-badge">LIVE · Data k {new Intl.DateTimeFormat("cs-CZ").format(new Date(`${data.asOfDate}T12:00:00Z`))}</span></div><PortfolioScopePicker availableProperties={data.availableProperties} selection={selection}/></div>
    <nav className="report-tabs" aria-label="Report Center views">{Object.entries(views).map(([key,label])=><Link className={view===key?"active":""} key={key} href={`/reporty?view=${key}${selectionSuffix}${rangeSuffix}`}>{label}</Link>)}</nav>
    {view==="overview"&&<><Kpis items={[["Obsazenost",a.occupancyBps===null?"—":`${(a.occupancyBps/100).toFixed(1)} %`,<Home key="i"/>],["Měsíční čisté nájemné",money(a.netRentCents),<TrendingUp key="i"/>],["Inkaso kvartálu",a.collectionRateBps===null?"—":`${(a.collectionRateBps/100).toFixed(1)} %`,<BarChart3 key="i"/>],["Dluh po splatnosti",money(a.overdueDebtCents),<WalletCards key="i"/>],["Držené kauce",money(a.heldDepositCents),<ShieldCheck key="i"/>],["Smlouvy do 90 dní",String(a.expiring90Days),<CalendarClock key="i"/>]]}/><PropertyPerformance rows={data.propertyRows}/><QualityPanel issues={data.quality} entities={data.qualityEntities} user={{...user,memberships:data.memberships,unitMemberships:data.unitMemberships}}/></>}
    {view==="occupancy"&&<><Kpis items={[["Pronajímatelné jednotky",String(a.rentable),<Building2 key="i"/>],["Obsazené",String(a.occupied),<Home key="i"/>],["Volné",String(a.vacant),<Home key="i"/>],["V rekonstrukci",String(a.renovation),<Building2 key="i"/>],["Neaktivní",String(a.inactive),<Building2 key="i"/>],["Neznámá historie",String(a.unknown),<Building2 key="i"/>]]}/><Table title="Obsazenost podle nemovitostí" headers={["Nemovitost","Celkem","Pronajímatelné","Obsazené","Volné","Rekonstrukce","Neaktivní","Obsazenost"]} rows={data.propertyRows.map((row)=>[<Link key="p" href={`/nemovitosti/${row.property.id}/jednotky`}>{row.property.name}</Link>,row.units.total,row.units.rentable,row.units.occupied,row.units.vacant,row.units.renovation,row.units.inactive,row.units.rentable?`${Math.round((row.units.occupied??0)*100/row.units.rentable)} %`:"—"])} rowHrefs={data.propertyRows.map((row)=>`/nemovitosti/${row.property.id}/jednotky`)}/><div className="card report-chart-card"><div className="report-chart-heading"><div><h2>Historie obsazenosti · {range.label}</h2><p className="muted-copy">Stav vždy ke konci měsíce; aktuální měsíc k LIVE datu. Neprůkazná starší provozní historie zůstává jako mezera.</p></div><ReportPeriodPicker view="occupancy" range={range} properties={selectionValue}/></div><OccupancyChart data={data.occupancyTrend}/></div></>}
    {view==="collections"&&<><Kpis items={[["Předpis kvartálu",money(a.quarterExpectedCents),<WalletCards key="i"/>],["Uhrazeno",money(a.quarterPaidCents),<TrendingUp key="i"/>],["Inkaso",a.collectionRateBps===null?"—":`${(a.collectionRateBps/100).toFixed(1)} %`,<BarChart3 key="i"/>],["Po splatnosti",money(a.overdueDebtCents),<WalletCards key="i"/>]]}/><Table title="Inkaso podle nemovitostí" headers={["Nemovitost","Předpis kvartálu","Uhrazeno","Inkaso","Po splatnosti"]} rows={data.propertyRows.map((row)=>[row.property.name,money(row.collections.quarterExpectedCents??0),money(row.collections.quarterPaidCents??0),row.collections.collectionRateBps===null?"—":`${(row.collections.collectionRateBps/100).toFixed(1)} %`,money(row.collections.overdueDebtCents??0)])} rowHrefs={data.propertyRows.map((row)=>`/nemovitosti/${row.property.id}/predpisy`)}/><div className="card report-chart-card"><div className="report-chart-heading"><div><h2>Inkaso · {range.label}</h2><p className="muted-copy">Současný pohled na předpisy a aktuálně alokované úhrady; nejde o immutable historický snapshot.</p></div><ReportPeriodPicker view="collections" range={range} properties={selectionValue}/></div><CollectionChart data={data.trend}/></div></>}
    {view==="tenancy"&&<><Kpis items={[["Aktivní smlouvy",String(a.activeLeases),<CalendarClock key="i"/>],["Weighted čisté nájemné Kč/m²",a.weightedRentPerM2Cents===null?"—":money(a.weightedRentPerM2Cents),<TrendingUp key="i"/>],["Průměrná délka vztahu",a.averageActiveDays===null?"—":`${a.averageActiveDays} dní`,<CalendarClock key="i"/>],["Nové smlouvy YTD",String(a.newLeasesYtd),<CalendarClock key="i"/>],["Ukončené YTD",String(a.endedYtd),<CalendarClock key="i"/>],["Expirace 90 dní",String(a.expiring90Days),<CalendarClock key="i"/>]]}/><Table title="Aktivní nájemní vztahy" headers={["Nájemník","Nemovitost","Jednotka","m²","Začátek","Konec","Čisté nájemné","Kč/m²","Služby","Kauce sjednána","Kauce držena","Dluh"]} rows={data.tenancyRows.map((row)=>[<Link key="t" href={`/najemnici/${row.tenantId}`}>{row.tenantName}</Link>,row.propertyName,<Link key="u" href={`/nemovitosti/${row.propertyId}/jednotky/${row.unitId}`}>{row.unitLabel}</Link>,row.areaM2??"—",date(row.startDate),row.endDate?date(row.endDate):"—",money(row.netRentCents),row.rentPerM2Cents===null?"—":money(row.rentPerM2Cents),money(row.servicesCents),money(row.agreedDepositCents),money(row.heldDepositCents),money(row.debtCents)])} rowHrefs={data.tenancyRows.map((row)=>`/smlouvy/${row.leaseId}`)}/></>}
    {view==="benchmark"&&<MfBenchmark data={data}/>}
    {view==="deposits"&&<><Kpis className="deposit-kpis" items={[["Sjednané kauce",money(a.agreedDepositCents),<ShieldCheck key="i"/>],["Skutečně drženo",money(a.heldDepositCents),<ShieldCheck key="i"/>],["Chybí složit",money(a.missingDepositCents),<WalletCards key="i"/>],["K vypořádání",`${a.toSettleLeases} ${a.toSettleLeases===1?"smlouva":a.toSettleLeases>1&&a.toSettleLeases<5?"smlouvy":"smluv"}`,<WalletCards key="i"/>]]}/><Table title="Kauce" headers={["Nájemník","Nemovitost / jednotka","Stav smlouvy","Sjednáno","Drženo","Chybí","Stav kauce","K vrácení dnes","Detail"]} rows={data.depositRows.map((row)=>[row.tenantName,`${row.propertyName} · ${row.unitLabel}`,leaseStatuses[row.leaseStatus]||row.leaseStatus,money(row.agreedCents),money(row.heldCents),money(row.missingCents),securityDepositStatuses[row.depositStatus],money(row.amountToReturnCents),<Link key="d" href={`/smlouvy/${row.leaseId}#kauce`}>Otevřít</Link>])} rowHrefs={data.depositRows.map((row)=>`/smlouvy/${row.leaseId}#kauce`)}/></>}
    {view==="contracts"&&<><Kpis items={[["Aktivní",String(a.activeLeases),<CalendarClock key="i"/>],["Budoucí",String(a.futureLeases),<CalendarClock key="i"/>],["Expirace do 90 dní",String(a.expiring90Days),<CalendarClock key="i"/>],["Ukončené YTD",String(a.endedYtd),<CalendarClock key="i"/>]]}/><Table title="Smlouvy" headers={["Nemovitost","Jednotka","Nájemník","Číslo smlouvy","Začátek","Efektivní konec","Stav","Nájem","Kauce","Alert"]} rows={data.contractRows.map((row)=>[row.propertyName,<Link key="u" href={`/nemovitosti/${row.propertyId}/jednotky/${row.unitId}`}>{row.unitLabel}</Link>,row.tenantName,row.contractNumber||"—",date(row.startDate),row.effectiveEnd?date(row.effectiveEnd):"—",leaseStatuses[row.status]||row.status,money(row.rentCents),money(row.depositCents),row.expiring90Days?"Do 90 dní":row.endedYtd?"Ukončeno YTD":"—"])} rowHrefs={data.contractRows.map((row)=>`/smlouvy/${row.leaseId}`)}/></>}
  </div></Shell>;
}
function Kpis({items,className=""}:{items:Array<[string,string,React.ReactNode]>;className?:string}){return <div className={`stat-grid v21-stat-grid ${className}`.trim()}>{items.map(([label,value,icon])=><div className="card stat" key={label}><div className="stat-icon blue">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>)}</div>}
function Table({title,headers,rows,rowHrefs}:{title:string;headers:string[];rows:React.ReactNode[][];rowHrefs?:Array<string|null>}){return <div className="card portfolio-table-card report-table-card"><div className="table-toolbar"><h2>{title}</h2></div><div className="table-wrap"><table><thead><tr>{headers.map((header)=><th key={header}>{header}</th>)}</tr></thead><tbody>{rows.length?rows.map((row,index)=>rowHrefs?.[index]?<NavigableTableRow href={rowHrefs[index]!} key={index}>{row.map((cell,column)=><td key={column}>{cell}</td>)}</NavigableTableRow>:<tr key={index}>{row.map((cell,column)=><td key={column}>{cell}</td>)}</tr>):<tr><td colSpan={headers.length} className="table-empty">Bez záznamů</td></tr>}</tbody></table></div></div>}
function PropertyPerformance({rows}:{rows:Awaited<ReturnType<typeof loadLiveReport>>["propertyRows"]}){return <Table title="Výkonnost nemovitostí" headers={["Nemovitost","Obsazeno / pronajímatelné","Obsazenost","Čisté nájemné / měsíc","Inkaso kvartálu","Dluh","Držené kauce","Smlouvy do 90 dní"]} rows={rows.map((row)=>[<Link key="p" href={`/nemovitosti/${row.property.id}/prehled`}>{row.property.name}</Link>,`${row.units.occupied} / ${row.units.rentable}`,row.units.rentable?`${Math.round((row.units.occupied??0)*100/row.units.rentable)} %`:"—",money(row.rentRoll.monthlyNetRentCents??0),row.collections.collectionRateBps===null?"—":`${(row.collections.collectionRateBps/100).toFixed(1)} %`,money(row.collections.overdueDebtCents??0),money(row.deposits.heldPrincipalCents??0),row.leases.expiring90Days])} rowHrefs={rows.map((row)=>`/nemovitosti/${row.property.id}/prehled`)}/>}
function MfBenchmark({data}:{data:Awaited<ReturnType<typeof loadLiveReport>>}){const mf=data.mfBenchmark,a=mf.aggregate,period=mf.release?`Q${mf.release.marketQuarter} ${mf.release.marketYear}`:"Nedostupný";const pct=(value:number|null)=>value===null?"—":`${(value/100).toFixed(1)} %`;return <><Kpis items={[["Skutečné čisté nájemné / m²",a.actualRentPerM2Cents===null?"—":money(a.actualRentPerM2Cents),<TrendingUp key="i"/>],["MF referenční nájemné / m²",a.marketRentPerM2Cents===null?"—":money(a.marketRentPerM2Cents),<BarChart3 key="i"/>],["Nájem / MF trh",pct(a.rentToMarketBps),<TrendingUp key="i"/>],["Potenciál / měsíc",a.coveredUnits?money(a.reversionaryPotentialCents):"—",<WalletCards key="i"/>],["Pokrytí plochy",pct(a.coverageBps),<Home key="i"/>],["Datové období MF",period,<CalendarClock key="i"/>]]}/>{!mf.release&&<div className="notice">Pro zvolený LIVE pohled zatím není dostupný žádný publikovaný dataset MF.</div>}<MfBenchmarkTable properties={mf.propertyRows} units={mf.rows}/><p className="muted-copy">Kliknutím na nemovitost rozbalíte benchmark jednotlivých bytových jednotek. Srovnání je pouze ke čtení z čistého nájemného bez služeb. Kladný potenciál znamená, že MF reference je nad aktuálním nájemným; záporná hodnota znamená nájem nad referencí. Zdrojem je poslední publikované období MF nejvýše k LIVE datu. Benchmark nikdy nemění smlouvy ani předpisy.</p></>}
function QualityPanel({issues,entities,user}:{issues:Awaited<ReturnType<typeof loadLiveReport>>["quality"];entities:Awaited<ReturnType<typeof loadLiveReport>>["qualityEntities"];user:Parameters<typeof reportingQualityIssueTarget>[1]}){const groups=groupReportingQualityIssues(issues);return <details className="card quality-panel"><summary>Datová konzistence · {issues.length} upozornění</summary><div className="quality-list">{groups.length?groups.map((group)=><details className="quality-group" key={group.code}><summary><strong>{group.label}</strong><span> · {group.occurrences.length} {group.occurrences.length===1?"případ":group.occurrences.length<5?"případy":"případů"}</span></summary><div className="quality-occurrences">{group.occurrences.map((issue,index)=>{const target=reportingQualityIssueTarget(issue,user);return <div className={`quality-occurrence ${issue.severity}`} key={`${issue.propertyId}:${issue.unitId}:${issue.leaseId}:${index}`}><div><strong>{issue.propertyId?entities.properties[issue.propertyId]||"Neznámá nemovitost":"Neznámá nemovitost"}</strong>{issue.unitId&&<span>Jednotka: {entities.units[issue.unitId]||"neznámá"}</span>}{issue.leaseId&&<span>Smlouva: {entities.leases[issue.leaseId]||issue.leaseId}</span>}<p>{group.description}</p></div>{target&&<Link className="table-link quality-action" href={target.href}>{target.actionLabel}</Link>}</div>})}</div></details>):<p>Bez upozornění.</p>}</div></details>}
