import Link from "next/link";
import { Shell } from "@/components/Shell";
import { PageHeading } from "@/components/PageHeading";
import { Flash } from "@/components/FormUi";
import { TenantAnnouncementForm } from "@/components/TenantAnnouncementForm";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { date } from "@/lib/format";
import { tenantAnnouncementManagerScope } from "@/lib/tenant-portal-messages";

export const dynamic = "force-dynamic";
export default async function TenantAnnouncementsPage({ searchParams }: { searchParams: Promise<{ ok?: string; error?: string; leaseId?: string }> }) {
  const user = await requireUser();
  const query = await searchParams;
  const scope = await tenantAnnouncementManagerScope(user);
  const announcements = await prisma.announcement.findMany({ where: scope.where, include: { audiences: { include: { property: { select: { name: true } }, lease: { select: { unit: { select: { label: true, property: { select: { name: true } } } }, tenant: { select: { name: true } } } } } }, createdBy: { select: { name: true } }, _count: { select: { userStates: { where: { readAt: { not: null } } } } } }, orderBy: { createdAt: "desc" } });
  const now = new Date();
  return <Shell user={user}><div className="page announcements-page"><div className="breadcrumb"><Link href="/ukoly/oznameni">Oznámení</Link><span>›</span><span>Nájemníkům</span></div><div className="page-title"><div><PageHeading>Oznámení nájemníkům</PageHeading><p>Sdělení do portálu nájemníka pro konkrétní nájem nebo celý dům.</p></div></div><Flash ok={query.ok} error={query.error}/><div className="detail-grid"><div className="col-5">{scope.properties.length || scope.leases.length ? <TenantAnnouncementForm key={query.leaseId || "all"} initialLeaseId={query.leaseId} properties={scope.properties.map(item => ({ value: `property:${item.id}`, label: item.name }))} leases={scope.leases.map(item => ({ value: `lease:${item.id}`, label: `${item.unit.property.name} · ${item.unit.label} · ${item.tenant.name}` }))}/> : <div className="card"><p>K zveřejnění potřebujete právo editace domu nebo jednotky s aktuální smlouvou.</p></div>}</div><div className="col-7 stack-column">{announcements.map(item => <article className="card" id={item.id} key={item.id}><div className="card-head"><h2>{item.title}</h2><span className="status">{!item.active ? "Staženo z portálu" : item.startsAt > now ? "Naplánováno" : item.expiresAt && item.expiresAt <= now ? "V archivu" : "Zveřejněno"}</span></div><p style={{ whiteSpace: "pre-wrap" }}>{item.body}</p><p className="muted-copy">{item.audiences.map(audience => audience.kind === "TENANT_PROPERTY" ? `Nájemníci domu ${audience.property?.name}` : `${audience.lease?.unit.property.name} · ${audience.lease?.unit.label} · ${audience.lease?.tenant.name}`).join(" · ")}</p><p>{item.createdBy.name} · od {date(item.startsAt)}{item.expiresAt ? ` do ${date(item.expiresAt)}` : " · bez omezení"} · přečetlo {item._count.userStates}</p><details><summary>Upravit sdělení</summary><form className="form-grid" action={`/api/tenant-announcements/${item.id}`} method="post"><input type="hidden" name="action" value="edit"/><input type="hidden" name="revision" value={item.updatedAt.toISOString()}/><label className="field field-full"><span>Název</span><input name="title" required maxLength={200} defaultValue={item.title}/></label><label className="field field-full"><span>Sdělení</span><textarea name="body" rows={4} required maxLength={5000} defaultValue={item.body}/></label><p>Po úpravě se oznámení znovu nabídne k přečtení.</p><button className="primary">Uložit sdělení</button></form></details><form action={`/api/tenant-announcements/${item.id}`} method="post"><input type="hidden" name="action" value={item.active ? "deactivate" : "activate"}/><input type="hidden" name="revision" value={item.updatedAt.toISOString()}/><button className="secondary">{item.active ? "Stáhnout z portálu" : "Znovu zveřejnit"}</button></form></article>)}{!announcements.length && <div className="card"><h2>Zatím žádná oznámení nájemníkům</h2><p>Nové sdělení můžete zveřejnit formulářem vlevo.</p></div>}</div></div></div></Shell>;
}
