// Approved prototype adapted for authenticated private use. No keys or map pixels are bundled.
export const houseAvatarTemplate = [
  "<!doctype html>",
  "<html lang=\"cs\">",
  "<head>",
  "<meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">",
  "<meta name=\"referrer\" content=\"strict-origin-when-cross-origin\">",
  "<title>FlatBerry · Test 3D pohledu</title>",
  "<style>",
  ":root{font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif;color:#19334a;background:#f4f6f8;font-size:15px}*{box-sizing:border-box}body{margin:0}button,input,select{font:inherit}button,select,input{border:1px solid #cbd7df;border-radius:9px;padding:11px 13px;background:white;color:inherit}button{cursor:pointer;font-weight:600}button:hover:enabled{border-color:#27664e;background:#f2faf6}button:disabled{opacity:.45;cursor:not-allowed}button.primary{background:#215b46;color:white;border-color:#215b46}input,select{width:100%;margin-top:6px}input[type=checkbox]{width:auto;margin:0 8px 0 0}input[type=range]{padding:0;accent-color:#215b46}input:focus-visible,button:focus-visible,select:focus-visible,a:focus-visible{outline:3px solid #70b3eb;outline-offset:2px}header{padding:24px max(24px,calc((100vw - 1260px)/2));border-bottom:1px solid #e0e6eb;background:white;display:flex;align-items:center;justify-content:space-between;gap:16px}.brand{font-size:24px;font-weight:750;letter-spacing:-1px}.brand span{color:#54876d}.badge{font-size:12px;border-radius:20px;padding:6px 11px;background:#e9f0ec;color:#27664e;letter-spacing:.05em}main{max-width:1308px;padding:28px 24px;margin:auto}.intro{margin-bottom:24px}.intro h1{font-size:30px;margin:0 0 9px;letter-spacing:-.8px}.intro p{margin:0;color:#607284;line-height:1.5}.layout{display:grid;grid-template-columns:345px minmax(0,1fr);gap:20px}.card{background:white;border:1px solid #e0e6eb;border-radius:16px;padding:22px}.stack{display:grid;gap:18px;align-content:start}h2{font-size:17px;margin:0 0 15px}h3{font-size:15px;margin:0 0 10px}label{display:block;font-size:13px;font-weight:600;line-height:1.5}.help,small{font-size:12px;color:#657586;line-height:1.55}.help{margin:8px 0 14px}.buttons{display:flex;gap:8px;flex-wrap:wrap}.buttons button{flex:1}.full{width:100%}.divider{height:1px;background:#e3e9ed;margin:20px 0}.status{border-left:3px solid #597b99;padding:13px 15px;background:#edf3f8;border-radius:8px;font-size:13px;line-height:1.5;margin-bottom:16px}.status.error{background:#fff1ef;border-color:#ae4b3c}.status.good{background:#eef6ef;border-color:#41815e}.status.warn{background:#fff6e5;border-color:#ac7d25}#viewport{height:500px;background:#edf1f4;border:1px solid #dde5eb;position:relative;border-radius:12px;overflow:hidden}#map{width:100%;height:100%}gmp-map-3d{display:block;width:100%;height:100%}#empty{position:absolute;inset:0;display:grid;place-content:center;text-align:center;padding:30px;pointer-events:none}#empty strong{font-size:20px;display:block;margin:14px 0 8px}#empty p{max-width:320px;margin:0;line-height:1.55;color:#6a7b8b;font-size:14px}.house{font-size:38px;color:#678b7c}#empty[hidden],*[hidden]{display:none!important}.views{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:16px 0}.view{padding:15px 8px;text-align:left}.view b{display:block;font-size:13px;margin-bottom:5px}.view span{font-size:20px;font-weight:400}.view[aria-pressed=true]{border:2px solid #2c7458;background:#edf7f1;padding:14px 7px}.view em{display:block;font-size:11px;font-style:normal;margin-top:5px;color:#607284}.field{margin-bottom:15px}.row{display:flex;justify-content:space-between;gap:12px}.choice{display:grid;grid-template-columns:1fr 1fr;gap:10px}.review[aria-pressed=true]{background:#eaf3ee;border-color:#2c7458}.notice{padding:14px 16px;border-radius:10px;background:#fff5e6;margin-top:14px;line-height:1.55;font-size:14px}.success{background:#ebf5ee}#resolved{font-size:13px;color:#607284;line-height:1.5;margin:9px 0 0}.check{display:flex;align-items:start;font-weight:400;font-size:14px;margin:16px 0}.check input{margin-top:5px;flex:none}details{font-size:13px;line-height:1.6}summary{cursor:pointer;font-weight:600}details ol{padding-left:20px}a{color:#28654e}code{font-size:12px;overflow-wrap:anywhere}#log{font:12px/1.6 ui-monospace,monospace;white-space:pre-wrap;max-height:190px;overflow:auto;color:#647787}footer{margin:22px 0 0;color:#7b8997;font-size:12px;line-height:1.6}.muted{color:#728291}#selection{margin-top:15px}#candidates{margin-top:15px}@media(max-width:850px){.layout{grid-template-columns:1fr}.stack{gap:14px}#viewport{height:440px}main{padding:24px 16px}.intro h1{font-size:26px}}@media(max-width:480px){.views{gap:6px}.view span{font-size:17px}.card{padding:16px}header{padding:20px 16px}#viewport{height:360px}.choice{grid-template-columns:1fr}}",
  "#crop-overlay{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}#crop-options{margin-top:16px;padding-top:12px;border-top:1px solid #e3e9ed}#crop-options .check{margin:0 0 12px}#crop-size{max-width:320px}#crop-readout{font-size:12px;color:#657586}",
  "</style>",
  "<style>",
  ":root {font-family:Inter,system-ui,sans-serif;color:#152b4d;background:#f7f9fe} main{padding:0;max-width:none}.layout{grid-template-columns:minmax(250px,320px) minmax(0,1fr)}.card{border-color:#dfe8f7;border-radius:18px}.primary,button.primary{background:#2468ff;border-color:#2468ff}button:hover:enabled{border-color:#2468ff;background:#edf3ff}button.primary:hover:enabled{background:#1856da;color:white}.view[aria-pressed=true]{border-color:#2468ff;background:#edf3ff}input[type=range]{accent-color:#2468ff}a{color:#2468ff}#viewport{height:560px} @media(max-width:820px){.layout{grid-template-columns:1fr}#viewport{height:450px}}",
  "</style></head>",
  "<body>",
  "",
  "<main>",
  "  ",
  "  <div class=\"layout\">",
  "    <aside class=\"stack\">",
  "      <section class=\"card\">",
  "        <h2>1. Připojení a adresa</h2>",
  "        <label for=\"key\">Google Maps API klíč</label>",
  "        <input id=\"key\" type=\"password\" autocomplete=\"off\" spellcheck=\"false\" placeholder=\"Vložte klíč pro tento test\">",
  "        <p class=\"help\">Klíč se ukládá šifrovaně jen k vašemu administrátorskému účtu. Mapové SDK jej při použití odešle Googlu.</p>",
  "        <div class=\"buttons\"><button id=\"save-key\" type=\"button\">Uložit klíč</button><button id=\"change-key\" type=\"button\">Změnit</button><button id=\"forget-key\" type=\"button\">Zapomenout</button></div><p id=\"key-state\" class=\"help\" role=\"status\">Ověřuji uložené nastavení…</p><label for=\"address\">Adresa domu v ČR</label>",
  "        <input id=\"address\" value=\"Onšovecká 427, Praha\" autocomplete=\"street-address\">",
  "        <button id=\"search\" class=\"primary full\" style=\"margin-top:12px\">Vyhledat adresu</button>",
  "        <div id=\"candidates\" hidden>",
  "          <label for=\"results\">Nalezená adresa</label><select id=\"results\"></select>",
  "          <button id=\"load\" class=\"full\" style=\"margin-top:10px\">Zobrazit vybranou adresu</button>",
  "        </div>",
  "        <div class=\"divider\"></div>",
  "        <button id=\"preset\" class=\"full\">Rychlý test: Onšovecká 427</button>",
  "        <p class=\"help\">Použije předem dohledané souřadnice. Stačí Maps JavaScript API, vyhledávání adres nepotřebuje.</p>",
  "        <label for=\"coordinates\" style=\"margin-top:16px\">Nebo souřadnice (šířka, délka)</label><input id=\"coordinates\" placeholder=\"50.0772314, 14.6446833\"><button id=\"load-coordinates\" class=\"full\" style=\"margin-top:8px\">Zobrazit souřadnice</button><p class=\"help\">Vyhledávání adres může být u demo klíče omezené. Rychlý test a souřadnice geokódování nepotřebují.</p><details><summary>Jak spustit test</summary>",
  "          <ol>",
  "            <li>Pro rychlý test Onšovecké můžete použít bezplatný <a href=\"https://developers.google.com/maps/documentation/javascript/demo-key\" target=\"_blank\" rel=\"noreferrer\">Maps Demo Key</a>. Pro standardní klíč povolte v Google Cloud projektu s fakturací <b>Maps JavaScript API</b> a pro vyhledávání adres také <b>Geocoding API</b>.</li>",
  "            <li>API klíč omezte na tyto služby a na adresu, kde test běží. Lokálně například <code>http://localhost:8080/*</code>.</li>",
  "            <li>Vložte klíč výše a klikněte na rychlý test. Po načtení vyberte správný dům a prohlédněte čtyři strany.</li>",
  "          </ol>",
  "          <p>Potřebujete prohlížeč s WebGL2 a zapnutou hardwarovou akcelerací. Demo klíč má bezplatné denní limity; standardní klíč se účtuje podle projektu. Prototyp vytváří jednu mapu a směry přepíná v ní.</p>",
  "          <p><a href=\"https://developers.google.com/maps/documentation/javascript/3d/get-started\" target=\"_blank\" rel=\"noreferrer\">Dokumentace Google 3D Maps</a></p>",
  "        </details>",
  "      </section>",
  "      <section class=\"card\">",
  "        <h2>Doladění pohledu</h2>",
  "        <div class=\"field\"><label class=\"row\" for=\"bearing\">Základní natočení <output id=\"bearing-value\">45°</output></label><input id=\"bearing\" type=\"range\" min=\"0\" max=\"359\" step=\"1\" value=\"45\" disabled></div>",
  "        <div class=\"field\"><label class=\"row\" for=\"range\">Vzdálenost kamery <output id=\"range-value\">110 m</output></label><input id=\"range\" type=\"range\" min=\"30\" max=\"600\" step=\"5\" value=\"110\" disabled></div>",
  "        <div class=\"field\"><label class=\"row\" for=\"tilt\">Náklon od svislice <output id=\"tilt-value\">55°</output></label><input id=\"tilt\" type=\"range\" min=\"30\" max=\"75\" step=\"1\" value=\"55\" disabled></div>",
  "        <div class=\"field\"><label class=\"row\" for=\"height\">Bod pohledu nad terénem <output id=\"height-value\">8 m</output></label><input id=\"height\" type=\"range\" min=\"0\" max=\"100\" step=\"1\" value=\"8\" disabled></div>",
  "        <button id=\"recenter\" class=\"full\" disabled>Upřesnit dům kliknutím do mapy</button>",
  "        <p class=\"help\">Natočením srovnejte ulici přibližně do diagonály. Všechny čtyři varianty zachovají stejný střed, vzdálenost a náklon.</p>",
  "      </section>",
  "    </aside>",
  "    <div class=\"stack\">",
  "      <section class=\"card\">",
  "        <h2>2. Prohlédněte dům ze čtyř stran</h2>",
  "        <div id=\"status\" class=\"status\" role=\"status\" aria-live=\"polite\">Připraveno k testu. Vložte API klíč a načtěte adresu.</div>",
  "        <div id=\"viewport\">",
  "          <div id=\"map\"></div>",
  "          <svg id=\"crop-overlay\" aria-hidden=\"true\" hidden>",
  "            <path id=\"crop-mask\" fill=\"rgba(9,20,31,.62)\" fill-rule=\"evenodd\"></path>",
  "            <rect id=\"crop-outline\" fill=\"none\" stroke=\"rgba(9,20,31,.85)\" stroke-width=\"12\"></rect>",
  "            <rect id=\"crop-dash\" fill=\"none\" stroke=\"white\" stroke-width=\"8\" stroke-dasharray=\"20 13\"></rect>",
  "          </svg>",
  "          <div id=\"empty\"><div class=\"house\">⌂</div><strong>Tady se zobrazí skutečná mapa</strong><p>Po připojení načteme místo z Google 3D Maps. Zatím nejsou načtena žádná mapová data.</p></div>",
  "        </div>",
  "        <div id=\"crop-options\">",
  "          <label class=\"check\"><input id=\"crop-visible\" type=\"checkbox\" checked><span>Zobrazit čtvercový rám a ztlumit okolí</span></label>",
  "          <label class=\"row\" for=\"crop-size\">Velikost výřezu <output id=\"crop-size-value\">100 %</output></label>",
  "          <input id=\"crop-size\" type=\"range\" min=\"55\" max=\"100\" step=\"1\" value=\"100\">",
  "          <p id=\"crop-readout\">Poměr stran 1 : 1</p>",
  "          <p class=\"help\">Umístěte celý dům dovnitř rámu s malým odstupem od okrajů. Mapu můžete ovládat i přes masku. Rám slouží k výběru kompozice.</p>",
  "        </div>",
  "        <p id=\"resolved\">Výchozí test: Onšovecká 427, Praha · dostupnost 3D zatím neověřena.</p>",
  "        <div class=\"views\" role=\"group\" aria-label=\"Čtyři úhly pohledu\">",
  "          <button class=\"view\" data-index=\"0\" aria-pressed=\"true\" disabled><b>Pohled A</b><span>45°</span><em>základní směr</em></button>",
  "          <button class=\"view\" data-index=\"1\" aria-pressed=\"false\" disabled><b>Pohled B</b><span>135°</span><em>+90°</em></button>",
  "          <button class=\"view\" data-index=\"2\" aria-pressed=\"false\" disabled><b>Pohled C</b><span>225°</span><em>+180°</em></button>",
  "          <button class=\"view\" data-index=\"3\" aria-pressed=\"false\" disabled><b>Pohled D</b><span>315°</span><em>+270°</em></button>",
  "        </div>",
  "        <p class=\"help\">Jeden živý náhled, čtyři přepínatelné směry. U každého porovnejte fasádu a střechu; preferovaný pohled zvolíte níže.</p>",
  "      </section>",
  "      <section class=\"card\">",
  "        <h2>3. Potvrďte výsledek</h2>",
  "        <label class=\"check\"><input id=\"confirmed\" type=\"checkbox\" disabled><span>Ve středu mapy je správný dům a snímek je dostatečně detailní.</span></label>",
  "        <div class=\"choice\"><button id=\"has3d\" class=\"review\" aria-pressed=\"false\" disabled>Vidím prostorové fasády a střechu</button><button id=\"flat\" class=\"review\" aria-pressed=\"false\" disabled>Dům je pouze plochý snímek</button></div>",
  "        <p class=\"help\">V této první verzi posuzuje 3D uživatel. Dokončené vykreslení samo o sobě nepotvrzuje 3D model budovy. Prázdnou, rozmazanou či chybovou mapu neoznačujte jako plochou.</p>",
  "        <div id=\"fallback\" class=\"notice\" hidden>Pro tento dům jste označili pouze plochý podklad. Z tohoto pohledu avatar nevytvoříme. Nahrajte do FlatBerry vlastní titulní fotografii domu.</div>",
  "        <button id=\"select\" class=\"primary full\" disabled>Použít tento pohled</button>",
  "        <div id=\"selection\" class=\"notice success\" role=\"status\" hidden></div>",
  "        <button id=\"export-crop\" class=\"primary full\" style=\"margin-top:14px\" disabled>Připravit výřez (PNG)</button>",
  "        <p class=\"help\">Prohlížeč vás požádá o sdílení této karty. Snímek se zpracuje pouze ve vašem prohlížeči. Vyberte právě tuto kartu Flatberry, nikoli celé okno nebo jinou kartu.</p>",
  "        <div id=\"export-result\" hidden><h3>Lokální náhled výřezu</h3><img id=\"export-preview\" alt=\"Skutečný vybraný výřez domu se zdrojovou lištou\" style=\"display:block;width:min(100%,400px);height:auto\"><label class=\"check\"><input type=\"checkbox\" id=\"export-confirm\"><span>Výřez ukazuje správný dům, neobsahuje ovladače a zdrojová lišta je úplná a čitelná.</span></label><button id=\"download-crop\" disabled>Stáhnout výřez (PNG)</button><p>Stažený obrázek vložte do ChatGPT Work a požádejte dovednost „flatberry-avatary-domu“ o jedno překreslení ve schváleném stylu. Tato aplikace AI generování nespouští.</p></div>",
  "      </section>",
  "      <details class=\"card\"><summary>Diagnostika testu</summary><pre id=\"log\">Čeká se na první test.</pre><p class=\"help\">Výsledek platí jen pro tuto relaci. Prototyp neukládá mapové podklady ani nevytváří AI obrázek.</p></details>",
  "    </div>",
  "  </div>",
  "  <footer>Flatberry · Soukromý výběr pohledu<br>Soukromý test výřezu. Podmínky dalšího použití mapových podkladů ještě nejsou uzavřené; tento nástroj není potvrzením licence. Placené Google ani AI služby se zde neaktivují.</footer>",
  "</main>",
  "<script id=\"probe-core\">",
  "/* FlatBerry 3D probe — independent state and camera logic. */",
  "globalThis.FlatBerryProbe = (() => {",
  "  const initial = () => ({ phase: 'idle', coverage: 'unknown', targetConfirmed: false, selected: null });",
  "  function reduce(state, event) {",
  "    switch (event.type) {",
  "      case 'START': return { ...initial(), phase: 'loading' };",
  "      case 'MOVING': return { ...state, phase: 'loading', targetConfirmed: false, coverage: 'unknown', selected: null };",
  "      case 'STEADY': return state.phase === 'error' ? state : { ...state, phase: 'ready' };",
  "      case 'TIMEOUT': return state.phase === 'loading' ? { ...state, phase: 'timeout', selected: null } : state;",
  "      case 'ERROR': return { ...initial(), phase: 'error' };",
  "      case 'CONFIRM_TARGET': return { ...state, targetConfirmed: event.value, coverage: 'unknown', selected: null };",
  "      case 'REVIEW':",
  "        if (state.phase !== 'ready' || !state.targetConfirmed || !['3d', 'flat', 'unknown'].includes(event.value)) return state;",
  "        return { ...state, coverage: event.value, selected: null };",
  "      case 'SELECT': return canSelect(state) ? { ...state, selected: event.camera } : state;",
  "      default: return state;",
  "    }",
  "  }",
  "  const canSelect = state => state.phase === 'ready' && state.targetConfirmed && state.coverage === '3d';",
  "  const showFallback = state => state.phase === 'ready' && state.targetConfirmed && state.coverage === 'flat';",
  "  const headings = base => Array.from({ length: 4 }, (_, i) => ((Number(base) + i * 90) % 360 + 360) % 360);",
  "  function cameraFor(target, base, index, range, tilt, height, altitudeMode) {",
  "    if (!target || !Number.isFinite(target.lat) || !Number.isFinite(target.lng) ||",
  "        Math.abs(target.lat) > 90 || Math.abs(target.lng) > 180 ||",
  "        !Number.isFinite(base) || !Number.isInteger(index) || index < 0 || index > 3 ||",
  "        !Number.isFinite(range) || range < 30 || range > 600 ||",
  "        !Number.isFinite(tilt) || tilt < 30 || tilt > 75 ||",
  "        !Number.isFinite(height) || height < 0 || height > 100) throw new Error('Neplatné nastavení kamery.');",
  "    return { center: { lat: target.lat, lng: target.lng, altitude: height },",
  "      altitudeMode, heading: headings(base)[index], range, tilt, roll: 0 };",
  "  }",
  "  return { initial, reduce, canSelect, showFallback, headings, cameraFor };",
  "})();",
  "",
  "</script>",
  "<script id=\"probe-app\">",
  "(() => {",
  "  'use strict';",
  "  const P = globalThis.FlatBerryProbe, $ = id => document.getElementById(id);",
  "  const views = [...document.querySelectorAll('.view')];",
  "  const controls = ['bearing', 'range', 'tilt', 'height'];",
  "  let state = P.initial(), map = null, mapAbort = null, library = null, target = null;",
  "  let sdkPromise = null, loadedKey = '', run = 0, index = 0, busy = false, timer = null;",
  "  let results = [], picking = false, animationDone = false, steady = false, chosenCamera = null;",
  "  const lines = [];",
  "  function log(message) {",
  "    lines.push(new Date().toLocaleTimeString('cs-CZ') + ' · ' + message);",
  "    $('log').textContent = lines.slice(-35).join('\\n');",
  "  }",
  "  function message(text, kind = '') { $('status').textContent = text; $('status').className = 'status ' + kind; }",
  "  function dispatch(event) { state = P.reduce(state, event); refresh(); }",
  "  function cropBounds() {",
  "    const width = $('viewport').clientWidth, height = $('viewport').clientHeight;",
  "    // Reserve a clear bottom strip for Google's attribution and controls.",
  "    const edge = Math.max(0, Math.min(width - 48, height - 176)) * +$('crop-size').value / 100;",
  "    return { x: (width - edge) / 2, y: (height - edge) / 2, width: edge, height: edge, viewportWidth: width, viewportHeight: height };",
  "  }",
  "  function updateCrop() {",
  "    const c = cropBounds(), w = c.viewportWidth, h = c.viewportHeight;",
  "    $('crop-overlay').toggleAttribute('hidden', !map || !$('crop-visible').checked);",
  "    $('crop-overlay').setAttribute('viewBox', `0 0 ${w} ${h}`);",
  "    // Even-odd fill leaves the square clear. No pixels of the map are extracted.",
  "    $('crop-mask').setAttribute('d', `M0 0H${w}V${Math.max(0,h-76)}H0Z M${c.x} ${c.y}h${c.width}v${c.height}h${-c.width}Z`);",
  "    for (const id of ['crop-outline', 'crop-dash']) {",
  "      for (const name of ['x', 'y', 'width', 'height']) $(id).setAttribute(name, String(c[name]));",
  "    }",
  "    $('crop-size-value').textContent = $('crop-size').value + ' %';",
  "    $('crop-readout').textContent = `Poměr stran 1 : 1 · ${Math.round(c.width)} × ${Math.round(c.height)} px v náhledu`;",
  "  }",
  "  function refresh() {",
  "    const active = Boolean(map) && state.phase !== 'error';",
  "    controls.forEach(id => { $(id).disabled = !active || busy; });",
  "    views.forEach((button, i) => {",
  "      button.disabled = !active || busy;",
  "      button.setAttribute('aria-pressed', String(index === i));",
  "      button.querySelector('span').textContent = P.headings(+$('bearing').value)[i] + '°';",
  "    });",
  "    $('search').disabled = busy; $('preset').disabled = busy; $('load').disabled = busy;",
  "    $('key').disabled = busy || Boolean(sdkPromise); $('address').disabled = busy;",
  "    $('results').disabled = busy; $('confirmed').disabled = state.phase !== 'ready';",
  "    $('confirmed').checked = state.targetConfirmed;",
  "    $('recenter').disabled = !active || busy;",
  "    for (const [id, value] of [['has3d', '3d'], ['flat', 'flat']]) {",
  "      $(id).disabled = state.phase !== 'ready' || !state.targetConfirmed;",
  "      $(id).setAttribute('aria-pressed', String(state.coverage === value));",
  "    }",
  "    $('fallback').hidden = !P.showFallback(state);",
  "    $('select').disabled = !P.canSelect(state);",
  "    $('export-crop').disabled = !state.selected || state.phase !== 'ready';",
  "    $('selection').hidden = !state.selected;",
  "    controls.forEach(id => { $(id + '-value').textContent = $(id).value + (['bearing', 'tilt'].includes(id) ? '°' : ' m'); });",
  "    updateCrop();",
  "  }",
  "  function fail(text) {",
  "    clearTimeout(timer); dispatch({ type: 'ERROR' });",
  "    message(text + ' Dostupnost 3D domu z této chyby nelze určit.', 'error'); log(text);",
  "  }",
  "  function webglAvailable() {",
  "    const canvas = document.createElement('canvas');",
  "    const gl = canvas.getContext('webgl2');",
  "    if (!gl) return false;",
  "    gl.getExtension('WEBGL_lose_context')?.loseContext();",
  "    return true;",
  "  }",
  "  function loadSDK(key) {",
  "    if (sdkPromise) {",
  "      if (loadedKey !== key) throw new Error('Pro změnu použijte tlačítko Změnit klíč.');",
  "      return sdkPromise;",
  "    }",
  "    loadedKey = key;",
  "    sdkPromise = new Promise((resolve, reject) => {",
  "      let settled = false;",
  "      const timeout = setTimeout(() => done(new Error('Načítání API překročilo 25 sekund. Ověřte připojení a obnovte stránku.')), 25000);",
  "      function done(error) {",
  "        if (settled) return;",
  "        settled = true; clearTimeout(timeout);",
  "        error ? reject(error) : resolve();",
  "      }",
  "      window.flatberryMapsLoaded = () => done();",
  "      window.gm_authFailure = () => {",
  "        const error = new Error('Google odmítl API klíč, jeho omezení nebo fakturaci. Opravte konfiguraci a obnovte stránku.');",
  "        done(error); fail(error.message);",
  "      };",
  "      const script = document.createElement('script');",
  "      const params = new URLSearchParams({ key, v: 'weekly', loading: 'async', callback: 'flatberryMapsLoaded', language: 'cs', region: 'CZ' });",
  "      script.src = 'https://maps.googleapis.com/maps/api/js?' + params;",
  "      script.async = true;",
  "      script.onerror = () => done(new Error('Nepodařilo se stáhnout Google Maps API. Zkontrolujte síť nebo blokování skriptů a obnovte stránku.'));",
  "      document.head.append(script);",
  "    });",
  "    return sdkPromise;",
  "  }",
  "  async function withTimeout(promise, label, ms = 25000) {",
  "    let timeout;",
  "    try { return await Promise.race([promise, new Promise((_, reject) => { timeout = setTimeout(() => reject(new Error(label)), ms); })]); }",
  "    finally { clearTimeout(timeout); }",
  "  }",
  "  async function prepare() {",
  "    const response = await fetch('/api/admin/skills/maps-key?use=sdk', {cache:'no-store'});",
  "    if (!response.ok) throw new Error('Klíč není dostupný. Ukončete případný náhled uživatele a ověřte přihlášení.');",
  "    const key = (await response.json()).key;",
  "    if (key) $('key').value = '';",
  "    if (!key) throw new Error('Nejdřív uložte svůj Google Maps demo klíč.');",
  "    if (!webglAvailable()) throw new Error('Tento prohlížeč neposkytuje WebGL2. Zkuste aktuální Chrome nebo Edge se zapnutou hardwarovou akcelerací.');",
  "    log('WebGL2 kontext byl vytvořen. Připojuji Google Maps JavaScript API.');",
  "    await loadSDK(key);",
  "    if (state.phase === 'error') throw new Error('API hlásí chybu. Opravte konfiguraci a obnovte stránku.');",
  "    library = await withTimeout(google.maps.importLibrary('maps3d'), 'Knihovna 3D se nenačetla včas. Obnovte stránku.');",
  "    log('Knihovna maps3d načtena. To ještě nepotvrzuje 3D pokrytí.');",
  "  }",
  "  function disposeMap() {",
  "    run++; clearTimeout(timer); mapAbort?.abort(); mapAbort = null;",
  "    map?.remove(); map = null; target = null; chosenCamera = null;",
  "    picking = false; $('recenter').textContent = 'Upřesnit dům kliknutím do mapy';",
  "    $('empty').hidden = false; animationDone = false; steady = false;",
  "  }",
  "  async function action(task) {",
  "    if (busy) return;",
  "    disposeMap(); dispatch({ type: 'START' }); busy = true; refresh();",
  "    $('candidates').hidden = true;",
  "    message('Ověřuji prohlížeč a připojení k mapové službě…');",
  "    try { await prepare(); await task(); }",
  "    catch (error) { fail(safeError(error)); }",
  "    finally { busy = false; refresh(); }",
  "  }",
  "  function safeError(error) {",
  "    // Never put SDK request URLs or keys into diagnostics.",
  "    const text = String(error?.message || error?.code || error || 'Neznámá chyba.');",
  "    return text.replaceAll(loadedKey || '\\0', '[API klíč]').replace(/https?:\\/\\/\\S+/g, '[odkaz]').slice(0, 500);",
  "  }",
  "  function armTimer() {",
  "    clearTimeout(timer);",
  "    timer = setTimeout(() => {",
  "      dispatch({ type: 'TIMEOUT' });",
  "      if (state.phase === 'timeout') {",
  "        message('Mapa se do 40 sekund neustálila. Může jít o síť, výkon nebo data; 3D pokrytí zatím neznáme. Můžete vyčkat nebo test spustit znovu.', 'warn');",
  "        log('Časový limit vykreslení. Pokrytí nevyhodnoceno.');",
  "      }",
  "    }, 40000);",
  "  }",
  "  function rendered() {",
  "    if (!steady || state.phase === 'error' || !map || !chosenCamera) return;",
  "    // A completed render is sufficient; zero-duration camera moves need not animate.",
  "    const center = map.center;",
  "    if (!center || Math.abs(center.lat-chosenCamera.center.lat)>0.00001 || Math.abs(center.lng-chosenCamera.center.lng)>0.00001) return;",
  "    animationDone = true;",
  "    clearTimeout(timer); dispatch({ type: 'STEADY' });",
  "    message('Scéna je vykreslena. Zkontrolujte správný dům a potvrďte, zda má prostorové fasády.', 'good');",
  "    log('Scéna ustálena; 3D model domu musí potvrdit uživatel.');",
  "  }",
  "  function moveCamera() {",
  "    if (!map || state.phase === 'error') return;",
  "    try {",
  "      chosenCamera = P.cameraFor(target, +$('bearing').value, index, +$('range').value,",
  "        +$('tilt').value, +$('height').value, library.AltitudeMode.RELATIVE_TO_GROUND);",
  "      animationDone = false; steady = false; dispatch({ type: 'MOVING' });",
  "      message('Načítám pohled ' + 'ABCD'[index] + ' (' + chosenCamera.heading + '°)…');",
  "      armTimer();",
  "      map.flyCameraTo({ endCamera: chosenCamera, durationMillis: 500 });",
  "    } catch (error) { fail(safeError(error)); }",
  "  }",
  "  function mount(location, label, note = '') {",
  "    disposeMap(); target = { lat: location.lat, lng: location.lng }; index = 0;",
  "    dispatch({ type: 'START' });",
  "    $('resolved').textContent = label + (note ? ' · ' + note : '');",
  "    // Start safely above Czech terrain, then resolve the target relative to ground.",
  "    // center.altitude in the constructor is ABSOLUTE; never use 0 as Czech ground level.",
  "    map = new library.Map3DElement({ center: { ...target, altitude: 3000 }, range: 5000, tilt: 0,",
  "      defaultUIHidden: true, mode: library.MapMode.SATELLITE, gestureHandling: library.GestureHandling.COOPERATIVE,",
  "      description: 'Dům pro FlatBerry: ' + label });",
  "    const currentRun = run; const currentMap = map;",
  "    mapAbort = new AbortController();",
  "    function listen(name, callback) {",
  "      currentMap.addEventListener(name, event => { if (currentRun === run && map === currentMap) callback(event); }, { signal: mapAbort.signal });",
  "    }",
  "    listen('gmp-error', () => fail('3D mapa se nedokázala inicializovat. Zkontrolujte nastavení API a konzoli prohlížeče.'));",
  "    listen('gmp-steadychange', event => {",
  "      steady = event.isSteady === true;",
  "      if (!steady && state.phase === 'ready') { dispatch({ type: 'MOVING' }); armTimer(); }",
  "      rendered();",
  "    });",
  "    listen('gmp-animationend', () => { animationDone = true; rendered(); });",
  "    listen('gmp-centerchange', () => {",
  "      // Manual panning can move to another building. Require a fresh review.",
  "      if (animationDone) dispatch({ type: 'CONFIRM_TARGET', value: false });",
  "    });",
  "    listen('gmp-click', event => {",
  "      if (!picking || !event.position) return;",
  "      target = { lat: event.position.lat, lng: event.position.lng };",
  "      picking = false; $('recenter').textContent = 'Upřesnit dům kliknutím do mapy';",
  "      dispatch({ type: 'CONFIRM_TARGET', value: false });",
  "      log('Uživatel upřesnil střed domu kliknutím do mapy.'); moveCamera();",
  "    });",
  "    $('map').replaceChildren(map); $('empty').hidden = true;",
  "    log('3D mapa vytvořena, čekám na cílovou scénu.');",
  "    moveCamera(); refresh();",
  "  }",
  "  $('preset').addEventListener('click', () => action(async () => {",
  "    $('address').value = 'Onšovecká 427, Praha';",
  "    mount({ lat: 50.0772314, lng: 14.6446833 }, 'Onšovecká 427, Praha', 'předem dohledaná poloha, ověřte správnou budovu');",
  "  }));",
  "  $('search').addEventListener('click', () => {",
  "    const address = $('address').value.trim();",
  "    if (!address) { message('Zadejte ulici, číslo domu a obec.', 'warn'); return; }",
  "    action(async () => {",
  "      message('Vyhledávám adresu v České republice…');",
  "      const response = await withTimeout(fetch('/api/admin/skills/geocode', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({address}), cache:'no-store'}), 'Vyhledání adresy překročilo časový limit.');",
  "      const data = await response.json();",
  "      if (!response.ok) throw new Error(data.error || 'Vyhledávání není dostupné. Použijte souřadnice.');",
  "      results = data.results || [];",
  "      if (!results.length) throw new Error('Adresa nebyla nalezena. Upřesněte číslo domu a obec.');",
  "      $('results').replaceChildren(...results.map((result, i) => {",
  "        const option = document.createElement('option'); option.value = String(i);",
  "        option.textContent = result.label + ' — ' + result.note; return option;",
  "      }));",
  "      $('candidates').hidden = false;",
  "      message('Vyberte nalezenou adresu a klikněte na „Zobrazit vybranou adresu“.');",
  "      clearTimeout(timer); log('Vyhledání dokončeno. Čekám na výběr adresy.');",
  "    });",
  "  });",
  "  $('load').addEventListener('click', () => {",
  "    const result = results[+$('results').value]; if (!result || busy) return;",
  "    try {",
  "      const loc = result.location;",
  "      mount(loc, result.label, result.note);",
  "    } catch (error) { fail(safeError(error)); }",
  "  });",
  "  views.forEach(button => button.addEventListener('click', () => { index = +button.dataset.index; moveCamera(); }));",
  "  controls.forEach(id => { $(id).addEventListener('input', refresh); $(id).addEventListener('change', moveCamera); });",
  "  $('recenter').addEventListener('click', () => {",
  "    picking = !picking; $('recenter').textContent = picking ? 'Zrušit upřesnění domu' : 'Upřesnit dům kliknutím do mapy';",
  "    if (picking) message('Klikněte na střed správného domu. Potom znovu potvrďte budovu a 3D.');",
  "  });",
  "  $('confirmed').addEventListener('change', () => dispatch({ type: 'CONFIRM_TARGET', value: $('confirmed').checked }));",
  "  $('has3d').addEventListener('click', () => dispatch({ type: 'REVIEW', value: '3d' }));",
  "  $('flat').addEventListener('click', () => dispatch({ type: 'REVIEW', value: 'flat' }));",
  "  $('load-coordinates').addEventListener('click', () => {",
  "    const values = $('coordinates').value.trim().split(/[,;\\s]+/).map(Number);",
  "    if(values.length !== 2 || !values.every(Number.isFinite) || Math.abs(values[0]) > 90 || Math.abs(values[1]) > 180) { message('Zadejte dvě platné souřadnice: šířku a délku.', 'warn'); return; }",
  "    action(async () => mount({lat:values[0],lng:values[1]}, $('address').value.trim() || 'Vybraná poloha'));",
  "  });",
  "  $('select').addEventListener('click', () => {",
  "    if (!P.canSelect(state) || !map) return;",
  "    // Read the actual camera so manual map gestures are reflected in the selection.",
  "    const camera = { center: { lat: map.center.lat, lng: map.center.lng, altitude: map.center.altitude },",
  "      heading: map.heading, tilt: map.tilt, range: map.range, roll: map.roll || 0,",
  "      altitudeMode: library.AltitudeMode.ABSOLUTE, coverageEvidence: 'user-confirmed', crop: cropBounds() };",
  "    dispatch({ type: 'SELECT', camera });",
  "    $('selection').textContent = 'Pohled a čtvercový výřez vybrány pro tuto relaci (' + Math.round(camera.heading) + '°). 3D potvrdil uživatel. Nyní můžete připravit PNG výřez.';",
  "    window.dispatchEvent(new CustomEvent('flatberry:view-selected', { detail: camera }));",
  "    log('Uživatel vybral pohled. Žádný snímek nebyl exportován.');",
  "  });",
  "  $('crop-visible').addEventListener('change', updateCrop);",
  "  $('crop-size').addEventListener('input', () => {",
  "    state = { ...state, selected: null }; refresh();",
  "  });",
  "  new ResizeObserver(() => {",
  "    // A changed viewport changes the composition; discard a stale selection.",
  "    state = { ...state, selected: null }; refresh();",
  "  }).observe($('viewport'));",
  "",
  "  let exportBlobUrl = null;",
  "  let exportFilename = 'flatberry-dum.png';",
  "  const captureNonce = 'flatberry-' + crypto.randomUUID();",
  "  const topMedia = window.top.navigator.mediaDevices;",
  "  const captureSupported = Boolean(navigator.mediaDevices?.getDisplayMedia && topMedia?.setCaptureHandleConfig);",
  "  if (captureSupported) topMedia.setCaptureHandleConfig({handle:captureNonce,exposeOrigin:true,permittedOrigins:[location.origin]});",
  "  function discardExport() {",
  "    if (exportBlobUrl) URL.revokeObjectURL(exportBlobUrl);",
  "    exportBlobUrl = null; $('export-result').hidden = true; $('export-confirm').checked = false; $('download-crop').disabled = true;",
  "  }",
  "  async function keyStatus() {",
  "    try {",
  "      const response = await fetch('/api/admin/skills/maps-key', {cache:'no-store'});",
  "      if(!response.ok) throw new Error();",
  "      const {configured} = await response.json();",
  "      $('key').placeholder = configured ? '•••••••• — klíč je uložený' : 'Vložte demo klíč';",
  "      $('key-state').textContent = configured ? 'Soukromý klíč je uložený a použije se automaticky.' : 'Zatím není uložený klíč.';",
  "      $('forget-key').disabled = !configured;",
  "    } catch { $('key-state').textContent = 'Nastavení není dostupné. Ověřte přihlášení administrátora.'; }",
  "  }",
  "  $('save-key').addEventListener('click', async () => {",
  "    const key = $('key').value.trim(); if(!key) { $('key-state').textContent='Nejdřív vložte klíč.'; return; }",
  "    try {",
  "      const response = await fetch('/api/admin/skills/maps-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})});",
  "      if(!response.ok) { $('key-state').textContent=(await response.json()).error || 'Uložení se nezdařilo.'; return; }",
  "      $('key').value=''; location.reload();",
  "    } catch { $('key-state').textContent='Uložení se nezdařilo. Zkontrolujte připojení.'; }",
  "  });",
  "  $('change-key').addEventListener('click', () => { $('key').disabled=false; $('key').value=''; $('key').focus(); $('key-state').textContent='Vložte nový klíč a zvolte Uložit klíč. Mapa se poté obnoví.'; });",
  "  $('forget-key').addEventListener('click', async () => {",
  "    try {",
  "      const response=await fetch('/api/admin/skills/maps-key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'forget'})});",
  "      if(!response.ok) throw new Error();",
  "      location.reload();",
  "    } catch { $('key-state').textContent='Klíč se nepodařilo zapomenout. Zkuste to znovu.'; }",
  "  });",
  "  $('export-confirm').addEventListener('change', () => { $('download-crop').disabled=!exportBlobUrl || !$('export-confirm').checked; });",
  "  $('download-crop').addEventListener('click', () => {",
  "    if(!exportBlobUrl || !$('export-confirm').checked) return;",
  "    const link=document.createElement('a'); link.href=exportBlobUrl; link.download=exportFilename; link.click();",
  "  });",
  "  $('export-crop').addEventListener('click', async () => {",
  "    if (!state.selected || !map || state.phase !== 'ready') return;",
  "    if (!captureSupported) { message('Export vyžaduje aktuální desktopový Chrome nebo Edge s podporou zachycení této karty. Vybraný pohled zůstává zachovaný.', 'warn'); return; }",
  "    let stream = null, video = null;",
  "    const selected = state.selected;",
  "    discardExport();",
  "    try {",
  "      // Must be called directly from the user's click. Do not automate or bypass consent.",
  "      stream = await navigator.mediaDevices.getDisplayMedia({video:{displaySurface:'browser'},audio:false,preferCurrentTab:true,selfBrowserSurface:'include',surfaceSwitching:'exclude',monitorTypeSurfaces:'exclude',systemAudio:'exclude'});",
  "      const track=stream.getVideoTracks()[0];",
  "      if(track.getSettings().displaySurface !== 'browser' || track.getCaptureHandle?.()?.handle !== captureNonce || track.getCaptureHandle?.()?.origin !== location.origin) throw new Error('Vyberte právě tuto kartu Flatberry. Jiná karta ani celé okno se nezpracují.');",
  "      // Only hide the selection overlay; Google's attribution remains visible.",
  "      $('crop-overlay').style.visibility='hidden';",
  "      const viewport=$('viewport'); viewport.scrollIntoView({block:'center'});",
  "      video=document.createElement('video'); video.muted=true; video.srcObject=stream; await video.play();",
  "      await new Promise((resolve,reject)=> { const t=setTimeout(()=>reject(new Error('Sdílená karta neposkytla obraz.')),10000); video.requestVideoFrameCallback(()=>video.requestVideoFrameCallback(()=>{clearTimeout(t);resolve();})); });",
  "      if(state.selected !== selected || state.phase !== 'ready') throw new Error('Pohled se změnil. Potvrďte výběr a export opakujte.');",
  "      const frame=window.frameElement?.getBoundingClientRect() || {left:0,top:0};",
  "      const rect=viewport.getBoundingClientRect();",
  "      const c=cropBounds();",
  "      const left=frame.left+rect.left, top=frame.top+rect.top;",
  "      if(left<0 || top<0 || left+rect.width>window.top.innerWidth+1 || top+rect.height>window.top.innerHeight+1) throw new Error('Celá mapa včetně spodní zdrojové lišty se musí vejít do okna. Zvětšete okno nebo snižte přiblížení stránky.');",
  "      const sx=video.videoWidth/window.top.innerWidth, sy=video.videoHeight/window.top.innerHeight;",
  "      if(Math.abs(sx-sy)>0.04) throw new Error('Poměr zachycené karty neodpovídá náhledu. Export opakujte bez změny velikosti okna.');",
  "      const canvas=document.createElement('canvas'); canvas.width=canvas.height=1024;",
  "      const ctx=canvas.getContext('2d'); if(!ctx) throw new Error('Prohlížeč neumí vytvořit PNG.');",
  "      ctx.fillStyle='white'; ctx.fillRect(0,0,1024,1024);",
  "      // Preserve the actual rendered source strip, not a invented replacement attribution.",
  "      const sourceHeight=76, footer=Math.ceil(1024*sourceHeight/rect.width), picture=1024-footer;",
  "      ctx.drawImage(video,(left+c.x)*sx,(top+c.y)*sy,c.width*sx,c.height*sy,(1024-picture)/2,0,picture,picture);",
  "      ctx.drawImage(video,left*sx,(top+rect.height-sourceHeight)*sy,rect.width*sx,sourceHeight*sy,0,picture,1024,footer);",
  "      const pixels=ctx.getImageData(Math.ceil((1024-picture)/2),0,Math.floor(picture),Math.floor(picture)).data; let min=255,max=0;",
  "      for(let i=0;i<pixels.length;i+=64){min=Math.min(min,pixels[i]);max=Math.max(max,pixels[i]);}",
  "      if(max-min<12) throw new Error('Výřez je prázdný nebo jednolitý. Vyčkejte na dokončení mapy.');",
  "      let blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png')); if(!blob) throw new Error('PNG se nepodařilo vytvořit.');",
  "      for (const quality of [0.95,0.9,0.85,0.8]) { if(blob.size<=2000000) break; blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality)); if(!blob) throw new Error('JPG se nepodařilo vytvořit.'); }",
  "      if(blob.size>2000000) throw new Error('Výřez překročil 2 MB. Zvolte menší výřez a zkuste znovu.');",
  "      exportBlobUrl=URL.createObjectURL(blob);",
  "      exportFilename=($('address').value.normalize('NFKD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-|-$/g,'').slice(0,90)||'flatberry-dum')+(blob.type==='image/jpeg'?'.jpg':'.png');",
  "      $('export-preview').src=exportBlobUrl; $('export-result').hidden=false;",
  "      message('Výřez je připravený pouze v tomto prohlížeči. Zkontrolujte dům i úplnost zdrojové lišty a potvrďte stažení.','good');",
  "    } catch(error) { message(error.name==='NotAllowedError' ? 'Sdílení nebylo povoleno. Pohled zůstává zachovaný; export můžete opakovat.' : safeError(error), 'warn'); }",
  "    finally { stream?.getTracks().forEach(track=>track.stop()); if(video)video.srcObject=null; $('crop-overlay').style.visibility=''; }",
  "  });",
  "  window.addEventListener('beforeunload',discardExport);",
  "  keyStatus();",
  "  refresh();",
  "})();",
  "",
  "</script>",
  "</body>",
  "</html>"
].join("\n");
