import { DocumentCategory, Prisma } from "@prisma/client";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { documentAccessWhere } from "@/lib/documents/access";
import { Shell } from "@/components/Shell";
import { DocumentAttachments } from "@/components/documents/DocumentAttachments";

export const dynamic="force-dynamic";
export default async function DocumentsPage({searchParams}:{searchParams:Promise<{q?:string;property?:string;category?:string;type?:string;page?:string}>}){const user=await requireUser();const q=await searchParams;const page=Math.max(1,Number(q.page)||1);const filters:Prisma.DocumentWhereInput={...documentAccessWhere(user),...(q.property?{propertyId:q.property}:{}),...(q.category&&Object.values(DocumentCategory).includes(q.category as DocumentCategory)?{category:q.category as DocumentCategory}:{}),...(q.type?{fileAsset:{mimeType:{startsWith:q.type==="image"?"image/":q.type}}}:{}),...(q.q?{OR:[{title:{contains:q.q,mode:"insensitive"}},{description:{contains:q.q,mode:"insensitive"}},{fileAsset:{originalName:{contains:q.q,mode:"insensitive"}}}]}:{})};const [documents,total,properties]=await Promise.all([prisma.document.findMany({where:filters,orderBy:{createdAt:"desc"},skip:(page-1)*50,take:50,include:{fileAsset:true,property:{select:{name:true}},unit:{select:{label:true}},lease:{select:{contractNumber:true}},task:{select:{title:true}},complianceRecord:{select:{id:true}}}}),prisma.document.count({where:filters}),prisma.property.findMany({where:{documents:{some:documentAccessWhere(user)}},select:{id:true,name:true},orderBy:{name:"asc"}})]);return <Shell user={user}><div className="page"><div className="page-title"><div><h1>Dokumenty</h1><p>Soukromý katalog smluv, protokolů, fotografií a příloh, ke kterým máte přístup.</p></div></div><form className="card filter-row" method="get"><input name="q" defaultValue={q.q} placeholder="Hledat název nebo soubor"/><select name="property" defaultValue={q.property||""}><option value="">Všechny nemovitosti</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="category" defaultValue={q.category||""}><option value="">Všechny kategorie</option>{Object.values(DocumentCategory).map(c=><option key={c}>{c}</option>)}</select><select name="type" defaultValue={q.type||""}><option value="">Všechny typy</option><option value="image">Fotografie</option><option value="application/pdf">PDF</option></select><button className="secondary">Filtrovat</button></form><div className="card"><div className="card-head"><h2>Nalezené dokumenty</h2><span>{total}</span></div><DocumentAttachments documents={documents}/>{total>50&&<div className="pagination"><a href={`?${new URLSearchParams({...q,page:String(Math.max(1,page-1))})}`}>Předchozí</a><span>{page} / {Math.ceil(total/50)}</span><a href={`?${new URLSearchParams({...q,page:String(page+1)})}`}>Další</a></div>}</div></div></Shell>}
