import Link from "next/link";
import {redirect} from "next/navigation";
import {CalendarClock,Handshake,Plus,UserRound,Users} from "lucide-react";
import {Shell} from "@/components/Shell";
import {Flash} from "@/components/FormUi";
import {canSeeAll,requireUser} from "@/lib/auth";
import {prisma} from "@/lib/db";
import {date,money} from "@/lib/format";
import {dateInput,moneyInput} from "@/lib/forms";
import {distributionOpportunityStages} from "@/lib/distribution/crm";

export const dynamic="force-dynamic";
export default async function DistributionCrmPage({searchParams}:{searchParams:Promise<{ok?:string;error?:string}>}){const[user,query]=await Promise.all([requireUser(),searchParams]);if(!canSeeAll(user.role))redirect("/portfolio");const[prospects,properties]=await Promise.all([prisma.distributionProspect.findMany({where:{active:true},include:{opportunities:{include:{unit:{include:{property:{select:{id:true,name:true,flatcloudConsolidationBasisPoints:true}}}}},orderBy:[{nextActionAt:"asc"},{updatedAt:"desc"}]}},orderBy:{name:"asc"}}),prisma.property.findMany({where:{active:true,flatcloudConsolidationBasisPoints:{gt:0}},select:{id:true,name:true,units:{select:{id:true,label:true,valuationSnapshots:{orderBy:[{valuationDate:"desc"},{createdAt:"desc"}],take:1}}}},orderBy:{name:"asc"}})]);const opportunities=prospects.flatMap((prospect)=>prospect.opportunities.map((opportunity)=>({prospect,...opportunity}))).filter((item)=>(item.unit.property.flatcloudConsolidationBasisPoints||0)>0),open=opportunities.filter((item)=>!['WON','LOST'].includes(item.stage)),now=new Date(),overdue=open.filter((item)=>item.nextActionAt&&item.nextActionAt<now),units=properties.flatMap((property)=>property.units.map((unit)=>({property,...unit})));
return <Shell user={user}><div className="page distribution-crm-page"><div className="breadcrumb"><Link href="/distribuce">Kategorizace a distribuce</Link><span>›</span><span>Zájemci</span></div><div className="page-title"><div><h1>CRM zájemců o jednotky</h1><p>Interní pipeline kontaktů, prohlídek, nabídek a rezervací pro potvrzená aktiva FlatCloud.</p></div><div className="action-row"><Link className="secondary" href="/distribuce/reporting">Reportovací podklady</Link><Link className="secondary" href="/distribuce">Zpět na jednotky</Link></div></div><Flash ok={query.ok} error={query.error}/>
  <div className="stat-grid v21-stat-grid distribution-crm-kpis"><Stat label="Aktivní zájemci" value={String(prospects.length)} icon={<Users/>}/><Stat label="Otevřené příležitosti" value={String(open.length)} icon={<Handshake/>}/><Stat label="Nabídky / rezervace" value={String(open.filter((item)=>item.stage==="OFFER"||item.stage==="RESERVED").length)} icon={<UserRound/>}/><Stat label="Další krok po termínu" value={String(overdue.length)} icon={<CalendarClock/>}/></div>
  <div className="notice"><strong>Interní osobní údaje · bez veřejného publikování</strong><span>Kontakt je dostupný pouze interním správcům. Založení nebo změna příležitosti neposílá e-mail, nevytváří rezervaci v právním smyslu a nezveřejňuje jednotku.</span></div>
  <div className="distribution-crm-create"><details className="card create-panel"><summary><Plus size={15}/> Nový zájemce</summary><form action="/api/distribution/prospects" method="post" className="form-grid"><label className="field"><span>Jméno / název *</span><input name="name" required/></label><label className="field"><span>E-mail</span><input name="email" type="email"/></label><label className="field"><span>Telefon</span><input name="phone"/></label><label className="field"><span>Zdroj kontaktu</span><input name="source" placeholder="Doporučení, web, makléř…"/></label><label className="field field-full"><span>Poznámka</span><textarea name="note" rows={2}/></label><button className="primary field-full" type="submit">Přidat zájemce</button></form></details>
  <details className="card create-panel"><summary><Plus size={15}/> Nový zájem o jednotku</summary><form action="/api/distribution/opportunities" method="post" className="form-grid"><label className="field"><span>Zájemce *</span><select name="prospectId" required><option value="">Vyberte zájemce</option>{prospects.map((prospect)=><option value={prospect.id} key={prospect.id}>{prospect.name}</option>)}</select></label><label className="field"><span>Jednotka *</span><select name="unitId" required><option value="">Vyberte jednotku</option>{units.map((unit)=><option value={unit.id} key={unit.id}>{unit.property.name} · {unit.label}</option>)}</select></label><label className="field"><span>Fáze *</span><select name="stage" defaultValue="NEW">{Object.entries(distributionOpportunityStages).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>Nabídková cena Kč</span><input name="askingPrice" type="number" min="0.01" step="0.01"/></label><label className="field"><span>Nabídka zájemce Kč</span><input name="offeredPrice" type="number" min="0.01" step="0.01"/></label><label className="field"><span>Další krok k datu</span><input name="nextActionAt" type="date"/></label><label className="field field-full"><span>Poznámka</span><textarea name="note" rows={2}/></label><button className="primary field-full" type="submit" disabled={!prospects.length||!units.length}>Založit příležitost</button></form></details></div>
  <section className="card portfolio-table-card"><div className="table-toolbar"><div><h2>Prodejní pipeline</h2><p>Každý řádek spojuje jednoho zájemce s jednou konkrétní jednotkou.</p></div></div><div className="table-wrap"><table><thead><tr><th>Zájemce</th><th>Jednotka</th><th>Fáze</th><th>Nabídková cena</th><th>Nabídka zájemce</th><th>Další krok</th><th>Kontakt</th><th></th></tr></thead><tbody>{opportunities.length?opportunities.map((item)=>{const isOverdue=item.nextActionAt&&item.nextActionAt<now&&!['WON','LOST'].includes(item.stage);return <tr key={item.id} className={isOverdue?"row-debt":""}><td><strong>{item.prospect.name}</strong><span className="owner-sub">{item.prospect.source||"Zdroj neuveden"}</span></td><td><Link className="entity-link" href={`/nemovitosti/${item.unit.property.id}/jednotky/${item.unitId}`}>{item.unit.property.name} · {item.unit.label}</Link></td><td><span className={`status ${item.stage==="WON"?"ok":item.stage==="LOST"?"":item.stage==="RESERVED"?"warn":""}`}>{distributionOpportunityStages[item.stage]}</span></td><td>{item.askingPriceCents?money(Number(item.askingPriceCents)):"—"}</td><td>{item.offeredPriceCents?money(Number(item.offeredPriceCents)):"—"}</td><td>{item.nextActionAt?<strong className={isOverdue?"negative":""}>{date(item.nextActionAt)}</strong>:"Nenastaven"}</td><td><span>{item.prospect.email||item.prospect.phone||"—"}</span></td><td><details className="crm-opportunity-edit"><summary>Upravit</summary><form action={`/api/distribution/opportunities/${item.id}`} method="post"><label className="field"><span>Fáze *</span><select name="stage" defaultValue={item.stage}>{Object.entries(distributionOpportunityStages).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span>Nabídková cena Kč</span><input name="askingPrice" type="number" min="0.01" step="0.01" defaultValue={moneyInput(item.askingPriceCents?Number(item.askingPriceCents):null)}/></label><label className="field"><span>Nabídka zájemce Kč</span><input name="offeredPrice" type="number" min="0.01" step="0.01" defaultValue={moneyInput(item.offeredPriceCents?Number(item.offeredPriceCents):null)}/></label><label className="field"><span>Další krok k datu</span><input name="nextActionAt" type="date" defaultValue={dateInput(item.nextActionAt)}/></label><label className="field"><span>Poznámka</span><textarea name="note" rows={2} defaultValue={item.note||""}/></label><button className="primary" type="submit">Uložit fázi a další krok</button></form></details></td></tr>}):<tr><td className="table-empty" colSpan={8}>Zatím není založený žádný zájem o jednotku.</td></tr>}</tbody></table></div></section>
</div></Shell>}
function Stat({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="card stat"><div className="stat-icon blue">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
