import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Shell } from '@/components/Shell';
import { Flash } from '@/components/FormUi';
import { requireUser } from '@/lib/auth';
import { documentAccessWhere } from '@/lib/documents/access';
import { prisma } from '@/lib/db';
import { sourceAccess, sourcePropertyWhere } from '@/lib/settlement-sources';
import { OWNER_COST_WARNING,SOURCE_SERVICES,lineReadiness,type SourcePayload } from '@/lib/settlement-source-rules';
import { date } from '@/lib/format';
export default async function SourceDetail({params,searchParams}:{params:Promise<{id:string;sourceId:string}>;searchParams:Promise<{ok?:string;error?:string}>}){
 const actor=await requireUser(),{id,sourceId}=await params,q=await searchParams;await sourceAccess(actor,id).catch(()=>notFound());
 const s=await prisma.settlementSource.findFirst({where:{id:sourceId,propertyId:id},include:{document:{include:{fileAsset:true}},next:true,createdBy:{select:{name:true}},confirmedBy:{select:{name:true}},allocationBatches:{include:{rows:true}}}});if(!s)notFound();
 const p=s.payload as unknown as SourcePayload;const canEdit=await prisma.property.findFirst({where:{id,...sourcePropertyWhere(actor,true)},select:{id:true}});const [units,rules]=await Promise.all([prisma.unit.findMany({where:{propertyId:id},select:{id:true,label:true}}),prisma.settlementAllocationRule.findMany({where:{propertyId:id,active:true},orderBy:{validFrom:"desc"}})]);const hasOriginal=s.documentId?await prisma.document.findFirst({where:{id:s.documentId,...documentAccessWhere(actor),fileAsset:{deletedAt:null}},select:{id:true}}):null;
 return <Shell user={actor} taskPropertyId={id}><div className="page"><div className="breadcrumb"><Link href={`/nemovitosti/${id}/vyuctovani/podklady`}>← Podklady vyúčtování</Link></div><div className="page-title"><div><h1>{p.vendor} · {p.reference}</h1><p>Verze {s.version} · {p.mode==='HOUSE'?'Celý dům':'Jednotka – externí vyúčtování'} · {p.from} – {p.to}</p></div><span className={`status ${s.confirmedAt?'ok':'warn'}`}>{s.confirmedAt?'Údaje potvrzeny':'Návrh – nepotvrzeno'}</span></div><Flash ok={q.ok} error={q.error}/>
 <section className="card"><h2>Originál a kontrolní částky</h2><p>Náklad dodávky: <strong>{p.supplyAmount} Kč</strong> · dodavatelské zálohy pouze informativně: {p.supplierAdvances} Kč</p>{hasOriginal?<Link className="secondary" href={`/api/documents/${s.documentId}/download`}>Otevřít originál · {s.document!.title}</Link>:<p className="legal-warning">Originál chybí nebo není dostupný. Podklad nelze používat jako úplný; vytvořte opravu s dostupným originálem.</p>}{p.propertyCostId&&<p>Navázáno na již evidovaný náklad; potvrzení nezakládá nový náklad.</p>}{p.creditForId&&<Link href={`/nemovitosti/${id}/vyuctovani/podklady/${p.creditForId}`}>Původní faktura k dobropisu</Link>}</section>
 <section className="card"><h2>Řádky a použitelnost</h2>{p.lines.map(l=><div className="card" key={l.key}><h3>{l.key} · {SOURCE_SERVICES.find(x=>x[0]===l.service)?.[1]}</h3><p>{l.from} – {l.to} · {units.find(u=>u.id===l.unitId)?.label||'Celý dům'}{l.leaseId?` · smlouva ${l.leaseId}`:''}</p><p><strong>{l.amount} Kč</strong> · {s.confirmedAt&&hasOriginal?lineReadiness(p,l):'Čeká na potvrzení / dostupný originál'}</p>{l.role==='SUMMARY'&&<p>Informativní souhrn – nepřičítá se k nákladům.</p>}{(l.base||l.consumptionComponent||l.correction||l.rounding)&&<p>Základní: {l.base||'neuvedeno'} · spotřební: {l.consumptionComponent||'neuvedeno'} · korekce: {l.correction||'neuvedeno'} · zaokrouhlení: {l.rounding||'neuvedeno'} Kč. {l.componentsComplete?'Úplný rozpad ověřen proti částce řádku.':'Dílčí údaje zdroje; součet složek se nepovažuje za úplný rozpad.'}</p>}{l.quantity&&<p>Spotřeba: {l.quantity} {l.measure}</p>}{l.explanation&&<p>Rozdělení: {l.explanation}</p>}{l.ownerOverride&&<div className="legal-warning"><strong>{OWNER_COST_WARNING}</strong><p>Odůvodnění: {l.ownerReason}</p></div>}{!l.unitId&&l.role==="COST"&&s.confirmedAt&&(()=>{const batch=s.allocationBatches.find(b=>b.lineKey===l.key);const matching=rules.filter(r=>r.service===l.service&&r.validFrom<=new Date(l.to+"T23:59:59Z")&&(!r.validTo||r.validTo>=new Date(l.from+"T00:00:00Z")));return batch?<div className="notice"><strong>Rozdělení potvrzeno</strong><span>{batch.method} · {batch.rows.length} řádků · součet {(batch.rows.reduce((a,r)=>a+r.amountCents,0)/100).toLocaleString("cs-CZ")} Kč</span></div>:canEdit?<form className="compact-form" method="post" action={`/api/properties/${id}/settlement-sources/${sourceId}/allocate`}><input type="hidden" name="lineKey" value={l.key}/><label className="field"><span>Pravidlo rozdělení</span><select name="ruleId" required><option value="">Vyberte…</option>{matching.map(r=><option key={r.id} value={r.id}>{r.method} · od {r.validFrom.toLocaleDateString("cs-CZ")}</option>)}</select></label><button className="secondary">Spočítat a potvrdit rozdělení</button>{!matching.length&&<Link href={`/nemovitosti/${id}/vyuctovani/pravidla`}>Nejprve založit pravidlo →</Link>}</form>:null})()}</div>)}</section>
 <div className="notice"><strong>Potvrzení podkladu není vystavení vyúčtování</strong><p>Nevytváří předpis, kredit ani platbu. Teplo se nepřepočítává z ručních odečtů; přebírá se potvrzený odborný výsledek.</p></div>
 {canEdit&&!s.confirmedAt&&!s.next&&<form className="card" method="post" action={`/api/properties/${id}/settlement-sources/${sourceId}/confirm`}><h2>Kontrola originálu</h2><label className="checkbox-field"><input type="checkbox" name="confirm"/>Zkontroloval/a jsem originál, období, přiřazení, částky a náklad před odečtením dodavatelských záloh.</label>{p.lines.some(l=>l.ownerOverride)&&<div className="legal-warning"><strong>{OWNER_COST_WARNING}</strong><label className="checkbox-field"><input type="checkbox" name="ownerWarning"/>Beru na vědomí upozornění; potvrzení nemění právní přípustnost.</label></div>}<button className="primary">Potvrdit údaje podkladu</button></form>}
 <section className="card"><h2>Audit a opravy</h2><p>Uložil/a {s.createdBy.name} · {date(s.createdAt)}{s.confirmedAt?` · Potvrdil/a ${s.confirmedBy?.name} · ${date(s.confirmedAt)}`:''}</p>{p.revisionReason&&<p>Důvod opravy: {p.revisionReason}</p>}{s.previousId&&<Link className="secondary" href={`/nemovitosti/${id}/vyuctovani/podklady/${s.previousId}`}>Předchozí verze</Link>}{s.next?<Link className="secondary" href={`/nemovitosti/${id}/vyuctovani/podklady/${s.next.id}`}>Následující verze</Link>:canEdit&&<Link className="secondary" href={`/nemovitosti/${id}/vyuctovani/podklady?revise=${s.id}`}>Vytvořit opravu</Link>}<p>Uložené údaje se nepřepisují. Do potvrzení opravné verze zůstává předchozí potvrzená verze historickým zdrojem; budoucí rozúčtování musí výslovně zvolit aktuální verzi.</p></section>
 </div></Shell>;
}
