import React from "react";
import { Document, Font, Image, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";
import { ANNUAL_REPORT_COVER_PATH, REPORT_PDF_CONTENT_HEADER_PATH, REPORT_PDF_LOGO_REPORT_PATH, REPORT_PDF_LOGO_WHITE_PATH, REPORT_PDF_RALEWAY_BOLD_PATH, REPORT_PDF_RALEWAY_REGULAR_PATH } from "./assets";
import type { FrozenAnnualReportPdfData, FrozenAnnualReportPdfProperty } from "./annual-report-pdf-data";

export const ANNUAL_REPORT_PDF_RENDERER_VERSION = "r18b-annual-v2";
export const ANNUAL_REPORT_PAGE_SIZE = { width: 780, height: 540 } as const;
const FONT_FAMILY = "FlatCloudRalewayAnnual";
Font.register({ family: FONT_FAMILY, src: REPORT_PDF_RALEWAY_REGULAR_PATH });
Font.register({ family: FONT_FAMILY, src: REPORT_PDF_RALEWAY_BOLD_PATH, fontWeight: 700 });

const colors = { ink: "#231f20", muted: "#687386", primary: "#26639f", light: "#caddf2", pale: "#eef5fb", line: "#b9cce0", white: "#ffffff" };
const styles = StyleSheet.create({
  page: { fontFamily: FONT_FAMILY, fontSize: 9, lineHeight: 1.3, color: colors.ink, position: "relative", backgroundColor: colors.white },
  absolute: { position: "absolute" }, content: { position: "absolute", left: 48, right: 48, top: 132, bottom: 42 },
  footerLeft: { position: "absolute", left: 48, bottom: 18, color: colors.muted, fontSize: 7.5 }, footerRight: { position: "absolute", right: 48, bottom: 18, color: colors.muted, fontSize: 7.5 },
  masterLabel: { position: "absolute", left: 48, top: 27, color: colors.white, fontSize: 10, fontWeight: 700, letterSpacing: 0.5 },
  masterTitle: { position: "absolute", left: 48, top: 47, color: colors.white, fontSize: 24, fontWeight: 700 },
  masterLogo: { position: "absolute", right: 45, top: 29, width: 128, height: 24, objectFit: "contain", objectPosition: "right" },
  eyebrow: { color: colors.primary, fontSize: 8, fontWeight: 700, letterSpacing: 1.2, marginBottom: 7 }, h2: { fontSize: 12, fontWeight: 700, color: colors.primary, marginBottom: 6 }, body: { fontSize: 10, lineHeight: 1.35 }, muted: { color: colors.muted },
  draft: { alignSelf: "flex-start", color: colors.primary, backgroundColor: colors.pale, borderColor: colors.line, borderWidth: 0.6, paddingVertical: 4, paddingHorizontal: 8, fontSize: 7, fontWeight: 700, marginBottom: 10 },
  columns: { flexDirection: "row", gap: 24 }, column: { width: "48.2%" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  metric: { width: "23.3%", minHeight: 69, borderTopWidth: 5, borderTopColor: colors.primary, backgroundColor: colors.pale, paddingHorizontal: 9, paddingVertical: 8 },
  metricLabel: { fontSize: 7.2, color: colors.muted, minHeight: 20 }, metricValue: { fontSize: 13, fontWeight: 700, color: colors.primary, marginTop: 4 },
  editorial: { borderLeftWidth: 4, borderLeftColor: colors.primary, backgroundColor: "#f7fafc", padding: 10, marginBottom: 9, minHeight: 46 }, editorialTitle: { fontSize: 8, fontWeight: 700, color: colors.primary, marginBottom: 3 },
  table: { borderWidth: 0.8, borderColor: colors.primary }, row: { flexDirection: "row", minHeight: 28, borderBottomWidth: 0.5, borderBottomColor: colors.line, alignItems: "center" }, headerRow: { backgroundColor: colors.primary, borderBottomColor: colors.primary }, lastRow: { borderBottomWidth: 0 },
  cell: { paddingHorizontal: 7, fontSize: 8 }, th: { color: colors.white, fontWeight: 700 }, propertyCell: { width: "37%" }, valueCell: { width: "21%", textAlign: "right" },
  tocRow: { flexDirection: "row", alignItems: "center", marginBottom: 13 }, tocNumber: { width: 34, fontSize: 18, fontWeight: 700, color: colors.primary }, tocText: { flexGrow: 1, fontSize: 13, fontWeight: 700, borderBottomWidth: 0.7, borderBottomColor: colors.line, paddingBottom: 5 },
  propertyIntro: { flexDirection: "row", gap: 18, marginTop: 7, marginBottom: 13 }, propertyName: { fontSize: 23, lineHeight: 1.05, fontWeight: 700, color: colors.primary, marginBottom: 9 }, propertyAddress: { fontSize: 10, lineHeight: 1.2, color: colors.muted },
  valueBand: { width: 215, backgroundColor: colors.primary, padding: 13 }, valueBandLabel: { color: colors.light, fontSize: 7, marginBottom: 3 }, valueBandValue: { color: colors.white, fontSize: 18, fontWeight: 700 },
  coverPhoto: { position: "absolute", left: 0, top: 0, width: 368, height: 540, objectFit: "cover" }, coverBlue: { position: "absolute", left: 368, top: 0, width: 412, height: 540, backgroundColor: colors.primary },
  coverAccent: { position: "absolute", left: 353, top: 0, width: 24, height: 540, backgroundColor: colors.light }, coverLogo: { position: "absolute", right: 48, top: 42, width: 170, height: 50, objectFit: "contain", objectPosition: "right" },
  coverText: { position: "absolute", left: 424, right: 44, top: 174, color: colors.white }, coverYear: { fontSize: 58, fontWeight: 700, lineHeight: 0.95 }, coverTitle: { fontSize: 24, marginTop: 13 }, coverGroup: { fontSize: 11, marginTop: 14, color: colors.light },
  closingPanel: { width: "56%", backgroundColor: colors.primary, padding: 20, color: colors.white, minHeight: 230 }, closingAside: { width: "39%", paddingTop: 10 }, disclaimer: { fontSize: 7.4, lineHeight: 1.35, color: colors.muted, marginTop: 18 },
});

const dash = "—";
const money = (value: bigint | null) => value === null ? dash : `${(value / BigInt(100)).toLocaleString("cs-CZ")} Kč`;
const count = (value: number | null) => value === null ? dash : value.toLocaleString("cs-CZ");
const fallback = "Obsah této kapitoly zatím nebyl redakčně doplněn.";

function ContentPage({ data, section, title, pageNumber, children }: { data: FrozenAnnualReportPdfData; section: string; title: string; pageNumber: number; children: React.ReactNode }) { return <Page size={ANNUAL_REPORT_PAGE_SIZE} style={styles.page}><Image src={REPORT_PDF_CONTENT_HEADER_PATH} style={[styles.absolute, { left: 0, top: 0, width: 780, height: 138 }]}/><Text style={styles.masterLabel}>{section}</Text><Text style={styles.masterTitle}>{title}</Text><Image src={REPORT_PDF_LOGO_REPORT_PATH} style={styles.masterLogo}/><View style={styles.content}>{children}</View><Text style={styles.footerLeft}>FlatCloud | výroční report {data.year}</Text><Text style={styles.footerRight}>{pageNumber}</Text></Page>; }
function DraftHint() { return <Text style={styles.draft}>PRACOVNÍ NÁHLED · CHYBĚJÍCÍ TEXT BUDE DOPLNĚN</Text>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
function Editorial({ title, value }: { title: string; value: string | null }) { return <View style={styles.editorial} wrap={false}><Text style={styles.editorialTitle}>{title}</Text><Text>{value || fallback}</Text></View>; }

function ContentsPage({ data }: { data: FrozenAnnualReportPdfData }) {
  const items = [["01", "Slovo zakladatele"], ["02", "Klíčové údaje"], ["03", "Portfolio nemovitostí"], ["04", "Vývoj jednotlivých aktiv"], ["05", "Kontakty a důležitá upozornění"]];
  return <ContentPage data={data} section="OBSAH" title="Výroční report" pageNumber={2}><View style={{ width: "72%", marginTop: 5 }}>{items.map(([number, label]) => <View style={styles.tocRow} key={number}><Text style={styles.tocNumber}>{number}</Text><Text style={styles.tocText}>{label}</Text></View>)}</View><View style={[styles.absolute, { right: 0, top: 3, width: 145, height: 290, backgroundColor: colors.pale, padding: 15 }]}><Text style={styles.eyebrow}>REPORTOVACÍ OBDOBÍ</Text><Text style={{ fontSize: 30, fontWeight: 700, color: colors.primary }}>{data.year}</Text><Text style={[styles.muted, { marginTop: 10 }]}>Rozhodné datum 31. prosince. Hodnoty vycházejí ze zmrazené výroční vrstvy.</Text></View></ContentPage>;
}

function FounderPage({ data }: { data: FrozenAnnualReportPdfData }) { return <ContentPage data={data} section="01" title="Slovo zakladatele" pageNumber={3}><View style={styles.columns}><View style={[styles.column, { paddingRight: 6 }]}>{!data.founderLetter && <DraftHint/>}<Text style={[styles.body, { fontSize: 11 }]}>{data.founderLetter || fallback}</Text></View><View style={[styles.column, { backgroundColor: colors.pale, minHeight: 270, padding: 18 }]}><Text style={styles.eyebrow}>POHLED NA ROK</Text><Text style={{ fontSize: 19, fontWeight: 700, color: colors.primary, marginBottom: 11 }}>FlatCloud portfolio</Text><Text style={styles.body}>{data.executiveSummary || "Manažerské shrnutí bude doplněno v editoru výročního reportu."}</Text><View style={{ borderTopWidth: 1, borderTopColor: colors.line, marginTop: 22, paddingTop: 10 }}><Text style={styles.muted}>Za FlatCloud</Text><Text style={{ fontWeight: 700, color: colors.primary, marginTop: 3 }}>Zakladatel a vedení společnosti</Text></View></View></View></ContentPage>; }

function PortfolioPage({ data }: { data: FrozenAnnualReportPdfData }) {
  const shares = data.issuedShares === null || data.treasuryShares === null ? null : data.issuedShares - data.treasuryShares;
  return <ContentPage data={data} section="02" title="Klíčové údaje" pageNumber={4}><View style={styles.grid}><Metric label="Hrubá hodnota aktiv" value={money(data.grossAssetValueCents)}/><Metric label="Čistá hodnota aktiv" value={money(data.netAssetValueCents)}/><Metric label="Dluh" value={money(data.debtCents)}/><Metric label="Cílová hodnota portfolia" value={money(data.targetPortfolioValueCents)}/><Metric label="Cena akcie" value={money(data.sharePriceCents)}/><Metric label="Akcie v oběhu" value={count(shares)}/><Metric label="Realizované exity" value={money(data.realizedExitProceedsCents)}/><Metric label="Plánované exity" value={money(data.plannedExitProceedsCents)}/></View><View style={[styles.columns, { marginTop: 15 }]}><View style={styles.column}><Editorial title="Investiční teze" value={data.investmentThesis}/><Editorial title="Tvorba hodnoty" value={data.valueCreationSummary}/></View><View style={styles.column}><Editorial title="Manažerské shrnutí" value={data.executiveSummary}/><Editorial title="Výhled" value={data.outlook}/></View></View></ContentPage>;
}

function PropertyTable({ data }: { data: FrozenAnnualReportPdfData }) { return <ContentPage data={data} section="03" title="Portfolio nemovitostí" pageNumber={5}><Text style={[styles.body, { marginBottom: 12 }]}>Hodnotový vývoj aktiv zahrnutých do výročního reportu.</Text><View style={styles.table}><View style={[styles.row, styles.headerRow]}><Text style={[styles.cell, styles.propertyCell, styles.th]}>Nemovitost</Text><Text style={[styles.cell, styles.valueCell, styles.th]}>Počátek roku</Text><Text style={[styles.cell, styles.valueCell, styles.th]}>Konec roku</Text><Text style={[styles.cell, styles.valueCell, styles.th]}>Cíl</Text></View>{data.properties.map((property, index) => <View style={[styles.row, index === data.properties.length - 1 ? styles.lastRow : {}]} key={property.propertyName}><View style={[styles.cell, styles.propertyCell]}><Text style={{ fontWeight: 700 }}>{property.propertyName}</Text><Text style={[styles.muted, { fontSize: 7 }]}>{property.propertyAddress}</Text></View><Text style={[styles.cell, styles.valueCell]}>{money(property.openingValueCents)}</Text><Text style={[styles.cell, styles.valueCell, { fontWeight: 700, color: colors.primary }]}>{money(property.currentValueCents)}</Text><Text style={[styles.cell, styles.valueCell]}>{money(property.targetValueCents)}</Text></View>)}{!data.properties.length && <View style={[styles.row, styles.lastRow]}><Text style={[styles.cell, { color: colors.muted }]}>Do reportu zatím nebyla zařazena žádná nemovitost.</Text></View>}</View><View style={[styles.columns, { marginTop: 18 }]}><View style={styles.column}><Text style={styles.h2}>Realizované exity</Text><Text style={{ fontSize: 20, fontWeight: 700, color: colors.primary }}>{money(data.realizedExitProceedsCents)}</Text></View><View style={styles.column}><Text style={styles.h2}>Plánované exity</Text><Text style={{ fontSize: 20, fontWeight: 700, color: colors.primary }}>{money(data.plannedExitProceedsCents)}</Text></View></View></ContentPage>; }

function PropertyPage({ data, property, index }: { data: FrozenAnnualReportPdfData; property: FrozenAnnualReportPdfProperty; index: number }) { return <ContentPage data={data} section={`04.${index + 1}`} title="Vývoj aktiva" pageNumber={6 + index}><View style={styles.propertyIntro}><View style={{ flexGrow: 1 }}><Text style={styles.propertyName}>{property.propertyName}</Text><Text style={styles.propertyAddress}>{property.propertyAddress}</Text></View><View style={styles.valueBand}><Text style={styles.valueBandLabel}>HODNOTA KE KONCI ROKU</Text><Text style={styles.valueBandValue}>{money(property.currentValueCents)}</Text></View></View><View style={[styles.grid, { marginBottom: 13 }]}><Metric label="Hodnota na začátku roku" value={money(property.openingValueCents)}/><Metric label="Cílová hodnota" value={money(property.targetValueCents)}/><Metric label="Realizovaný exit" value={money(property.realizedExitProceedsCents)}/><Metric label="Plánovaný exit" value={money(property.plannedExitProceedsCents)}/></View><View style={styles.columns}><View style={styles.column}><Editorial title="Investiční případ" value={property.investmentCase}/><Editorial title="Tvorba hodnoty v roce" value={property.valueCreationNarrative}/></View><View style={styles.column}><Editorial title="Výhled a milníky" value={property.outlook}/><Editorial title="Zdroj a redakční poznámka" value={property.sourceNote}/><Text style={[styles.muted, { fontSize: 7 }]}>Plánovaný rok exitu: {property.plannedExitYear || dash}</Text></View></View></ContentPage>; }

function ClosingPage({ data }: { data: FrozenAnnualReportPdfData }) { return <ContentPage data={data} section="05" title="Kontakty" pageNumber={6 + data.properties.length}><View style={[styles.columns, { marginTop: 5 }]}><View style={styles.closingPanel}><Text style={{ fontSize: 24, fontWeight: 700, marginBottom: 18 }}>FlatCloud</Text><Text style={{ fontSize: 11, marginBottom: 6 }}>Výroční akcionářský report {data.year}</Text><Text style={{ color: colors.light }}>Dlouhodobá správa a rozvoj nájemního bydlení</Text><Text style={{ marginTop: 55, fontSize: 14, fontWeight: 700 }}>www.flatcloud.cz</Text></View><View style={styles.closingAside}><Image src={REPORT_PDF_LOGO_REPORT_PATH} style={{ width: 175, height: 32, objectFit: "contain", objectPosition: "left" }}/><Text style={[styles.h2, { marginTop: 27 }]}>Důvěrný dokument</Text><Text style={styles.body}>Tento report je určen akcionářům a oprávněným příjemcům. Před dalším šířením ověřte aktuální schválenou verzi.</Text><Text style={styles.disclaimer}>Informace v dokumentu mají reportovací charakter a nepředstavují veřejnou nabídku, investiční doporučení ani závazek k budoucímu výnosu. Hodnoty a výhledy vycházejí z podkladů dostupných k rozhodnému datu.</Text></View></View></ContentPage>; }

function AnnualReportPdf({ data }: { data: FrozenAnnualReportPdfData }) { return <Document title={`Výroční report FlatCloud ${data.year}`} author="FlatCloud" subject="Výroční akcionářský report" creator={`FlatCloud ${ANNUAL_REPORT_PDF_RENDERER_VERSION}`} producer={`FlatCloud ${ANNUAL_REPORT_PDF_RENDERER_VERSION}`} creationDate={data.asOfDate} modificationDate={data.asOfDate}><Page size={ANNUAL_REPORT_PAGE_SIZE} style={styles.page}><Image src={ANNUAL_REPORT_COVER_PATH} style={styles.coverPhoto}/><View style={styles.coverBlue}/><View style={styles.coverAccent}/><Image src={REPORT_PDF_LOGO_WHITE_PATH} style={styles.coverLogo}/><View style={styles.coverText}><Text style={styles.coverYear}>{data.year}</Text><Text style={styles.coverTitle}>Výroční report</Text><Text style={styles.coverGroup}>FlatCloud portfolio</Text></View></Page><ContentsPage data={data}/><FounderPage data={data}/><PortfolioPage data={data}/><PropertyTable data={data}/>{data.properties.map((property, index) => <PropertyPage data={data} property={property} index={index} key={property.propertyName}/>)}<ClosingPage data={data}/></Document>; }

export async function renderAnnualReportPdf(data: FrozenAnnualReportPdfData): Promise<Uint8Array> { return new Uint8Array(await renderToBuffer(<AnnualReportPdf data={data}/>)); }
