import React from "react";
import { Document, Font, Image, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";
import { ANNUAL_REPORT_COVER_PATH, CZECH_REGIONS_MAP_PATH, REPORT_PDF_CONTENT_HEADER_PATH, REPORT_PDF_LOGO_REPORT_PATH, REPORT_PDF_LOGO_WHITE_PATH, REPORT_PDF_RALEWAY_BOLD_PATH, REPORT_PDF_RALEWAY_REGULAR_PATH } from "./assets";
import type { FrozenAnnualReportPdfData, FrozenAnnualReportPdfProperty } from "./annual-report-pdf-data";

export const ANNUAL_REPORT_PDF_RENDERER_VERSION = "r18d-annual-v3";
export const ANNUAL_REPORT_PAGE_SIZE = { width: 780, height: 540 } as const;
const FONT_FAMILY = "FlatCloudRalewayAnnual";
Font.register({ family: FONT_FAMILY, src: REPORT_PDF_RALEWAY_REGULAR_PATH });
Font.register({ family: FONT_FAMILY, src: REPORT_PDF_RALEWAY_BOLD_PATH, fontWeight: 700 });

const colors = { ink: "#231f20", muted: "#687386", primary: "#26639f", light: "#caddf2", pale: "#eef5fb", line: "#b9cce0", white: "#ffffff" };
const styles = StyleSheet.create({
  page: { fontFamily: FONT_FAMILY, fontSize: 9, lineHeight: 1.3, color: colors.ink, position: "relative", backgroundColor: colors.white },
  absolute: { position: "absolute" }, content: { position: "absolute", left: 48, right: 48, top: 132, bottom: 42 },
  footerLeft: { position: "absolute", left: 48, bottom: 18, color: colors.muted, fontSize: 7.5 }, footerRight: { position: "absolute", right: 48, bottom: 18, color: colors.muted, fontSize: 7.5 },
  masterLabel: { position: "absolute", left: 48, top: 27, color: colors.white, fontSize: 10, fontWeight: 700, letterSpacing: 0.5 },
  masterTitle: { position: "absolute", left: 48, top: 47, color: colors.white, fontSize: 24, fontWeight: 700 },
  masterLogo: { position: "absolute", right: 45, top: 29, width: 128, height: 24, objectFit: "contain", objectPosition: "right" },
  eyebrow: { color: colors.primary, fontSize: 8, fontWeight: 700, letterSpacing: 1.2, marginBottom: 7 }, h2: { fontSize: 12, fontWeight: 700, color: colors.primary, marginBottom: 6 }, body: { fontSize: 10, lineHeight: 1.35 }, muted: { color: colors.muted },
  draft: { alignSelf: "flex-start", color: colors.primary, backgroundColor: colors.pale, borderColor: colors.line, borderWidth: 0.6, paddingVertical: 4, paddingHorizontal: 8, fontSize: 7, fontWeight: 700, marginBottom: 10 },
  columns: { flexDirection: "row", gap: 24 }, column: { width: "48.2%" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  metric: { width: "23.3%", minHeight: 69, borderTopWidth: 5, borderTopColor: colors.primary, backgroundColor: colors.pale, paddingHorizontal: 9, paddingVertical: 8 },
  metricLabel: { fontSize: 7.2, color: colors.muted, minHeight: 20 }, metricValue: { fontSize: 13, fontWeight: 700, color: colors.primary, marginTop: 4 },
  editorial: { borderLeftWidth: 4, borderLeftColor: colors.primary, backgroundColor: "#f7fafc", padding: 10, marginBottom: 9, minHeight: 46 }, editorialTitle: { fontSize: 8, fontWeight: 700, color: colors.primary, marginBottom: 3 },
  table: { borderWidth: 0.8, borderColor: colors.primary }, row: { flexDirection: "row", minHeight: 28, borderBottomWidth: 0.5, borderBottomColor: colors.line, alignItems: "center" }, headerRow: { backgroundColor: colors.primary, borderBottomColor: colors.primary }, lastRow: { borderBottomWidth: 0 },
  cell: { paddingHorizontal: 7, fontSize: 8 }, th: { color: colors.white, fontWeight: 700 }, propertyCell: { width: "37%" }, valueCell: { width: "21%", textAlign: "right" },
  tocRow: { flexDirection: "row", alignItems: "center", marginBottom: 13 }, tocNumber: { width: 34, fontSize: 18, fontWeight: 700, color: colors.primary }, tocText: { flexGrow: 1, fontSize: 13, fontWeight: 700, borderBottomWidth: 0.7, borderBottomColor: colors.line, paddingBottom: 5 },
  propertyIntro: { flexDirection: "row", gap: 18, marginTop: 7, marginBottom: 13 }, propertyName: { fontSize: 23, lineHeight: 1.05, fontWeight: 700, color: colors.primary, marginBottom: 9 }, propertyAddress: { fontSize: 10, lineHeight: 1.2, color: colors.muted },
  valueBand: { width: 215, backgroundColor: colors.primary, padding: 13 }, valueBandLabel: { color: colors.light, fontSize: 7, marginBottom: 3 }, valueBandValue: { color: colors.white, fontSize: 18, fontWeight: 700 },
  coverPhoto: { position: "absolute", left: 0, top: 0, width: 368, height: 540, objectFit: "cover" }, coverBlue: { position: "absolute", left: 368, top: 0, width: 412, height: 540, backgroundColor: colors.primary },
  coverAccent: { position: "absolute", left: 353, top: 0, width: 24, height: 540, backgroundColor: colors.light }, coverLogo: { position: "absolute", right: 48, top: 42, width: 170, height: 50, objectFit: "contain", objectPosition: "right" },
  coverText: { position: "absolute", left: 424, right: 44, top: 174, color: colors.white }, coverYear: { fontSize: 58, fontWeight: 700, lineHeight: 0.95 }, coverTitle: { fontSize: 24, marginTop: 13 }, coverGroup: { fontSize: 11, marginTop: 14, color: colors.light },
  closingPanel: { width: "56%", backgroundColor: colors.primary, padding: 20, color: colors.white, minHeight: 230 }, closingAside: { width: "39%", paddingTop: 10 }, disclaimer: { fontSize: 7.4, lineHeight: 1.35, color: colors.muted, marginTop: 18 },
  mapImage: { position: "absolute", left: 175, top: 38, width: 490, height: 290, objectFit: "contain" },
  mapCard: { position: "absolute", width: 148, minHeight: 70, backgroundColor: colors.primary, color: colors.white }, mapCardPhoto: { width: 148, height: 62, objectFit: "cover" }, mapCardCopy: { padding: 8 }, mapCardTitle: { fontSize: 8.5, fontWeight: 700, marginBottom: 2 }, mapCardAddress: { fontSize: 7, color: colors.light },
  teamGrid: { flexDirection: "row", flexWrap: "wrap", gap: 14 }, teamMember: { width: 126 }, teamPhoto: { width: 126, height: 112, objectFit: "cover", marginBottom: 9 }, teamPlaceholder: { width: 126, height: 112, marginBottom: 9, backgroundColor: colors.pale, color: colors.primary, fontSize: 30, fontWeight: 700, alignItems: "center", justifyContent: "center" }, teamName: { color: colors.primary, fontSize: 9, fontWeight: 700 }, teamRole: { fontSize: 8, fontWeight: 700, minHeight: 30, marginTop: 4 }, teamEmail: { fontSize: 7.5, color: colors.muted },
  structureParent: { alignSelf: "center", width: 330, minHeight: 100, padding: 15, backgroundColor: colors.primary, color: colors.white, borderRadius: 8, textAlign: "center" }, structureChildren: { flexDirection: "row", flexWrap: "wrap", gap: 14, justifyContent: "center", marginTop: 52 }, structureChild: { width: 205, minHeight: 92, padding: 12, borderWidth: 1, borderColor: colors.primary, borderRadius: 8, textAlign: "center" }, structureName: { fontSize: 10, fontWeight: 700, marginBottom: 5 }, structureMeta: { fontSize: 7.5, lineHeight: 1.4 },
  contactGrid: { flexDirection: "row", gap: 28 }, contactLabels: { width: 135 }, contactValues: { width: 475 }, contactRow: { minHeight: 20, fontSize: 8.5 }, contactHeading: { fontSize: 10, fontWeight: 700, marginBottom: 12 }, legalBlock: { marginTop: 18, paddingTop: 15, borderTopWidth: 1, borderTopColor: colors.line },
});

const dash = "—";
const czechMapPoint = (latitude: number, longitude: number) => { const bounds = { west: 12, east: 18.95, north: 51.15, south: 48.45 }; return { x: Math.max(0, Math.min(1, (longitude - bounds.west) / (bounds.east - bounds.west))), y: Math.max(0, Math.min(1, (bounds.north - latitude) / (bounds.north - bounds.south))) }; };
const money = (value: bigint | null) => value === null ? dash : `${(value / BigInt(100)).toLocaleString("cs-CZ")} Kč`;
const count = (value: number | null) => value === null ? dash : value.toLocaleString("cs-CZ");
const fallback = "Obsah této kapitoly zatím nebyl redakčně doplněn.";

function ContentPage({ data, section, title, pageNumber, children }: { data: FrozenAnnualReportPdfData; section: string; title: string; pageNumber: number; children: React.ReactNode }) { return <Page size={ANNUAL_REPORT_PAGE_SIZE} style={styles.page}><Image src={REPORT_PDF_CONTENT_HEADER_PATH} style={[styles.absolute, { left: 0, top: 0, width: 780, height: 138 }]}/><Text style={styles.masterLabel}>{section}</Text><Text style={styles.masterTitle}>{title}</Text><Image src={REPORT_PDF_LOGO_REPORT_PATH} style={styles.masterLogo}/><View style={styles.content}>{children}</View><Text style={styles.footerLeft}>FlatCloud | výroční report {data.year}</Text><Text style={styles.footerRight}>{pageNumber}</Text></Page>; }
function DraftHint() { return <Text style={styles.draft}>PRACOVNÍ NÁHLED · CHYBĚJÍCÍ TEXT BUDE DOPLNĚN</Text>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
function Editorial({ title, value }: { title: string; value: string | null }) { return <View style={styles.editorial} wrap={false}><Text style={styles.editorialTitle}>{title}</Text><Text>{value || fallback}</Text></View>; }

function ContentsPage({ data }: { data: FrozenAnnualReportPdfData }) {
  const items = [["01", "Slovo zakladatele"], ["02", "Klíčové údaje"], ["03", "Mapa portfolia"], ["04", "Portfolio nemovitostí a vývoj aktiv"], ["05", "Tým"], ["06", "Struktura skupiny"], ["07", "Kontakty a poučení o důvěrnosti"]];
  return <ContentPage data={data} section="OBSAH" title="Výroční report" pageNumber={2}><View style={{ width: "72%", marginTop: 5 }}>{items.map(([number, label]) => <View style={styles.tocRow} key={number}><Text style={styles.tocNumber}>{number}</Text><Text style={styles.tocText}>{label}</Text></View>)}</View><View style={[styles.absolute, { right: 0, top: 3, width: 145, height: 290, backgroundColor: colors.pale, padding: 15 }]}><Text style={styles.eyebrow}>REPORTOVACÍ OBDOBÍ</Text><Text style={{ fontSize: 30, fontWeight: 700, color: colors.primary }}>{data.year}</Text><Text style={[styles.muted, { marginTop: 10 }]}>Rozhodné datum 31. prosince. Hodnoty vycházejí ze zmrazené výroční vrstvy.</Text></View></ContentPage>;
}

function MapPage({ data }: { data: FrozenAnnualReportPdfData }) {
  const located = data.properties.filter((property) => property.mapLatitude !== null && property.mapLongitude !== null);
  const placements = located.map((property, index) => { const forceRight = property.mapCardSide === "RIGHT"; const right = forceRight || (property.mapCardSide === "AUTO" && index >= 3); const laneIndex = right ? index - 3 : index; return { property, right, cardX: right ? 536 : 0, cardY: 14 + Math.max(0, laneIndex) * 111 }; });
  return <ContentPage data={data} section="03" title="Mapa portfolia" pageNumber={5}><Image src={CZECH_REGIONS_MAP_PATH} style={styles.mapImage}/>{placements.map(({ property, right, cardX, cardY }) => { const point = czechMapPoint(property.mapLatitude!, property.mapLongitude!); const x = 193 + point.x * 438; const y = 66 + point.y * 222; const startX = right ? cardX : cardX + 148; const elbowX = right ? x + 24 : x - 24; return <MapConnector startX={startX} startY={cardY + 37} elbowX={elbowX} pointX={x} pointY={y} key={`line-${property.propertyName}`}/>; })}{placements.map(({ property, cardX, cardY }) => <View style={[styles.mapCard, { left: cardX, top: cardY }]} key={property.propertyName}>{property.mapPhotoDataUrl ? <Image src={property.mapPhotoDataUrl} style={styles.mapCardPhoto}/> : null}<View style={styles.mapCardCopy}><Text style={styles.mapCardTitle}>{property.mapLabel || property.propertyName}</Text><Text style={styles.mapCardAddress}>{property.propertyAddress}</Text></View></View>)}{!located.length && <View style={[styles.absolute, { left: 0, top: 45, width: 150 }]}><DraftHint/><Text style={styles.body}>V editoru doplňte souřadnice objektů z uložených adres.</Text></View>}<Text style={[styles.muted, styles.absolute, { right: 0, bottom: 0, fontSize: 6.5 }]}>Souřadnice: OpenStreetMap contributors</Text></ContentPage>;
}

function MapConnector({ startX, startY, elbowX, pointX, pointY }: { startX: number; startY: number; elbowX: number; pointX: number; pointY: number }) { const horizontalStart = Math.min(startX, elbowX); const pointStart = Math.min(elbowX, pointX); return <><View style={[styles.absolute, { left: horizontalStart, top: startY, width: Math.abs(startX - elbowX), height: 1.2, backgroundColor: colors.light }]}/><View style={[styles.absolute, { left: elbowX, top: Math.min(startY, pointY), width: 1.2, height: Math.abs(startY - pointY), backgroundColor: colors.light }]}/><View style={[styles.absolute, { left: pointStart, top: pointY, width: Math.abs(elbowX - pointX), height: 1.2, backgroundColor: colors.light }]}/><View style={[styles.absolute, { left: pointX - 5, top: pointY - 5, width: 10, height: 10, borderRadius: 5, backgroundColor: "#86b4e2" }]}/></>; }

const initials = (name: string) => name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join("");
function TeamPage({ data, pageNumber }: { data: FrozenAnnualReportPdfData; pageNumber: number }) { return <ContentPage data={data} section="05" title="Tým" pageNumber={pageNumber}>{data.team.length ? <View style={styles.teamGrid}>{data.team.map((member, index) => <View style={styles.teamMember} key={`${member.name}-${index}`}>{member.photoDataUrl ? <Image src={member.photoDataUrl} style={styles.teamPhoto}/> : <View style={styles.teamPlaceholder}><Text>{initials(member.name)}</Text></View>}<Text style={styles.teamName}>{member.name}</Text><Text style={styles.teamRole}>{member.role || "Role bude doplněna"}</Text><Text style={styles.teamEmail}>{member.email}</Text></View>)}</View> : <><DraftHint/><Text style={styles.body}>Tým zatím nebyl v editoru výročního reportu uložen.</Text></>}</ContentPage>; }

function StructurePage({ data, pageNumber }: { data: FrozenAnnualReportPdfData; pageNumber: number }) { const s = data.groupStructure; const firstRow = Math.min(3, s.subsidiaries.length); const centers = firstRow === 1 ? [342] : firstRow === 2 ? [232, 452] : [123, 342, 561]; return <ContentPage data={data} section="06" title="Struktura skupiny" pageNumber={pageNumber}><View style={styles.structureParent}><Text style={[styles.structureName, { color: colors.white, fontSize: 16 }]}>{s.parent.name}</Text><Text style={styles.structureMeta}>{[s.parent.type, s.parent.ico && `IČO: ${s.parent.ico}`, s.parent.address && `Sídlo: ${s.parent.address}`, s.parent.leadership && `Statutární orgán: ${s.parent.leadership}`].filter(Boolean).join("\n")}</Text></View>{firstRow > 0 && <><View style={[styles.absolute, { left: 342, top: 100, width: 1, height: 42, backgroundColor: colors.primary }]}/><View style={[styles.absolute, { left: centers[0], top: 142, width: centers[centers.length - 1] - centers[0] || 1, height: 1, backgroundColor: colors.primary }]}/>{centers.map((center) => <View style={[styles.absolute, { left: center, top: 142, width: 1, height: 10, backgroundColor: colors.primary }]} key={center}/>)}</>}<View style={styles.structureChildren}>{s.subsidiaries.map((entity, index) => <View style={styles.structureChild} key={`${entity.name}-${index}`}><Text style={[styles.structureName, { color: colors.primary }]}>{entity.name}</Text><Text style={styles.structureMeta}>{[entity.type, entity.ico && `IČO: ${entity.ico}`, entity.address && `Sídlo: ${entity.address}`, entity.leadership && `Jednatelé: ${entity.leadership}`].filter(Boolean).join("\n")}</Text></View>)}</View></ContentPage>; }

function FounderPage({ data }: { data: FrozenAnnualReportPdfData }) { return <ContentPage data={data} section="01" title="Slovo zakladatele" pageNumber={3}><View style={styles.columns}><View style={[styles.column, { paddingRight: 6 }]}>{!data.founderLetter && <DraftHint/>}<Text style={[styles.body, { fontSize: 11 }]}>{data.founderLetter || fallback}</Text></View><View style={[styles.column, { backgroundColor: colors.pale, minHeight: 270, padding: 18 }]}><Text style={styles.eyebrow}>POHLED NA ROK</Text><Text style={{ fontSize: 19, fontWeight: 700, color: colors.primary, marginBottom: 11 }}>FlatCloud portfolio</Text><Text style={styles.body}>{data.executiveSummary || "Manažerské shrnutí bude doplněno v editoru výročního reportu."}</Text><View style={{ borderTopWidth: 1, borderTopColor: colors.line, marginTop: 22, paddingTop: 10 }}><Text style={styles.muted}>Za FlatCloud</Text><Text style={{ fontWeight: 700, color: colors.primary, marginTop: 3 }}>Zakladatel a vedení společnosti</Text></View></View></View></ContentPage>; }

function PortfolioPage({ data }: { data: FrozenAnnualReportPdfData }) {
  const shares = data.issuedShares === null || data.treasuryShares === null ? null : data.issuedShares - data.treasuryShares;
  return <ContentPage data={data} section="02" title="Klíčové údaje" pageNumber={4}><View style={styles.grid}><Metric label="Hrubá hodnota aktiv" value={money(data.grossAssetValueCents)}/><Metric label="Čistá hodnota aktiv" value={money(data.netAssetValueCents)}/><Metric label="Dluh" value={money(data.debtCents)}/><Metric label="Cílová hodnota portfolia" value={money(data.targetPortfolioValueCents)}/><Metric label="Cena akcie" value={money(data.sharePriceCents)}/><Metric label="Akcie v oběhu" value={count(shares)}/><Metric label="Realizované exity" value={money(data.realizedExitProceedsCents)}/><Metric label="Plánované exity" value={money(data.plannedExitProceedsCents)}/></View><View style={[styles.columns, { marginTop: 15 }]}><View style={styles.column}><Editorial title="Investiční teze" value={data.investmentThesis}/><Editorial title="Tvorba hodnoty" value={data.valueCreationSummary}/></View><View style={styles.column}><Editorial title="Manažerské shrnutí" value={data.executiveSummary}/><Editorial title="Výhled" value={data.outlook}/></View></View></ContentPage>;
}

function PropertyTable({ data }: { data: FrozenAnnualReportPdfData }) { return <ContentPage data={data} section="04" title="Portfolio nemovitostí" pageNumber={6}><Text style={[styles.body, { marginBottom: 12 }]}>Hodnotový vývoj aktiv zahrnutých do výročního reportu.</Text><View style={styles.table}><View style={[styles.row, styles.headerRow]}><Text style={[styles.cell, styles.propertyCell, styles.th]}>Nemovitost</Text><Text style={[styles.cell, styles.valueCell, styles.th]}>Počátek roku</Text><Text style={[styles.cell, styles.valueCell, styles.th]}>Konec roku</Text><Text style={[styles.cell, styles.valueCell, styles.th]}>Cíl</Text></View>{data.properties.map((property, index) => <View style={[styles.row, index === data.properties.length - 1 ? styles.lastRow : {}]} key={property.propertyName}><View style={[styles.cell, styles.propertyCell]}><Text style={{ fontWeight: 700 }}>{property.propertyName}</Text><Text style={[styles.muted, { fontSize: 7 }]}>{property.propertyAddress}</Text></View><Text style={[styles.cell, styles.valueCell]}>{money(property.openingValueCents)}</Text><Text style={[styles.cell, styles.valueCell, { fontWeight: 700, color: colors.primary }]}>{money(property.currentValueCents)}</Text><Text style={[styles.cell, styles.valueCell]}>{money(property.targetValueCents)}</Text></View>)}{!data.properties.length && <View style={[styles.row, styles.lastRow]}><Text style={[styles.cell, { color: colors.muted }]}>Do reportu zatím nebyla zařazena žádná nemovitost.</Text></View>}</View><View style={[styles.columns, { marginTop: 18 }]}><View style={styles.column}><Text style={styles.h2}>Realizované exity</Text><Text style={{ fontSize: 20, fontWeight: 700, color: colors.primary }}>{money(data.realizedExitProceedsCents)}</Text></View><View style={styles.column}><Text style={styles.h2}>Plánované exity</Text><Text style={{ fontSize: 20, fontWeight: 700, color: colors.primary }}>{money(data.plannedExitProceedsCents)}</Text></View></View></ContentPage>; }

function PropertyPage({ data, property, index }: { data: FrozenAnnualReportPdfData; property: FrozenAnnualReportPdfProperty; index: number }) { return <ContentPage data={data} section={`04.${index + 1}`} title="Vývoj aktiva" pageNumber={7 + index}><View style={styles.propertyIntro}><View style={{ flexGrow: 1 }}><Text style={styles.propertyName}>{property.propertyName}</Text><Text style={styles.propertyAddress}>{property.propertyAddress}</Text></View><View style={styles.valueBand}><Text style={styles.valueBandLabel}>HODNOTA KE KONCI ROKU</Text><Text style={styles.valueBandValue}>{money(property.currentValueCents)}</Text></View></View><View style={[styles.grid, { marginBottom: 13 }]}><Metric label="Hodnota na začátku roku" value={money(property.openingValueCents)}/><Metric label="Cílová hodnota" value={money(property.targetValueCents)}/><Metric label="Realizovaný exit" value={money(property.realizedExitProceedsCents)}/><Metric label="Plánovaný exit" value={money(property.plannedExitProceedsCents)}/></View><View style={styles.columns}><View style={styles.column}><Editorial title="Investiční případ" value={property.investmentCase}/><Editorial title="Tvorba hodnoty v roce" value={property.valueCreationNarrative}/></View><View style={styles.column}><Editorial title="Výhled a milníky" value={property.outlook}/><Editorial title="Zdroj a redakční poznámka" value={property.sourceNote}/><Text style={[styles.muted, { fontSize: 7 }]}>Plánovaný rok exitu: {property.plannedExitYear || dash}</Text></View></View></ContentPage>; }

function ClosingPage({ data, pageNumber }: { data: FrozenAnnualReportPdfData; pageNumber: number }) { const c = data.contact; const rows = [["Adresa sídla společnosti", c.registeredAddress], ["Adresa kanceláře", c.officeAddress], ["Telefon", c.phone], ["E-mail", c.email], ["Datová schránka", c.dataBox], ["Správní rada", c.boardMembers], ["Investiční výbor", c.investmentCommittee]]; return <ContentPage data={data} section="07" title="Kontakty" pageNumber={pageNumber}><View style={{ marginTop: 13 }}><Text style={styles.contactHeading}>Kontaktní údaje</Text><Text style={[styles.h2, { color: colors.ink }]}>{c.companyName}</Text><View style={styles.contactGrid}><View style={styles.contactLabels}>{rows.map(([label]) => <Text style={[styles.contactRow, { fontWeight: 700 }]} key={label}>{label}</Text>)}</View><View style={styles.contactValues}>{rows.map(([label, value]) => <Text style={styles.contactRow} key={label}>{value || dash}</Text>)}</View></View><View style={styles.legalBlock}><Text style={styles.contactHeading}>Důvěrný dokument · Poučení o důvěrnosti</Text><Text style={styles.body}>{c.confidentialityNotice}</Text><Text style={[styles.body, { fontWeight: 700, marginTop: 13 }]}>{c.investmentDisclaimer}</Text></View></View></ContentPage>; }

function AnnualReportPdf({ data }: { data: FrozenAnnualReportPdfData }) { const teamPage = 7 + data.properties.length; return <Document title={`Výroční report FlatCloud ${data.year}`} author="FlatCloud" subject="Výroční akcionářský report" creator={`FlatCloud ${ANNUAL_REPORT_PDF_RENDERER_VERSION}`} producer={`FlatCloud ${ANNUAL_REPORT_PDF_RENDERER_VERSION}`} creationDate={data.asOfDate} modificationDate={data.asOfDate}><Page size={ANNUAL_REPORT_PAGE_SIZE} style={styles.page}><Image src={ANNUAL_REPORT_COVER_PATH} style={styles.coverPhoto}/><View style={styles.coverBlue}/><View style={styles.coverAccent}/><Image src={REPORT_PDF_LOGO_WHITE_PATH} style={styles.coverLogo}/><View style={styles.coverText}><Text style={styles.coverYear}>{data.year}</Text><Text style={styles.coverTitle}>Výroční report</Text><Text style={styles.coverGroup}>FlatCloud portfolio</Text></View></Page><ContentsPage data={data}/><FounderPage data={data}/><PortfolioPage data={data}/><MapPage data={data}/><PropertyTable data={data}/>{data.properties.map((property, index) => <PropertyPage data={data} property={property} index={index} key={property.propertyName}/>)}<TeamPage data={data} pageNumber={teamPage}/><StructurePage data={data} pageNumber={teamPage + 1}/><ClosingPage data={data} pageNumber={teamPage + 2}/></Document>; }

export async function renderAnnualReportPdf(data: FrozenAnnualReportPdfData): Promise<Uint8Array> { return new Uint8Array(await renderToBuffer(<AnnualReportPdf data={data}/>)); }
