"use client";
import { useState } from "react";
import { expenseRuleActions } from "@/lib/bank-expense-rule-policy";
import { propertyCostCategories } from "@/lib/asset-finance";
type Row={id:string;date:string;amountCents:number;label:string};
type Rule={id:string;name:string;active:boolean;action:string;usedCount:number;lastUsedAt:string|null;createdBy:string;conditions:unknown;bankAccountId:string;targetPropertyId:string;unitId:string|null;category:string;costKind:string};
export function BankExpenseRules({propertyId,accounts,targets,rules,initial}:{propertyId:string;accounts:{id:string;label:string}[];targets:{id:string;name:string;units:{id:string;label:string}[]}[];rules:Rule[];initial?:{bankAccountId:string;counterpartyIban:string|null;counterpartyName:string|null;variableSymbol:string|null;message:string|null;amountCents:number}}){
 const [target,setTarget]=useState(propertyId),[preview,setPreview]=useState<{rows:Row[];truncated:boolean}|null>(null),[draft,setDraft]=useState<unknown>(null),[selectedRule,setSelectedRule]=useState<string|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const endpoint=`/api/properties/${propertyId}/bank-expense-rules`;
 async function call(body:unknown){const r=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}
 async function run(work:()=>Promise<void>){setBusy(true);setMessage("");try{await work();}catch(e){setMessage(e instanceof Error?e.message:"Operace se nezdařila.");}finally{setBusy(false);}}
 return <><p>Pravidla platí pro zvolený účet. Všechny vyplněné podmínky musí souhlasit. Při více shodách zůstane pohyb k ručnímu rozhodnutí. Nový náklad vzniká jako návrh, nikoli automaticky jako skutečný náklad v KPI.</p>{message&&<p role="status" className="notice">{message}</p>}
 <form className="card form-grid" onChange={()=>{setPreview(null);setDraft(null);}} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),get=(k:string)=>String(f.get(k)||"");const rule={name:get("name"),bankAccountId:get("bankAccountId"),targetPropertyId:target,unitId:get("unitId")||null,category:get("category"),costKind:get("costKind"),action:get("action"),conditions:{direction:get("direction"),fromDay:get("fromDay"),toDay:get("toDay"),counterpartyAccount:get("counterpartyAccount"),counterpartyName:get("counterpartyName"),variableSymbol:get("variableSymbol"),message:get("message"),minCents:get("min")?Math.round(Number(get("min"))*100):null,maxCents:get("max")?Math.round(Number(get("max"))*100):null}};void run(async()=>{setPreview(await call({operation:"preview",rule}));setDraft(rule);setSelectedRule(null);});}}>
 <h2 className="field-full">Nové pravidlo</h2>
 <label className="field"><span>Název pravidla / nového nákladu</span><input name="name" required maxLength={200}/></label>
 <label className="field"><span>Účet</span><select name="bankAccountId" defaultValue={initial?.bankAccountId} required>{accounts.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label>
 <label className="field"><span>Směr</span><select name="direction" defaultValue={initial&&initial.amountCents>0?"IN":"OUT"}><option value="OUT">Odchozí</option><option value="IN">Příchozí vratka / jiný pohyb</option></select></label>
 <label className="field"><span>Účet protistrany – přesná shoda</span><input name="counterpartyAccount" defaultValue={initial?.counterpartyIban||""}/></label>
 <label className="field"><span>Jméno protistrany – přesná shoda</span><input name="counterpartyName" defaultValue={initial?.counterpartyName||""}/></label>
 <label className="field"><span>Variabilní symbol – přesná shoda</span><input name="variableSymbol" defaultValue={initial?.variableSymbol||""}/></label>
 <label className="field field-full"><span>Zpráva obsahuje</span><input name="message"/></label>
 <label className="field"><span>Částka od (Kč, bez znaménka)</span><input name="min" type="number" min="0" step="0.01"/></label><label className="field"><span>Částka do (Kč, bez znaménka)</span><input name="max" type="number" min="0" step="0.01"/></label>
 <label className="field"><span>Datum pohybu od (volitelné)</span><input name="fromDay" type="date"/></label><label className="field"><span>Datum pohybu do (volitelné)</span><input name="toDay" type="date"/></label>
 <label className="field field-full"><span>Účinek pravidla</span><select name="action">{Object.entries(expenseRuleActions).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label className="field"><span>Cílový dům</span><select value={target} onChange={e=>setTarget(e.target.value)}>{targets.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
 <label className="field"><span>Jednotka</span><select name="unitId" key={target}><option value="">Celý dům</option>{targets.find(t=>t.id===target)?.units.map(u=><option key={u.id} value={u.id}>{u.label}</option>)}</select></label>
 <label className="field"><span>Kategorie nového nákladu</span><select name="category" defaultValue="OTHER">{Object.entries(propertyCostCategories).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field"><span>Typ nákladu</span><select name="costKind"><option>OPEX</option><option>CAPEX</option></select></label>
 <button className="secondary" disabled={busy||!accounts.length}>Zobrazit náhled pravidla</button></form>
 {preview&&<section className="card"><h2>Náhled: {preview.rows.length} odpovídajících pohybů</h2><p>Kontrola podmínek; použití ještě ověří kolize pravidel, oprávnění a vhodný náklad. {preview.truncated&&"Náhled je omezen na posledních 1 000 nezpracovaných pohybů."}</p><div className="table-wrap"><table><thead><tr><th>Datum</th><th>Pohyb</th><th>Kč</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.label}</td><td>{(r.amountCents/100).toLocaleString("cs-CZ")}</td></tr>)}</tbody></table></div><button className="primary" disabled={busy} onClick={()=>void run(async()=>{if(selectedRule){const r=await call({operation:"apply",id:selectedRule,ids:preview.rows.map(r=>r.id),confirmed:true});setMessage(`Použito: ${r.applied}; ponecháno ke kontrole: ${r.review}.`);setPreview(null);}else{await call({operation:"save",rule:draft,confirmed:true});window.location.reload();}})}>{selectedRule?"Potvrdit použití na zobrazené pohyby":"Uložit pravidlo pro budoucí importy"}</button></section>}
 <section className="card"><h2>Pravidla párování a ignorování</h2>{rules.map(r=><article className="card" key={r.id}><h3>{r.name} · {r.active?"Zapnuto":"Vypnuto"}</h3><p>{expenseRuleActions[r.action as keyof typeof expenseRuleActions]} · {r.createdBy} · použito {r.usedCount}× · naposledy {r.lastUsedAt?new Date(r.lastUsedAt).toLocaleString("cs-CZ"):"dosud nepoužito"}</p><p>{(()=>{const c=r.conditions as Record<string,unknown>;return [c.direction==="OUT"?"Odchozí":"Příchozí",c.counterpartyAccount?`Účet: ${c.counterpartyAccount}`:null,c.counterpartyName?`Protistrana: ${c.counterpartyName}`:null,c.variableSymbol?`VS: ${c.variableSymbol}`:null,c.message?`Zpráva obsahuje: ${c.message}`:null,c.minCents!=null?`Od ${Number(c.minCents)/100} Kč`:null,c.maxCents!=null?`Do ${Number(c.maxCents)/100} Kč`:null,c.fromDay?`Od data ${c.fromDay}`:null,c.toDay?`Do data ${c.toDay}`:null].filter(Boolean).join(" · ");})()}</p><div className="form-actions"><button className="secondary" disabled={busy} onClick={()=>void run(async()=>{await call({operation:"toggle",id:r.id});window.location.reload();})}>{r.active?"Vypnout":"Zapnout"}</button><button className="secondary" disabled={busy||!r.active} onClick={()=>void run(async()=>{setPreview(await call({operation:"preview",rule:r}));setSelectedRule(r.id);setDraft(null);})}>Náhled zpětného použití</button></div></article>)}{!rules.length&&<p>Zatím bez pravidel.</p>}</section></>;
}
