"use client";
import { useRef,useState } from "react";
type Preview={token:string;rows:{id:string;state:string;date:string;amountCents:number;label:string;possibleMatches:number}[]};
export function BankExpenseImport({propertyId,accounts}:{propertyId:string;accounts:{id:string;label:string}[]}){
 const form=useRef<HTMLFormElement>(null),[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(operation:string){if(!form.current)return;setBusy(true);setError("");try{const data=new FormData(form.current);data.set("operation",operation);if(preview)data.set("previewToken",preview.token);const r=await fetch(`/api/properties/${propertyId}/bank-expenses/import`,{method:"POST",body:data});const body=await r.json();if(!r.ok)throw new Error(body.error||"Import se nezdařil.");if(operation==="preview")setPreview(body);else window.location.assign(body.back+"?ok="+encodeURIComponent(body.message));}catch(e){setError(e instanceof Error?e.message:"Import se nezdařil.");}finally{setBusy(false);}}
 return <form ref={form} action={`/api/properties/${propertyId}/bank-expenses/import`} className="form-grid" onSubmit={e=>{e.preventDefault();void submit("import");}}>
 <label className="field"><span>Účet vlastníka</span><select name="accountId" required defaultValue="" onChange={()=>setPreview(null)}><option value="" disabled>Vyberte účet</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label>
 <label className="field"><span>CSV výpis / vlastní evidence podle šablony</span><input name="file" type="file" accept=".csv,text/csv" required onChange={()=>setPreview(null)}/></label>
 <div className="field-full"><button type="button" className="secondary" disabled={busy} onClick={()=>void submit("preview")}>Zkontrolovat a zobrazit náhled</button></div>
 {error&&<p role="alert" className="notice field-full">{error}</p>}
 {preview&&<><div className="table-wrap field-full"><table><thead><tr><th>Datum / ID</th><th>Pohyb</th><th>Kč</th><th>Kontrola</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.id}><td>{r.date} · {r.id}</td><td>{r.label}</td><td>{(r.amountCents/100).toLocaleString("cs-CZ")}</td><td>{r.state==="new"?"Nový":r.state==="duplicate"?"Již evidováno – přeskočí se":r.state==="conflict"?"Konflikt ID – import blokován":<label><input type="checkbox" name="allowSuspect" value={r.id}/> Možná duplicita ({r.possibleMatches}); přesto importovat</label>}</td></tr>)}</tbody></table></div><p className="field-full">Podezřelé pohyby se ve výchozím stavu přeskočí. Stejná částka a datum nejsou samy důkazem duplicity. Kontrola nezaručuje rozpoznání všech různě zapsaných plateb.</p><label className="field-full"><input type="checkbox" name="confirmed" required/> Ověřil jsem účet, stabilní ID, znaménka a vyloučení příjmů nájemného.</label><button className="primary" disabled={busy||preview.rows.some(r=>r.state==="conflict")}>Potvrdit import</button></>}
 </form>;
}
