"use client";
import { useState } from "react";

type Account = { id:string; ownerId:string; label:string; verified:boolean; available:boolean };
type Unit = { id:string; ownerId:string; label:string; accountLabel:string; revision:string; leases:Array<{label:string;tenants:string}> };
export function BankAccountChangeForm({accounts,units,initialUnitId,initialAccountId,today,requestId}:{accounts:Account[];units:Unit[];initialUnitId?:string;initialAccountId?:string;today:string;requestId:string}) {
  const initialUnit=units.find(u=>u.id===initialUnitId);
  const [accountId,setAccountId]=useState(initialAccountId||""),[selected,setSelected]=useState<string[]>(initialUnit?[initialUnit.id]:[]),[step,setStep]=useState(1),[effectiveDate,setDate]=useState(today),[reason,setReason]=useState("");
  const account=accounts.find(a=>a.id===accountId), chosen=units.filter(u=>selected.includes(u.id));
  const candidates=accounts.filter(a=>a.available&&(!initialUnit||a.ownerId===initialUnit.ownerId));
  function chooseAccount(id:string){setAccountId(id);const owner=accounts.find(a=>a.id===id)?.ownerId;setSelected(current=>current.filter(id=>units.some(u=>u.id===id&&u.ownerId===owner)));}
  return <section className="card" id="zmena-uctu"><h2>Změnit účet pro nájemné</h2><p>Krok {step} ze 3 · {step===1?"Vybrat účet":step===2?"Použití a účinnost":"Zkontrolovat a potvrdit"}</p>
    <form action="/api/bank-accounts/changes" method="post" className="edit-form">
      <input type="hidden" name="requestId" value={requestId}/><input type="hidden" name="accountId" value={accountId}/><input type="hidden" name="effectiveDate" value={effectiveDate}/><input type="hidden" name="reason" value={reason}/><input type="hidden" name="revisions" value={JSON.stringify(Object.fromEntries(chosen.map(u=>[u.id,u.revision])))}/>{selected.map(id=><input key={id} type="hidden" name="unitIds" value={id}/>)}
      {step===1&&<><label className="field"><span>Nový účet pro nájemné</span><select value={accountId} onChange={e=>chooseAccount(e.target.value)}><option value="">Vyberte účet</option>{candidates.map(a=><option key={a.id} value={a.id}>{a.label} · {a.verified?"Notifikace ověřeny":"Čeká na ověření"}</option>)}</select></label><p><a href="#pridat-ucet">Přidat nový účet</a></p>{account&&!account.verified&&<p className="notice">Nejprve dokončete <a href={`#ucet-${account.id}`}>ověření tohoto účtu</a>. Účet zatím není použit u vybraných jednotek.</p>}<button className="primary" type="button" disabled={!account?.verified} onClick={()=>setStep(2)}>Pokračovat</button></>}
      {step===2&&<><fieldset><legend>Jednotky pro tuto změnu</legend>{units.filter(u=>u.ownerId===account?.ownerId).map(u=><label className="checkbox-field" key={u.id}><input type="checkbox" checked={selected.includes(u.id)} onChange={e=>setSelected(e.target.checked?[...selected,u.id]:selected.filter(id=>id!==u.id))}/><span>{u.label}<small> · {u.accountLabel} · {u.leases.length?`${u.leases.length} smlouvy`:"Bez nájemní smlouvy"}</small></span></label>)}</fieldset><label className="field"><span>Účinnost od</span><input type="date" min={today} value={effectiveDate} onChange={e=>setDate(e.target.value)}/></label><label className="field"><span>Důvod a smluvní podklad oznámení</span><textarea maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Např. změna účtu vlastníka podle článku smlouvy o platebních údajích."/></label><div className="action-row"><button className="secondary" type="button" onClick={()=>setStep(1)}>Zpět</button><button className="primary" type="button" disabled={!selected.length||!reason.trim()||effectiveDate<today} onClick={()=>setStep(3)}>Zobrazit dopad změny</button></div></>}
      {step===3&&<><h3>Od {effectiveDate}: {account?.label}</h3>{chosen.map(u=><div key={u.id} className="notice"><strong>{u.label}</strong><p>{u.accountLabel} → {account?.label}</p>{u.leases.map((l,i)=><p key={i}>{l.label} · {l.tenants}</p>)}</div>)}<details open><summary>Náhled obsahu oznámení</summary><p>Od {effectiveDate} používejte pro další úhrady nájemného, záloh i dosavadních nedoplatků účet {account?.label}. Variabilní symbol, částky a splatnosti zůstávají podle smlouvy. Upravte prosím trvalý příkaz a potvrďte přečtení v portálu.</p><p>Podklad: {reason}</p><p>Každá smlouva dostane vlastní PDF s identifikací jednotky, smlouvy, nájemců, původním a novým účtem a vystavitelem.</p></details><p>Oznámení se zveřejní nyní. Nové platební pokyny se použijí od účinnosti. U neaktivního objektu se e-mail neodesílá; doručení je sledováno úkolem.</p><label className="checkbox-field"><input type="checkbox" name="noticeAllowed" required/><span>Ověřil/a jsem oprávnění ke změně a smluvní podklad pro oznámení změny účtu. Vyžaduje-li smlouva dohodu, mám ji již doloženou.</span></label><label className="checkbox-field"><input type="checkbox" name="confirm" required/><span>Potvrzuji uvedené jednotky, účet, účinnost a zveřejnění oznámení nájemníkům.</span></label><div className="action-row"><button className="secondary" type="button" onClick={()=>setStep(2)}>Zpět</button><button className="primary" type="submit">Potvrdit změnu a oznámení</button></div></>}
    </form>
  </section>;
}
