"use client";
import { useEffect,useId,useState } from "react";
type Person={id:string;name:string;email:string};
export function CollaboratorPicker({propertyId}:{propertyId:string}) {
 const [name,setName]=useState(""),[email,setEmail]=useState(""),[query,setQuery]=useState(""),[users,setUsers]=useState<Person[]>([]),[selected,setSelected]=useState<Person|null>(null),[index,setIndex]=useState(-1),[open,setOpen]=useState(false);const listId=useId();
 useEffect(()=>{const abort=new AbortController();const timer=setTimeout(async()=>{if(query.trim().length<2){setUsers([]);return;}try{const r=await fetch(`/api/properties/${propertyId}/collaborator-search?q=${encodeURIComponent(query)}`,{signal:abort.signal,cache:"no-store"});if(r.ok){setUsers((await r.json()).users);setIndex(-1);}}catch{}},250);return()=>{clearTimeout(timer);abort.abort();};},[query,propertyId]);
 function select(p:Person){setSelected(p);setName(p.name);setEmail(p.email);setOpen(false);setUsers([]);}
 function keyboard(e:React.KeyboardEvent<HTMLInputElement>){if(e.key==="Escape")setOpen(false);if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();setOpen(true);setIndex(i=>Math.max(0,Math.min(users.length-1,i+(e.key==="ArrowDown"?1:-1))));}if(e.key==="Enter"&&open&&users[index]){e.preventDefault();select(users[index]);}}
 return <div className="collaborator-picker" onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false);}}><input type="hidden" name="existingUserId" value={selected?.id||""}/><label className="field"><span>Jméno</span><input name="name" value={name} autoComplete="off" role="combobox" aria-autocomplete="list" aria-expanded={open&&users.length>0} aria-controls={listId} aria-activedescendant={index>=0?`${listId}-${index}`:undefined} onKeyDown={keyboard} onChange={e=>{setName(e.target.value);setSelected(null);setQuery(e.target.value);setOpen(true);}}/></label><label className="field"><span>E-mail</span><input name="email" type="email" required value={email} autoComplete="off" role="combobox" aria-autocomplete="list" aria-expanded={open&&users.length>0} aria-controls={listId} aria-activedescendant={index>=0?`${listId}-${index}`:undefined} onKeyDown={keyboard} onChange={e=>{setEmail(e.target.value);setSelected(null);setQuery(e.target.value);setOpen(true);}}/></label>{open&&users.length>0&&<ul id={listId} role="listbox" className="collaborator-options">{users.map((p,i)=><li key={p.id} id={`${listId}-${i}`} role="option" aria-selected={index===i}><button type="button" className="secondary" onMouseDown={e=>e.preventDefault()} onClick={()=>select(p)}><strong>{p.name}</strong><small>{p.email}</small></button></li>)}</ul>}<small>{selected?`Vybraný existující účet: ${selected.email}`:"Vyhledejte jméno nebo e-mail. Jiný e-mail stejné osoby nelze automaticky rozpoznat; před novou pozvánkou ověřte jméno."}</small></div>;
}
