import Link from "next/link";
import type { loadGeneralKpis } from "@/lib/reporting/general-kpis";
import { money, date } from "@/lib/format";
import { SaleScenarioCalculator } from "@/components/SaleScenarioCalculator";
import { saleBenchmarkConfidenceLabels } from "@/lib/reporting/sale-benchmark";

export function GeneralKpis({data}:{data:Awaited<ReturnType<typeof loadGeneralKpis>>}) {
  const amount=(value:number|null)=>value===null?"—":money(value);
  const percent=(value:number|null)=>value===null?"—":`${(value/100).toLocaleString("cs-CZ",{maximumFractionDigits:2})} %`;
  if(!data.includedCount)return <section className="card"><h2>KPIs nemovitostí</h2><p>Vyberte celý objekt, ke kterému máte přístup. Výnosové ukazatele potřebují jeho nájemné, náklady a ocenění; z údajů jediné jednotky nelze hodnotit celý dům.</p></section>;
  return <>
    <div className="stat-grid v21-stat-grid">{[["NOI · roční přepočet",amount(data.noiCents)],["Čistý výnos (Yield)",percent(data.yieldBps)],["Výnos vlastního kapitálu (ROE)",percent(data.roeBps)],["Hodnota nemovitostí",amount(data.marketValueCents)],["Evidovaná jistina úvěrů",data.principalComplete?amount(data.outstandingPrincipalCents):"—"],["Zadlužení (LTV)",percent(data.ltvBps)]].map(([name,value])=><div className="card stat" key={name}><div><span>{name}</span><strong>{value}</strong></div></div>)}</div>
    <section className="card"><h2>Jak číst ukazatele</h2><p className="metric-definition">NOI = aktuální měsíční čisté nájemné × 12 − evidované provozní náklady za posledních 12 měsíců. Yield = NOI / poslední potvrzená hodnota nemovitosti. ROE zde vyjadřuje peněžní výnos: (NOI − roční splátky úvěrů) / (hodnota − jistina). LTV = jistina / hodnota. Změna tržní ceny se do ROE nezapočítává.</p><p className="metric-definition">Výsledky odpovídají úplnosti vaší evidence. Bez podkladů nájemného, nákladů nebo ocenění příslušné ukazatele nedopočítáváme; pomlčka není nula. Nejsou-li úvěry evidovány, výpočet předpokládá financování bez dluhu. Úvěr bez doloženého stavu zablokuje ukazatele závislé na financování.</p></section>
    <section className="card"><div className="card-head"><div><h2>Asset benchmark</h2><p className="muted-copy">Orientační hodnota z realizované ceny za m². Je zobrazena vedle potvrzené valuace a sama ji nepřepisuje.</p></div><span className="status">pokrytí {data.benchmarkCoverageCount}/{data.includedCount}</span></div><div className="stat-grid v21-stat-grid"><div className="stat"><span>Benchmarková hodnota</span><strong>{amount(data.benchmarkValueCents)}</strong></div><div className="stat"><span>Yield na benchmarku</span><strong>{percent(data.benchmarkYieldBps)}</strong></div><div className="stat"><span>ROE na benchmarku</span><strong>{percent(data.benchmarkRoeBps)}</strong></div><div className="stat"><span>LTV na benchmarku</span><strong>{percent(data.benchmarkLtvBps)}</strong></div></div></section>
    <SaleScenarioCalculator benchmarkValueCents={data.benchmarkValueCents} principalCents={data.principalComplete?data.outstandingPrincipalCents:null}/>
    <section className="card portfolio-table-card"><div className="table-toolbar"><h2>KPIs podle nemovitostí</h2></div><div className="table-wrap"><table><thead><tr><th>Nemovitost</th><th>NOI</th><th>Yield / benchmark</th><th>ROE / benchmark</th><th>Potvrzená hodnota</th><th>Orientační benchmark</th><th>Podklady</th></tr></thead><tbody>{data.propertyRows.map(row=><tr key={row.propertyId}><td><Link href={`/nemovitosti/${row.propertyId}/finance`}>{row.propertyName}</Link></td><td>{amount(row.noiCents)}</td><td>{percent(row.yieldBps)}<span className="owner-sub">benchmark {percent(row.benchmarkYieldBps)}</span></td><td>{percent(row.roeBps)}<span className="owner-sub">benchmark {percent(row.benchmarkRoeBps)}</span></td><td>{amount(row.marketValueCents)}<span className="owner-sub">{row.valuationAsOfDate?date(row.valuationAsOfDate):"bez data"}</span></td><td>{amount(row.benchmarkValueCents)}<span className="owner-sub">{row.benchmarkQuarter||"bez dat"}{row.benchmarkConfidence?` · důvěra ${saleBenchmarkConfidenceLabels[row.benchmarkConfidence].toLocaleLowerCase("cs")}`:""}{row.benchmarkQoqBps==null?"":` · QoQ ${row.benchmarkQoqBps>=0?"+":""}${(row.benchmarkQoqBps/100).toLocaleString("cs-CZ",{maximumFractionDigits:2})} %`}</span></td><td>{[!row.rentComplete&&"Doplnit podklady nájemného",!row.opexComplete&&"Doplnit provozní náklady",row.marketValueCents===null&&"Doplnit ocenění",row.benchmarkValueCents===null&&"Chybí prodejní benchmark nebo plocha",!row.principalComplete&&"Doplnit stav úvěru",row.annualDebtServiceCents===null&&"Doplnit splátky"].filter(Boolean).join(" · ")||"Evidované podklady dostupné"}</td></tr>)}</tbody></table></div></section>
  </>;
}
