import { meterConsumption, type ConsumptionReading, type ConsumptionTariff } from "@/lib/meter-consumption";
import { date, money } from "@/lib/format";
import { businessDateKey } from "@/lib/calendar";
export function MeterConsumption({ readings, tariffs, unit, action, canManage, leaseBoundaries = [] }: { readings:ConsumptionReading[]; tariffs:ConsumptionTariff[]; unit:string; action:string; canManage:boolean; leaseBoundaries?:Date[] }) {
  const intervals = meterConsumption(readings,tariffs,unit,leaseBoundaries), latest=intervals.at(-1), current=tariffs.filter(t=>t.validFrom<=new Date()).at(-1);
  const graph=intervals.slice(-12), max=Math.max(1,...graph.flatMap(r=>[r.monthlyCostCents||0,r.monthlyAdvanceCents||0]));
  const x=(i:number)=>55+i*580/Math.max(1,graph.length-1), y=(v:number)=>165-v/max*125;
  return <section className="meter-consumption" aria-label="Spotřeba a odhad nákladů"><h3>Spotřeba a odhad nákladů</h3>
    <div className="consumption-summary"><div><span>Průměrná denní spotřeba</span><strong>{latest?.daily==null?"—":`${latest.daily.toLocaleString("cs-CZ",{maximumFractionDigits:3})} ${unit}`}</strong></div><div><span>Odhad za měsíc</span><strong>{latest?.monthlyCostCents==null?"—":money(latest.monthlyCostCents)}</strong></div><div><span>Měsíční záloha</span><strong>{current?money(current.monthlyAdvanceCents):"—"}</strong></div></div>
    {graph.length>0 ? <><svg viewBox="0 0 700 215" role="img" aria-label="Odhad měsíčních nákladů a záloh podle odečtů"><title>Odhad nákladů z průměrné denní spotřeby</title>{[0,.5,1].map(f=><g key={f}><line x1="50" x2="645" y1={y(max*f)} y2={y(max*f)} stroke="var(--line)"/><text x="3" y={y(max*f)-4} fill="var(--muted)" fontSize="10">{Math.round(max*f/100).toLocaleString("cs-CZ")} Kč</text></g>)}{graph.map((r,i)=><g key={r.id}>{i>0&&r.monthlyCostCents!==null&&graph[i-1].monthlyCostCents!==null&&<line x1={x(i-1)} y1={y(graph[i-1].monthlyCostCents!)} x2={x(i)} y2={y(r.monthlyCostCents)} stroke="currentColor" strokeWidth="2.5"/>}{r.monthlyCostCents!==null&&<circle cx={x(i)} cy={y(r.monthlyCostCents)} r="4" fill="currentColor"><title>{date(r.to)}: {money(r.monthlyCostCents)}</title></circle>}{r.monthlyAdvanceCents!==null&&<line x1={x(i)-12} x2={x(i)+12} y1={y(r.monthlyAdvanceCents)} y2={y(r.monthlyAdvanceCents)} stroke="#d99943" strokeWidth="3"/>}{(i===0||i===graph.length-1||i%3===0)&&<text x={x(i)} y="195" textAnchor="middle" fill="var(--muted)" fontSize="10">{date(r.to)}</text>}</g>)}</svg><div className="consumption-key"><span>Modrá · odhad měsíčních nákladů</span><span>Oranžová · nastavená záloha</span></div></> : <p>Pro výpočet spotřeby doplňte alespoň dva odečty.</p>}
    <p className="muted-copy">Odhad vychází z průměrné denní spotřeby mezi odečty a vaší ceny za {unit}; měsíc odpovídá 30,44 dne. Není vyúčtováním. Při změně ceny uvnitř období rozdělujeme spotřebu rovnoměrně. Změnu nájemníka oddělte předávacím odečtem.</p>
    {intervals.length>0&&<div className="table-wrap"><table><thead><tr><th>Období</th><th>Spotřeba [{unit}]</th><th>Za den [{unit}]</th><th>Odhad nákladů období</th><th>Podklad</th></tr></thead><tbody>{intervals.slice().reverse().map(r=><tr key={r.id}><td>{date(r.from)} – {date(r.to)}</td><td>{r.quantity?.toLocaleString("cs-CZ",{maximumFractionDigits:3})??"—"}</td><td>{r.daily?.toLocaleString("cs-CZ",{maximumFractionDigits:3})??"—"}</td><td>{r.estimatedCostCents===null?"—":money(r.estimatedCostCents)}</td><td>{r.reason||(r.estimatedReading?"Odhadovaný odečet":"Naměřené odečty")}{!r.reason&&r.estimatedCostCents===null?" · doplňte cenu platnou po celé období":""}</td></tr>)}</tbody></table></div>}
    <details><summary>Ceny a zálohy v čase</summary>{tariffs.length>0&&<div className="summary-list">{tariffs.map(t=><div key={t.validFrom.toISOString()}><span>Od {date(t.validFrom)}</span><strong>{(t.priceCentsPerUnit/100).toLocaleString("cs-CZ",{maximumFractionDigits:4})} Kč/{t.unitOfMeasure} · záloha {money(t.monthlyAdvanceCents)}</strong></div>)}</div>}{canManage&&<form className="compact-form" action={action} method="post"><label className="field"><span>Platnost od</span><input type="date" name="validFrom" defaultValue={businessDateKey(new Date())} required/></label><label className="field"><span>Cena Kč / {unit}</span><input type="number" name="price" min="0" max="1000000" step="0.0001" required/></label><label className="field"><span>Měsíční záloha Kč</span><input type="number" name="advance" min="0" max="10000000" step="0.01" required/></label><button className="secondary">Uložit cenu a zálohu</button><small>Nové datum zachová historii; shodné datum opraví cenu tohoto období. U plynu uvádějte cenu ve stejné jednotce jako měřidlo, přepočet m³/kWh se neprovádí.</small></form>}</details>
  </section>;
}
