"use client";
import { useState } from "react";

const money=(cents:number)=>new Intl.NumberFormat("cs-CZ",{style:"currency",currency:"CZK",maximumFractionDigits:0}).format(cents/100);
const number=(value:string,min:number,max:number)=>{const parsed=Number(value.replace(",","."));return Number.isFinite(parsed)?Math.min(max,Math.max(min,parsed)):0};

export function SaleScenarioCalculator({benchmarkValueCents,principalCents}:{benchmarkValueCents:number|null;principalCents:number|null}){
  const[costPercent,setCostPercent]=useState("4"),[taxPercent,setTaxPercent]=useState("0"),[reserveCzk,setReserveCzk]=useState("0");
  if(benchmarkValueCents==null)return <section className="card"><h2>Hypotetický prodej</h2><p className="muted-copy">Scénář bude dostupný po úplném benchmarkovém pokrytí vybraných nemovitostí. Chybějící hodnota se nepovažuje za nulu.</p></section>;
  const costs=Math.round(benchmarkValueCents*number(costPercent,0,100)/100),tax=Math.round(benchmarkValueCents*number(taxPercent,0,100)/100),reserve=Math.round(number(reserveCzk,0,1_000_000_000_000)*100),net=principalCents==null?null:benchmarkValueCents-costs-tax-reserve-principalCents;
  return <section className="card"><div className="card-head"><div><h2>Hypotetický čistý výnos při prodeji</h2><p className="muted-copy">Pracovní scénář nad orientačním benchmarkem; nejde o nabídku, účetní výpočet ani daňové stanovisko.</p></div><span className="status warn">Scénář</span></div><div className="form-grid"><label className="field"><span>Transakční náklady (%)</span><input value={costPercent} onChange={event=>setCostPercent(event.target.value)} inputMode="decimal"/></label><label className="field"><span>Daňová rezerva (%)</span><input value={taxPercent} onChange={event=>setTaxPercent(event.target.value)} inputMode="decimal"/></label><label className="field"><span>Další rezerva (Kč)</span><input value={reserveCzk} onChange={event=>setReserveCzk(event.target.value)} inputMode="decimal"/></label></div><div className="summary-list"><div><span>Orientační prodejní hodnota</span><strong>{money(benchmarkValueCents)}</strong></div><div><span>− transakční náklady</span><strong>{money(costs)}</strong></div><div><span>− daňová rezerva</span><strong>{money(tax)}</strong></div><div><span>− další rezerva</span><strong>{money(reserve)}</strong></div><div><span>− evidovaná jistina úvěrů</span><strong>{principalCents==null?"—":money(principalCents)}</strong></div><div><span>Hypotetický čistý výnos</span><strong className={net==null?undefined:net>=0?"positive":"negative"}>{net==null?"—":money(net)}</strong></div></div>{principalCents==null&&<p className="muted-copy">Výsledek nelze dopočítat bez úplného evidovaného stavu úvěrů; chybějící jistina není nula.</p>}</section>;
}
