"use client";
import Link from "next/link";
import { useState } from "react";
import { money } from "@/lib/format";
import { leaseStatuses } from "@/lib/labels";
export type TenancyReportRow = {leaseId:string;propertyId:string;propertyName:string;unitLabel:string;tenantName:string;contractNumber:string|null;start:string;end:string;status:string;rentCents:number;depositCents:number;note:string|null;areaM2:number|null;servicesCents:number|null;rentPerM2Cents:number|null;agreedDepositCents:number|null;debtCents:number|null;expiring90Days:boolean;endedYtd:boolean};
export function TenancyReport({rows,initialStatus=""}:{rows:TenancyReportRow[];initialStatus?:string}) {
 const [search,setSearch]=useState(""),[status,setStatus]=useState(initialStatus);
 const visible=rows.filter(row=>(!status||row.status===status)&&`${row.tenantName} ${row.propertyName} ${row.unitLabel} ${row.contractNumber||""} ${row.note||""}`.toLocaleLowerCase("cs-CZ").includes(search.toLocaleLowerCase("cs-CZ")));
 const headers=["Nájemník","Nemovitost / jednotka","Smlouva","Stav","Od","Do","Plocha m²","Čisté nájemné","Nájemné Kč/m²","Služby","Sjednaná kauce","Držená kauce","Dluh","Poznámka"];
 const values=(row:TenancyReportRow)=>[row.tenantName,`${row.propertyName} · ${row.unitLabel}`,row.contractNumber||"—",leaseStatuses[row.status]||row.status,row.start,row.end,row.areaM2?.toLocaleString("cs-CZ")||"—",money(row.rentCents),row.rentPerM2Cents===null?"—":money(row.rentPerM2Cents),row.servicesCents===null?"—":money(row.servicesCents),row.agreedDepositCents===null?"—":money(row.agreedDepositCents),money(row.depositCents),row.debtCents===null?"—":money(row.debtCents),[row.expiring90Days&&"Končí do 90 dní",row.endedYtd&&"Ukončeno letos",row.note].filter(Boolean).join(" · ")||"—"];
 function download(){const quote=(value:string)=>`"${(/^[=+@\-\t\r]/.test(value)?"'":"")+value.replaceAll('"','""')}"`;const csv=[headers,...visible.map(values)].map(row=>row.map(quote).join(";")).join("\r\n");const url=URL.createObjectURL(new Blob(["\uFEFF",csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="najemni-vztahy.csv";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="card portfolio-table-card"><div className="table-toolbar"><div><h2>Nájemní vztahy</h2><p>{visible.length} smluv · aktivní i historické vztahy v jednom přehledu</p></div><div className="action-row"><label className="field"><span>Hledat ve vztazích</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nájemník, objekt nebo smlouva"/></label><label className="field"><span>Stav smlouvy</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Všechny stavy</option>{Object.entries(leaseStatuses).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label><button className="secondary" onClick={download}>Stáhnout CSV</button></div></div><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(row=><tr key={row.leaseId}>{values(row).map((value,i)=><td key={i}>{i===0?<Link href={`/nemovitosti/${row.propertyId}/smlouvy/${row.leaseId}`}>{value}</Link>:value}</td>)}</tr>)}{!visible.length&&<tr><td colSpan={headers.length} className="table-empty">Výběru neodpovídají žádné nájemní vztahy.</td></tr>}</tbody></table></div></section>;
}
