import { test, expect } from '@playwright/test';
test('R27A: custom market, 20-year horizon, chart toggle and immutable saved revision', async ({ page }) => {
  if (!process.env.DATABASE_URL || !['localhost','127.0.0.1','postgres'].includes(new URL(process.env.DATABASE_URL).hostname)) throw new Error('Isolated CI database required');
  const { PrismaClient } = await import('@prisma/client'); const db = new PrismaClient();
  try {
    const property = await db.property.findFirstOrThrow({ where: { active: true } });
    await page.goto('/login');
    await page.getByLabel('E-mail').fill(process.env.E2E_ADMIN_EMAIL || 'e2e.admin@flatcloud.test');
    await page.getByLabel('Heslo').fill(process.env.E2E_ADMIN_PASSWORD || 'FlatCloud-E2E-Only-Password-2026');
    await page.getByRole('button', { name: 'Přihlásit se', exact: true }).click();
    await expect(page).toHaveURL(/\/portfolio/);
    await page.goto(`/reporty?view=forecast&properties=${property.id}`);
    await page.getByLabel('Roční růst trhu', { exact: true }).fill('-1.25');
    await page.getByLabel('Doba přiblížení k dnešnímu trhu', { exact: true }).fill('60');
    await page.getByRole('button', { name: 'Přepočítat vlastní scénář', exact: true }).click();
    await page.locator('.forecast-custom-horizon summary').click();
    await page.getByLabel('Délka období', { exact: true }).fill('20');
    await page.getByRole('button', { name: 'Použít období', exact: true }).click();
    await expect(page).toHaveURL(/horizon=240/);
    await expect(page.getByLabel('Roční růst trhu', { exact: true })).toHaveValue('-1.25');
    await expect(page.getByLabel('Doba přiblížení k dnešnímu trhu', { exact: true })).toHaveValue('60');
    await expect(page.locator('.forecast-point')).toHaveCount(21);
    await page.getByRole('button', { name: 'Po měsících', exact: true }).click();
    await expect(page.locator('.forecast-point')).toHaveCount(240);
    const mf = page.getByRole('button', { name: 'MF', exact: true });
    await expect(mf).toHaveAttribute('aria-pressed', 'true');
    await mf.click(); await expect(mf).toHaveAttribute('aria-pressed', 'false');
    await expect(page.locator('.financial-chart-values')).not.toContainText('Tržní nájemné');
    await mf.click(); await expect(page.locator('.financial-chart-values')).toContainText('Tržní nájemné');
    await page.getByText('Uložit tuto variantu', { exact: true }).click();
    const name = `R24_AGENT_QA_2026_09 R27A ${crypto.randomUUID()}`;
    await page.getByLabel('Název scénáře *', { exact: true }).fill(name);
    await page.getByRole('button', { name: 'Uložit jako koncept', exact: true }).click();
    await expect(page).toHaveURL(/\/reporty\/valorizace\//);
    const plan = await db.rentForecastPlan.findFirstOrThrow({ where: { name } });
    expect(plan.horizonMonths).toBe(240);
    expect(plan.inputSnapshot).toMatchObject({ schemaVersion: 2, market: { annualGrowthBps: -125, catchUpMonths: 60 } });
    await expect(page.getByText(/Růst trhu −?\-?1,25 % ročně/)).toBeVisible();
    await page.getByText('Schválit tuto revizi', { exact: true }).click();
    await page.getByRole('button', { name: 'Potvrdit schválení plánu', exact: true }).click();
    await expect(page.getByText('Scénář byl schválen. Smlouvy ani předpisy se nezměnily.')).toBeVisible();
    await page.getByRole('button', { name: /Nová revize z LIVE dat/ }).click();
    await expect(page).not.toHaveURL(new RegExp(`${plan.id}$`));
    const revision = await db.rentForecastPlan.findFirstOrThrow({ where: { seriesId: plan.seriesId, revision: 2 } });
    expect(revision.inputSnapshot).toMatchObject({ schemaVersion: 2, market: { annualGrowthBps: -125, catchUpMonths: 60 } });
    expect((await db.rentForecastPlan.findUniqueOrThrow({ where: { id: plan.id } })).inputSnapshot).toEqual(plan.inputSnapshot);
    await page.goto('/metodika?view=chapters&q=valorizace');
    await expect(page.getByText('Valuace, valorizace a plán nájemného', { exact: true })).toBeVisible();
  } finally { await db.$disconnect(); }
});
