import { test,expect } from '@playwright/test';
test('R26B: source draft preserves input, requires original confirmation and retains revisions',async({page})=>{
 if(!process.env.DATABASE_URL||!['localhost','127.0.0.1','postgres'].includes(new URL(process.env.DATABASE_URL).hostname))throw new Error('Isolated CI database required');
 const {PrismaClient}=await import('@prisma/client');const db=new PrismaClient();try{
 const tag=`R24_AGENT_QA_2026_09 R26B ${crypto.randomUUID().slice(0,8)}`;
 const admin=await db.user.findUniqueOrThrow({where:{email:process.env.E2E_ADMIN_EMAIL||'e2e.admin@flatcloud.test'}});const owner=await db.owner.create({data:{name:tag}}),property=await db.property.create({data:{ownerId:owner.id,name:tag,address:'Syntetická 26',city:'Praha'}});
 const file=await db.fileAsset.create({data:{storageKey:tag,originalName:'synthetic.pdf',mimeType:'application/pdf',sizeBytes:10,sha256:tag,uploadedById:admin.id}});await db.document.create({data:{propertyId:property.id,fileAssetId:file.id,title:tag+' originál',category:'OTHER',createdById:admin.id}});
 await page.goto('/login');await page.getByLabel('E-mail').fill(process.env.E2E_ADMIN_EMAIL||'e2e.admin@flatcloud.test');await page.getByLabel('Heslo').fill(process.env.E2E_ADMIN_PASSWORD||'FlatCloud-E2E-Only-Password-2026');await page.getByRole('button',{name:'Přihlásit se',exact:true}).click();await expect(page).toHaveURL(/\/portfolio/);
 await page.goto(`/nemovitosti/${property.id}/vyuctovani/podklady`);
 await page.getByLabel('Dodavatel / zpracovatel',{exact:true}).fill(tag);await page.getByLabel('Číslo dokladu',{exact:true}).fill('QA-INV');await page.getByLabel('Celkový náklad dodávky Kč',{exact:true}).fill('120000');await page.getByLabel('Zálohy zaplacené dodavateli Kč – pouze informace',{exact:true}).fill('100000');await page.getByLabel('Řádek 1 – Náklad Kč',{exact:true}).fill('20000');
 await page.getByRole('button',{name:'Uložit návrh podkladu',exact:true}).click();await expect(page.getByText('Součet nákladových řádků se musí rovnat nákladu dodávky. Souhrny se nepřičítají.',{exact:true})).toBeVisible();await expect(page.getByLabel('Číslo dokladu',{exact:true})).toHaveValue('QA-INV');
 await page.getByLabel('Řádek 1 – Náklad Kč',{exact:true}).fill('120000');await page.getByLabel('Originál z dokumentů nemovitosti',{exact:true}).selectOption({label:tag+' originál'});await page.getByRole('button',{name:'Uložit návrh podkladu',exact:true}).click();await expect(page.getByRole('heading',{name:tag+' · QA-INV',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Potvrdit údaje podkladu',exact:true}).click();await expect(page.getByText('Potvrďte kontrolu originálu a všech načtených údajů.',{exact:true})).toBeVisible();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Potvrdit údaje podkladu',exact:true}).click();await expect(page.getByText('Údaje potvrzeny',{exact:true})).toBeVisible();
 expect(await db.charge.count({where:{lease:{unit:{propertyId:property.id}}}})).toBe(0);expect(await db.leaseCredit.count({where:{lease:{unit:{propertyId:property.id}}}})).toBe(0);
 await page.getByRole('link',{name:'Vytvořit opravu',exact:true}).click();await page.getByLabel('Důvod opravy',{exact:true}).fill('Oprava vysvětlení dodavatelského podkladu');await page.getByRole('button',{name:'Uložit návrh podkladu',exact:true}).click();await expect(page.getByRole('link',{name:'Předchozí verze',exact:true})).toBeVisible();expect(await db.settlementSource.count({where:{propertyId:property.id}})).toBe(2);
 }finally{await db.$disconnect();}
});
