import {expect,test,type Page} from "@playwright/test";import {PrismaClient} from "@prisma/client";import {R24_ROLE_PASSWORD,R24_ROLE_USERS} from "../prisma/seed-r24-agent-roles";
const db=new PrismaClient();const password=process.env.E2E_ROLE_PASSWORD||R24_ROLE_PASSWORD;
test.beforeAll(()=>{if(!["localhost","127.0.0.1","postgres"].includes(new URL(process.env.DATABASE_URL!).hostname))throw new Error("Requires isolated CI DB")});test.afterAll(()=>db.$disconnect());
async function login(page:Page,email:string){await page.context().clearCookies();await page.goto("/login");await page.getByLabel("E-mail").fill(email);await page.getByLabel("Heslo").fill(password);await page.getByRole("button",{name:"Přihlásit se"}).click();await expect(page).toHaveURL(/\/portfolio/)}
async function fixture(){const users=await db.user.findMany({where:{email:{in:[R24_ROLE_USERS.advanced,R24_ROLE_USERS.externalOwner,R24_ROLE_USERS.technicalManager,R24_ROLE_USERS.novice,R24_ROLE_USERS.internalAssistant,R24_ROLE_USERS.unitManager]}}});const by=new Map(users.map(u=>[u.email,u]));const owner=await db.owner.create({data:{name:"R26 agent owner"}}),property=await db.property.create({data:{ownerId:owner.id,name:"R26 agent house",address:"Syntetická 26",city:"Praha",memberships:{create:[{userId:by.get(R24_ROLE_USERS.advanced)!.id,permission:"EDIT"},{userId:by.get(R24_ROLE_USERS.technicalManager)!.id,permission:"EDIT"},{userId:by.get(R24_ROLE_USERS.externalOwner)!.id,permission:"VIEW"},{userId:by.get(R24_ROLE_USERS.internalAssistant)!.id,permission:"EDIT"},{userId:by.get(R24_ROLE_USERS.unitManager)!.id,permission:"EDIT"}]}}}),unit=await db.unit.create({data:{propertyId:property.id,label:"1",areaM2:50,userAccesses:{create:{userId:by.get(R24_ROLE_USERS.novice)!.id,permission:"VIEW"}}}}),tenant=await db.tenant.create({data:{name:"R26 agent tenant"}}),lease=await db.lease.create({data:{unitId:unit.id,tenantId:tenant.id,startDate:new Date("2025-01-01"),financialTrackingFromPeriod:"2025-01",variableSymbol:`R26${Date.now()}`,rentCents:100000,servicesCents:10000,autoChargesEnabled:false}}),protocol=await db.serviceSettlementProtocol.create({data:{leaseId:lease.id,periodFrom:new Date("2025-01-01"),periodTo:new Date("2025-12-31"),advancesCents:120000,actualCostsCents:100000,balanceCents:-20000,issuedById:by.get(R24_ROLE_USERS.advanced)!.id,snapshot:{schemaVersion:2,purpose:"WORKING_PAPER",blockers:[],period:{from:"2025-01-01",to:"2025-12-31"},property:{id:property.id,name:property.name,address:property.address,city:property.city},unit:{id:unit.id,label:unit.label},lease:{id:lease.id,contractNumber:null,tenantNames:["R26 agent tenant"]},totals:{advancesCents:120000,actualCostsCents:100000,balanceCents:-20000},advances:[],costs:[],meters:[],warnings:[]}}});return{property,unit,lease,protocol}}
test("R26 agent wave: manager, technician, owner and novice see correct settlement surfaces",async({page})=>{const f=await fixture();
 await login(page,R24_ROLE_USERS.advanced);await page.goto(`/nemovitosti/${f.property.id}/vyuctovani/pravidla`);await expect(page.getByRole("heading",{name:"Pravidla rozúčtování"})).toBeVisible();await expect(page.getByRole("heading",{name:"Nové pravidlo"})).toBeVisible();
 await login(page,R24_ROLE_USERS.technicalManager);await page.goto(`/nemovitosti/${f.property.id}/meridla`);await expect(page.getByRole("heading",{name:"Domovní měřidla"})).toBeVisible();await expect(page.getByText("Přidat domovní měřidlo")).toBeVisible();
 await login(page,R24_ROLE_USERS.externalOwner);await page.goto(`/nemovitosti/${f.property.id}/vyuctovani/pravidla`);await expect(page.getByRole("heading",{name:"Pravidla rozúčtování"})).toBeVisible();await expect(page.getByRole("heading",{name:"Nové pravidlo"})).toHaveCount(0);
 await login(page,R24_ROLE_USERS.novice);await page.goto(`/nemovitosti/${f.property.id}/vyuctovani/pravidla`);await expect(page.getByRole("heading",{name:"Pravidla rozúčtování"})).toHaveCount(0);
 await login(page,R24_ROLE_USERS.advanced);await page.goto(`/smlouvy/${f.lease.id}/vyuctovani/${f.protocol.id}`);await expect(page.getByRole("heading",{name:"Dokončení vyúčtování"})).toBeVisible();await expect(page.getByRole("button",{name:"1. Uzavřít skutečné úhrady"})).toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
});
