import { readingMethods } from "@/lib/meter-reading-rules";
import { SettlementEvidenceTable } from "@/components/SettlementEvidenceTable";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Shell } from "@/components/Shell";
import { Flash } from "@/components/FormUi";
import { PrintButton } from "@/components/PrintButton";
import { requireUser } from "@/lib/auth";
import { date, moneyExact as money } from "@/lib/format";
import { loadServiceSettlementProtocol, parseServiceSettlementSnapshot } from "@/lib/service-settlement-protocols";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function ServiceSettlementProtocolPage({ params, searchParams }: { params: Promise<{ leaseId: string; protocolId: string }>; searchParams: Promise<{ ok?: string; error?: string }> }) {
  const user = await requireUser(), { leaseId, protocolId } = await params, query = await searchParams;
  let protocol: Awaited<ReturnType<typeof loadServiceSettlementProtocol>>;
  try { protocol = await loadServiceSettlementProtocol(user, leaseId, protocolId); } catch { notFound(); }
  const snapshot = parseServiceSettlementSnapshot(protocol.snapshot);
  const workflow = await prisma.serviceSettlementWorkflow.findUnique({where:{protocolId},include:{charge:true,credit:true}});
  const paymentSnapshot = workflow?.paymentSnapshot as null | {prescribedAdvancesCents:number;paidServiceAdvancesCents:number;actualCostsCents:number;finalBalanceCents:number;blockers:string[];rows:Array<{period:string;serviceAdvanceCents:number;bankPaidCents:number;confirmedPaidServiceAdvanceCents:number}>;sourceSnapshot?:{costs:typeof snapshot.costs;evidence:typeof snapshot.confirmedCosts;warnings:string[]}};
  const finalCosts=paymentSnapshot?.sourceSnapshot?.costs||snapshot.costs;
  const working = snapshot.schemaVersion === 2;
  const finalized = Boolean(workflow?.approvedAt);
  const missingCosts = !finalized && working && snapshot.costs.length === 0;
  const finalBalance=paymentSnapshot?.finalBalanceCents;
  const resultLabel = finalized ? (finalBalance!>0?"Nedoplatek":finalBalance!<0?"Přeplatek":"Vyrovnáno") : working ? "Pracovní rozdíl proti předpisům" : protocol.balanceCents > 0 ? "Nedoplatek" : protocol.balanceCents < 0 ? "Přeplatek" : "Vyrovnáno";
  return <Shell user={user} taskPropertyId={protocol.lease.unit.propertyId} taskLeaseId={protocol.leaseId}><div className="page service-protocol-page">
    <div className="breadcrumb"><Link href={`/smlouvy/${leaseId}/vyuctovani?from=${snapshot.period.from}&to=${snapshot.period.to}`}>← Vyúčtování</Link><span>›</span><span>Vystavený protokol</span></div>
    <div className="page-title"><div><span className="eyebrow">Neměnný protokol · vystaveno {date(protocol.issuedAt)}</span><h1>{finalized ? "Vyúčtování služeb" : working ? "Pracovní protokol služeb" : "Vyúčtování služeb"}</h1><p>{snapshot.lease.tenantNames.join(" + ")} · {snapshot.property.name} · {snapshot.unit.label}</p></div><div className="action-row"><span className={`status ${workflow?.status==="SETTLED"?"ok":workflow?.status==="APPROVED"||workflow?.status==="DELIVERED"?"ok":"warn"}`}>{workflow?.status||"WORKING"}</span><PrintButton label="Vytisknout / uložit PDF"/></div></div>
    <Flash ok={query.ok} error={query.error}/>
    {working&&!finalized&&<div className="legal-warning"><p><strong>NÁVRH — NEURČENO K ÚHRADĚ</strong></p><strong>Neúplný pracovní podklad – není určen k doručení nájemníkovi.</strong><p>Porovnání s předepsanými zálohami není konečný výsledek proti přijatým úhradám. Uložení nezměnilo předpisy, kredity ani platby.</p>{snapshot.blockers?.map((blocker)=><p key={blocker}>{blocker}</p>)}</div>}
    <section className="card protocol-identity"><div><small>Zúčtovací období</small><strong>{snapshot.period.from} – {snapshot.period.to}</strong></div><div><small>Smlouva</small><strong>{snapshot.lease.contractNumber || "Bez čísla"}</strong></div><div><small>Nemovitost</small><strong>{snapshot.property.name}</strong><span>{snapshot.property.address}, {snapshot.property.city}</span></div><div><small>Nájemce</small><strong>{snapshot.lease.tenantNames.join(" + ")}</strong></div></section>
    <div className="settlement-summary-grid"><Summary label={finalized?"Potvrzeně uhrazené zálohy":"Předepsané zálohy"} value={money(finalized&&paymentSnapshot?paymentSnapshot.paidServiceAdvancesCents:protocol.advancesCents)}/><Summary label="Skutečné náklady" value={missingCosts ? "Chybí podklady" : money(finalized&&paymentSnapshot?paymentSnapshot.actualCostsCents:protocol.actualCostsCents)}/><Summary label={resultLabel} value={missingCosts ? "Nelze určit" : money(Math.abs(finalized&&finalBalance!=null?finalBalance:protocol.balanceCents))} tone={(finalized&&finalBalance!=null?finalBalance:protocol.balanceCents)>0?"warn":"ok"}/></div>
    <section className="card protocol-result"><div><h2>{finalized ? "Výsledek vyúčtování" : working ? "Pracovní rozdíl proti předpisům" : "Výsledek vyúčtování"}</h2><p>{finalized&&paymentSnapshot ? (paymentSnapshot.finalBalanceCents>0?`Nedoplatek ${money(paymentSnapshot.finalBalanceCents)}.`:paymentSnapshot.finalBalanceCents<0?`Přeplatek ${money(Math.abs(paymentSnapshot.finalBalanceCents))}.`:"Vyúčtování je vyrovnané.") : working ? "Tato částka není zaúčtována ani splatná. Finanční vypořádání bude samostatný krok po kontrole a schválení." : protocol.balanceCents>0?`Nájemci vznikl nedoplatek ${money(protocol.balanceCents)} se splatností ${protocol.dueDate?date(protocol.dueDate):"—"}.`:protocol.balanceCents<0?`Nájemci vznikl přeplatek ${money(Math.abs(protocol.balanceCents))}, který je evidován u smlouvy.`:"Náklady a předepsané zálohy jsou vyrovnané."}</p></div>{(workflow?.charge||protocol.charge)&&<Link className="primary" href={`/nemovitosti/${snapshot.property.id}/predpisy/mesicni/${workflow?.charge?.id||protocol.charge!.id}`}>Otevřít nedoplatek</Link>}{(workflow?.credit||protocol.credit)&&<Link className="primary" href={`/smlouvy/${leaseId}#vyuctovani`}>Otevřít přeplatek</Link>}</section>
    <section className="card settlement-workflow-card"><h2>Dokončení vyúčtování</h2><p>Pracovní protokol je neměnný. Uzávěrka úhrad, schválení, doručení a finanční vypořádání jsou samostatné auditované kroky.</p>
      {!workflow&&<form method="post" action={`/api/leases/${leaseId}/service-settlements/${protocolId}/close-payments`}><button className="primary">1. Uzavřít skutečné úhrady</button></form>}
      {workflow?.status==="WORKING"&&<form method="post" action={`/api/leases/${leaseId}/service-settlements/${protocolId}/close-payments`}><button className="primary">1. Uzavřít skutečné úhrady</button></form>}
      {paymentSnapshot&&<div className="settlement-summary-grid"><Summary label="Předepsané zálohy" value={money(paymentSnapshot.prescribedAdvancesCents)}/><Summary label="Potvrzeně uhrazené zálohy" value={money(paymentSnapshot.paidServiceAdvancesCents)}/><Summary label="Konečný výsledek proti úhradám" value={money(Math.abs(paymentSnapshot.finalBalanceCents))} tone={paymentSnapshot.finalBalanceCents>0?"warn":"ok"}/></div>}
      {paymentSnapshot?.blockers?.map(b=><div className="legal-warning" key={b}>{b}</div>)}
      {workflow?.status==="PAYMENT_CLOSED"&&<form method="post" action={`/api/leases/${leaseId}/service-settlements/${protocolId}/approve`}><button className="primary">2. Schválit vyúčtování</button></form>}
      {workflow?.status==="APPROVED"&&<form className="compact-form" method="post" action={`/api/leases/${leaseId}/service-settlements/${protocolId}/deliver`}><label className="field"><span>Způsob doručení</span><select name="method"><option>E-mail</option><option>Datová schránka</option><option>Osobně</option><option>Pošta</option></select></label><label className="field"><span>Reference doručení</span><input name="reference"/></label><label className="field"><span>Námitky do</span><input type="date" name="objectionUntil"/></label><button className="primary">3. Zaznamenat doručení</button></form>}
      {workflow?.status==="DELIVERED"&&!workflow.objectionRaisedAt&&<form className="compact-form" method="post" action={`/api/leases/${leaseId}/service-settlements/${protocolId}/objection`}><label className="field field-full"><span>Zaznamenat námitku nájemce</span><textarea name="note" required/></label><button className="secondary">Uložit námitku</button></form>}
      {workflow?.status==="OBJECTION_OPEN"&&<form className="compact-form" method="post" action={`/api/leases/${leaseId}/service-settlements/${protocolId}/resolve-objection`}><div className="legal-warning field-full"><strong>Otevřená námitka</strong><span>{workflow.objectionNote}</span></div><label className="field field-full"><span>Způsob vyřízení</span><textarea name="resolution" required/></label><button className="secondary">Uzavřít námitku</button></form>}
      {(workflow?.status==="DELIVERED"||workflow?.status==="OBJECTION_OPEN")&&<form className="compact-form" method="post" action={`/api/leases/${leaseId}/service-settlements/${protocolId}/settle`}><label className="field"><span>Splatnost případného nedoplatku</span><input type="date" name="dueDate" required defaultValue={new Date(Date.now()+14*86400000).toISOString().slice(0,10)}/></label><button className="primary">4. Finančně vypořádat</button></form>}
      {workflow?.status==="SETTLED"&&<div className="notice"><strong>Vyúčtování je uzavřeno</strong><span>{workflow.chargeId?"Vznikl samostatný předpis nedoplatku.":workflow.creditId?"Vznikl samostatný přeplatek.":"Výsledek je nulový."}</span></div>}
    </section>
    <section className="card settlement-source-card"><h2>Rozpis skutečných nákladů</h2><div className="table-wrap"><table><thead><tr><th>Datum</th><th>Zdroj</th><th>{snapshot.costBasis === "CONFIRMED_SOURCES" ? "Náklad řádku" : "Částka dokladu"}</th><th>{snapshot.costBasis === "CONFIRMED_SOURCES" ? "Náklad smlouvy" : "Podíl jednotky"}</th><th>Způsob rozdělení</th></tr></thead><tbody>{finalCosts.map((row)=><tr key={row.sourceCostId}><td>{row.effectiveAt}</td><td><strong>{row.title}</strong></td><td>{money(row.sourceAmountCents)}</td><td>{money(row.allocatedAmountCents)}</td><td>{row.allocationLabel}</td></tr>)}</tbody></table></div></section>
    <SettlementEvidenceTable rows={snapshot.confirmedCosts || []}/>
    <section className="card settlement-source-card"><h2>Rozpis předepsaných záloh</h2><div className="settlement-chip-list">{snapshot.advances.map((row)=><span key={row.period}><small>{row.period}</small><strong>{money(row.amountCents)}</strong></span>)}</div></section>
    <section className="card settlement-source-card"><h2>Odečty</h2><div className="table-wrap"><table><thead><tr><th>Měřidlo</th><th>Počáteční stav</th><th>Koncový stav</th><th>Spotřeba</th></tr></thead><tbody>{snapshot.meters.length?snapshot.meters.map((row)=><tr key={`${row.label}-${row.unitOfMeasure}`}><td><strong>{row.label}</strong></td><td>{row.opening?`${row.opening.value.toLocaleString("cs-CZ")} · ${row.opening.date} · ${readingMethods[(row.opening.method || "LEGACY") as keyof typeof readingMethods]}`:"—"}</td><td>{row.closing?`${row.closing.value.toLocaleString("cs-CZ")} · ${row.closing.date} · ${readingMethods[(row.closing.method || "LEGACY") as keyof typeof readingMethods]}`:"—"}</td><td>{row.consumption==null?"—":`${row.consumption.toLocaleString("cs-CZ")} ${row.unitOfMeasure}`}</td></tr>):<tr><td className="table-empty" colSpan={4}>Bez evidovaných měřidel.</td></tr>}</tbody></table></div></section>
    {snapshot.warnings.length>0&&<section className="card protocol-notes"><h2>Poznámky k podkladům</h2>{snapshot.warnings.map((warning)=><p key={warning}>{warning}</p>)}</section>}
    <footer className="protocol-footer"><span>Vystavil/a {protocol.issuedBy.name}</span><span>{date(protocol.issuedAt)}</span><span>ID protokolu {protocol.id}</span></footer>
  </div></Shell>;
}

function Summary({label,value,tone=""}:{label:string;value:string;tone?:string}){return <div className={`card settlement-summary ${tone}`}><span>{label}</span><strong>{value}</strong><small>zmrazeno při vystavení</small></div>}
