import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { requirePropertyAccess, unitAccessWhere } from "@/lib/access";
import { Shell } from "@/components/Shell";
import { Field, Flash, FormCard, FormPage, Select, Textarea } from "@/components/FormUi";
import { dateInput, moneyInput } from "@/lib/forms";

export const dynamic="force-dynamic";
export default async function NewManualPayment({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{ok?:string;error?:string}>}){const user=await requireUser();const {id}=await params;const [property,charges,query]=await Promise.all([requirePropertyAccess(user,id),prisma.charge.findMany({where:{lease:{unit:unitAccessWhere(user,id)}},include:{allocations:true,lease:{include:{tenant:true,unit:true}}},orderBy:[{dueDate:"desc"}]}),searchParams]);if(!property)notFound();const openCharges=charges.filter(charge=>charge.allocations.reduce((s,a)=>s+a.amountCents,0)<charge.amountCents);return <Shell user={user}><FormPage title="Přidat ruční platbu" description="Dočasná evidence pro testování sald před připojením banky." backHref={`/nemovitosti/${id}/platby`}><Flash ok={query.ok} error={query.error}/>{openCharges.length?<FormCard action={`/api/properties/${id}/payments/manual`} cancelHref={`/nemovitosti/${id}/platby`} submitLabel="Uložit platbu"><Select label="Předpis" name="chargeId" required full options={openCharges.map(charge=>{const paid=charge.allocations.reduce((s,a)=>s+a.amountCents,0);return [charge.id,`${charge.lease.unit.label} · ${charge.lease.tenant.name} · ${charge.period} · zbývá ${moneyInput(charge.amountCents-paid)} Kč`]})}/><Field label="Datum přijetí" name="bookedAt" type="date" defaultValue={dateInput(new Date())} required/><Field label="Částka Kč" name="amount" type="number" step="0.01" min={0} required/><Field label="Jméno plátce" name="counterpartyName"/><Field label="Variabilní symbol" name="variableSymbol"/><Textarea label="Poznámka" name="message"/></FormCard>:<div className="card empty-state"><h2>Nejsou otevřené předpisy</h2><p>Nejprve vytvořte měsíční předpisy nebo jsou všechny již uhrazené.</p></div>}</FormPage></Shell>}
