/** Event workflows live outside TaskAutomationRule; links lead to their real controls. */
export const eventTaskWorkflows = [
  { name: "Upomínky a dluh na nájemném", trigger: "Splatné platební zprávy; při opravě plateb se případ znovu vyhodnotí. Po uhrazení se uzavírá.", assignee: "Správce, jinak jednoznačný vlastník jednotky.", controls: "Termíny, aktivace a texty zpráv", href: "/nastaveni/system#odesilani-emailu" },
  { name: "Nevyřešený bankovní pohyb", trigger: "Příjem notifikace, nespárovaná transakce nebo ruční změna párování. Vyřešený pohyb úkol uzavře.", assignee: "Odpovědná osoba účtu; u domovního účtu správce, jinak oprávněný správce systému.", controls: "Fronta pohybů a pravidla u účtu; bezpečnostní kontrola nemá vypínač", href: "/platby/nesparovane" },
  { name: "Změna účtu pro nájemné", trigger: "Naplánovaná změna účtu vytvoří oznámení jen pro dotčenou smlouvu a úkol k potvrzení doručení.", assignee: "Správce, jinak jednoznačný vlastník jednotky. Blokovanou změnu řeší zadavatel.", controls: "Změna a datum účinnosti u bankovního účtu", href: "/bankovni-ucty" },
  { name: "Odečty měřidel", trigger: "Průběžně po 90 dnech a roční odečty v prosinci. Checklist se doplňuje a uzavírá podle odečtů.", assignee: "Správce nebo vlastník podle rozsahu měřidla.", controls: "Evidence na kartě měřidel; produkční spuštění řídí konfigurace služby", href: "/portfolio" },
  { name: "Zpráva, závada a změna kontaktu od nájemníka", trigger: "Požadavek odeslaný z portálu vytvoří případ s vazbou na konkrétní nájemní smlouvu.", assignee: "Kontaktní správce či vlastník příslušné jednotky.", controls: "Zpracování případu v Úkolech; událostní pravidlo bez časového plánovače", href: "/ukoly" },
  { name: "Souhlas s podpisem dokladů", trigger: "Přiřazení zástupce vystavitele; po souhlasu se úkol uzavře, po odvolání znovu otevře.", assignee: "Konkrétní určený zástupce.", controls: "Vystavitel a zástupci na kartě vlastníka", href: "/vlastnici" },
  { name: "Realizace plánu obnovy", trigger: "Potvrzený převod položky plánu do realizace založí navázaný úkol. Nejde o pravidelný cron.", assignee: "Správce objektu, jinak uživatel, který převod potvrdil.", controls: "Plán obnovy a CAPEX", href: "/portfolio/kvalita/plan" },
] as const;
