// Public instructions checked against the linked bank documentation on 2026-10-07.
// Documentation coverage is NOT a statement of parser compatibility.
export const bankNotificationGuides = [
  { code: "3030", name: "Air Bank", title: "Oznámení o změně zůstatku", helpUrl: "https://www.airbank.cz/co-vas-nejvic-zajima/nastaveni-upozorneni-pod-uctem/", steps: ["V My Air otevřete Menu → Nastavení a banka → Oznámení. Upozornění nastavujete pro každý účet zvlášť.", "Vyberte zasílání mailem. Zkontrolujte, že jde o jednotlivé příchozí platby s částkou, účtem a VS, ne pouze pravidelný přehled zůstatku."] },
  { code: "5500", name: "Raiffeisenbank", title: "Informuj mě", helpUrl: "https://www.rb.cz/osobni/ucty/sluzby-k-uctum/informuj-me", steps: ["V bankovnictví otevřete Informuj mě a vyberte účet nájemného. V mobilní aplikaci službu najdete v Menu → Nastavení → Informuj mě.", "Nastavte e-mailová oznámení o příchozích pohybech. Zkontrolujte příjemce a částkový limit; pokud nabídka umožňuje vynechat zůstatek, vypněte jeho připojení."] },
  { code: "0800", name: "Česká spořitelna", title: "Informační zprávy v Georgi", helpUrl: "https://www.csas.cz/cs/caste-dotazy/jak-si-v-georgi-nastavim-zasilani-informacnich-zprav", steps: ["V Georgi na počítači otevřete ikonu profilu → Informační zprávy. U příchozích plateb klikněte na Aktivovat a vyberte účet.", "Zvolte doručení e-mailem, zadejte nebo vyberte kontakt a potvrďte. Zkontrolujte stav Aktivní. Mobilní návod popisuje push oznámení; George Business má vlastní nastavení notifikací."] },
  { code: "0300", name: "ČSOB", title: "Moje info", helpUrl: "https://www.csob.cz/lide/ucty/internetove-a-mobilni-bankovnictvi/internetove-bankovnictvi", steps: ["V bankovnictví otevřete Moje info a vyberte upozornění na zaúčtovanou platbu či pohyb na účtu. Nabídka firemního ČSOB CEB se liší.", "Zapněte e-mailové doručení pro účet nájemného a ověřte obsah zprávy. Aktuální podrobné menu ověřte v nápovědě svého bankovnictví."] },
  { code: "2010", name: "Fio banka", title: "Oznámení o pohybech", helpUrl: "https://www2.fio.cz/bankovni-sluzby/oznameni", steps: ["V Internetbankingu otevřete Nastavení → Oznámení; ve Smartbankingu Moje Fio → Oznámení. Vyberte Pohyby a příchozí platby.", "Zvolte e-mail. Přímo v bance lze omezit oznámení minimální částkou, účtem protistrany nebo konkrétním variabilním symbolem. Pro soukromý účet použijte VS nájmů."] },
  { code: "0100", name: "Komerční banka", title: "Oznámení v KB+", helpUrl: "https://www.kb.cz/cs/podpora/mobilni-aplikace/vylepsujeme-oznameni-v-kb", steps: ["Ve webové KB+ otevřete Nastavení → Nastavení služeb → Oznámení. Zvolte Příchozí platby a účet nájemného.", "Zapněte e-mailové oznámení a uložte změnu. Po změně systému oznámení je podle banky potřeba dřívější e-mailová oznámení znovu zapnout.", "Používáte stále MojeBanka? Tam otevřete Oznámení o platbách a vyberte příchozí úhrady. Jiného příjemce lze přidat přes Nastavení → Přidání nového příjemce; tato možnost není potvrzením stejné funkce v KB+."] },
  { code: "0600", name: "MONETA Money Bank", title: "Info Servis", helpUrl: "https://www.moneta.cz/caste-dotazy/odpoved/jak-si-nastavim-info-servis-", steps: ["Podle nápovědy banky se Info Servis nastavuje v původní Internet Bance: Osobní nastavení → Nastavení Info Servisu.", "Vyberte e-mailové zprávy o příchozích penězích. Zkontrolujte adresu a minimální částku. Pokud původní Internet Banku nemáte, požádejte o nastavení banku; v nové verzi může nabídka chybět."] },
  { code: "2700", name: "UniCredit Bank", title: "E-mailové notifikace v Online Bankingu", helpUrl: "https://www.unicreditbank.cz/cs/obcane/digital/online-banking.html", steps: ["V Online Bankingu klikněte na ozubené kolo vpravo nahoře a otevřete nastavení notifikací. Vyberte účet a upozornění na jeho transakce.", "Zvolte e-mail, jednotlivé transakce místo denního souhrnu a vyplňte cílovou adresu. Omezte oznámení na příchozí platby podle dostupných podmínek."] },
  { code: "5800", name: "J&T Banka", title: "Notifikace o pohybech", helpUrl: "https://vitejte.jtbank.cz/", steps: ["V internetovém bankovnictví vyberte účet a jeho Vlastnosti. V detailu otevřete nastavení notifikací o zůstatku a pohybech.", "Vyberte pohyby, nastavte minimální částku a kontakt pro e-mail. Uložte a potvrďte autorizačním kódem. Ověřte, že notifikace obsahuje údaje pro přiřazení platby."] },
] as const;

export type BankNotificationInstructions = { name: string; title: string; helpUrl: string; steps: readonly string[] };

// No invented click paths for banks whose current payment-email setup is not established.
export const otherNotificationBanks = [
  { code: "6210", name: "mBank", note: "Oficiální nápověda popisuje push oznámení. E-mailové avízo každé příchozí platby nemáme doložené; měsíční výpis není náhradou.", helpUrl: "https://www.mbank.cz/osobni/mobilni-aplikace/funkce/" },
  { code: "2250", name: "Banka CREDITAS", note: "Banka uvádí e-mailová upozornění na pohyby. Konkrétní nastavení v aktuální aplikaci a formát zprávy je potřeba ověřit s bankou.", helpUrl: "https://www.creditas.cz/faq" },
  { code: "6363", name: "Partners Banka", note: "E-mailové avízo příchozí platby s VS zatím nemáme doložené. Nejdříve ověřte tuto možnost s bankou.", helpUrl: "https://www.partnersbanka.cz/zustante-v-bezpeci" },
  { code: "2070", name: "TRINITY BANK", note: "Aktuální nastavení e-mailového avíza příchozí platby s VS ověřte s bankou; samotné oznámení o zůstatku nestačí.", helpUrl: "https://www.trinitybank.cz/" },
  { code: "6000", name: "PPF banka", note: "Notifikace závisí na verzi bankovnictví. Aktuální postup pro příchozí platby ověřte s bankou.", helpUrl: "https://www.ppfbanka.cz/" },
  { code: "8040", name: "Oberbank", note: "E-mailové avízo příchozí platby s VS a jeho nastavení zatím nemáme ověřené. Obraťte se na podporu banky.", helpUrl: "https://www.oberbank.cz/" },
  { code: "OTHER", name: "Jiná banka", note: "Nejdříve u banky ověřte, zda nabízí e-mailové avízo jednotlivé příchozí platby s částkou, účtem a VS. Push zpráva ani souhrnný výpis nestačí.", helpUrl: "" },
] as const;
