import { PaymentStatus, type Prisma } from "@prisma/client";
import { hasAllPropertyAccess } from "./auth";
import { prisma } from "./db";
import { allocateAvailableTransactionToLeaseTx, recomputeTransactionStatusTx } from "./matching";
import { serializableTransaction } from "./serializable";
import { reconcileCollectionTasksAfterPaymentCorrectionTx } from "./tasks";

type Actor={id:string;role:string;allProperties?:boolean};
type CorrectionTransaction={id:string;bankAccount:{propertyId:string};suggestedLease?:{unitId:string;variableSymbol:string;tenant:{name:string}}|null;allocations:Array<{charge:{lease:{unitId:string;variableSymbol:string;tenant:{name:string}}}}> ;securityDepositReceipts:Array<{lease:{unitId:string}}>};
type AllocationSnapshot={allocationId:string;chargeId:string;leaseId:string;amountCents:number};
const correctionInclude={bankAccount:true,suggestedLease:{select:{unitId:true,variableSymbol:true,tenant:{select:{name:true}}}},allocations:{include:{charge:{include:{lease:{select:{id:true,unitId:true,variableSymbol:true,tenant:{select:{name:true}}}}}}}},securityDepositReceipts:{include:{lease:{select:{id:true,unitId:true}}}}} as const;

export function transactionCorrectionUnitIds(transaction:CorrectionTransaction){return [...new Set([...transaction.allocations.map(row=>row.charge.lease.unitId),...transaction.securityDepositReceipts.map(row=>row.lease.unitId),...(transaction.suggestedLease?[transaction.suggestedLease.unitId]:[])])];}
export function canCorrectTransactionFromGrants(propertyId:string,unitIds:string[],grants:{wholePropertyIds:string[];unitIds:string[]},allProperties=false){return allProperties||grants.wholePropertyIds.includes(propertyId)||(unitIds.length>0&&unitIds.every(id=>grants.unitIds.includes(id)))}
export function canRemoveFinalTransactionUnitAnchor(hasPropertyAccess:boolean,remainingAuthoritativeUnitIds:string[]){return hasPropertyAccess||remainingAuthoritativeUnitIds.length>0}
export async function hasPropertyCorrectionAccess(actor:Actor,propertyId:string,tx:Prisma.TransactionClient|typeof prisma=prisma){if(hasAllPropertyAccess(actor))return true;return Boolean(await tx.userProperty.findFirst({where:{userId:actor.id,propertyId,permission:{in:["EDIT","ADMIN"]}},select:{propertyId:true}}))}
export async function canCorrectTransaction(actor:Actor,propertyId:string,unitIds:string[],tx:Prisma.TransactionClient|typeof prisma=prisma){if(hasAllPropertyAccess(actor))return true;const [propertyGrant,unitGrants]=await Promise.all([tx.userProperty.findFirst({where:{userId:actor.id,propertyId,permission:{in:["EDIT","ADMIN"]}},select:{propertyId:true}}),unitIds.length?tx.userUnit.findMany({where:{userId:actor.id,unitId:{in:unitIds},permission:{in:["EDIT","ADMIN"]},unit:{propertyId}},select:{unitId:true}}):[]]);return canCorrectTransactionFromGrants(propertyId,unitIds,{wholePropertyIds:propertyGrant?[propertyGrant.propertyId]:[],unitIds:unitGrants.map(row=>row.unitId)})}
async function requireTransactionCorrectionAccess(tx:Prisma.TransactionClient,actor:Actor,transaction:CorrectionTransaction,additionalUnitIds:string[]=[]){const unitIds=[...new Set([...transactionCorrectionUnitIds(transaction),...additionalUnitIds])];if(!await canCorrectTransaction(actor,transaction.bankAccount.propertyId,unitIds,tx))throw new Error("Nemáte oprávnění opravovat přiřazení této platby.")}
const snapshots=(transaction:any):AllocationSnapshot[]=>transaction.allocations.map((row:any)=>({allocationId:row.id,chargeId:row.chargeId,leaseId:row.charge.leaseId,amountCents:row.amountCents}));
export function uniqueAssignmentLeaseId(leaseIds:string[]){const unique=[...new Set(leaseIds)];return unique.length===1?unique[0]:null}
export function manualCancellationError(input:{source:string;status:string;matchNote?:string|null;depositLinked:boolean}){if(input.source!=="manual")return "Stornovat lze pouze ručně evidovanou platbu.";if(input.status===PaymentStatus.IGNORED)return input.matchNote==="Ruční platba stornována správcem."?"Ruční platba již byla stornována.":"Ruční platba je již označena jako ignorovaná a nelze ji tímto způsobem stornovat.";if(input.depositLinked)return "Platbu nelze stornovat, protože její část byla zaúčtována jako kauce. Nejprve je nutné opravit evidenci kauce.";return null}
export function crossPropertyReassignError(source:string,sourcePropertyId:string,targetPropertyId:string){return sourcePropertyId!==targetPropertyId&&source!=="manual"?"Bankovní transakci nelze přesunout mezi nemovitostmi. Přepárovat ji lze pouze v rámci objektu, na jehož bankovní účet byla přijata.":null}
export function reassignedManualMetadata(input:{source:string;counterpartyName:string|null;variableSymbol:string|null;previousTenantName?:string;previousLeaseVariableSymbol?:string;targetTenantName:string;targetLeaseVariableSymbol:string}){return {counterpartyName:input.source==="manual"&&input.previousTenantName&&input.counterpartyName===input.previousTenantName?input.targetTenantName:input.counterpartyName,variableSymbol:input.source==="manual"&&input.previousLeaseVariableSymbol&&input.variableSymbol===input.previousLeaseVariableSymbol?input.targetLeaseVariableSymbol:input.variableSymbol}}

const finalAnchorError="Úplné odpárování platby může provést pouze správce celé nemovitosti. Platbu můžete přímo přepárovat na jinou jednotku, ke které máte oprávnění.";
async function requireRemainingUnitAnchorOrPropertyAccess(tx:Prisma.TransactionClient,actor:Actor,propertyId:string,remainingUnitIds:string[]){if(!canRemoveFinalTransactionUnitAnchor(await hasPropertyCorrectionAccess(actor,propertyId,tx),remainingUnitIds))throw new Error(finalAnchorError)}

export async function reconcileTransactionAssignmentMetadata(tx:Prisma.TransactionClient,transactionId:string,note="Ruční korekce přiřazení správcem."){const transaction=await tx.bankTransaction.findUnique({where:{id:transactionId},include:{allocations:{include:{charge:{select:{leaseId:true}}}},securityDepositReceipts:{select:{leaseId:true}}}});if(!transaction)throw new Error("Platba nebyla nalezena.");const leaseIds=[...transaction.allocations.map(row=>row.charge.leaseId),...transaction.securityDepositReceipts.map(row=>row.leaseId)];await tx.bankTransaction.update({where:{id:transactionId},data:{suggestedLeaseId:uniqueAssignmentLeaseId(leaseIds),matchedRuleId:null,matchNote:note}});return [...new Set(leaseIds)]}

export async function unallocatePayment(actor:Actor,propertyId:string,transactionId:string,allocationId:string){return serializableTransaction(async tx=>{const transaction=await tx.bankTransaction.findFirst({where:{id:transactionId,bankAccount:{propertyId}},include:correctionInclude});if(!transaction)throw new Error("Platba nebyla nalezena.");if(transaction.status===PaymentStatus.IGNORED)throw new Error("Stornovanou nebo ignorovanou platbu nelze opravovat.");await requireTransactionCorrectionAccess(tx,actor,transaction);const allocation=transaction.allocations.find(row=>row.id===allocationId);if(!allocation)throw new Error("Platba již byla odpárována.");const remainingUnitIds=[...new Set([...transaction.allocations.filter(row=>row.id!==allocationId).map(row=>row.charge.lease.unitId),...transaction.securityDepositReceipts.map(row=>row.lease.unitId)])];await requireRemainingUnitAnchorOrPropertyAccess(tx,actor,propertyId,remainingUnitIds);const previous:AllocationSnapshot={allocationId:allocation.id,chargeId:allocation.chargeId,leaseId:allocation.charge.leaseId,amountCents:allocation.amountCents};await tx.paymentAllocation.delete({where:{id:allocation.id}});await reconcileTransactionAssignmentMetadata(tx,transactionId);await recomputeTransactionStatusTx(tx,transactionId);await reconcileCollectionTasksAfterPaymentCorrectionTx(tx,[previous.leaseId]);await tx.auditLog.create({data:{userId:actor.id,propertyId,action:"PAYMENT_UNALLOCATED",entityType:"BankTransaction",entityId:transactionId,details:{transactionId,...previous}}});return previous})}

export async function unallocateAllPayment(actor:Actor,propertyId:string,transactionId:string){return serializableTransaction(async tx=>{const transaction=await tx.bankTransaction.findFirst({where:{id:transactionId,bankAccount:{propertyId}},include:correctionInclude});if(!transaction)throw new Error("Platba nebyla nalezena.");if(transaction.status===PaymentStatus.IGNORED)throw new Error("Stornovanou nebo ignorovanou platbu nelze opravovat.");await requireTransactionCorrectionAccess(tx,actor,transaction);const previousAllocations=snapshots(transaction);if(!previousAllocations.length)throw new Error("Platba již nemá žádná přiřazení nájemného.");const remainingUnitIds=[...new Set(transaction.securityDepositReceipts.map(row=>row.lease.unitId))];await requireRemainingUnitAnchorOrPropertyAccess(tx,actor,propertyId,remainingUnitIds);await tx.paymentAllocation.deleteMany({where:{transactionId}});await reconcileTransactionAssignmentMetadata(tx,transactionId);await recomputeTransactionStatusTx(tx,transactionId);await reconcileCollectionTasksAfterPaymentCorrectionTx(tx,previousAllocations.map(row=>row.leaseId));await tx.auditLog.create({data:{userId:actor.id,propertyId,action:"PAYMENT_UNALLOCATED_ALL",entityType:"BankTransaction",entityId:transactionId,details:{transactionId,previousAllocations}}});return previousAllocations})}

export async function reassignPayment(actor:Actor,propertyId:string,transactionId:string,targetLeaseId:string){return serializableTransaction(async tx=>{
  const transaction=await tx.bankTransaction.findFirst({where:{id:transactionId,bankAccount:{propertyId}},include:correctionInclude});
  if(!transaction)throw new Error("Platba nebyla nalezena.");
  await requireTransactionCorrectionAccess(tx,actor,transaction);
  if(transaction.status===PaymentStatus.IGNORED)throw new Error("Stornovanou nebo ignorovanou platbu nelze přepárovat.");
  if(transaction.securityDepositReceipts.length)throw new Error("Část platby je zaúčtována jako kauce. Lze opravit jednotlivé alokace nájemného, ale celou platbu nelze přepárovat.");
  const sourcePropertyId=transaction.bankAccount.propertyId;
  const target=await tx.lease.findFirst({where:{id:targetLeaseId,unit:{property:{active:true}}},select:{id:true,unitId:true,variableSymbol:true,tenant:{select:{name:true}},unit:{select:{label:true,propertyId:true,property:{select:{name:true}}}}}});
  if(!target)throw new Error("Cílový nájemní vztah nebyl nalezen.");
  const targetPropertyId=target.unit.propertyId;
  if(!await canCorrectTransaction(actor,targetPropertyId,[target.unitId],tx))throw new Error("Nemáte oprávnění přepárovat platbu na cílový nájemní vztah.");
  const crossPropertyBlocked=crossPropertyReassignError(transaction.source,sourcePropertyId,targetPropertyId);
  if(crossPropertyBlocked)throw new Error(crossPropertyBlocked);
  const previousAllocations=snapshots(transaction);
  const previousLeaseIds=[...new Set(previousAllocations.map(row=>row.leaseId))];
  const uniquePreviousLeaseId=previousLeaseIds.length===1?previousLeaseIds[0]:null;
  const allocationLease=uniquePreviousLeaseId?transaction.allocations.find(row=>row.charge.lease.id===uniquePreviousLeaseId)?.charge.lease:null;
  const previousLease=transaction.suggestedLease||allocationLease;
  const previousCounterpartyName=transaction.counterpartyName;
  const previousVariableSymbol=transaction.variableSymbol;
  const correctedMetadata=reassignedManualMetadata({source:transaction.source,counterpartyName:previousCounterpartyName,variableSymbol:previousVariableSymbol,previousTenantName:previousLease?.tenant.name,previousLeaseVariableSymbol:previousLease?.variableSymbol,targetTenantName:target.tenant.name,targetLeaseVariableSymbol:target.variableSymbol});
  const newCounterpartyName=correctedMetadata.counterpartyName,newVariableSymbol=correctedMetadata.variableSymbol;
  let targetBankAccountId=transaction.bankAccountId;
  if(sourcePropertyId!==targetPropertyId){
    const targetAccount=await tx.bankAccount.upsert({where:{provider_externalAccountId:{provider:"manual",externalAccountId:`manual-${targetPropertyId}`}},update:{},create:{propertyId:targetPropertyId,provider:"manual",bankName:"Ruční evidence",ibanMasked:"RUČNÍ PLATBY",externalAccountId:`manual-${targetPropertyId}`}});
    targetBankAccountId=targetAccount.id;
  }
  await tx.paymentAllocation.deleteMany({where:{transactionId}});
  if(targetBankAccountId!==transaction.bankAccountId)await tx.bankTransaction.update({where:{id:transactionId},data:{bankAccountId:targetBankAccountId}});
  const allocated=await allocateAvailableTransactionToLeaseTx(tx,transactionId,targetLeaseId);
  if(!allocated)throw new Error("Platbu se nepodařilo přepárovat.");
  await tx.bankTransaction.update({where:{id:transactionId},data:{suggestedLeaseId:targetLeaseId,matchedRuleId:null,matchNote:"Ruční platba přepárována správcem.",counterpartyName:newCounterpartyName,variableSymbol:newVariableSymbol}});
  await recomputeTransactionStatusTx(tx,transactionId);
  await reconcileCollectionTasksAfterPaymentCorrectionTx(tx,[...previousLeaseIds,targetLeaseId]);
  const details={transactionId,sourcePropertyId,targetPropertyId,previousLeaseIds,targetLeaseId,previousAllocations,newAllocations:allocated.allocations,remainingCents:allocated.remainingCents,previousCounterpartyName,newCounterpartyName,previousVariableSymbol,newVariableSymbol};
  await tx.auditLog.create({data:{userId:actor.id,propertyId:sourcePropertyId,action:"PAYMENT_REASSIGNED",entityType:"BankTransaction",entityId:transactionId,details}});
  if(sourcePropertyId!==targetPropertyId)await tx.auditLog.create({data:{userId:actor.id,propertyId:targetPropertyId,action:"PAYMENT_REASSIGNED",entityType:"BankTransaction",entityId:transactionId,details}});
  return {previousAllocations,...allocated,targetPropertyId,targetPropertyName:target.unit.property.name,targetUnitLabel:target.unit.label,targetTenantName:target.tenant.name,manual:transaction.source==="manual"};
})}

export async function cancelManualPayment(actor:Actor,propertyId:string,transactionId:string){return serializableTransaction(async tx=>{const transaction=await tx.bankTransaction.findFirst({where:{id:transactionId,bankAccount:{propertyId}},include:correctionInclude});if(!transaction)throw new Error("Platba nebyla nalezena.");await requireTransactionCorrectionAccess(tx,actor,transaction);const blocked=manualCancellationError({source:transaction.source,status:transaction.status,matchNote:transaction.matchNote,depositLinked:transaction.securityDepositReceipts.length>0});if(blocked)throw new Error(blocked);await requireRemainingUnitAnchorOrPropertyAccess(tx,actor,propertyId,[]);const previousAllocations=snapshots(transaction),previousSuggestedLeaseId=transaction.suggestedLeaseId;await tx.paymentAllocation.deleteMany({where:{transactionId}});await tx.bankTransaction.update({where:{id:transactionId},data:{suggestedLeaseId:null,matchedRuleId:null,status:PaymentStatus.IGNORED,matchNote:"Ruční platba stornována správcem."}});await reconcileCollectionTasksAfterPaymentCorrectionTx(tx,previousAllocations.map(row=>row.leaseId));await tx.auditLog.create({data:{userId:actor.id,propertyId,action:"MANUAL_PAYMENT_CANCELLED",entityType:"BankTransaction",entityId:transactionId,details:{transactionId,amountCents:transaction.amountCents,bookedAt:transaction.bookedAt.toISOString(),counterpartyName:transaction.counterpartyName,variableSymbol:transaction.variableSymbol,message:transaction.message,previousSuggestedLeaseId,previousAllocations}}});return {previousAllocations}})}
