import { PaymentStatus, type Prisma } from "@prisma/client";
import { hasAllPropertyAccess } from "./auth";
import { prisma } from "./db";
import { allocateAvailableTransactionToLeaseTx, recomputeTransactionStatusTx } from "./matching";
import { serializableTransaction } from "./serializable";
import { reconcileCollectionTasksAfterPaymentCorrectionTx } from "./tasks";

type Actor={id:string;role:string;allProperties?:boolean};
type CorrectionTransaction={id:string;bankAccount:{propertyId:string};suggestedLease?:{unitId:string}|null;allocations:Array<{charge:{lease:{unitId:string}}}>;securityDepositReceipts:Array<{lease:{unitId:string}}>};
type AllocationSnapshot={allocationId:string;chargeId:string;leaseId:string;amountCents:number};
const correctionInclude={bankAccount:true,suggestedLease:{select:{unitId:true}},allocations:{include:{charge:{include:{lease:{select:{id:true,unitId:true}}}}}},securityDepositReceipts:{include:{lease:{select:{id:true,unitId:true}}}}} as const;

export function transactionCorrectionUnitIds(transaction:CorrectionTransaction){return [...new Set([...transaction.allocations.map(row=>row.charge.lease.unitId),...transaction.securityDepositReceipts.map(row=>row.lease.unitId),...(transaction.suggestedLease?[transaction.suggestedLease.unitId]:[])])];}
export function canCorrectTransactionFromGrants(propertyId:string,unitIds:string[],grants:{wholePropertyIds:string[];unitIds:string[]},allProperties=false){return allProperties||grants.wholePropertyIds.includes(propertyId)||(unitIds.length>0&&unitIds.every(id=>grants.unitIds.includes(id)))}
export async function canCorrectTransaction(actor:Actor,propertyId:string,unitIds:string[],tx:Prisma.TransactionClient|typeof prisma=prisma){if(hasAllPropertyAccess(actor))return true;const [propertyGrant,unitGrants]=await Promise.all([tx.userProperty.findFirst({where:{userId:actor.id,propertyId,permission:{in:["EDIT","ADMIN"]}},select:{propertyId:true}}),unitIds.length?tx.userUnit.findMany({where:{userId:actor.id,unitId:{in:unitIds},permission:{in:["EDIT","ADMIN"]},unit:{propertyId}},select:{unitId:true}}):[]]);return canCorrectTransactionFromGrants(propertyId,unitIds,{wholePropertyIds:propertyGrant?[propertyGrant.propertyId]:[],unitIds:unitGrants.map(row=>row.unitId)})}
async function requireTransactionCorrectionAccess(tx:Prisma.TransactionClient,actor:Actor,transaction:CorrectionTransaction,additionalUnitIds:string[]=[]){const unitIds=[...new Set([...transactionCorrectionUnitIds(transaction),...additionalUnitIds])];if(!await canCorrectTransaction(actor,transaction.bankAccount.propertyId,unitIds,tx))throw new Error("Nemáte oprávnění opravovat přiřazení této platby.")}
const snapshots=(transaction:any):AllocationSnapshot[]=>transaction.allocations.map((row:any)=>({allocationId:row.id,chargeId:row.chargeId,leaseId:row.charge.leaseId,amountCents:row.amountCents}));
export function uniqueAssignmentLeaseId(leaseIds:string[]){const unique=[...new Set(leaseIds)];return unique.length===1?unique[0]:null}
export function manualCancellationError(input:{source:string;status:string;matchNote?:string|null;depositLinked:boolean}){if(input.source!=="manual")return "Stornovat lze pouze ručně evidovanou platbu.";if(input.status===PaymentStatus.IGNORED&&input.matchNote==="Ruční platba stornována správcem.")return "Ruční platba již byla stornována.";if(input.depositLinked)return "Platbu nelze stornovat, protože její část byla zaúčtována jako kauce. Nejprve je nutné opravit evidenci kauce.";return null}

export async function reconcileTransactionAssignmentMetadata(tx:Prisma.TransactionClient,transactionId:string,note="Ruční korekce přiřazení správcem."){const transaction=await tx.bankTransaction.findUnique({where:{id:transactionId},include:{allocations:{include:{charge:{select:{leaseId:true}}}},securityDepositReceipts:{select:{leaseId:true}}}});if(!transaction)throw new Error("Platba nebyla nalezena.");const leaseIds=[...transaction.allocations.map(row=>row.charge.leaseId),...transaction.securityDepositReceipts.map(row=>row.leaseId)];await tx.bankTransaction.update({where:{id:transactionId},data:{suggestedLeaseId:uniqueAssignmentLeaseId(leaseIds),matchedRuleId:null,matchNote:note}});return [...new Set(leaseIds)]}

export async function unallocatePayment(actor:Actor,propertyId:string,transactionId:string,allocationId:string){return serializableTransaction(async tx=>{const transaction=await tx.bankTransaction.findFirst({where:{id:transactionId,bankAccount:{propertyId}},include:correctionInclude});if(!transaction)throw new Error("Platba nebyla nalezena.");if(transaction.status===PaymentStatus.IGNORED)throw new Error("Stornovanou nebo ignorovanou platbu nelze opravovat.");await requireTransactionCorrectionAccess(tx,actor,transaction);const allocation=transaction.allocations.find(row=>row.id===allocationId);if(!allocation)throw new Error("Platba již byla odpárována.");const previous:AllocationSnapshot={allocationId:allocation.id,chargeId:allocation.chargeId,leaseId:allocation.charge.leaseId,amountCents:allocation.amountCents};await tx.paymentAllocation.delete({where:{id:allocation.id}});await reconcileTransactionAssignmentMetadata(tx,transactionId);await recomputeTransactionStatusTx(tx,transactionId);await reconcileCollectionTasksAfterPaymentCorrectionTx(tx,[previous.leaseId]);await tx.auditLog.create({data:{userId:actor.id,propertyId,action:"PAYMENT_UNALLOCATED",entityType:"BankTransaction",entityId:transactionId,details:{transactionId,...previous}}});return previous})}

export async function unallocateAllPayment(actor:Actor,propertyId:string,transactionId:string){return serializableTransaction(async tx=>{const transaction=await tx.bankTransaction.findFirst({where:{id:transactionId,bankAccount:{propertyId}},include:correctionInclude});if(!transaction)throw new Error("Platba nebyla nalezena.");if(transaction.status===PaymentStatus.IGNORED)throw new Error("Stornovanou nebo ignorovanou platbu nelze opravovat.");await requireTransactionCorrectionAccess(tx,actor,transaction);const previousAllocations=snapshots(transaction);if(!previousAllocations.length)throw new Error("Platba již nemá žádná přiřazení nájemného.");await tx.paymentAllocation.deleteMany({where:{transactionId}});await reconcileTransactionAssignmentMetadata(tx,transactionId);await recomputeTransactionStatusTx(tx,transactionId);await reconcileCollectionTasksAfterPaymentCorrectionTx(tx,previousAllocations.map(row=>row.leaseId));await tx.auditLog.create({data:{userId:actor.id,propertyId,action:"PAYMENT_UNALLOCATED_ALL",entityType:"BankTransaction",entityId:transactionId,details:{transactionId,previousAllocations}}});return previousAllocations})}

export async function reassignPayment(actor:Actor,propertyId:string,transactionId:string,targetLeaseId:string){return serializableTransaction(async tx=>{const transaction=await tx.bankTransaction.findFirst({where:{id:transactionId,bankAccount:{propertyId}},include:correctionInclude});if(!transaction)throw new Error("Platba nebyla nalezena.");await requireTransactionCorrectionAccess(tx,actor,transaction);if(transaction.status===PaymentStatus.IGNORED)throw new Error("Stornovanou nebo ignorovanou platbu nelze přepárovat.");if(transaction.securityDepositReceipts.length)throw new Error("Část platby je zaúčtována jako kauce. Lze opravit jednotlivé alokace nájemného, ale celou platbu nelze přepárovat.");const target=await tx.lease.findFirst({where:{id:targetLeaseId,unit:{propertyId}},select:{id:true,unitId:true}});if(!target)throw new Error("Cílový nájemní vztah nepatří do této nemovitosti.");await requireTransactionCorrectionAccess(tx,actor,transaction,[target.unitId]);const previousAllocations=snapshots(transaction);await tx.paymentAllocation.deleteMany({where:{transactionId}});const allocated=await allocateAvailableTransactionToLeaseTx(tx,transactionId,targetLeaseId);if(!allocated)throw new Error("Platbu se nepodařilo přepárovat.");await tx.bankTransaction.update({where:{id:transactionId},data:{suggestedLeaseId:targetLeaseId,matchedRuleId:null,matchNote:"Ručně přepárováno správcem."}});await recomputeTransactionStatusTx(tx,transactionId);await reconcileCollectionTasksAfterPaymentCorrectionTx(tx,[...previousAllocations.map(row=>row.leaseId),targetLeaseId]);await tx.auditLog.create({data:{userId:actor.id,propertyId,action:"PAYMENT_REASSIGNED",entityType:"BankTransaction",entityId:transactionId,details:{transactionId,previousAllocations,targetLeaseId,newAllocations:allocated.allocations,remainingCents:allocated.remainingCents}}});return {previousAllocations,...allocated}})}

export async function cancelManualPayment(actor:Actor,propertyId:string,transactionId:string){return serializableTransaction(async tx=>{const transaction=await tx.bankTransaction.findFirst({where:{id:transactionId,bankAccount:{propertyId}},include:correctionInclude});if(!transaction)throw new Error("Platba nebyla nalezena.");await requireTransactionCorrectionAccess(tx,actor,transaction);const blocked=manualCancellationError({source:transaction.source,status:transaction.status,matchNote:transaction.matchNote,depositLinked:transaction.securityDepositReceipts.length>0});if(blocked)throw new Error(blocked);const previousAllocations=snapshots(transaction),previousSuggestedLeaseId=transaction.suggestedLeaseId;await tx.paymentAllocation.deleteMany({where:{transactionId}});await tx.bankTransaction.update({where:{id:transactionId},data:{suggestedLeaseId:null,matchedRuleId:null,status:PaymentStatus.IGNORED,matchNote:"Ruční platba stornována správcem."}});await reconcileCollectionTasksAfterPaymentCorrectionTx(tx,previousAllocations.map(row=>row.leaseId));await tx.auditLog.create({data:{userId:actor.id,propertyId,action:"MANUAL_PAYMENT_CANCELLED",entityType:"BankTransaction",entityId:transactionId,details:{transactionId,amountCents:transaction.amountCents,bookedAt:transaction.bookedAt.toISOString(),counterpartyName:transaction.counterpartyName,variableSymbol:transaction.variableSymbol,message:transaction.message,previousSuggestedLeaseId,previousAllocations}}});return {previousAllocations}})}
