"use client";
import { useState } from "react";
import type { contractPrefill } from "@/lib/lease-contracts/service";
import type { buildContract } from "@/lib/lease-contracts/core";
import { unlistedContractTenants } from "@/lib/lease-contracts/occupancy";
import "./contract-builder.css";

type Draft=ReturnType<typeof contractPrefill>["initial"];
type Preview=ReturnType<typeof buildContract>;
const emptyTenant={name:"",birthDate:"",address:"",deliveryAddress:"",email:"",phone:""};
const emptyOccupant={name:"",birthDate:"",role:"Člen domácnosti"};
export function ContractBuilder({leaseId,initial,version,landlordSource}:{leaseId:string;initial:Draft;version:string;landlordSource:string}) {
  const [draft,setDraft]=useState(initial),[preview,setPreview]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[issues,setIssues]=useState<Array<{path:string;message:string}>>([]),[saved,setSaved]=useState<{downloadUrl:string;returnUrl:string;documentId:string}|null>(null);
  function update(path:string,value:string|number|boolean|null){setDraft(previous=>{const next=structuredClone(previous);let target:Record<string,unknown>=next as unknown as Record<string,unknown>;const parts=path.split(".");for(const part of parts.slice(0,-1))target=target[part] as Record<string,unknown>;target[parts.at(-1)!]=value;return next;});setPreview(null);setSaved(null);setIssues([]);setError("");}
  function value(path:string):unknown {let result:unknown=draft;for(const part of path.split("."))result=(result as Record<string,unknown>)[part];return result;}
  function optional(path:string){return /^(manager\.|landlord\.(email|phone)$|tenants\.\d+\.(email|phone)$|occupants\.\d+\.(birthDate|role)$)/.test(path);}
  function fieldLabel(label:string,isOptional=false){return <span className="contract-field-label">{label.replace(/ \(nepovinný\)$/u,"")}<span className={isOptional?"contract-optional":"contract-required"}>{isOptional?"nepovinné":<><span aria-hidden="true">*</span><span className="sr-only">povinné</span></>}</span></span>;}
  function field(label:string,path:string,type="text",hint?:string){const problem=issues.find(i=>i.path===path),isOptional=optional(path),v=value(path),missing=!isOptional&&(v===null||v===undefined||String(v).trim()===""),id=`contract-${path.replaceAll(".","-")}`,description=[hint?`${id}-hint`:null,problem||missing?`${id}-feedback`:null].filter(Boolean).join(" ")||undefined;return <label className="contract-field" data-incomplete={missing||undefined}>{fieldLabel(label,isOptional)}<input id={id} aria-label={label} type={type} value={String(v??"")} required={!isOptional} aria-required={!isOptional} aria-invalid={Boolean(problem)} aria-describedby={description} onChange={e=>update(path,type==="number"?(e.target.value===""?null:Number(e.target.value)):e.target.value)} step={type==="number"?"any":undefined}/>{hint&&<small id={`${id}-hint`}>{hint}</small>}{(problem||missing)&&<small id={`${id}-feedback`} className={problem?"contract-error":"contract-missing"}>{problem?.message||"Doplňte povinný údaj."}</small>}</label>;}
  function amount(label:string,path:string,scale=100){const v=value(path),problem=issues.find(i=>i.path===path),missing=v===null||v===undefined,id=`contract-${path.replaceAll(".","-")}`;return <label className="contract-field" data-incomplete={missing||undefined}>{fieldLabel(label)}<input id={id} aria-label={label} type="number" min="0" step="0.01" value={missing?"":Number(v)/scale} required aria-required="true" aria-invalid={Boolean(problem)} aria-describedby={problem||missing?`${id}-feedback`:undefined} onChange={e=>update(path,e.target.value===""?null:Math.round(Number(e.target.value)*scale))}/>{(problem||missing)&&<small id={`${id}-feedback`} className={problem?"contract-error":"contract-missing"}>{problem?.message||"Doplňte povinný údaj."}</small>}</label>;}
  async function request(mode:"preview"|"pdf"|"save"){
    setBusy(true);setError("");setIssues([]);
    try {
      const response=await fetch(`/api/leases/${leaseId}/contract`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({input:draft,mode,version})});
      if(!response.ok){const data=await response.json();setError(data.error);setIssues(data.issues||[]);return;}
      if(mode==="preview")setPreview((await response.json()).contract);
      else if(mode==="save")setSaved(await response.json());
      else{const blob=await response.blob(),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download="flatberry-najemni-smlouva-nahled.pdf";anchor.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
    }catch{setError("Spojení se nepodařilo. Údaje zůstávají ve formuláři; zkuste to znovu.");}finally{setBusy(false);}
  }
  const serviceTotal=draft.services.reduce((sum,s)=>sum+s.amountCents,0),currency=(n:number)=>(n/100).toLocaleString("cs-CZ",{style:"currency",currency:"CZK"});
  const unlistedTenants=unlistedContractTenants(draft.tenants,draft.occupants);
  return <div className="contract-builder">
    <div className="contract-intro card"><h2>Od údajů ke smlouvě</h2><p>Údaje z evidence jsou předvyplněné. Doplňte chybějící informace, projděte celý náhled a potom vytvořte PDF k podpisu. Vydání vytvoří nový soukromý dokument u této jednotky a smlouvy.</p><p className="contract-field-legend"><strong><span aria-hidden="true">* </span>Povinné údaje</strong> jsou označené hvězdičkou. Ostatní pole mají označení „nepovinné“.</p><p className="contract-note">Platby ani nastavení stávajícího nájemního vztahu se vytvořením dokumentu nemění. Vzor {version}.</p></div>
    <fieldset disabled={busy}>
      <section className="card"><h2>1. Varianta smlouvy</h2><div className="contract-grid"><label className="contract-field">{fieldLabel("Doba nájmu")}<select required aria-required="true" aria-label="Doba nájmu" value={draft.term} onChange={e=>{update("term",e.target.value);if(e.target.value==="INDEFINITE")update("endDate","");}}><option value="SHORT_FIXED">Doba určitá do jednoho roku · bez indexace</option><option value="LONG_FIXED">Víceletá doba určitá · indexace ČSÚ</option><option value="INDEFINITE">Doba neurčitá · indexace ČSÚ</option></select></label><label className="contract-field">{fieldLabel("Nájemci")}<select required aria-required="true" aria-label="Nájemci" value={draft.tenancy} onChange={e=>update("tenancy",e.target.value)}><option value="SINGLE">Jeden nájemce</option><option value="JOINT">Více společných nájemců</option><option value="SPOUSES">Manželé</option></select></label></div><p className="contract-note">U neurčité a víceleté varianty se použije odsouhlasená doložka ČSÚ: kladná průměrná roční inflace, k 1. dubnu nejdříve po 12 měsících a s oznámením 30 dnů předem.</p></section>
      <section className="card"><h2>2. Pronajímatel a zastoupení</h2><p>Pronajímatelem je skutečná smluvní strana. Majitel bankovního účtu ji neurčuje. Známé údaje přebíráme z evidence.</p><p className="contract-note">{landlordSource}</p><div className="contract-grid"><label className="contract-field">{fieldLabel("Typ pronajímatele")}<select required aria-required="true" aria-label="Typ pronajímatele" value={draft.landlord.type} onChange={e=>update("landlord.type",e.target.value)}><option value="PERSON">Fyzická osoba</option><option value="COMPANY">Společnost</option></select></label>{field("Jméno / název","landlord.name")}{field(draft.landlord.type==="PERSON"?"Datum narození":"IČO","landlord.identifier",draft.landlord.type==="PERSON"?"date":"text")}{field("Bydliště / sídlo","landlord.address")}{field("E-mail (nepovinný)","landlord.email","email")}{field("Telefon (nepovinný)","landlord.phone")}{draft.landlord.type==="COMPANY"&&field("Zápis v rejstříku a způsob jednání","landlord.registry")}{field("Podepisující osoba","landlord.signer")}{field("Oprávnění podepisujícího","landlord.authority","text","Např. osobně, jednatel jednající samostatně, plná moc ze dne…")}</div><label className="contract-check"><input type="checkbox" checked={draft.landlord.represented} onChange={e=>update("landlord.represented",e.target.checked)}/>Pronajímatel je zastoupen na základě doloženého oprávnění.</label><p className="contract-note">Obrázek podpisu pro doklady o zaplacení se na nájemní smlouvu nepřenáší. Tuto smlouvu podepíší její smluvní strany.</p></section>
      <section className="card"><h2>3. Smluvní nájemci</h2><p>Uveďte jen osoby uzavírající smlouvu. Další členové domácnosti se nezakládají jako nájemci.</p>{draft.tenants.map((t,i)=><div className="contract-person" key={i}><div className="card-head"><h3>Nájemce {i+1}</h3>{draft.tenants.length>1&&<button type="button" className="secondary" onClick={()=>updateArray("tenants",draft.tenants.filter((_,j)=>i!==j))}>Odebrat osobu</button>}</div><div className="contract-grid">{field("Jméno a příjmení",`tenants.${i}.name`)}{field("Datum narození",`tenants.${i}.birthDate`,"date")}{field("Bydliště",`tenants.${i}.address`)}{field("Doručovací adresa",`tenants.${i}.deliveryAddress`)}{field("E-mail (nepovinný)",`tenants.${i}.email`,"email")}{field("Telefon (nepovinný)",`tenants.${i}.phone`)}</div></div>)}{draft.tenants.length<8&&<button type="button" className="secondary" onClick={()=>{updateArray("tenants",[...draft.tenants,{...emptyTenant}]);update("tenancy",draft.tenancy==="SPOUSES"?"SPOUSES":"JOINT");}}>Přidat smluvního nájemce</button>}</section>
      <section className="card"><h2>4. Byt a termíny</h2><div className="contract-grid">{field("Adresa bytu","unit.address")}{field("Označení bytu","unit.label")}{field("Podlaží a umístění","unit.floor")}{field("Dispozice","unit.disposition")}{field("Plocha v m²","unit.areaM2","number")}{field("Katastrální identifikace","unit.cadastral","text","Jednotka nebo budova, parcela, katastrální území a LV.")}{field("Příslušenství a rozsah užívání","unit.accessories")}{field("Začátek nájmu","startDate","date")}{draft.term!=="INDEFINITE"&&field("Konec nájmu včetně","endDate","date")}{field("Datum předání","handoverDate","date")}{field("Datum podpisu","signingDate","date")}{field("Místo podpisu","signingPlace")}</div></section>
      <section className="card"><h2>5. Platby, služby a jistota</h2><div className="contract-grid">{amount("Čisté měsíční nájemné v Kč","rentCents")}{field("Den splatnosti v daném měsíci (5–28)","dueDay","number")}{field("Účet / IBAN","account")}{field("Variabilní symbol","variableSymbol")}{field("Splatnost první platby","firstPaymentDate","date")}{amount("Jistota v Kč","depositCents")}{draft.depositCents>0&&field("Splatnost jistoty","depositDueDate","date")}{amount("Individuální úrok jistoty v % ročně","depositAnnualRateBps")}</div><h3>Měsíční zálohy na skutečně zajišťované služby</h3>{draft.services.map((s,i)=><div className="contract-service" key={i}>{field("Služba",`services.${i}.name`)}{amount("Záloha v Kč",`services.${i}.amountCents`)}<button type="button" className="secondary" onClick={()=>updateArray("services",draft.services.filter((_,j)=>i!==j))}>Odebrat službu</button></div>)}{draft.services.length<30&&<button className="secondary" type="button" onClick={()=>updateArray("services",[...draft.services,{name:"",amountCents:0}])}>Přidat službu</button>}<div className="contract-total"><span>Služby {currency(serviceTotal)}</span><strong>Celkem měsíčně {currency(draft.rentCents+serviceTotal)}</strong></div><div className="contract-grid">{field("Energie sjednané přímo nájemcem","directEnergy","text","Např. elektřina a plyn, nebo Žádné.")}</div><p className="contract-note">Sazba úročení je údaj této smlouvy. Chybějící individuální sazbu doplňte; zákonné minimum zůstává zachováno i při sjednané nulové sazbě.</p></section>
      <section className="card"><h2>6. Osoby v bytě</h2>
        <p>Jmenný seznam uvedeme na titulním listu smlouvy. Předvyplněné osoby vycházejí z aktuální evidence domácnosti; ověřte, kdo bude v bytě bydlet ke dni zahájení nájmu. Smluvní nájemce přidejte do seznamu, pokud v bytě bude také bydlet.</p>
        <div className="contract-grid">{field("Počet osob při zahájení","occupantCount","number","Počet pro rozúčtování přebíráme z období platného ke dni zahájení nájmu. Není-li období jednoznačně evidované, doplňte počet ručně. Při změně začátku nájmu počet znovu ověřte.")}</div>
        <div className="contract-residents-head"><h3>Jmenný seznam osob</h3><span className="contract-optional">nepovinné doplnění</span></div>
        {draft.occupants.length===0&&<p className="contract-note">Jmenný seznam zatím není vyplněný. Samotný počet osob neurčuje jejich jména.</p>}
        {draft.occupants.map((_,i)=><div className="contract-person" key={i}><div className="card-head"><h3>Osoba {i+1}</h3><button type="button" className="secondary" onClick={()=>updateArray("occupants",draft.occupants.filter((_,j)=>i!==j))}>Odebrat ze seznamu</button></div><div className="contract-grid">{field("Jméno osoby",`occupants.${i}.name`)}{field("Datum narození osoby",`occupants.${i}.birthDate`,"date")}{field("Vztah k nájmu",`occupants.${i}.role`,"text","Např. nájemce nebo člen domácnosti.")}</div></div>)}
        <div className="action-row">{draft.occupants.length<50&&<button type="button" className="secondary" onClick={()=>updateArray("occupants",[...draft.occupants,{...emptyOccupant}])}>Přidat osobu do seznamu</button>}<button type="button" className="secondary" disabled={!unlistedTenants.length||draft.occupants.length+unlistedTenants.length>50} onClick={()=>updateArray("occupants",[...draft.occupants,...unlistedTenants.map(tenant=>({name:tenant.name,birthDate:tenant.birthDate,role:"Nájemce"}))])}>Převzít smluvní nájemce do seznamu</button></div>
        <p className="contract-note">Úprava seznamu nemění počet osob pro rozúčtování ani evidenci domácnosti v aplikaci. Datum narození uveďte pouze tehdy, pokud ho znáte.</p>
        {draft.occupantCount!==null&&draft.occupants.length!==draft.occupantCount&&<p className="contract-residents-status" role="status">{draft.occupants.length<draft.occupantCount?`Seznam obsahuje ${draft.occupants.length} z ${draft.occupantCount} osob. V PDF bude označen jako neúplný.`:`Ve jmenném seznamu je více osob (${draft.occupants.length}) než v počtu pro rozúčtování (${draft.occupantCount}). Před vytvořením smlouvy údaje sjednoťte.`}</p>}
      </section>
      <section className="card"><h2>7. Správce a přílohy</h2><div className="contract-grid">{field("Správce (pokud je určen)","manager.name")}{field("E-mail správce","manager.email","email")}{field("Telefon správce","manager.phone")}{field("Skutečně připojené přílohy","attachments","text","Uveďte připojené dokumenty, případně Žádné. Při zastoupení připojte doklad oprávnění.")}</div><label className="contract-check"><input type="checkbox" required aria-required="true" checked={draft.confirmed} onChange={e=>update("confirmed",e.target.checked)}/>Ověřil/a jsem pronajímatele, oprávnění všech podepisujících, údaje bytu, platby, osoby v bytě a skutečně připojené přílohy. *</label></section>
    </fieldset>
    {error&&<div role="alert" className="card contract-error"><strong>{error}</strong>{issues.length>0&&<p>Opravte označená pole. Zkontrolujte také zvolenou dobu nájmu, počet nájemců a potvrzení údajů.</p>}{issues.filter(i=>["term","tenancy","tenants","landlord","occupantCount","occupants","services","confirmed"].includes(i.path)).map((i,n)=><p key={n}>{i.message}</p>)}</div>}
    <div className="contract-actions card"><button className="primary" disabled={busy} onClick={()=>request("preview")}>{busy?"Připravuji…":"Zobrazit celý náhled"}</button><button className="secondary" disabled={busy||!preview} onClick={()=>request("pdf")}>Stáhnout náhled PDF</button><button className="primary" disabled={busy||!preview||Boolean(saved)} onClick={()=>request("save")}>Vytvořit PDF k podpisu a uložit</button><small>Vytvoření neodesílá e-mail a dokument nezpřístupní nájemníkovi. Sdílení nastavíte v dokumentech.</small></div>
    {saved&&<div className="card contract-success" role="status"><h2>Smlouva je připravena k podpisu</h2><p>PDF můžete vytisknout, podepsat fyzicky a naskenovanou podepsanou smlouvu vložit do dokumentů. Nebo ji předat k podpisu v portálu.</p><div className="action-row"><a className="primary" href={saved.downloadUrl}>Stáhnout smlouvu</a><a className="secondary" href={saved.returnUrl}>Nahrát podepsanou smlouvu</a><a className="secondary" href={`/smlouvy/${leaseId}/potvrzeni?documentId=${saved.documentId}`}>Předat k podpisu do portálu</a></div></div>}
    {preview&&<article className="contract-preview card" aria-label="Náhled nájemní smlouvy"><div className="contract-preview-label">Náhled · před podpisem ověřte celý dokument</div><h2>Nájemní smlouva k bytu</h2><p>Smlouva podle § 2235 a násl. občanského zákoníku. Úvodní přehled je nedílnou součástí smlouvy.</p><dl>{preview.cover.map(([label,v],i)=><div key={i}><dt>{label}</dt><dd>{v}</dd></div>)}</dl>{preview.sections.map(s=><section key={s.title}><h3>{s.title}</h3>{s.paragraphs.map((p,i)=><p key={i}>{p}</p>)}</section>)}<p><strong>{preview.signing}</strong></p>{preview.signatures.map((s,i)=><div className="contract-signature" key={i}><strong>{s.role}: {s.name}</strong><p>{s.detail}</p><p>Podpis: __________________________</p></div>)}</article>}
  </div>;
  function updateArray<K extends "tenants"|"services"|"occupants">(key:K,v:Draft[K]){setDraft(p=>({...p,[key]:v}));setPreview(null);setSaved(null);setError("");setIssues([]);}
}
