import Link from "next/link";
import Image from "next/image";
import {notFound,redirect} from "next/navigation";
import {CreditCard, Droplets, FileText, House, Phone, Wrench} from "lucide-react";
import {actualUser} from "@/lib/auth";
import {prisma} from "@/lib/db";
import {leaseStatusAt} from "@/lib/lease-lifecycle-core";
import {outstandingCents} from "@/lib/charges";
import {money,date,phone} from "@/lib/format";
import {RentPaymentQr} from "@/components/RentPaymentQr";
import {EntityAvatar} from "@/components/EntityAvatar";
import {defaultPropertyIllustration} from "@/lib/illustration-library";
import {domesticAccountLabel,formatIban} from "@/lib/owner-bank-account";
import {Flash} from "@/components/FormUi";
import {businessTodayKey} from "@/lib/calendar";
import {hasTenantPortalAccess} from "@/lib/tenant-portal-access";
import {taskStatuses} from "@/lib/labels";

export const dynamic="force-dynamic";
export default async function TenantPortal({params,searchParams}:{params:Promise<{tenantId:string}>;searchParams:Promise<{ok?:string;error?:string}>}) {
 const actor=await actualUser();const {tenantId}=await params;
 if(!actor)redirect(`/login?portal=${encodeURIComponent(tenantId)}`);
 if(actor.role!=="SUPER_ADMIN"&&!await hasTenantPortalAccess(actor.id,actor.email,tenantId))notFound();
 const tenant=await prisma.tenant.findUnique({where:{id:tenantId}});if(!tenant)notFound();
 const leaseRows=await prisma.lease.findMany({where:{OR:[{tenantId},{parties:{some:{tenantId,role:{in:["CONTRACTING_PARTY","PAYER"]}}}}]},include:{unit:{include:{property:{include:{manager:true}},meters:{where:{active:true},include:{readings:{orderBy:{readAt:"desc"},take:1}}}}},ownerBankAccount:true,charges:{where:{active:true},include:{allocations:true,securityDepositOffsets:true,creditApplications:true},orderBy:{dueDate:"asc"}},documents:{where:{tenantVisible:true,deletedAt:null}},parties:{where:{tenantId},select:{role:true}},tasks:{where:{tenantId,tenantPortalRequest:true},orderBy:{createdAt:"desc"},take:10,select:{id:true,title:true,status:true,createdAt:true,tenantEntryConsentAt:true}}}});
 const leases=leaseRows.filter(row=>leaseStatusAt(row)==="ACTIVE");const preview=actor.role==="SUPER_ADMIN";
 const first=leases[0],firstCanAct=first&&(first.tenantId===tenantId||first.parties.some(p=>p.role==="CONTRACTING_PARTY"));
 return <div className="tenant-portal basic-shell"><header className="tenant-portal-top"><Link href={preview?"/portfolio":"/portal/najemnik"} className="tenant-portal-logo">●● Flat<span>berry</span></Link><span>{preview?`Náhled portálu · ${tenant.name}`:`Můj domov · ${tenant.name}`}</span>{preview?<Link href={`/najemnici/${tenant.id}`}>Zpět na kartu nájemníka</Link>:<form action="/api/auth/logout" method="post"><button type="submit" className="secondary">Odhlásit se</button></form>}</header><div className="tenant-portal-body"><nav className="tenant-portal-nav" aria-label="Portál nájemníka"><a href="#domov">⌂ Můj domov</a>{first&&<a href={`#historie-${first.id}`}>▣ Platby</a>}{firstCanAct&&<><a href={`#zavady-${first.id}`}>⚒ Požadavky</a><a href={`#odecty-${first.id}`}>◉ Odečty</a><a href={`#dokumenty-${first.id}`}>▤ Dokumenty</a></>}{first&&<a href={`#kontakt-${first.id}`}>☏ Kontakt</a>}</nav><main className="page" id="domov"><Flash {...await searchParams}/>
 <section className="tenant-portal-hero"><div><span className="eyebrow">FlatBerry · můj domov</span><h1>Dobrý den, {tenant.name}</h1><p>Vše důležité k vašemu bydlení na jednom místě.</p>{preview&&<small>Náhled správce: odesílání akcí je vypnuté.</small>}</div><div className="tenant-portal-berry"><span>Potřebujete něco vyřešit? Začněte tady.</span><Image src="/guide/welcome.webp" width={180} height={180} alt="Berry vás vítá"/></div></section>
 {!leases.length&&<section className="card">Tento nájemník nemá aktuální nájemní smlouvu.</section>}
 {leases.map(lease=>{const canAct=lease.tenantId===tenantId||lease.parties.some(p=>p.role==="CONTRACTING_PARTY");const manager=lease.unit.property.manager;const charge=lease.charges.find(c=>outstandingCents(c)>0&&c.debtTreatment==="CURRENT");const lastRequest=lease.tasks[0];const lastMeter=lease.unit.meters.map(m=>m.readings[0]?.readAt).filter((v):v is Date=>Boolean(v)).sort((a,b)=>b.getTime()-a.getTime())[0];return <section key={lease.id} className="portal-lease">
 <div className="tenant-portal-location"><House size={23}/><div><strong>Můj domov</strong><span>{lease.unit.property.name} · {lease.unit.label}</span></div></div>
 <div className="tenant-portal-priority"><section className="tenant-portal-payment"><span className="tenant-portal-tile-icon green"><CreditCard/></span><h2>Platby</h2>{charge?<><strong className="portal-amount">{money(outstandingCents(charge))}</strong><p>Aktuální předpis · splatnost {date(charge.dueDate)}</p><a className="primary" href={`#platba-${lease.id}`}>Zaplatit nájem →</a></>:<><strong className="tenant-portal-paid">Aktuálně bez dluhu</strong><p>Zaplatit nájem půjde po vystavení dalšího předpisu.</p><a className="secondary" href={`#historie-${lease.id}`}>Zobrazit platby →</a></>}</section><section className="tenant-portal-contact" id={`kontakt-${lease.id}`}><span className="tenant-portal-tile-icon blue"><Phone/></span><h2>Kontakt na správce</h2><strong>{manager?.name||"Správce není přiřazen"}</strong>{manager?.phone?<a className="tenant-portal-call" href={`tel:${manager.phone}`}>{phone(manager.phone)}</a>:<p>Telefon není vyplněn.</p>}{manager?.email&&<a href={`mailto:${manager.email}`}>Napsat správci →</a>}</section></div>
 <h2 className="tenant-portal-section-title">Co potřebujete vyřídit?</h2><div className="tenant-portal-actions">{canAct&&<a href={`#zavady-${lease.id}`} className="tenant-portal-action"><span className="tenant-portal-tile-icon blue"><Wrench/></span><strong>Nahlásit závadu</strong><p>Popis a fotografie</p><b>Přejít k hlášení →</b></a>}{canAct&&<a href={`#odecty-${lease.id}`} className="tenant-portal-action"><span className="tenant-portal-tile-icon amber"><Droplets/></span><strong>Odečty měřidel</strong><p>{lastMeter?`Poslední odečet ${date(lastMeter)}`:"Čeká první odečet"}</p><b>Zapsat stav →</b></a>}{canAct&&<a href={`#dokumenty-${lease.id}`} className="tenant-portal-action"><span className="tenant-portal-tile-icon violet"><FileText/></span><strong>Dokumenty</strong><p>Smlouvy a doklady</p><b>Zobrazit dokumenty →</b></a>}</div>
 <div className="tenant-portal-lower"><section className="tenant-portal-home"><h2>Můj domov</h2><div className="tenant-portal-home-image"><EntityAvatar kind="unit" size="lg" identity={lease.unitId} photoId={defaultPropertyIllustration("unit",lease.unit.propertyId)}/></div><p>{lease.unit.property.name} · {lease.unit.label}</p></section><section className="tenant-portal-requests"><h2>Moje požadavky</h2>{canAct?lastRequest?<p><strong>{lastRequest.title}</strong><span>{taskStatuses[lastRequest.status]} · {date(lastRequest.createdAt)}</span></p>:<p>Zatím nemáte žádné hlášení.</p>:<p>Požadavky vyřizuje smluvní strana.</p>}<a href={`#zavady-${lease.id}`}>Zobrazit podrobnosti →</a></section></div>
 {charge&&<section className="card tenant-portal-detail" id={`platba-${lease.id}`}><h2>Zaplatit nájem</h2><p>{charge.period} · zbývá {money(outstandingCents(charge))}</p><RentPaymentQr account={lease.ownerBankAccount} amountCents={outstandingCents(charge)} currency={lease.currency} variableSymbol={lease.variableSymbol}/><p>{lease.ownerBankAccount&&(domesticAccountLabel(lease.ownerBankAccount.accountNumber,lease.ownerBankAccount.bankCode)||formatIban(lease.ownerBankAccount.iban))||"Účet pro platbu není potvrzen."} · VS: {lease.variableSymbol}</p></section>}
 {canAct&&<section className="card tenant-portal-detail" id={`zavady-${lease.id}`}><h2>Nahlásit závadu</h2>{preview?<p>Náhled: odesílání je vypnuté.</p>:<form action={`/api/portal/tenants/${tenantId}/defects`} method="post" encType="multipart/form-data" className="account-form"><input type="hidden" name="leaseId" value={lease.id}/><label className="field"><span>Co se stalo?</span><input name="title" minLength={5} maxLength={140} required/></label><label className="field"><span>Popis závady</span><textarea name="description" minLength={10} maxLength={5000} required/></label><label className="field"><span>Fotografie (max. 3)</span><input type="file" name="files" accept="image/jpeg,image/png,image/webp" multiple/></label><label className="field"><span>Možný termín a pokyny pro návštěvu</span><input name="tenantVisitNote" maxLength={500}/></label><label><input type="checkbox" name="tenantEntryConsent" value="yes"/> Souhlasím se vstupem správce nebo pověřeného technika po předchozí domluvě. Souhlas mohu odvolat.</label><button className="primary" type="submit">Předat závadu</button></form>}<h3>Moje hlášení</h3><div className="tenant-portal-request-history">{lease.tasks.map(t=><div key={t.id}><strong>{t.title}</strong><span>{taskStatuses[t.status]} · {date(t.createdAt)}</span>{t.tenantEntryConsentAt&&!preview&&<form action={`/api/portal/tenants/${tenantId}/defects/${t.id}/entry-consent`} method="post"><button className="secondary" type="submit">Odvolat souhlas se vstupem</button></form>}</div>)}</div></section>}
 {canAct&&<section className="card tenant-portal-detail" id={`odecty-${lease.id}`}><h2>Odečty měřidel</h2>{lease.unit.meters.map(m=><div key={m.id} className="tenant-portal-meter"><strong>{m.label||m.type}</strong><span>{m.readings[0]?`${m.readings[0].value} ${m.unitOfMeasure} · ${date(m.readings[0].readAt)}`:"Čeká první odečet"}</span>{!preview&&<form action={`/api/portal/tenants/${tenantId}/readings`} method="post" className="compact-form"><input type="hidden" name="leaseId" value={lease.id}/><input type="hidden" name="meterId" value={m.id}/><label className="field"><span>Datum odečtu</span><input name="readAt" type="date" defaultValue={businessTodayKey()} required/></label><label className="field"><span>Nový stav ({m.unitOfMeasure})</span><input name="value" type="number" min="0" step="any" required/></label><button className="primary" type="submit">Uložit odečet</button></form>}</div>)}{!lease.unit.meters.length&&<p>Zatím bez měřidel.</p>}</section>}
 {canAct&&<section className="card tenant-portal-detail" id={`dokumenty-${lease.id}`}><h2>Dokumenty</h2>{lease.documents.map(doc=><p key={doc.id}>{preview?doc.title:<a href={`/api/portal/tenants/${tenantId}/documents/${doc.id}`}>{doc.title}</a>}</p>)}{!lease.documents.length&&<p>Zatím bez dokumentů zveřejněných správou.</p>}</section>}
 <section className="card tenant-portal-detail" id={`historie-${lease.id}`}><h2>Moje platby</h2><p className="muted-copy">Zobrazeny jsou zaúčtované úhrady a zápočty. Právě odeslaná platba se může objevit později.</p>{lease.charges.slice(-6).map(c=>{const bank=c.allocations.reduce((sum,a)=>sum+a.amountCents,0),offset=c.securityDepositOffsets.reduce((sum,a)=>sum+a.amountCents,0)+c.creditApplications.reduce((sum,a)=>sum+a.amountCents,0),remaining=outstandingCents(c);return <p key={c.id}><strong>{c.period}</strong> · předpis {money(c.amountCents)} · bankou přiřazeno {money(bank)}{offset>0?` · započteno ${money(offset)}`:""} · {remaining>0?`zbývá ${money(remaining)}`:bank>0?"vypořádáno":"vypořádáno zápočtem"}</p>})}</section>
 </section>})}</main></div></div>;
}
