import {TenantPortalNav} from "@/components/TenantPortalNav";
import {UserAvatar} from "@/components/UserAvatar";
import {greeting} from "@/lib/greeting";
import {periodLabel,currentPeriod} from "@/lib/period";
import {isPastDue} from "@/lib/charges";
import {receiptEligible,receiptIssuerForLease} from "@/lib/tenant-payment-receipts";
import Link from "next/link";
import Image from "next/image";
import {notFound,redirect} from "next/navigation";
import {CreditCard, Droplets, FileText, House, Phone, Wrench} from "lucide-react";
import {actualUser} from "@/lib/auth";
import {prisma} from "@/lib/db";
import {leaseStatusAt} from "@/lib/lease-lifecycle-core";
import {outstandingCents} from "@/lib/charges";
import {money,date,phone} from "@/lib/format";
import {RentPaymentQr} from "@/components/RentPaymentQr";
import {EntityAvatar} from "@/components/EntityAvatar";
import {defaultPropertyIllustration} from "@/lib/illustration-library";
import {domesticAccountLabel,formatIban} from "@/lib/owner-bank-account";
import {Flash} from "@/components/FormUi";
import {businessTodayKey} from "@/lib/calendar";
import {hasTenantPortalAccess,manageableTenantLeaseIds} from "@/lib/tenant-portal-access";
import {taskStatuses} from "@/lib/labels";

export const dynamic="force-dynamic";
export default async function TenantPortal({params,searchParams}:{params:Promise<{tenantId:string}>;searchParams:Promise<{ok?:string;error?:string}>}) {
 const actor=await actualUser();const {tenantId}=await params;
 if(!actor)redirect(`/login?portal=${encodeURIComponent(tenantId)}`);
 const tenantAccess=await hasTenantPortalAccess(actor.id,actor.email,tenantId);
 const manageableIds=tenantAccess?[]:await manageableTenantLeaseIds(actor,tenantId);
 if(!tenantAccess&&!manageableIds.length)notFound();
 const preview=!tenantAccess;
 const tenant=await prisma.tenant.findUnique({where:{id:tenantId}});if(!tenant)notFound();
 const leaseRows=await prisma.lease.findMany({where:{...(!tenantAccess?{id:{in:manageableIds}}:{}),OR:[{tenantId},{parties:{some:{tenantId,role:{in:["CONTRACTING_PARTY","PAYER"]}}}}]},include:{unit:{include:{property:{include:{manager:{select:{id:true,name:true,phone:true,email:true,avatarMimeType:true,avatarChoice:true,updatedAt:true}}}},meters:{where:{active:true},include:{readings:{orderBy:{readAt:"desc"},take:1}}}}},ownerBankAccount:{include:{owner:{select:{name:true}}}},charges:{where:{active:true},include:{allocations:{include:{transaction:{select:{bookedAt:true,amountCents:true,currency:true,status:true}}}},securityDepositOffsets:true,creditApplications:true,paymentReceipts:{select:{id:true,issuedAt:true},orderBy:{issuedAt:"desc"}}},orderBy:{dueDate:"asc"}},documents:{where:{tenantVisible:true,deletedAt:null}},parties:{where:{tenantId},select:{role:true}},tasks:{where:{tenantId,tenantPortalRequest:true},orderBy:{createdAt:"desc"},take:10,select:{id:true,title:true,status:true,createdAt:true,tenantEntryConsentAt:true}}}});
 const leases=leaseRows.filter(row=>leaseStatusAt(row)==="ACTIVE");
 const issuers=new Map(await Promise.all(leases.map(async lease=>[lease.id,Boolean(await receiptIssuerForLease(lease.id))] as const)));
 const first=leases[0],firstCanAct=first&&(first.tenantId===tenantId||first.parties.some(p=>p.role==="CONTRACTING_PARTY"));
 return <div className="tenant-portal basic-shell"><header className="tenant-portal-top"><Link href={preview?"/portfolio":"/portal/najemnik"} className="tenant-portal-logo">●● Flat<span>berry</span></Link><span>{preview?`Náhled portálu · ${tenant.name}`:`Můj domov · ${tenant.name}`}</span>{preview?<Link href={`/najemnici/${tenant.id}`}>Zpět na kartu nájemníka</Link>:<form action="/api/auth/logout" method="post"><button type="submit" className="secondary">Odhlásit se</button></form>}</header><div className="tenant-portal-body"><TenantPortalNav leaseId={first?.id} canAct={Boolean(firstCanAct)}/><main className="page" id="domov"><Flash {...await searchParams}/>
 <section className="tenant-portal-hero"><div><span className="eyebrow">FlatBerry · můj domov</span><h1>{greeting(tenant.name,tenant.type==="PERSON")}</h1><p>Vše důležité k vašemu bydlení na jednom místě.</p>{preview&&<small>Náhled správce: odesílání akcí je vypnuté.</small>}</div><div className="tenant-portal-berry"><span>Potřebujete něco vyřešit? Začněte tady.</span><Image src="/guide/welcome.webp" width={180} height={180} alt="Berry vás vítá"/></div></section>
 {!leases.length&&<section className="card">Tento nájemník nemá aktuální nájemní smlouvu.</section>}
 {leases.map(lease=>{const canAct=lease.tenantId===tenantId||lease.parties.some(p=>p.role==="CONTRACTING_PARTY");const manager=lease.unit.property.manager;const unpaid=lease.charges.filter(c=>outstandingCents(c)>0&&c.debtTreatment==="CURRENT");const charge=unpaid.find(c=>isPastDue(c.dueDate))||unpaid.find(c=>c.period===currentPeriod())||unpaid[0];const paidRents=lease.charges.filter(c=>receiptEligible(c,lease.currency));const lastRequest=lease.tasks[0];const lastMeter=lease.unit.meters.map(m=>m.readings[0]?.readAt).filter((v):v is Date=>Boolean(v)).sort((a,b)=>b.getTime()-a.getTime())[0];return <section key={lease.id} className="portal-lease">
 <div className="tenant-portal-location"><House size={23}/><div><strong>Můj domov</strong><span>{lease.unit.property.name} · {lease.unit.label}</span></div></div>
 <div className="tenant-portal-priority"><section className="tenant-portal-payment"><span className="tenant-portal-tile-icon green"><CreditCard/></span><h2>Zaplatit nájem</h2>{charge?<><strong className="portal-amount">{money(outstandingCents(charge))}</strong><p><strong>{rentPeriod(charge.period)}</strong><br/>{isPastDue(charge.dueDate)?"Po splatnosti":"Splatnost"} {date(charge.dueDate)}</p><a className="primary" href={`#platba-${lease.id}`}>Zaplatit nájem →</a></>:<><strong className="tenant-portal-paid">Aktuálně bez dluhu</strong><p>Zaplatit nájem půjde po vystavení dalšího předpisu.</p><a className="secondary" href={`#historie-${lease.id}`}>Zobrazit platby →</a></>}</section><section className="tenant-portal-contact" id={`kontakt-${lease.id}`}><span className="tenant-portal-tile-icon blue"><Phone/></span><h2>Kontakt na správce</h2><div className="portal-manager-person">{manager&&<UserAvatar user={manager} size="lg" imageUrl={`/api/portal/tenants/${tenantId}/manager-avatar/${manager.id}`}/>}<strong>{manager?.name||"Správce není přiřazen"}</strong></div>{manager?.phone?<a className="tenant-portal-call" href={`tel:${manager.phone}`}>{phone(manager.phone)}</a>:<p>Telefon není vyplněn.</p>}{manager?.email&&<><a className="portal-manager-email" href={`mailto:${manager.email}`}>{manager.email}</a><a className="primary" href={`mailto:${manager.email}`}>Napsat správci →</a></>}{!manager?.email&&<p>E-mail není vyplněn.</p>}</section></div>
 <h2 className="tenant-portal-section-title">Co potřebujete vyřídit?</h2><div className="tenant-portal-actions">{canAct&&<a href={`#zavady-${lease.id}`} className="tenant-portal-action"><span className="tenant-portal-tile-icon blue"><Wrench/></span><strong>Nahlásit závadu</strong><p>Popis a fotografie</p><b>Přejít k hlášení →</b></a>}{canAct&&<a href={`#odecty-${lease.id}`} className="tenant-portal-action"><span className="tenant-portal-tile-icon amber"><Droplets/></span><strong>Odečty měřidel</strong><p>{lastMeter?`Poslední odečet ${date(lastMeter)}`:lease.unit.meters.length?"Čeká první odečet":"Zatím bez měřidel"}</p><b>Zapsat stav →</b></a>}{canAct&&<a href={`#dokumenty-${lease.id}`} className="tenant-portal-action"><span className="tenant-portal-tile-icon violet"><FileText/></span><strong>Dokumenty</strong><p>Smlouvy a doklady</p><b>Zobrazit dokumenty →</b></a>}</div>
 <div className="tenant-portal-lower"><section className="tenant-portal-home"><h2><House size={23} aria-hidden="true"/> Můj domov</h2><div className="tenant-portal-home-image"><EntityAvatar kind="unit" size="lg" identity={lease.unitId} photoId={defaultPropertyIllustration("unit",lease.unit.propertyId)}/></div><p>{lease.unit.property.name} · {lease.unit.label}</p></section><section className="tenant-portal-requests"><h2><Wrench size={23} aria-hidden="true"/> Poslední požadavek</h2>{canAct?lastRequest?<p><strong>{lastRequest.title}</strong><span>{taskStatuses[lastRequest.status]} · {date(lastRequest.createdAt)}</span></p>:<p>Zatím nemáte žádné hlášení.</p>:<p>Požadavky vyřizuje smluvní strana.</p>}</section></div>
 {charge&&<section className="card tenant-portal-detail" id={`platba-${lease.id}`}><h2><CreditCard size={23} aria-hidden="true"/> Platební údaje</h2><p><strong>{rentPeriod(charge.period)}</strong></p><dl className="portal-payment-fields"><div><dt>K úhradě</dt><dd>{money(outstandingCents(charge)).replace("Kč",lease.currency)}</dd></div><div><dt>Datum splatnosti</dt><dd>{date(charge.dueDate)}</dd></div><div><dt>Příjemce platby</dt><dd>{lease.ownerBankAccount?.owner.name||"Příjemce není potvrzen"}</dd></div></dl><RentPaymentQr account={lease.ownerBankAccount} amountCents={outstandingCents(charge)} currency={lease.currency} variableSymbol={lease.variableSymbol}/><p><strong>Účet příjemce: </strong>{lease.ownerBankAccount&&(domesticAccountLabel(lease.ownerBankAccount.accountNumber,lease.ownerBankAccount.bankCode)||formatIban(lease.ownerBankAccount.iban))||"Účet pro platbu není potvrzen."} · <strong>Variabilní symbol: </strong>{lease.variableSymbol||"Není uveden"}</p></section>}
 {canAct&&<section className="card tenant-portal-detail" id={`zavady-${lease.id}`}><h2><Wrench size={23} aria-hidden="true"/> Požadavky</h2>{preview?<p>Náhled: odesílání je vypnuté.</p>:<form action={`/api/portal/tenants/${tenantId}/defects`} method="post" encType="multipart/form-data" className="account-form"><input type="hidden" name="leaseId" value={lease.id}/><label className="field"><span>Co se stalo?</span><input name="title" minLength={5} maxLength={140} required/></label><label className="field"><span>Popis závady</span><textarea name="description" minLength={10} maxLength={5000} required/></label><label className="field"><span>Fotografie (max. 3)</span><input type="file" name="files" accept="image/jpeg,image/png,image/webp" multiple/></label><label className="field"><span>Možný termín a pokyny pro návštěvu</span><input name="tenantVisitNote" maxLength={500}/></label><label><input type="checkbox" name="tenantEntryConsent" value="yes"/> Souhlasím se vstupem správce nebo pověřeného technika po předchozí domluvě. Souhlas mohu odvolat.</label><button className="primary" type="submit">Předat závadu</button></form>}<h3>Moje hlášení</h3><div className="tenant-portal-request-history">{lease.tasks.map(t=><div key={t.id}><strong>{t.title}</strong><span>{taskStatuses[t.status]} · {date(t.createdAt)}</span>{t.tenantEntryConsentAt&&!preview&&<form action={`/api/portal/tenants/${tenantId}/defects/${t.id}/entry-consent`} method="post"><button className="secondary" type="submit">Odvolat souhlas se vstupem</button></form>}</div>)}</div></section>}
 {canAct&&<section className="card tenant-portal-detail" id={`odecty-${lease.id}`}><h2><Droplets size={23} aria-hidden="true"/> Odečty měřidel</h2>{lease.unit.meters.map(m=><div key={m.id} className="tenant-portal-meter"><strong>{m.label||m.type}</strong><span>{m.readings[0]?`${m.readings[0].value} ${m.unitOfMeasure} · ${date(m.readings[0].readAt)}`:"Čeká první odečet"}</span>{!preview&&<form action={`/api/portal/tenants/${tenantId}/readings`} method="post" className="compact-form"><input type="hidden" name="leaseId" value={lease.id}/><input type="hidden" name="meterId" value={m.id}/><label className="field"><span>Datum odečtu</span><input name="readAt" type="date" defaultValue={businessTodayKey()} required/></label><label className="field"><span>Nový stav ({m.unitOfMeasure})</span><input name="value" type="number" min="0" step="any" required/></label><button className="primary" type="submit">Uložit odečet</button></form>}</div>)}{!lease.unit.meters.length&&<p>Zatím bez měřidel.</p>}</section>}
 {canAct&&<section className="card tenant-portal-detail" id={`dokumenty-${lease.id}`}><h2><FileText size={23} aria-hidden="true"/> Dokumenty</h2><div className="portal-receipt-picker"><h3>Doklad o zaplacení nájmu</h3><p>Vyberte nájem plně uhrazený připsanými platbami. Doklad se uloží a stáhne jako PDF.</p>{paidRents.length?<form action={`/api/portal/tenants/${tenantId}/receipts`} method="post" className="compact-form"><label className="field"><span>Zaplacený nájem</span><select name="chargeId" required defaultValue={paidRents.at(-1)?.id}>{paidRents.map(c=><option key={c.id} value={c.id}>{rentPeriod(c.period)} · {money(c.amountCents).replace("Kč",lease.currency)}</option>)}</select></label><button className="primary" disabled={preview||!issuers.get(lease.id)}>Vygenerovat a stáhnout PDF</button></form>:<p>Zatím není evidovaný nájem plně uhrazený připsanou platbou.</p>}{!issuers.get(lease.id)&&<p className="muted-copy">Vystavitel zatím nepovolil vystavování dokladů nebo nemá uložený podpis.</p>}{preview&&<small>Náhled správce je pouze pro čtení. Podpis nastavíte v <Link href="/ucet#podpis">Můj účet → Podpis a doklady</Link>.</small>}</div>
 <div className="portal-document-list">{lease.charges.flatMap(c=>c.paymentReceipts.map(receipt=><p key={receipt.id}><FileText size={20}/>{preview?<span>Doklad · {rentPeriod(c.period)}</span>:<a href={`/api/portal/tenants/${tenantId}/receipts/${receipt.id}`}>Doklad · {rentPeriod(c.period)} · stáhnout PDF</a>}<small>Vystaveno {date(receipt.issuedAt)}</small></p>))}{lease.documents.map(doc=><p key={doc.id}><FileText size={20}/>{preview?<span>{doc.title}</span>:<a href={`/api/portal/tenants/${tenantId}/documents/${doc.id}`}>{doc.title}</a>}</p>)}</div>{!lease.documents.length&&!lease.charges.some(c=>c.paymentReceipts.length)&&<p>Zatím bez uložených dokumentů.</p>}</section>}
 <section className="card tenant-portal-detail" id={`historie-${lease.id}`}><h2><CreditCard size={23} aria-hidden="true"/> Moje platby</h2><p className="muted-copy">Přehled předpisů včetně budoucích období. Právě odeslaná platba se objeví po připsání a přiřazení k nájmu. Zápočty jsou uvedené samostatně.</p><div className="portal-payment-legend"><span className="portal-paid">Uhrazeno</span><span className="portal-scheduled">Před splatností</span><span className="portal-overdue">Po splatnosti</span></div><div className="table-wrap"><table className="portal-payment-history"><thead><tr><th>Období nájmu</th><th>Předpis</th><th>Přijaté úhrady</th><th>K úhradě</th><th>Stav / splatnost</th></tr></thead><tbody>{lease.charges.map(c=>{const bank=c.allocations.reduce((sum,a)=>sum+a.amountCents,0),offset=c.securityDepositOffsets.reduce((sum,a)=>sum+a.amountCents,0)+c.creditApplications.reduce((sum,a)=>sum+a.amountCents,0),remaining=outstandingCents(c),tone=remaining===0?"paid":isPastDue(c.dueDate)&&c.debtTreatment==="CURRENT"?"overdue":"scheduled";return <tr key={c.id} className={`portal-${tone}`}><td><strong>{rentPeriod(c.period)}</strong></td><td>{money(c.amountCents).replace("Kč",lease.currency)}</td><td><strong>{money(bank).replace("Kč",lease.currency)}</strong>{c.allocations.map(a=><small className="owner-sub" key={a.id}>Připsáno {date(a.transaction.bookedAt)} · {money(a.amountCents).replace("Kč",lease.currency)}</small>)}{offset>0&&<small className="owner-sub">Zápočet {money(offset).replace("Kč",lease.currency)}</small>}</td><td>{money(remaining).replace("Kč",lease.currency)}</td><td><span className="portal-payment-state">{remaining===0?offset>0?"Vypořádáno se zápočtem":"Uhrazeno":c.debtTreatment==="HISTORICAL"?"Historická pohledávka":c.debtTreatment==="EXCLUDED"?"Mimo aktuální dluh":tone==="overdue"?bank>0?"Částečně uhrazeno · po splatnosti":"Po splatnosti":bank>0?"Částečně uhrazeno":"Před splatností"}</span><small className="owner-sub">Splatnost {date(c.dueDate)}</small></td></tr>})}{!lease.charges.length&&<tr><td colSpan={5}>Zatím bez předpisů.</td></tr>}</tbody></table></div></section>
 </section>})}</main></div></div>;
}

function rentPeriod(period:string){return /^\d{4}-(0[1-9]|1[0-2])$/.test(period)?`Nájem za ${periodLabel(period)}`:`Předpis · ${period}`;}
