import { PropertyPermission } from "@prisma/client";
import { prisma } from "@/lib/db";
import { currentUser } from "@/lib/auth";
import { invitationToken } from "@/lib/invitations";
import { sendInvitationEmail } from "@/lib/email";
import { propertyPermissions } from "@/lib/labels";
import { redirectUrl } from "@/lib/redirect-url";
import { audit } from "@/lib/management";
import { go, goWithMessage } from "@/lib/route-response";
export async function POST(request:Request){const admin=await currentUser();if(!admin||admin.role!=="SUPER_ADMIN")return go(request,"/login");try{const form=await request.formData();const name=String(form.get("name")||"").trim();const email=String(form.get("email")||"").trim().toLowerCase();const allProperties=form.get("allProperties")==="on";const propertyIds=form.getAll("propertyIds").map(String).filter(Boolean);const rawPermission=String(form.get("permission")||PropertyPermission.VIEW) as PropertyPermission;const permission=Object.values(PropertyPermission).includes(rawPermission)?rawPermission:PropertyPermission.VIEW;if(!name)throw new Error("Zadejte jméno pozvaného člena.");if(!/^\S+@\S+\.\S+$/.test(email))throw new Error("Zadejte platný e-mail.");if(!allProperties&&!propertyIds.length)throw new Error("Vyberte alespoň jednu nemovitost nebo přístup ke všem.");const properties=await prisma.property.findMany({where:{id:{in:propertyIds},active:true},select:{id:true,name:true}});if(properties.length!==propertyIds.length)throw new Error("Některá vybraná nemovitost nebyla nalezena.");const primary=properties[0]||await prisma.property.findFirst({where:{active:true},orderBy:{name:"asc"},select:{id:true,name:true}});if(!primary)throw new Error("Nejprve vytvořte nemovitost.");await prisma.userInvitation.updateMany({where:{email,status:"PENDING"},data:{status:"REVOKED"}});const{token,tokenHash}=invitationToken();const invitation=await prisma.userInvitation.create({data:{email,name,tokenHash,propertyId:primary.id,propertyIds,allProperties,permission,invitedById:admin.id,expiresAt:new Date(Date.now()+7*24*60*60*1000)}});const inviteUrl=redirectUrl(`/pozvanka/${token}`,request).toString();const propertyName=allProperties?"všem nemovitostem FlatCloud":properties.map(p=>p.name).join(", ");const result=await sendInvitationEmail({to:email,inviterName:admin.name,propertyName,permissionLabel:propertyPermissions[permission],inviteUrl});await audit(admin.id,"USER_INVITED","UserInvitation",invitation.id,{propertyIds,allProperties,email,permission,sent:result.sent});const message=result.sent?`Pozvánka byla odeslána na ${email}.`:"Pozvánka byla vytvořena, ale SMTP není nakonfigurováno. Odkaz je zobrazen níže.";return go(request,`/uzivatele?ok=${encodeURIComponent(message)}${result.sent?"":`&invite=${encodeURIComponent(inviteUrl)}`}`)}catch(error){return goWithMessage(request,"/uzivatele","error",error instanceof Error?error.message:"Pozvánku se nepodařilo odeslat.")}}
