import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { requirePropertyAccess } from "@/lib/access";
import { Shell } from "@/components/Shell";
import { Field, Flash, FormCard, FormPage, Select, Textarea } from "@/components/FormUi";
import { dateInput, moneyInput } from "@/lib/forms";
import { leaseStatuses } from "@/lib/labels";

export const dynamic="force-dynamic";
export default async function EditLease({params,searchParams}:{params:Promise<{id:string;leaseId:string}>;searchParams:Promise<{ok?:string;error?:string}>}){const user=await requireUser();const {id,leaseId}=await params;const [property,lease,tenants,query]=await Promise.all([requirePropertyAccess(user,id),prisma.lease.findFirst({where:{id:leaseId,unit:{propertyId:id}},include:{tenant:true,unit:true}}),prisma.tenant.findMany({where:{OR:[{leases:{some:{id:leaseId}}},{active:true,leases:{some:{unit:{propertyId:id}}}}]},orderBy:{name:"asc"}}),searchParams]);if(!property||!lease)notFound();return <Shell user={user}><FormPage title={`Upravit smlouvu: ${lease.unit.label}`} description={lease.tenant.name} backHref={`/nemovitosti/${id}/smlouvy`}><Flash ok={query.ok} error={query.error}/><FormCard action={`/api/properties/${id}/leases/${lease.id}`} cancelHref={`/nemovitosti/${id}/smlouvy`}><Select label="Jednotka" name="unitId" defaultValue={lease.unitId} options={property.units.map(unit=>[unit.id,unit.label])}/><Select label="Nájemník" name="tenantId" defaultValue={lease.tenantId} options={tenants.map(tenant=>[tenant.id,tenant.name])}/><Field label="Číslo smlouvy" name="contractNumber" defaultValue={lease.contractNumber}/><Field label="Platnost od" name="startDate" type="date" defaultValue={dateInput(lease.startDate)} required/><Field label="Platnost do" name="endDate" type="date" defaultValue={dateInput(lease.endDate)}/><Select label="Stav" name="status" defaultValue={lease.status} options={Object.entries(leaseStatuses)}/><Field label="Den splatnosti" name="dueDay" type="number" min={1} max={31} defaultValue={lease.dueDay} required/><Select label="Způsob placení nájemného" name="rentTiming" defaultValue={lease.rentTiming} options={[["ADVANCE","Dopředné"],["ARREARS","Zpětné"]]}/><Field label="Variabilní symbol" name="variableSymbol" defaultValue={lease.variableSymbol} required/><Field label="Nájemné Kč / měsíc" name="rent" type="number" step="0.01" min={0} defaultValue={moneyInput(lease.rentCents).replace(",",".")}/><Field label="Služby Kč / měsíc" name="services" type="number" step="0.01" min={0} defaultValue={moneyInput(lease.servicesCents).replace(",",".")}/><Field label="Kauce Kč" name="deposit" type="number" step="0.01" min={0} defaultValue={moneyInput(lease.depositCents).replace(",",".")}/><Textarea label="Poznámka" name="note" defaultValue={lease.note}/></FormCard></FormPage></Shell>}
