import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { appSettings, syncIntervalHours } from "@/lib/settings";
import { Shell } from "@/components/Shell";
import { Flash } from "@/components/FormUi";

export const dynamic = "force-dynamic";
const options = [1, 2, 3, 4, 6, 8, 12, 24];
const variables = "{{property}}, {{unit}}, {{tenant}}, {{period}}, {{dueDate}}, {{oldestDueDate}}, {{amount}}, {{outstanding}}, {{iban}}, {{variableSymbol}}, {{owner}}";
export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ ok?: string; error?: string }> }) {
  const user = await requireUser(); if (user.role !== "SUPER_ADMIN") redirect("/portfolio");
  const [settings, query] = await Promise.all([appSettings(), searchParams]);
  return <Shell user={user}><div className="page"><div className="page-title"><div><h1>Administrace aplikace</h1><p>Bankovní automatizace, SMTP a komunikace k nájemnému. Dostupné pouze hlavnímu administrátorovi.</p></div></div><Flash ok={query.ok} error={query.error}/>
    <div className="detail-grid"><form className="card col-7 edit-form" action="/api/settings/banking" method="post"><h2>Automatická synchronizace bank</h2><p className="muted-copy">Kontrolní úloha běží jednou za hodinu.</p><div className="form-grid" style={{marginTop:18}}><label className="checkbox-field field-full"><input type="checkbox" name="automaticBankSync" defaultChecked={settings.automaticBankSync}/><span>Automatické stahování plateb je aktivní</span></label><label className="field field-full"><span>Počet synchronizací za den</span><select name="bankSyncsPerDay" defaultValue={settings.bankSyncsPerDay}>{options.map(v=><option value={v} key={v}>{v}× denně {v===24?"(každou hodinu)":`(přibližně každých ${syncIntervalHours(v)} h)`}</option>)}</select></label></div><div className="form-actions"><button className="primary" type="submit">Uložit nastavení bank</button></div></form><div className="card col-5"><h2>Stav bankovního plánovače</h2><div className="summary-list"><div><span>Poslední start</span><strong>{settings.lastCronStartedAt?.toLocaleString("cs-CZ")||"Zatím neběžel"}</strong></div><div><span>Poslední dokončení</span><strong>{settings.lastCronFinishedAt?.toLocaleString("cs-CZ")||"—"}</strong></div><div><span>Výsledek</span><strong>{settings.lastCronSummary||"—"}</strong></div></div></div></div>
    <form className="card edit-form" action="/api/settings/notifications" method="post" style={{marginTop:20}}><div className="card-head"><div><h2>SMTP a automatická komunikace k nájmu</h2><p className="muted-copy">Heslo je uloženo šifrovaně. Prázdné pole hesla zachová současnou hodnotu; pokud databázová konfigurace chybí, pozvánky nadále použijí Render environment variables.</p></div></div>
      <div className="form-grid"><label className="field"><span>SMTP server</span><input name="smtpHost" defaultValue={settings.smtpHost||process.env.SMTP_HOST||""}/></label><label className="field"><span>Port</span><input type="number" name="smtpPort" min={1} max={65535} defaultValue={settings.smtpPort||587}/></label><label className="field"><span>Uživatel</span><input name="smtpUser" defaultValue={settings.smtpUser||process.env.SMTP_USER||""}/></label><label className="field"><span>Heslo</span><input type="password" name="smtpPassword" placeholder={settings.smtpPasswordEncrypted||process.env.SMTP_PASSWORD?"Nastaveno – vyplňte jen při změně":""}/></label><label className="field"><span>Jméno odesílatele</span><input name="smtpFromName" defaultValue={settings.smtpFromName||process.env.SMTP_FROM_NAME||"FlatCloud"}/></label><label className="field"><span>E-mail odesílatele</span><input type="email" name="smtpFromEmail" defaultValue={settings.smtpFromEmail||process.env.SMTP_FROM_EMAIL||""}/></label><label className="field"><span>Reply-To</span><input type="email" name="smtpReplyTo" defaultValue={settings.smtpReplyTo||""}/></label><label className="checkbox-field"><input type="checkbox" name="smtpSecure" defaultChecked={settings.smtpSecure}/><span>Přímé TLS (obvykle port 465)</span></label>
      <label className="checkbox-field field-full"><input type="checkbox" name="remindersEnabled" defaultChecked={settings.remindersEnabled}/><span>Automatické platební zprávy a upomínky jsou aktivní</span></label><label className="field"><span>Hodina odesílání (Praha)</span><input type="number" name="reminderSendHour" min={0} max={23} defaultValue={settings.reminderSendHour}/></label><label className="field"><span>Platební údaje před splatností</span><input type="number" name="paymentNoticeDaysBefore" min={0} max={31} defaultValue={settings.paymentNoticeDaysBefore}/><small>dní před splatností</small></label><label className="field"><span>První upozornění</span><input type="number" name="firstReminderDaysAfter" min={1} max={90} defaultValue={settings.firstReminderDaysAfter}/><small>dní po splatnosti</small></label><label className="field"><span>Druhá upomínka</span><input type="number" name="secondReminderDaysAfter" min={1} max={180} defaultValue={settings.secondReminderDaysAfter}/><small>dní po splatnosti</small></label><label className="field"><span>Interní upozornění správci</span><input type="number" name="managerAlertDaysAfter" min={1} max={365} defaultValue={settings.managerAlertDaysAfter}/><small>dní po splatnosti</small></label><label className="field"><span>Ruční eskalace</span><input type="number" name="escalationDaysAfter" min={1} max={365} defaultValue={settings.escalationDaysAfter}/><small>dní po splatnosti; právní krok se automaticky neprovede</small></label>
      <div className="field field-full"><span>Dostupné proměnné šablon</span><div className="notice">{variables}</div></div><label className="field field-full"><span>Předmět platebních údajů</span><input name="paymentNoticeSubject" defaultValue={settings.paymentNoticeSubject} required/></label><label className="field field-full"><span>Text platebních údajů</span><textarea name="paymentNoticeBody" defaultValue={settings.paymentNoticeBody} rows={9} required/></label><label className="field field-full"><span>Předmět prvního upozornění</span><input name="firstReminderSubject" defaultValue={settings.firstReminderSubject} required/></label><label className="field field-full"><span>Text prvního upozornění</span><textarea name="firstReminderBody" defaultValue={settings.firstReminderBody} rows={9} required/></label><label className="field field-full"><span>Předmět druhé upomínky</span><input name="secondReminderSubject" defaultValue={settings.secondReminderSubject} required/></label><label className="field field-full"><span>Text druhé upomínky</span><textarea name="secondReminderBody" defaultValue={settings.secondReminderBody} rows={9} required/></label></div>
      <div className="form-actions"><button className="primary" type="submit">Uložit SMTP a upomínky</button></div></form>
    <div className="detail-grid" style={{marginTop:20}}><div className="card col-7"><h2>Stav upomínkového plánovače</h2><div className="summary-list"><div><span>Poslední start</span><strong>{settings.lastReminderCronStartedAt?.toLocaleString("cs-CZ")||"Zatím neběžel"}</strong></div><div><span>Poslední dokončení</span><strong>{settings.lastReminderCronFinishedAt?.toLocaleString("cs-CZ")||"—"}</strong></div><div><span>Výsledek</span><strong>{settings.lastReminderCronSummary||"—"}</strong></div></div><div className="notice" style={{marginTop:16}}>Hlavička každé zprávy se vytváří systémově z komunikačního vlastníka nemovitosti, případně z jejího hlavního vlastníka. Nelze ji omylem odstranit úpravou šablony.</div></div><div className="card col-5"><h2>Kontrola</h2><div className="stack-actions"><form action="/api/settings/notifications/test" method="post"><button className="secondary" type="submit">Odeslat test SMTP na můj e-mail</button></form><form action="/api/settings/notifications/run" method="post"><button className="secondary" type="submit">Spustit kontrolu upomínek nyní</button></form></div></div></div>
  </div></Shell>;
}
