import { PageHeading } from "@/components/PageHeading";
import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { tenantAccessWhere, leaseAccessWhere } from "@/lib/access";
import { prisma } from "@/lib/db";
import { Shell } from "@/components/Shell";
import { leaseStatusAt } from "@/lib/lease-lifecycle-core";
import { NavigableTableRow } from "@/components/NavigableTableRow";
import { phone } from "@/lib/format";
import { TenantAvatar } from "@/components/TenantAvatar";

export const dynamic = "force-dynamic";
const labels: Record<string, string> = { ACTIVE: "Aktuální", FUTURE: "Budoucí", ENDED: "Bývalý", PROFILE: "Bez smlouvy" };

export default async function TenantsPage({ searchParams }: { searchParams: Promise<{ status?: string; property?: string; sort?: string; q?: string }> }) {
  const user = await requireUser();
  const query = await searchParams;
  const tenants = await prisma.tenant.findMany({ where: tenantAccessWhere(user), include: { leases: { where: leaseAccessWhere(user), include: { unit: { include: { property: true } } } }, leaseParties: { where: { lease: leaseAccessWhere(user) }, include: { lease: { include: { unit: { include: { property: true } } } } } } }, orderBy: { name: "asc" } });
  const rows = tenants.map((tenant) => { const relationships = Array.from(new Map([...tenant.leases, ...tenant.leaseParties.map((party) => party.lease)].map((lease) => [lease.id, lease])).values()); const status = !relationships.length ? "PROFILE" : relationships.some((lease) => leaseStatusAt(lease) === "ACTIVE") ? "ACTIVE" : relationships.some((lease) => leaseStatusAt(lease) === "FUTURE") ? "FUTURE" : "ENDED"; const relationship = relationships.find((lease) => leaseStatusAt(lease) === "ACTIVE") || relationships.find((lease) => leaseStatusAt(lease) === "FUTURE") || relationships[0]; return { tenant, relationships, status, relationship }; });
  const counts = { ALL: rows.length, ACTIVE: rows.filter((row) => row.status === "ACTIVE").length, FUTURE: rows.filter((row) => row.status === "FUTURE").length, ENDED: rows.filter((row) => row.status === "ENDED").length, PROFILE: rows.filter((row) => row.status === "PROFILE").length };
  const view = query.status || "ALL";
  const properties=Array.from(new Map(rows.flatMap(row=>row.relationships.map(lease=>[lease.unit.property.id,lease.unit.property.name] as const))).entries()).sort((a,b)=>a[1].localeCompare(b[1],"cs"));
  const visible = rows.filter((row) => (view === "ALL" || row.status === view) && (!query.property||query.property==="all"||row.relationships.some(lease=>lease.unit.propertyId===query.property)) && (!query.q||`${row.tenant.name} ${row.tenant.email||""}`.toLocaleLowerCase("cs").includes(query.q.toLocaleLowerCase("cs")))).sort((a,b)=>query.sort==="recent"?(b.relationship?.startDate.getTime()||0)-(a.relationship?.startDate.getTime()||0):query.sort==="property"?(a.relationship?.unit.property.name||"").localeCompare(b.relationship?.unit.property.name||"","cs"):a.tenant.name.localeCompare(b.tenant.name,"cs"));
  return <Shell user={user}><div className="page"><div className="page-title"><div><PageHeading>Nájemníci</PageHeading><p>Master profily osob a firem napříč dostupným portfoliem.</p></div><Link className="primary" href="/najemnici/novy">Nový profil</Link></div><nav className="registry-tabs">{Object.entries({ALL:`Všichni ${counts.ALL}`,ACTIVE:`Aktuální ${counts.ACTIVE}`,FUTURE:`Budoucí ${counts.FUTURE}`,ENDED:`Bývalí ${counts.ENDED}`,PROFILE:`Bez smlouvy ${counts.PROFILE}`}).map(([key,label])=><Link key={key} className={`registry-tab ${view===key?"active":""}`} href={`/najemnici?${new URLSearchParams({...query,status:key})}`}>{label}</Link>)}</nav><form className="registry-filters" method="get"><input type="hidden" name="status" value={view}/><label>Hledat<input name="q" defaultValue={query.q||""} placeholder="Jméno nebo e-mail"/></label><label>Nemovitost<select name="property" defaultValue={query.property||"all"}><option value="all">Všechny dostupné</option>{properties.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label>Řadit<select name="sort" defaultValue={query.sort||"name"}><option value="name">Podle jména</option><option value="property">Podle nemovitosti</option><option value="recent">Nejnovější vztah</option></select></label><button className="secondary">Zobrazit</button></form><div className="card table-wrap"><table className="registry-table"><thead><tr><th>Nájemník</th><th>Aktuální / poslední vztah</th><th>Typ</th><th>Stav</th><th>Smluv</th></tr></thead><tbody>{visible.map(({ tenant, relationships, relationship, status }) => <NavigableTableRow href={`/najemnici/${tenant.id}`} ariaLabel={`Otevřít nájemníka ${tenant.name}`} key={tenant.id}><td><div className="tenant-registry-cell"><TenantAvatar tenant={tenant}/><div><Link className="entity-primary" href={`/najemnici/${tenant.id}`}>{tenant.name}</Link><span className="entity-secondary">{tenant.email || phone(tenant.phone) || "Bez kontaktu"}</span></div></div></td><td>{relationship ? <><Link className="registry-context" href={`/smlouvy/${relationship.id}`}>{relationship.unit.property.name}</Link><span className="entity-secondary">{relationship.unit.label}</span></> : <span className="entity-secondary">Profil připraven k přiřazení</span>}</td><td>{tenant.type === "COMPANY" ? "Společnost" : "Osoba"}</td><td>{labels[status]}</td><td>{relationships.length}</td></NavigableTableRow>)}{!visible.length && <tr><td colSpan={5} className="muted-copy">Žádní nájemníci v tomto pohledu.</td></tr>}</tbody></table></div></div></Shell>;
}
