import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {prisma} from "../lib/db";
import {createUnitAssetAssessment} from "../lib/distribution/unit-assessments";

const read=(path:string)=>readFileSync(path,"utf8");let checks=0;
async function check(name:string,run:()=>Promise<void>|void){await run();checks++;console.log(`✓ ${checks}. ${name}`)}
async function main(){const admin=await prisma.user.findFirst({where:{role:"SUPER_ADMIN",active:true},select:{id:true,role:true,allProperties:true}});assert.ok(admin,"CI seed must contain an active super admin");const suffix=Date.now().toString();const owner=await prisma.owner.create({data:{name:`R6A owner ${suffix}`,affiliation:"FLATCLOUD_GROUP"}});const property=await prisma.property.create({data:{name:`R6A property ${suffix}`,address:"Test 6",city:"Praha",ownerId:owner.id,flatcloudConsolidationBasisPoints:10_000,units:{create:{label:"R6A-1",areaM2:50}}},include:{units:true}});const external=await prisma.property.create({data:{name:`R6A external ${suffix}`,address:"Test 0",city:"Praha",ownerId:owner.id,flatcloudConsolidationBasisPoints:0,units:{create:{label:"EXT-1"}}},include:{units:true}});
  await check("confirmed FlatCloud unit accepts a dated snapshot",async()=>{const result=await createUnitAssetAssessment(admin,property.id,property.units[0].id,{rating:"C_RENOVATE",investmentUrgency:"PLAN_12_MONTHS",estimatedCapexCents:250_000,distributionReady:false,assessedAt:new Date(),note:"CI"});assert.equal(result.rating,"C_RENOVATE");assert.equal(result.estimatedCapexCents,250_000);const audit=await prisma.auditLog.findFirst({where:{entityId:result.id,action:"UNIT_ASSET_ASSESSMENT_CREATED"}});assert.ok(audit);await assert.rejects(()=>prisma.unitAssetAssessment.update({where:{id:result.id},data:{estimatedCapexCents:1}}))});
  await check("external assets and non-internal users are rejected",async()=>{await assert.rejects(()=>createUnitAssetAssessment(admin,external.id,external.units[0].id,{rating:"B_GOOD",investmentUrgency:"MONITOR",estimatedCapexCents:0,distributionReady:false,assessedAt:new Date()}),/potvrzeného aktiva FlatCloud/);await assert.rejects(()=>createUnitAssetAssessment({id:admin.id,role:"OWNER"},property.id,property.units[0].id,{rating:"B_GOOD",investmentUrgency:"MONITOR",estimatedCapexCents:0,distributionReady:false,assessedAt:new Date()}),/pouze interním správcům/)});
  await check("schema and migration keep assessment history immutable",()=>{const schema=read("prisma/schema.prisma"),migration=read("prisma/migrations/20260905070000_unit_asset_assessments/migration.sql");for(const marker of ["enum UnitQualityRating","enum UnitInvestmentUrgency","model UnitAssetAssessment","estimatedCapexCents","distributionReady","@@index([unitId, assessedAt])"])assert.match(schema,new RegExp(marker.replace(/[?*+.[\]{}()]/g,"\\$&")));for(const marker of ["UnitAssetAssessment_capex_check","UnitAssetAssessment_immutable_trigger","BEFORE UPDATE OR DELETE","ON DELETE RESTRICT"])assert.match(migration,new RegExp(marker));assert.doesNotMatch(migration,/DROP TABLE|DROP COLUMN|TRUNCATE/)});
  await check("service scopes writes to internal roles and consolidated assets",()=>{const source=read("lib/distribution/unit-assessments.ts");for(const marker of ["canSeeAll(actor.role)","flatcloudConsolidationBasisPoints:{gt:0}","UNIT_ASSET_ASSESSMENT_CREATED","tx.unitAssetAssessment.create"])assert.match(source,new RegExp(marker.replace(/[()]/g,"\\$&")))});
  await check("UI makes rating, CAPEX and non-public readiness explicit",()=>{const page=read("app/distribuce/page.tsx"),shell=read("components/Shell.tsx");for(const marker of ["Interní modul · pouze FlatCloud Group","Rating je rozhodovací podklad, ne tržní ocenění","Odhad CAPEX","Interně připraveno pro distribuci","Uložit nový snapshot"])assert.match(page,new RegExp(marker));assert.match(shell,/href="\/distribuce"/)});
  await check("pipeline methodology browser smoke and CI cover R6A",()=>{assert.match(read("UX-REMODEL-PIPELINE.md"),/R6A implementováno aditivně/);assert.match(read("lib/methodology.ts"),/slug: "kategorizace-jednotek"/);assert.match(read("e2e/flatcloud.smoke.spec.ts"),/interní kategorizace ukládá nový neměnný snapshot/);assert.match(read(".github/workflows/ci.yml"),/verify:ux-remodel-r6a/)});
  console.log(`UX remodel R6A ověřen: ${checks} kontrol.`);
}
main().finally(()=>prisma.$disconnect());
