import assert from "node:assert/strict";
import {tenantPortalContact} from "../lib/tenant-portal-contact";

const owner={id:"owner",name:"Pronajímatel",email:"owner@example.test",phone:null,active:true};
const manager={id:"manager",name:"Správce",email:"manager@example.test",phone:"+420777000111",active:true};
const other={id:"other",name:"Jiný vlastník",email:"other@example.test",phone:null,active:true};
const base={unit:{property:{owner,manager,ownershipMode:"WHOLE_OBJECT"}}};
assert.equal(tenantPortalContact(base)?.kind,"manager");
assert.equal(tenantPortalContact({...base,ownerBankAccount:{owner:other}})?.name,"Správce");
const withoutManager={unit:{property:{owner,manager:null,ownershipMode:"WHOLE_OBJECT"}}};
assert.equal(tenantPortalContact(withoutManager)?.name,"Pronajímatel");
assert.equal(tenantPortalContact({...withoutManager,ownerBankAccount:{owner:other}})?.name,"Jiný vlastník");
const divided={unit:{property:{owner,manager:null,ownershipMode:"UNIT_BASED"},ownerships:[{owner},{owner:other}]}};
assert.equal(tenantPortalContact(divided),null,"Ambiguous unit ownership must not fall back to building owner");
assert.equal(tenantPortalContact({...divided,unit:{...divided.unit,ownerships:[{owner:other}]}})?.name,"Jiný vlastník");
assert.equal(tenantPortalContact({...divided,unit:{...divided.unit,property:{...divided.unit.property,communicationOwner:other}}})?.name,"Jiný vlastník");
const inactiveUser={...manager,active:false};
const fallback={...owner,email:null,user:inactiveUser};
assert.equal(tenantPortalContact({...withoutManager,ownerBankAccount:{owner:fallback}})?.user,null);
assert.equal(tenantPortalContact({...withoutManager,ownerBankAccount:{owner:fallback}})?.email,null);
console.log("Tenant portal contact: manager/owner precedence, ambiguity and inactive identity checks passed.");

const assigned = {...manager, id: "assigned", name: "Přidělený správce", role: "PROPERTY_MANAGER"};
const byGrant = (memberships: Array<{permission: string; user: typeof assigned}>, direct: typeof manager | null = null) => ({unit: {property: {owner, manager: direct, ownershipMode: "WHOLE_OBJECT", memberships}}});
assert.equal(tenantPortalContact(byGrant([{permission: "ADMIN", user: assigned}]))?.user?.id, assigned.id);
assert.equal(tenantPortalContact(byGrant([{permission: "EDIT", user: assigned}], manager))?.user?.id, manager.id, "Explicit house manager has precedence");
assert.equal(tenantPortalContact(byGrant([{permission: "VIEW", user: assigned}]))?.kind, "owner", "Read-only access is not management");
assert.equal(tenantPortalContact(byGrant([{permission: "ADMIN", user: {...assigned, active: false}}]))?.kind, "owner");
assert.equal(tenantPortalContact(byGrant([{permission: "ADMIN", user: {...assigned, role: "OWNER_VIEWER"}}]))?.kind, "owner");
const ambiguous = tenantPortalContact(byGrant([{permission: "ADMIN", user: assigned}, {permission: "EDIT", user: {...assigned, id: "second"}}]));
assert.equal(ambiguous?.kind, "manager", "Multiple assigned managers must not expose an unrelated landlord");
assert.equal(ambiguous?.user, null, "Do not nominate an arbitrary manager");
console.log("Whole-house manager grants: precedence, permissions, inactive users and ambiguity passed.");
