import assert from 'node:assert/strict';
import { calculateRentForecastWithAssumptions as calculate, parseRentForecastHorizon, marketGrowthBasisPoints, parseRentForecastAssumptions, type RentForecastInput } from '../lib/reporting/rent-forecast';
import { calculateSavedRentForecast, parseRentForecastPlanSnapshot } from '../lib/reporting/rent-forecast-plans';
import { calculateCashflowScenario } from '../lib/reporting/cashflow-scenario';
const row: RentForecastInput = { leaseId:'qa',propertyId:'qa',unitId:'qa',propertyName:'R24_AGENT_QA_2026_09',unitLabel:'A',currentRentCents:1_000_000,mfMarketRentCents:1_200_000,effectiveEnd:null,indexationEnabled:false,indexationPercentBps:null,nextIndexationAt:null };
const date=new Date('2026-01-01T00:00:00Z');
const assumptions={label:'QA',annualGrowthBps:0,marketAnnualGrowthBps:200,marketCatchUpMonths:24,vacancyBps:0,collectionBps:10000,marketGapCaptureBps:5000};
let count=0;function check(name:string,fn:()=>void){fn();console.log(`✓ ${++count}. ${name}`);}
check('horizon bounds and signed locale growth',()=>{assert.equal(parseRentForecastHorizon('240'),240);for(const x of ['0','361','1.5','NaN',''])assert.equal(parseRentForecastHorizon(x),24);assert.equal(marketGrowthBasisPoints('-1,25'),-125);for(const x of ['-20.01','21','1e2','Infinity'])assert.throws(()=>marketGrowthBasisPoints(x));assert.throws(()=>calculate([row],date,'qa',assumptions,361));});
check('horizon never changes overlapping periods in v2',()=>{const a=calculate([row],date,'qa',assumptions,12),b=calculate([row],date,'qa',assumptions,240);assert.deepEqual(a.months,b.months.slice(0,12));assert.equal(a.months[11].plannedCents,1_050_000);assert.equal(b.months[23].plannedCents,1_100_000);assert.equal(b.months[12].mfProjectedCents,1_224_000);});
check('market growth is independent from rental receipts',()=>{const a=calculate([row],date,'qa',assumptions,24),b=calculate([row],date,'qa',{...assumptions,marketAnnualGrowthBps:-200},24);assert.equal(b.months[12].mfProjectedCents,1_176_000);assert.equal(a.expectedCollectedTotalCents,b.expectedCollectedTotalCents);});
check('missing or partial MF never fabricates portfolio market line',()=>{for(const rows of [[],[{...row,mfMarketRentCents:null}],[row,{...row,mfMarketRentCents:null}]])assert.equal(calculate(rows,date,'qa',assumptions,24).months[0].mfProjectedCents,null);assert.equal(calculate([{...row,mfMarketRentCents:0}],date,'qa',assumptions,12).months[0].mfProjectedCents,0);});
check('v1 saved amounts and v2 snapshot roundtrip remain deterministic',()=>{const snapshotRow={leaseId:row.leaseId,propertyId:row.propertyId,unitId:row.unitId,propertyName:row.propertyName,unitLabel:row.unitLabel,currentRentCents:row.currentRentCents,mfMarketRentCents:row.mfMarketRentCents,effectiveEnd:null,indexationEnabled:row.indexationEnabled,indexationPercentBps:row.indexationPercentBps,nextIndexationAt:null};const snapshot={schemaVersion:1,scope:[{propertyId:'qa',propertyName:'QA'}],mfReferencePeriod:'Q4 2025',rows:[snapshotRow]};const plan={name:'QA',asOfDate:date,horizonMonths:12,...assumptions,inputSnapshot:snapshot};assert.equal(calculateSavedRentForecast(plan).months[11].plannedCents,1_100_000);const v2={...snapshot,schemaVersion:2,market:{annualGrowthBps:-200,catchUpMonths:24}};assert.equal(calculateSavedRentForecast({...plan,horizonMonths:240,inputSnapshot:v2}).months[12].mfProjectedCents,1_176_000);assert.equal(calculateSavedRentForecast({...plan,inputSnapshot:v2}).months[11].plannedCents,1_050_000);assert.throws(()=>parseRentForecastPlanSnapshot({...snapshot,schemaVersion:2}));});
check('indexation continues after tenth anniversary only in new model',()=>{const r={...row,indexationEnabled:true,indexationPercentBps:100,nextIndexationAt:new Date('2027-01-01')};const old=calculate([r],date,'qa',assumptions,240,1),fresh=calculate([r],date,'qa',assumptions,240);assert.equal(old.months[120].contractualCents,old.months[239].contractualCents);assert(fresh.months[239].contractualCents>fresh.months[120].contractualCents);});
check('long cashflow retains every month and counts expenditures once',()=>{const income=calculate([row],date,'qa',assumptions,240).months;const cf=calculateCashflowScenario(income,{openingCashCents:0,monthlyOpexCents:10000,annualOpexGrowthBps:0,monthlyDebtServiceCents:20000,capexCents:30000,capexMonth:240});assert.equal(cf.months.length,240);assert.equal(cf.netCashflowCents,cf.incomeCents-240*30000-30000);});
check('preset growth and valid custom assumptions persist',()=>{const a=parseRentForecastAssumptions({marketAnnualGrowthPercent:'-3',marketCatchUpMonths:'60'},'base');assert.equal(a.assumptions.marketAnnualGrowthBps,-300);assert.equal(a.assumptions.marketCatchUpMonths,60);});
check('extreme long cashflow rejects loss of monetary precision',()=>{const income=Array.from({length:360},(_,i)=>({period:String(i),contractualCents:0,expectedCollectedCents:0}));assert.throws(()=>calculateCashflowScenario(income,{openingCashCents:0,monthlyOpexCents:1_000_000_000_000,annualOpexGrowthBps:2000,monthlyDebtServiceCents:0,capexCents:0,capexMonth:1}),/číselný rozsah/);});
console.log(`R27A: ${count} checks passed.`);
