import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path: string) => readFileSync(path, "utf8");
const packageJson = JSON.parse(read("package.json"));
const lock = JSON.parse(read("package-lock.json"));
const schema = read("prisma/schema.prisma");
const create = read("lib/lease-create.ts");
const tenantRoute = read("app/api/properties/[id]/tenants/route.ts");
const leaseRoute = read("app/api/properties/[id]/leases/route.ts");
const retention = read("lib/inbound-bank/retention.ts");
const imap = read("lib/inbound-bank/imap.ts");
const scheduler = read("scripts/scheduler-cron.ts");
const reset = read("scripts/reset-test-tenants.ts");

assert.equal(packageJson.version, "1.21.4");
assert.equal(lock.version, "1.21.4");
assert.equal(lock.packages[""].version, "1.21.4");
assert.equal(packageJson.scripts["verify:v21.3.6"], "tsx scripts/verify-v21-3-6.ts");
assert.equal(packageJson.scripts["verify:v21.4"], "tsx scripts/verify-v21-4.ts");
for (const field of ["inboundMailResolvedRetentionDays", "inboundMailUnresolvedRetentionDays", "inboundMailUidValidity", "inboundMailLastCleanupAt", "inboundMailLastCleanupSummary", "imapUidValidity", "mailboxDeletedAt"]) assert.match(schema, new RegExp(field));
assert.match(tenantRoute, /createLeaseFromForm/);
assert.match(leaseRoute, /createLeaseFromForm/);
for (const rule of ["assertNoLeaseOverlap", "assertUniqueVariableSymbol", "propertyPaymentAccount.upsert", "syncUnitOccupancyCache", "syncLeaseCharges", "payerAccounts"]) assert.match(create, new RegExp(rule.replace(/[.]/g, "\\.")));
assert.match(retention, /imapUidValidity: settings\.inboundMailUidValidity/);
assert.match(retention, /status: \{ in: \["IMPORTED", "IGNORED"\] \}/);
assert.match(retention, /status: \{ in: \["RECEIVED", "UNMATCHED", "ERROR"\] \}/);
assert.match(retention, /mailboxDeletedAt: null/);
assert.match(imap, /BODY\.PEEK/);
assert.match(imap, /UID EXPUNGE/);
assert.match(imap, /supportsUidExpunge/);
assert.match(scheduler, /mailbox-retention/);
assert.ok(scheduler.indexOf("bank-email") < scheduler.indexOf("mailbox-retention"));
assert.ok(scheduler.indexOf("mailbox-retention") < scheduler.indexOf("charges"));
assert.match(reset, /const apply = args\.includes\("--apply"\)/);
assert.match(reset, /ALLOW_TEST_TENANT_RESET !== "1"/);
assert.match(reset, /tenantIds\.length/);
assert.match(reset, /tenantIds\.includes\("\*"\)/);
assert.match(reset, /if \(!apply\) return/);
assert.match(reset, /bankTransaction\.update/);
assert.match(reset, /meterReading\.updateMany/);
assert.match(reset, /auditLog\.create/);
console.log("V21.4 verification passed.");
