import assert from "node:assert/strict";
import { leaseAccountBalance } from "../lib/lease-account-balance";
const now = new Date("2026-10-02T12:00:00Z");
const past = new Date("2026-09-05T12:00:00Z"), future = new Date("2026-10-05T12:00:00Z");
const charge = (amountCents = 10000, dueDate = past) => ({ active:true, debtTreatment:"CURRENT" as "CURRENT" | "HISTORICAL" | "EXCLUDED", amountCents, dueDate, allocations:[] as {amountCents:number;transaction:{bookedAt:Date;status:string}}[], creditApplications:[] as {amountCents:number;credit:{effectiveAt:Date}}[], securityDepositOffsets:[] as {amountCents:number;effectiveAt:Date}[] });
const transaction = (amountCents = 12100) => ({ amountCents, bookedAt:past, status:"OVERPAYMENT", source:"fio", suggestedLeaseId:"lease", allocations:[{amountCents:10000,charge:{leaseId:"lease"}}],securityDepositReceipts:[] as {amountCents:number;type:string;leaseId:string}[] });
const credit = (amountCents=2100) => ({amountCents,effectiveAt:past,applications:[] as {amountCents:number}[]});
const run = (charges = [charge()], transactions = [] as ReturnType<typeof transaction>[], credits = [] as ReturnType<typeof credit>[]) => leaseAccountBalance({leaseId:"lease",charges,transactions,credits},now);
const paid = charge();paid.allocations=[{amountCents:10000,transaction:{bookedAt:past,status:"OVERPAYMENT"}}];
assert.equal(run([paid],[transaction()]).balanceCents,2100,"paid rent plus excess yields overpayment");
assert.equal(run([charge(10000,future)]).balanceCents,0,"future unpaid prescription is not debt");
assert.equal(run().balanceCents,-10000,"unpaid overdue rent is debt");
assert.equal(run([paid],[transaction()],[credit()]).balanceCents,4200,"settlement credit and payment excess both count");
const advance=charge(10000,future);advance.allocations=paid.allocations;
assert.equal(run([advance],[transaction()]).balanceCents,2100,"applied advance is not a free overpayment; only the residual is credit");
assert.equal(run([advance],[transaction(10000)]).balanceCents,0,"normal payment of a not-yet-due charge is settled, not an overpayment");
const futurePaid=charge();futurePaid.allocations=[{amountCents:10000,transaction:{bookedAt:future,status:"MATCHED"}}];
assert.equal(run([futurePaid],[{...transaction(),bookedAt:future}],[{...credit(),effectiveAt:future}]).balanceCents,-10000,"future payments and credits do not hide today's debt");
assert.equal(run([{...charge(),active:false},{...charge(),debtTreatment:"HISTORICAL"},{...charge(),debtTreatment:"EXCLUDED"}]).balanceCents,0,"inactive/historical/excluded debt is not current debt");
assert.equal(run([paid],[{...transaction(),status:"IGNORED"}]).unappliedPaymentCents,0,"ignored transaction has no excess");
assert.equal(run([], [{...transaction(),allocations:[],status:"SUGGESTED"}]).balanceCents,0,"bank matching suggestion alone is not a confirmed credit");
assert.equal(run([], [{...transaction(),source:"manual",allocations:[]}]).balanceCents,12100,"manual unallocated payment counts");
assert.equal(run([paid],[{...transaction(32100),securityDepositReceipts:[{amountCents:20000,type:"RECEIVED",leaseId:"lease"}]}]).balanceCents,2100,"deposit principal never appears as overpayment");
assert.equal(run([paid],[{...transaction(),allocations:[...transaction().allocations,{amountCents:100,charge:{leaseId:"other"}}]}]).balanceCents,0,"ambiguous multi-lease residual is not assigned twice");
assert.equal(run([paid],[{...transaction(),securityDepositReceipts:[{amountCents:100,type:"RECEIVED",leaseId:"other"}]}]).balanceCents,0,"cross-lease deposit does not assign ambiguous excess");
const withCredit=charge();withCredit.creditApplications=[{amountCents:2100,credit:{effectiveAt:past}}];
assert.equal(run([withCredit],[],[{...credit(),applications:[{amountCents:2100}]}]).balanceCents,-7900,"applied credit pays debt and is not counted again");
const withDeposit=charge();withDeposit.securityDepositOffsets=[{amountCents:10000,effectiveAt:past}];
assert.equal(run([withDeposit]).balanceCents,0,"deposit legally applied to rent pays debt without inflating credit");
console.log("Unit card saldo: 16 financial regression checks passed.");
