import assert from "node:assert/strict";
import fs from "node:fs";
import { createOpeningDepositBalance, resolveLeaseFinancialOnboarding } from "../lib/lease-financial-onboarding";
import { calculateSecurityDepositSnapshot } from "../lib/security-deposit-core";
import { calculatePropertySnapshot } from "../lib/reporting/snapshot-calculator";

let count = 0;
const check = async (name: string, assertion: () => unknown | Promise<unknown>) => { await assertion(); count += 1; console.log(`✓ ${count}. ${name}`); };
const form = (values: Record<string, string>) => { const data = new FormData(); for (const [key, value] of Object.entries(values)) data.set(key, value); return data; };
const now = new Date("2026-08-15T12:00:00Z");
const start = new Date("2022-06-01T12:00:00Z");
const snapshot = (movements: Array<{ type: "OPENING_BALANCE"; amountCents: number; effectiveAt: Date }>) => calculateSecurityDepositSnapshot({ depositCents: 3_000_000, terms: [{ agreedAmountCents: 3_000_000, annualRateBps: 0, effectiveFrom: start }], movements, asOf: now });

async function main() {
  await check("historical NOT_FUNDED holds zero and misses full deposit", () => { const onboarding = resolveLeaseFinancialOnboarding(start, form({ openingDepositStatus: "NOT_FUNDED" }), now, 3_000_000); const result = snapshot([]); assert.equal(onboarding.openingDepositHeldCents, 0); assert.equal(result.heldPrincipalCents, 0); assert.equal(result.missingDepositCents, 3_000_000); });
  const records: { movements: any[]; bankTransactions: any[]; paymentAllocations: any[] } = { movements: [], bankTransactions: [], paymentAllocations: [] };
  const tx: any = { securityDepositMovement: { create: async ({ data }: any) => { const row = { id: `movement-${records.movements.length + 1}`, ...data }; records.movements.push(row); return row; } } };
  await check("FULLY_FUNDED creates exactly one explicit opening movement", async () => { const onboarding = resolveLeaseFinancialOnboarding(start, form({ openingDepositStatus: "FULLY_FUNDED" }), now, 3_000_000); const created = await createOpeningDepositBalance(tx, { leaseId: "lease", financialTrackingFromPeriod: onboarding.financialTrackingFromPeriod, heldCents: onboarding.openingDepositHeldCents, createdById: "user" }); const result = snapshot(records.movements); assert.equal(records.movements.length, 1); assert.equal(created.openingDepositMovementId, "movement-1"); assert.equal(records.movements[0].type, "OPENING_BALANCE"); assert.equal(result.heldPrincipalCents, 3_000_000); assert.equal(result.missingDepositCents, 0); assert.equal(result.status, "FUNDED"); });
  await check("PARTIAL 12k holds 12k and misses 18k", () => { const onboarding = resolveLeaseFinancialOnboarding(start, form({ openingDepositStatus: "PARTIAL", openingDepositHeldAmount: "12000" }), now, 3_000_000); const result = snapshot([{ type: "OPENING_BALANCE", amountCents: onboarding.openingDepositHeldCents, effectiveAt: new Date("2026-08-01T12:00:00Z") }]); assert.equal(result.heldPrincipalCents, 1_200_000); assert.equal(result.missingDepositCents, 1_800_000); assert.equal(result.status, "PARTIAL"); });
  await check("opening deposit creates no bank or payment history", () => { assert.equal(records.bankTransactions.length, 0); assert.equal(records.paymentAllocations.length, 0); const source = fs.readFileSync("lib/lease-financial-onboarding.ts", "utf8"); assert.doesNotMatch(source, /bankTransaction|paymentAllocation/i); });
  await check("opening movement is provenance, not received cashflow", () => { const result = snapshot(records.movements); assert.equal(result.receivedCents, 0); assert.equal(result.heldPrincipalCents, 3_000_000); assert.match(records.movements[0].note, /Převzatý stav/); });
  await check("new lease ignores deposit onboarding and creates no opening movement", async () => { const onboarding = resolveLeaseFinancialOnboarding(new Date("2026-08-01T12:00:00Z"), form({ openingDepositStatus: "FULLY_FUNDED" }), now, 3_000_000); const before = records.movements.length; const created = await createOpeningDepositBalance(tx, { leaseId: "new", financialTrackingFromPeriod: onboarding.financialTrackingFromPeriod, heldCents: onboarding.openingDepositHeldCents }); assert.equal(onboarding.openingDepositHeldCents, 0); assert.equal(created.openingDepositMovementId, null); assert.equal(records.movements.length, before); });
  await check("RECEIVED RETURNED and OFFSET semantics stay unchanged", () => { const result = calculateSecurityDepositSnapshot({ depositCents: 3_000_000, movements: [{ type: "RECEIVED", amountCents: 3_000_000, effectiveAt: start }, { type: "RETURNED", amountCents: 500_000, effectiveAt: new Date("2023-01-01T12:00:00Z") }, { type: "OFFSET", amountCents: 250_000, effectiveAt: new Date("2024-01-01T12:00:00Z") }], asOf: now }); assert.equal(result.receivedCents, 3_000_000); assert.equal(result.returnedCents, 500_000); assert.equal(result.offsetCents, 250_000); assert.equal(result.heldPrincipalCents, 2_250_000); });
  await check("quarter snapshot reports opening deposit after cutover", () => { const lease: any = { id: "lease", unitId: "unit", startDate: start, endDate: null, terminatedOn: null, cancelledAt: null, financialTrackingFromPeriod: "2026-08", rentCents: 0, servicesCents: 0, depositCents: 3_000_000, paymentItems: [], charges: [], securityDepositTerms: [{ agreedAmountCents: 3_000_000, annualRateBps: 0, effectiveFrom: start }], securityDepositMovements: records.movements }; const report = calculatePropertySnapshot({ propertyId: "property", asOf: now, units: [{ id: "unit", areaM2: 50, operationalStatusEvents: [{ status: "STANDARD", effectiveAt: new Date("2020-01-01T12:00:00Z") }], leases: [lease] }] }); assert.equal(report.data.deposits.agreedCents, 3_000_000); assert.equal(report.data.deposits.heldPrincipalCents, 3_000_000); assert.equal(report.data.deposits.fundedLeases, 1); });
  await check("reporting has no deposit cashflow KPI", () => { const source = fs.readFileSync("lib/reporting/snapshot-calculator.ts", "utf8"); assert.doesNotMatch(source, /receivedCents|OPENING_BALANCE/); });
  await check("authorization and opening-only route boundary remain unchanged", () => { const route = fs.readFileSync("app/api/properties/[id]/leases/[leaseId]/deposit/movements/route.ts", "utf8"); assert.match(route, /editableUnitWhere/); assert.match(route, /type === SecurityDepositMovementType\.OPENING_BALANCE/); });
  await check("Prague cutover month is preserved", () => assert.equal(resolveLeaseFinancialOnboarding(start, form({ openingDepositStatus: "FULLY_FUNDED" }), new Date("2026-08-31T22:30:00Z"), 3_000_000).financialTrackingFromPeriod, "2026-09"));
  await check("audit contains deposit onboarding provenance", () => { const route = fs.readFileSync("app/api/properties/[id]/leases/route.ts", "utf8"); for (const key of ["agreedDepositCents", "openingDepositStatus", "openingDepositHeldCents", "openingDepositMovementId"]) assert.ok(route.includes(key), key); });
  console.log(`V22-C Part 1.1 verification passed: ${count} checks.`);
}
main().catch((error) => { console.error(error); process.exit(1); });
