import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {prisma} from "../lib/db";
import {createUnitValuationSnapshot} from "../lib/distribution/unit-valuations";
const read=(path:string)=>readFileSync(path,"utf8");let checks=0;async function check(name:string,run:()=>Promise<void>|void){await run();checks++;console.log(`✓ ${checks}. ${name}`)}
async function main(){const admin=await prisma.user.findFirst({where:{role:"SUPER_ADMIN",active:true},select:{id:true,role:true,allProperties:true}});assert.ok(admin);const suffix=Date.now().toString();const owner=await prisma.owner.create({data:{name:`R6B owner ${suffix}`,affiliation:"FLATCLOUD_GROUP"}});const property=await prisma.property.create({data:{name:`R6B property ${suffix}`,address:"Test 6B",city:"Praha",ownerId:owner.id,flatcloudConsolidationBasisPoints:10_000,units:{create:{label:"R6B-1",areaM2:40}}},include:{units:true}});const external=await prisma.property.create({data:{name:`R6B external ${suffix}`,address:"Test ext",city:"Praha",ownerId:owner.id,flatcloudConsolidationBasisPoints:0,units:{create:{label:"EXT-1"}}},include:{units:true}});
  await check("unit valuation is dated sourced audited and immutable",async()=>{const value=await createUnitValuationSnapshot(admin,property.id,property.units[0].id,{marketValueCents:5_000_000_00,source:"INTERNAL_COMPARABLES",valuationDate:new Date(),reference:"CI-COMP",note:"CI"});assert.equal(value.marketValueCents,BigInt(5_000_000_00));assert.equal(value.reference,"CI-COMP");assert.ok(await prisma.auditLog.findFirst({where:{entityId:value.id,action:"UNIT_VALUATION_SNAPSHOT_CREATED"}}));await assert.rejects(()=>prisma.unitValuationSnapshot.update({where:{id:value.id},data:{marketValueCents:BigInt(1)}}))});
  await check("valuation stays inside internal consolidated scope",async()=>{await assert.rejects(()=>createUnitValuationSnapshot(admin,external.id,external.units[0].id,{marketValueCents:1_000_000,source:"EXTERNAL_APPRAISAL",valuationDate:new Date()}),/potvrzeného aktiva FlatCloud/);await assert.rejects(()=>createUnitValuationSnapshot({id:admin.id,role:"OWNER"},property.id,property.units[0].id,{marketValueCents:1_000_000,source:"EXTERNAL_APPRAISAL",valuationDate:new Date()}),/pouze interním správcům/)});
  await check("schema and migration preserve valuation history",()=>{const schema=read("prisma/schema.prisma"),migration=read("prisma/migrations/20260905080000_unit_valuation_snapshots/migration.sql");for(const marker of ["enum UnitValuationSource","model UnitValuationSnapshot","marketValueCents BigInt","valuationDate","reference","@@index([unitId, valuationDate])"])assert.match(schema,new RegExp(marker.replace(/[?*+.[\]{}()]/g,"\\$&")));for(const marker of ["UnitValuationSnapshot_value_check","UnitValuationSnapshot_immutable_trigger","BEFORE UPDATE OR DELETE","ON DELETE RESTRICT"])assert.match(migration,new RegExp(marker));assert.doesNotMatch(migration,/DROP TABLE|DROP COLUMN|TRUNCATE/)});
  await check("UI separates technical rating and valuation source",()=>{const page=read("app/distribuce/page.tsx");for(const marker of ["Technický rating a valuace se aktualizují samostatnými snapshoty","Tržní hodnota jednotek","/m²","Nová valuace","Zdroj *","Reference / číslo posudku"])assert.match(page,new RegExp(marker.replace("*","\\*")))});
  await check("pipeline methodology browser smoke and CI cover R6B",()=>{assert.match(read("UX-REMODEL-PIPELINE.md"),/R6B implementováno aditivně/);assert.match(read("lib/methodology.ts"),/slug: "valuace-jednotek"/);assert.match(read("e2e/flatcloud.smoke.spec.ts"),/Uložit novou valuaci/);assert.match(read(".github/workflows/ci.yml"),/verify:ux-remodel-r6b/)});
  console.log(`UX remodel R6B ověřen: ${checks} kontrol.`);
}
main().finally(()=>prisma.$disconnect());
