import assert from "node:assert/strict";import {readFileSync} from "node:fs";import {prisma} from "../lib/db";import {createDistributionOpportunity,createDistributionProspect,updateDistributionOpportunity} from "../lib/distribution/crm";
const read=(path:string)=>readFileSync(path,"utf8");let checks=0;async function check(name:string,run:()=>Promise<void>|void){await run();checks++;console.log(`✓ ${checks}. ${name}`)}
async function main(){const admin=await prisma.user.findFirst({where:{role:"SUPER_ADMIN",active:true},select:{id:true,role:true,allProperties:true}});assert.ok(admin);const suffix=Date.now().toString(),owner=await prisma.owner.create({data:{name:`R6C owner ${suffix}`,affiliation:"FLATCLOUD_GROUP"}}),property=await prisma.property.create({data:{name:`R6C property ${suffix}`,address:"Test CRM",city:"Praha",ownerId:owner.id,flatcloudConsolidationBasisPoints:10_000,units:{create:{label:"CRM-1"}}},include:{units:true}}),external=await prisma.property.create({data:{name:`R6C external ${suffix}`,address:"Test ext",city:"Praha",ownerId:owner.id,flatcloudConsolidationBasisPoints:0,units:{create:{label:"EXT-1"}}},include:{units:true}});
  const prospect=await createDistributionProspect(admin,{name:`Buyer ${suffix}`,email:"buyer@example.test",source:"CI"});
  await check("prospect and unit opportunity are separate audited records",async()=>{const opportunity=await createDistributionOpportunity(admin,{prospectId:prospect.id,unitId:property.units[0].id,stage:"NEW",askingPriceCents:5_000_000_00,offeredPriceCents:null,nextActionAt:new Date(Date.now()+86_400_000),note:"CI"});assert.equal(opportunity.prospectId,prospect.id);assert.equal(opportunity.unitId,property.units[0].id);assert.ok(await prisma.auditLog.findFirst({where:{entityId:opportunity.id,action:"DISTRIBUTION_OPPORTUNITY_CREATED"}}));const updated=await updateDistributionOpportunity(admin,opportunity.id,{stage:"CONTACTED",askingPriceCents:5_000_000_00,offeredPriceCents:4_800_000_00,nextActionAt:new Date(Date.now()+2*86_400_000),note:"Call"});assert.equal(updated.stage,"CONTACTED");assert.ok(await prisma.auditLog.findFirst({where:{entityId:opportunity.id,action:"DISTRIBUTION_OPPORTUNITY_UPDATED"}}))});
  await check("contact and internal asset scope fail closed",async()=>{await assert.rejects(()=>createDistributionProspect(admin,{name:"No contact"}),/alespoň e-mail nebo telefon/);await assert.rejects(()=>createDistributionOpportunity(admin,{prospectId:prospect.id,unitId:external.units[0].id,stage:"NEW",askingPriceCents:null,offeredPriceCents:null,nextActionAt:null}),/potvrzeného aktiva FlatCloud/);await assert.rejects(()=>createDistributionProspect({id:admin.id,role:"OWNER"},{name:"Outside",email:"x@example.test"}),/pouze interním správcům/)});
  await check("schema and additive migration model prospect and opportunity",()=>{const schema=read("prisma/schema.prisma"),migration=read("prisma/migrations/20260905090000_distribution_crm/migration.sql");for(const marker of ["enum DistributionOpportunityStage","model DistributionProspect","model DistributionOpportunity","@@unique([prospectId, unitId])","nextActionAt","offeredPriceCents"])assert.match(schema,new RegExp(marker.replace(/[?*+.[\]{}()]/g,"\\$&")));for(const marker of ["DistributionOpportunity_prices_check","ON DELETE RESTRICT","stage_nextActionAt_idx"])assert.match(migration,new RegExp(marker));assert.doesNotMatch(migration,/DROP TABLE|DROP COLUMN|TRUNCATE/)});
  await check("CRM service validates scope prices and audits transitions",()=>{const source=read("lib/distribution/crm.ts");for(const marker of ["canSeeAll(actor.role)","flatcloudConsolidationBasisPoints:{gt:0}","DISTRIBUTION_PROSPECT_CREATED","DISTRIBUTION_OPPORTUNITY_CREATED","DISTRIBUTION_OPPORTUNITY_UPDATED","before:","after:"])assert.match(source,new RegExp(marker.replace(/[()]/g,"\\$&")))});
  await check("UI states privacy no publishing and next action",()=>{const page=read("app/distribuce/zajemci/page.tsx");for(const marker of ["Interní osobní údaje · bez veřejného publikování","neposílá e-mail","nevytváří rezervaci v právním smyslu","Další krok po termínu","Uložit fázi a další krok"])assert.match(page,new RegExp(marker))});
  await check("pipeline methodology browser smoke and CI cover R6C",()=>{assert.match(read("UX-REMODEL-PIPELINE.md"),/R6C implementováno aditivně/);assert.match(read("lib/methodology.ts"),/slug: "crm-distribuce"/);assert.match(read("e2e/flatcloud.smoke.spec.ts"),/interní CRM vede zájemce/);assert.match(read(".github/workflows/ci.yml"),/verify:ux-remodel-r6c/)});
  console.log(`UX remodel R6C ověřen: ${checks} kontrol.`)}main().finally(()=>prisma.$disconnect());
