import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const css=readFileSync("app/final-ui-polish.css","utf8");
const propertySubnav=readFileSync("components/PropertySubnav.tsx","utf8");
let n=0;const check=(name:string,fn:()=>void)=>{fn();console.log(`✓ ${++n}. ${name}`)};
check("category tabs use strong blue separator",()=>{assert.match(css,/border-top:4px solid var\(--fc-tab-blue\)/);assert.match(css,/--fc-tab-blue:#2563eb/)});
check("active tab is full blue with white text",()=>{assert.match(css,/background:var\(--fc-tab-blue\);\s*color:#fff/)});
check("first tab keeps approved slanted outer edge",()=>assert.match(css,/a:first-child[\s\S]*clip-path:polygon\(0 0,100% 0,100% 100%,10px 100%\)/));
check("last tab keeps approved slanted outer edge",()=>assert.match(css,/a:last-child[\s\S]*clip-path:polygon\(0 0,100% 0,calc\(100% - 10px\) 100%,0 100%\)/));
check("property navigation has a dedicated styling hook",()=>assert.match(propertySubnav,/section-nav v21-section-nav property-subnav/));
check("desktop property tabs attach directly below the identity card",()=>{assert.match(css,/property-header:has\(\+ \.property-subnav\)[\s\S]*margin-bottom:0/);assert.match(css,/property-header \+ \.property-subnav\{[\s\S]*margin:-1px 24px 18px;[\s\S]*border-top:0/)});
check("desktop property navigation is inset and scrollbar-free",()=>assert.match(css,/property-header \+ \.property-subnav\{[\s\S]*width:calc\(100% - 48px\)[\s\S]*overflow-x:hidden/));
check("mobile property navigation returns to the full-width separator variant",()=>assert.match(css,/@media\(max-width:700px\)[\s\S]*property-header \+ \.property-subnav\{[\s\S]*width:100%;[\s\S]*border-top:4px solid var\(--fc-tab-blue\);[\s\S]*overflow-x:auto/));
check("desktop tabs share width instead of scrolling",()=>assert.match(css,/@media\(min-width:901px\)[\s\S]*overflow-x:hidden;[\s\S]*flex:1 1 0;/));
check("mobile restores natural tab width and horizontal scrolling",()=>assert.match(css,/@media\(max-width:700px\)[\s\S]*flex:0 0 auto;[\s\S]*min-width:max-content/));
console.log(`TAB-NAV-V2.2 verified: ${n} checks.`);
