import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {receiptEligible} from "../lib/tenant-payment-receipts";
import {greeting} from "../lib/greeting";
import {tenantPortalStatus,portalEditableUnitWhere} from "../lib/tenant-portal-access";
import {portfolioSelectionLabel} from "../lib/portfolio-selection";
const charge={active:true,period:"2026-09",amountCents:10000,debtTreatment:"CURRENT",allocations:[{amountCents:10000,transaction:{amountCents:10000,currency:"CZK",bookedAt:new Date("2026-01-05T12:00Z"),status:"MATCHED"}}],securityDepositOffsets:[],creditApplications:[]};
assert.equal(receiptEligible(charge,"CZK"),true);
assert.equal(receiptEligible({...charge,allocations:[]},"CZK"),false);
assert.equal(receiptEligible({...charge,allocations:[{...charge.allocations[0],amountCents:5000}]},"CZK"),false);
assert.equal(receiptEligible({...charge,allocations:[{...charge.allocations[0],amountCents:10001}]},"CZK"),false);
assert.equal(receiptEligible({...charge,securityDepositOffsets:[{amountCents:1}]},"CZK"),false);
assert.equal(receiptEligible({...charge,creditApplications:[{amountCents:1}]},"CZK"),false);
assert.equal(receiptEligible({...charge,debtTreatment:"HISTORICAL"},"CZK"),false);
assert.equal(receiptEligible({...charge,active:false},"CZK"),false);
assert.equal(receiptEligible({...charge,period:"OPENING"},"CZK"),false);
assert.equal(receiptEligible(charge,"EUR"),false);
for(const status of ["IGNORED","SUGGESTED","UNMATCHED"])assert.equal(receiptEligible({...charge,allocations:[{...charge.allocations[0],transaction:{...charge.allocations[0].transaction,status}}]},"CZK"),false);
assert.equal(receiptEligible({...charge,allocations:[{...charge.allocations[0],transaction:{...charge.allocations[0].transaction,bookedAt:new Date("2099-01-01")}}]},"CZK"),false);
assert.equal(greeting("Ondřej Šohaj"),"Dobrý den, Ondřeji!");assert.equal(greeting("Neznámé jméno"),"Dobrý den!");assert.equal(greeting("Ondřej s.r.o.",false),"Dobrý den!");
const now=new Date("2026-10-04"),tenant={email:"tenant@test.cz",communicationEmail:null,portalAccesses:[] as {user:{active:boolean;email:string}}[],portalInvitations:[] as {email:string;expiresAt:Date}[]};
assert.equal(tenantPortalStatus(tenant,now).tone,"neutral");
assert.equal(tenantPortalStatus({...tenant,portalInvitations:[{email:tenant.email,expiresAt:new Date("2026-10-06")}]},now).tone,"warn");
assert.equal(tenantPortalStatus({...tenant,portalInvitations:[{email:tenant.email,expiresAt:new Date("2026-10-03")}]},now).tone,"neutral");
assert.equal(tenantPortalStatus({...tenant,portalAccesses:[{user:{active:true,email:tenant.email}}]},now).tone,"ok");
assert.equal(tenantPortalStatus({...tenant,communicationEmail:"changed@test.cz",portalAccesses:[{user:{active:true,email:tenant.email}}]},now).tone,"neutral");
assert.ok("OR" in portalEditableUnitWhere({id:"viewer",role:"OWNER_VIEWER",allProperties:true}));
assert.equal(portfolioSelectionLabel({mode:"ALL"},6,6,5),"Zobrazeno všech 6 dostupných objektů");
const portal=readFileSync("app/portal/najemnik/[tenantId]/page.tsx","utf8");
assert.doesNotMatch(portal,/charges\.slice\(-6\)/);assert.match(portal,/<PortalReceiptPicker/);assert.match(readFileSync("components/tenant-portal/PortalReceiptPicker.tsx","utf8"),/name="chargeId"/);assert.match(portal,/\.transaction\.bookedAt/);
console.log("Portal receipts: financial eligibility, permission boundary, access statuses and Czech labels passed.");
