import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import { emptySourceLine, validateSource } from '../lib/settlement-source-rules';
import { projectSettlementCosts, type ConfirmedSourceInput } from '../lib/settlement-cost-projection';
import { createSettlementSource, confirmSettlementSource } from '../lib/settlement-sources';
import { loadServiceSettlementPreview } from '../lib/service-settlement-preview';
import { issueServiceSettlementProtocol, parseServiceSettlementSnapshot } from '../lib/service-settlement-protocols';
const payload = validateSource({mode:'EXTERNAL_UNIT',kind:'EXTERNAL',vendor:'R24_AGENT_QA_2026_09',reference:'TEST',from:'2025-01-01',to:'2025-12-31',supplyAmount:'12000',supplierAdvances:'9000',unitId:'unit',lines:[{...emptySourceLine('2025-01-01','2025-12-31'),unitId:'unit',amount:'12000'}]});
const source:ConfirmedSourceInput={id:'source',identityKey:'invoice',version:1,confirmedAt:new Date('2026-01-01'),payload};
const scope={leaseId:'lease',unitId:'unit',from:'2025-01-01',to:'2025-12-31',leases:[{id:'lease',from:'2025-01-01',to:null}]};
let checks=0;async function check(name:string,run:()=>unknown|Promise<unknown>){await run();console.log(`✓ ${++checks}. ${name}`);}
async function main(){
 await check('delivery cost, not invoice remainder; confirmed zero remains evidence',()=>{assert.equal(projectSettlementCosts([source],scope).rows[0].amountCents,1200000);assert.equal(projectSettlementCosts([{...source,payload:{...payload,lines:[{...payload.lines[0],amount:'0'}]}}],scope).rows[0].amountCents,0);});
 await check('drafts excluded; newest confirmed revision only; pending correction blocks completion',()=>{assert.equal(projectSettlementCosts([{...source,confirmedAt:null}],scope).rows.length,0);const revised={...source,id:'v2',version:2,payload:{...payload,lines:[{...payload.lines[0],amount:'15000'}]}};assert.equal(projectSettlementCosts([source,revised],scope).rows[0].amountCents,1500000);const pending=projectSettlementCosts([source,{...revised,confirmedAt:null}],scope);assert.equal(pending.rows[0].amountCents,1200000);assert.ok(pending.blockers.some(b=>b.includes('nepotvrzená oprava')));});
 await check('house summaries and external components are never double counted',()=>{const p={...payload,lines:[{...payload.lines[0],service:'HEATING',base:'4000',consumptionComponent:'7999',rounding:'1',componentsComplete:true},{...payload.lines[0],key:'summary',role:'SUMMARY' as const,amount:'90000'}]};const result=projectSettlementCosts([{...source,payload:p}],scope);assert.equal(result.rows.length,1);assert.equal(result.rows[0].amountCents,1200000);assert.equal(result.rows[0].components.rounding,'1');});
 await check('thermal invoices wait; owner costs excluded; override retains warning',()=>{const p={...payload,kind:'INVOICE' as const,lines:[{...payload.lines[0],service:'HEATING'}]};assert.equal(projectSettlementCosts([{...source,payload:p}],scope).rows.length,0);assert.match(projectSettlementCosts([{...source,payload:p}],scope).blockers.join(),/externí/);const owner={...payload,lines:[{...payload.lines[0],service:'INSURANCE'}]};assert.equal(projectSettlementCosts([{...source,payload:owner}],scope).rows.length,0);assert.equal(projectSettlementCosts([{...source,payload:{...owner,lines:[{...owner.lines[0],ownerOverride:true,ownerReason:'Syntetický doložený důvod'}]}}],scope).warnings.length,1);});
 await check('another unit or lease does not leak into results',()=>{assert.equal(projectSettlementCosts([source],{...scope,unitId:'other'}).rows.length,0);assert.equal(projectSettlementCosts([{...source,payload:{...payload,lines:[{...payload.lines[0],leaseId:'other'}]}}],scope).rows.length,0);});
 await check('partial periods and overlapping leases cannot silently receive whole-year costs',()=>{assert.equal(projectSettlementCosts([source],{...scope,from:'2025-06-01'}).rows.length,0);const overlapping={...scope,leases:[...scope.leases,{id:'other',from:'2025-06-01',to:null}]};assert.equal(projectSettlementCosts([source],overlapping).rows.length,0);assert.equal(projectSettlementCosts([{...source,payload:{...payload,lines:[{...payload.lines[0],leaseId:'lease'}]}}],overlapping).rows.length,1);});
 await check('unallocated house cost stays blocked; original cost links across revisions retained',()=>{assert.equal(projectSettlementCosts([{...source,payload:{...payload,mode:'HOUSE',unitId:'',lines:[{...payload.lines[0],unitId:''}]}}],scope).rows.length,0);assert.deepEqual([...projectSettlementCosts([{...source,payload:{...payload,propertyCostId:'old'}},{...source,version:2,payload:{...payload,propertyCostId:'new'}}],scope).replacedCostIds],['old','new']);});
 await check('credit note reduces cost once and independently of source components',()=>{const credit={...source,id:'credit',identityKey:'credit',payload:{...payload,kind:'CREDIT_NOTE' as const,creditForId:source.id,lines:[{...payload.lines[0],amount:'-1000'}]}};assert.equal(projectSettlementCosts([source,credit],scope).rows.reduce((n,r)=>n+r.amountCents,0),1100000);});
 if(process.argv.includes('--rules-only'))return;
 const url=process.env.DATABASE_URL;if(!url||!['localhost','127.0.0.1','postgres'].includes(new URL(url).hostname))throw new Error('Isolated local/CI database required');
 const db=new PrismaClient();try{
 const tag=`R24_AGENT_QA_2026_09 R26D ${crypto.randomUUID()}`;
 const user=await db.user.create({data:{name:tag,email:`${crypto.randomUUID()}@example.test`,passwordHash:'test',role:'SUPER_ADMIN',allProperties:true}}),actor={id:user.id,role:user.role,allProperties:true};
 const owner=await db.owner.create({data:{name:tag}}),property=await db.property.create({data:{ownerId:owner.id,name:tag,address:'Syntetická 26',city:'Praha'}}),unit=await db.unit.create({data:{propertyId:property.id,label:tag}}),tenant=await db.tenant.create({data:{name:tag}});
 const lease=await db.lease.create({data:{unitId:unit.id,tenantId:tenant.id,startDate:new Date('2025-01-01'),financialTrackingFromPeriod:'2025-01',variableSymbol:'26',rentCents:1000000,servicesCents:100000,autoChargesEnabled:false}});
 const asset=await db.fileAsset.create({data:{storageKey:tag,originalName:'synthetic.pdf',mimeType:'application/pdf',sizeBytes:10,sha256:tag,uploadedById:user.id}}),doc=await db.document.create({data:{propertyId:property.id,fileAssetId:asset.id,title:tag,category:'OTHER',createdById:user.id}});
 const cost=await db.propertyCost.create({data:{propertyId:property.id,unitId:unit.id,kind:"OPEX",status:"ACTUAL",category:"UTILITIES",title:tag,amountCents:1200000,effectiveAt:new Date("2025-06-01")}});
 const p={...payload,unitId:unit.id,lines:[{...payload.lines[0],unitId:unit.id,leaseId:lease.id}]};
 const original=await createSettlementSource(actor,property.id,p,doc.id);await confirmSettlementSource(actor,property.id,original.id,true,false);
 await check('preview and immutable protocol consume confirmed rows without any financial posting',async()=>{const preview=await loadServiceSettlementPreview(actor,lease.id,'2025-01-01','2025-12-31');assert.equal(preview.actualCostsCents,1200000);assert.equal(preview.costRows.length,1);assert.ok(preview.warnings.some(w=>w.includes('nepřičítají')));assert.equal(preview.evidenceRows[0].sourceId,original.id);assert.equal(preview.ready,false);const protocol=await issueServiceSettlementProtocol(actor,lease.id,{from:'2025-01-01',to:'2025-12-31',propertyId:property.id});const snapshot=parseServiceSettlementSnapshot(protocol.snapshot);assert.equal(snapshot.confirmedCosts?.[0].sourceId,original.id);assert.equal(snapshot.costBasis,'CONFIRMED_SOURCES');assert.equal(protocol.chargeId,null);assert.equal(protocol.creditId,null);const revision=await createSettlementSource(actor,property.id,{...p,supplyAmount:'15000',lines:[{...p.lines[0],amount:'15000'}],revisionReason:'Oprava syntetického kontrolního příkladu'},doc.id,original.id);await confirmSettlementSource(actor,property.id,revision.id,true,false);assert.equal((await loadServiceSettlementPreview(actor,lease.id,'2025-01-01','2025-12-31')).actualCostsCents,1500000);assert.equal(parseServiceSettlementSnapshot((await db.serviceSettlementProtocol.findUniqueOrThrow({where:{id:protocol.id}})).snapshot).totals.actualCostsCents,1200000);assert.equal(await db.charge.count({where:{leaseId:lease.id}}),0);});
 await check('unrelated actor cannot read preview',()=>assert.rejects(()=>loadServiceSettlementPreview({id:'stranger',role:'VIEWER'},lease.id,'2025-01-01','2025-12-31'),/přístup/));
 }finally{await db.$disconnect();}
}
main().then(()=>console.log(`R26D: ${checks} kontrol prošlo.`)).catch(e=>{console.error(e);process.exitCode=1;});
