import assert from "node:assert/strict";
import { addBillingPeriod, deriveEntitlement, freshDefaultConfig, makeContract, quoteContract, renewalStart, validateConfig, DAY_MS } from "../lib/subscriptions/policy";
import { subscriptionsSandboxEnabled } from "../lib/subscriptions/service";
let checks = 0;
function check(name: string, action: () => void) { action(); checks++; console.log(`✓ ${name}`); }
const config = freshDefaultConfig(); config.enabled = true;
const now = new Date("2026-10-10T10:00:00Z");
const profi = makeContract(config, "PROFI", 10);
const defaultInput = { contract: profi, config, paidUntil: new Date("2026-11-10T10:00:00Z"), trialUntil: null, offerKind: "NONE" as const, offerUntil: null, teamEligible: false, featuresOverride: {}, overridesUntil: null, usage: { units: 3, properties: 1 }, now };
check("default catalogue valid and Free portal policy independent of paid feature keys", () => { validateConfig(config); assert.equal(config.plans.FREE.includedUnits, 3); assert.equal(config.plans.FREE.maxProperties, 1); assert.equal(config.plans.FREE.features.paymentReceipts, false); });
check("Profi 249 incl10 and Enterprise990 incl50", () => { assert.equal(quoteContract(profi, "MONTHLY", { kind: "NONE", until: null, percent: 0, fixedCents: null }, now), 24900); assert.equal(quoteContract(makeContract(config, "ENTERPRISE", 50), "MONTHLY", { kind: "NONE", until: null, percent: 0, fixedCents: null }, now), 99000); });
check("additional units 25 /15 Kč and annual tenmonths", () => { assert.equal(quoteContract(makeContract(config, "PROFI", 25), "MONTHLY", { kind: "NONE", until: null, percent: 0, fixedCents: null }, now), 62400); assert.equal(quoteContract(makeContract(config, "ENTERPRISE", 100), "MONTHLY", { kind: "NONE", until: null, percent: 0, fixedCents: null }, now), 174000); assert.equal(quoteContract(profi, "ANNUAL", { kind: "NONE", until: null, percent: 0, fixedCents: null }, now), 249000); });
check("percent campaign expires to contracted normal price", () => { const offer = { kind: "PERCENT" as const, until: new Date("2026-10-11T10:00:00Z"), percent: 20, fixedCents: null }; assert.equal(quoteContract(profi, "MONTHLY", offer, now), 19920); assert.equal(quoteContract(profi, "MONTHLY", offer, offer.until), 24900); });
check("fixed campaign is monthly price and annual uses ten months", () => { assert.equal(quoteContract(profi, "ANNUAL", { kind: "FIXED", until: null, percent: 0, fixedCents: 19900 }, now), 199000); });
check("catalogue repricing leaves contracted amount unchanged", () => { const changed = structuredClone(config); changed.plans.PROFI.monthlyPriceCents = 49900; assert.equal(profi.plan.monthlyPriceCents, 24900); assert.equal(makeContract(changed, "PROFI", 10).plan.monthlyPriceCents, 49900); });
check("feature toggle is live despite price snapshot", () => { const changed = structuredClone(config); changed.plans.PROFI.features.reports = false; assert.equal(deriveEntitlement({ ...defaultInput, config: changed }).features.reports, false); });
check("valid individual override can enable feature and expires exactly", () => { const until = new Date("2026-10-11T10:00:00Z"); const changed = structuredClone(config); changed.plans.PROFI.features.reports = false; assert.equal(deriveEntitlement({ ...defaultInput, config: changed, featuresOverride: { reports: true }, overridesUntil: until }).features.reports, true); assert.equal(deriveEntitlement({ ...defaultInput, config: changed, featuresOverride: { reports: true }, overridesUntil: until, now: until }).features.reports, false); });
check("matching requires banking even with independent override", () => { assert.equal(deriveEntitlement({ ...defaultInput, featuresOverride: { bankNotifications: false, paymentMatching: true } }).features.paymentMatching, false); });
check("free limit applies both units and distinct objects", () => { const free = makeContract(config, "FREE", 100); assert.equal(deriveEntitlement({ ...defaultInput, contract: free, paidUntil: null, usage: { units: 3, properties: 1 } }).writable, true); assert.equal(deriveEntitlement({ ...defaultInput, contract: free, paidUntil: null, usage: { units: 4, properties: 1 } }).writable, false); assert.equal(deriveEntitlement({ ...defaultInput, contract: free, paidUntil: null, usage: { units: 3, properties: 2 } }).writable, false); });
check("expiry begins grace, seven complete days freeze exactly", () => { const expiry = new Date("2026-10-10T10:00:00Z"); assert.equal(deriveEntitlement({ ...defaultInput, paidUntil: expiry }).status, "GRACE"); assert.equal(deriveEntitlement({ ...defaultInput, paidUntil: expiry, now: new Date(expiry.getTime() + 7 * DAY_MS - 1) }).writable, true); assert.equal(deriveEntitlement({ ...defaultInput, paidUntil: expiry, now: new Date(expiry.getTime() + 7 * DAY_MS) }).status, "FROZEN"); });
check("grace renewal preserves expiry, late recovery starts current day", () => { const expiry = new Date("2026-10-09T10:00:00Z"); assert.equal(renewalStart(expiry, now, 7).toISOString(), expiry.toISOString()); assert.equal(renewalStart(expiry, new Date("2026-10-20T10:00:00Z"), 7).toISOString(), "2026-10-20T10:00:00.000Z"); });
check("month-end handles short months and leap years", () => { assert.equal(addBillingPeriod(new Date("2026-01-31T10:00:00Z"), "MONTHLY").toISOString(), "2026-02-28T10:00:00.000Z"); assert.equal(addBillingPeriod(new Date("2024-02-29T10:00:00Z"), "ANNUAL").toISOString(), "2025-02-28T10:00:00.000Z"); });
check("unpaid paid-account awaits payment and cannot write", () => { assert.equal(deriveEntitlement({ ...defaultInput, paidUntil: null }).status, "FROZEN"); });
check("trial period grants access without payment", () => { assert.equal(deriveEntitlement({ ...defaultInput, paidUntil: null, trialUntil: new Date("2026-11-01T10:00:00Z") }).status, "TRIAL"); });
check("expired trial fitting Free downgrades without debt", () => { const summary = deriveEntitlement({ ...defaultInput, paidUntil: null, trialUntil: now }); assert.equal(summary.status, "FREE"); assert.equal(summary.features.profi, false); assert.equal(summary.effectiveCapacityUnits, 3); });
check("expired trial over Free is frozen with Free effective capacity", () => { const summary = deriveEntitlement({ ...defaultInput, paidUntil: null, trialUntil: now, usage: { units: 4, properties: 1 } }); assert.equal(summary.status, "FROZEN"); assert.equal(summary.effectiveCapacityUnits, 3); assert.equal(summary.effectiveMaxProperties, 1); });
check("free offer has defined end and expires to Free", () => { assert.equal(deriveEntitlement({ ...defaultInput, paidUntil: null, offerKind: "FREE_UNTIL", offerUntil: new Date(now.getTime() + DAY_MS) }).status, "GIFTED"); assert.equal(deriveEntitlement({ ...defaultInput, paidUntil: null, offerKind: "FREE_UNTIL", offerUntil: now }).status, "FREE"); });
check("team flag alone cannot exempt external client", () => { assert.equal(deriveEntitlement({ ...defaultInput, paidUntil: null, offerKind: "TEAM", teamEligible: false }).status, "FROZEN"); assert.equal(deriveEntitlement({ ...defaultInput, paidUntil: null, offerKind: "TEAM", teamEligible: true }).status, "TEAM"); });
check("warning horizon follows admin reminders", () => { const changed = structuredClone(config); changed.reminderDays = [-2, 0, 5]; const soon = new Date(now.getTime() + 3 * DAY_MS); assert.equal(deriveEntitlement({ ...defaultInput, config: changed, paidUntil: soon }).reminder, null); assert.notEqual(deriveEntitlement({ ...defaultInput, paidUntil: soon }).reminder, null); });
check("invalid dependency config rejected", () => { const changed = structuredClone(config); changed.plans.FREE.features.paymentMatching = true; assert.throws(() => validateConfig(changed)); });
check("sandbox hard boundary rejects production and arbitrary public DB", () => {
  const keys = ["FLATBERRY_SUBSCRIPTIONS_SANDBOX", "RENDER_SERVICE_ID", "RENDER_GIT_BRANCH", "IS_SANDBOX", "DATABASE_URL"] as const;
  const saved = Object.fromEntries(keys.map(key => [key, process.env[key]]));
  try {
    process.env.FLATBERRY_SUBSCRIPTIONS_SANDBOX = "1"; delete process.env.IS_SANDBOX;
    process.env.RENDER_SERVICE_ID = "production-service"; process.env.RENDER_GIT_BRANCH = "main"; process.env.DATABASE_URL = "postgresql://host/flatcloud_ux_sandbox"; assert.equal(subscriptionsSandboxEnabled(), false);
    process.env.RENDER_SERVICE_ID = "srv-dacselkmqu1s73bmjoq0"; process.env.RENDER_GIT_BRANCH = "sandbox/ux-agent"; assert.equal(subscriptionsSandboxEnabled(), true);
    process.env.DATABASE_URL = "postgresql://host/production"; assert.equal(subscriptionsSandboxEnabled(), false);
    delete process.env.RENDER_SERVICE_ID; delete process.env.RENDER_GIT_BRANCH; process.env.DATABASE_URL = "postgresql://remote/flatcloud_ux_sandbox"; assert.equal(subscriptionsSandboxEnabled(), false);
    process.env.DATABASE_URL = "postgresql://postgres@127.0.0.1/local_qa"; assert.equal(subscriptionsSandboxEnabled(), true);
    process.env.IS_SANDBOX = "0"; assert.equal(subscriptionsSandboxEnabled(), false);
  } finally { for (const key of keys) if (saved[key] === undefined) delete process.env[key]; else process.env[key] = saved[key]; }
});
console.log(`${checks} subscription domain checks passed.`);
