import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path: string) => readFileSync(path, "utf8");
const packageJson = JSON.parse(read("package.json"));
const lock = JSON.parse(read("package-lock.json"));
const schema = read("prisma/schema.prisma");
const create = read("lib/lease-create.ts");
const tenantRoute = read("app/api/properties/[id]/tenants/route.ts");
const leaseRoute = read("app/api/properties/[id]/leases/route.ts");
const retention = read("lib/inbound-bank/retention.ts");
const sync = read("lib/inbound-bank/sync.ts");
const imap = read("lib/inbound-bank/imap.ts");
const scheduler = read("scripts/scheduler-cron.ts");
const reset = read("scripts/reset-test-tenants.ts");
const tenantsPage = read("app/najemnici/page.tsx");
const tenantDetail = read("app/najemnici/[tenantId]/page.tsx");
const newTenant = read("app/nemovitosti/[id]/najemnici/novy/page.tsx");
const settingsRoute = read("app/api/settings/inbound-mail/route.ts");
const migration = read("prisma/migrations/20260827100000_v21_4_inbound_mail_retention/migration.sql");
const ci = read(".github/workflows/ci.yml");

assert.equal(packageJson.version, "1.22.0");
assert.equal(lock.version, "1.22.0");
assert.equal(lock.packages[""].version, "1.22.0");
assert.equal(packageJson.scripts["verify:v21.3.6"], "tsx scripts/verify-v21-3-6.ts");
assert.equal(packageJson.scripts["verify:v21.4"], "tsx scripts/verify-v21-4.ts");
assert.match(ci, /npm run verify:v21\.4/);
for (const field of ["inboundMailResolvedRetentionDays", "inboundMailUnresolvedRetentionDays", "inboundMailUidValidity", "inboundMailLastCleanupAt", "inboundMailLastCleanupSummary", "imapUidValidity", "mailboxDeletedAt"]) assert.match(schema, new RegExp(field));
assert.match(tenantRoute, /createLeaseFromForm/);
assert.match(leaseRoute, /createLeaseFromForm/);
assert.match(tenantsPage, /leases: \{ where: leaseAccessWhere\(user\)/);
assert.match(tenantDetail, /leases: \{ where: leaseAccessWhere\(user\)/);
assert.match(newTenant, /showGenerateCharges/);
for (const rule of ["assertNoLeaseOverlap", "assertUniqueVariableSymbol", "propertyPaymentAccount.upsert", "syncUnitOccupancyCache", "syncLeaseCharges", "payerAccounts"]) assert.match(create, new RegExp(rule.replace(/[.]/g, "\\.")));
assert.match(retention, /imapUidValidity: settings\.inboundMailUidValidity/);
assert.match(retention, /imapMailboxIdentity: currentMailboxIdentity/);
assert.match(sync, /imapMailboxIdentity: currentMailboxIdentity/);
assert.match(migration, /imapMailboxIdentity/);
assert.match(settingsRoute, /inboundMailUidValidity: null/);
assert.match(retention, /BANK_EMAIL_RAW_RETENTION_DAYS = 100/);
assert.match(retention, /receivedAt: \{ lte: cutoff \}/);
assert.match(retention, /rawExcerpt: null, rawPurgedAt: now/);
assert.match(retention, /mailboxDeletedAt: null/);
assert.match(imap, /BODY\.PEEK/);
assert.match(imap, /UID EXPUNGE/);
assert.match(imap, /supportsUidExpunge/);
assert.match(scheduler, /mailbox-retention/);
assert.ok(scheduler.indexOf("bank-email") < scheduler.indexOf("mailbox-retention"));
assert.ok(scheduler.indexOf("mailbox-retention") < scheduler.indexOf("charges"));
assert.match(reset, /const apply = args\.includes\("--apply"\)/);
assert.match(reset, /ALLOW_TEST_TENANT_RESET !== "1"/);
assert.match(reset, /tenantIds\.length/);
assert.match(reset, /tenantIds\.includes\("\*"\)/);
assert.match(reset, /if \(!apply\) return/);
assert.match(reset, /bankTransaction\.update/);
assert.match(reset, /transaction\.amountCents/);
assert.match(reset, /suggestedLeaseId: null/);
assert.match(reset, /matchedRuleId: null/);
assert.match(reset, /OVERPAYMENT/);
assert.match(reset, /PARTIAL/);
assert.match(reset, /meterReading\.updateMany/);
assert.match(reset, /auditLog\.create/);
console.log("V21.4 verification passed.");
