import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { parseBankNotification } from "../lib/inbound-bank/bank-email";

const read = (path: string) => readFileSync(path, "utf8");
const property = read("app/nemovitosti/[id]/[section]/page.tsx");
const unit = read("app/nemovitosti/[id]/jednotky/[unitId]/page.tsx");
const ownerAccess = read("lib/owner-self-service.ts");
const ownerRoute = read("app/api/properties/[id]/owner-bank-account/route.ts");
const sync = read("lib/inbound-bank/sync.ts");
const reprocess = read("app/api/inbound-payments/[id]/reprocess/route.ts");
const ignore = read("app/api/inbound-payments/[id]/ignore/route.ts");
const queue = read("app/platby/nesparovane/page.tsx");
const detail = read("app/platby/nesparovane/email/[id]/page.tsx");
const subnav = read("components/PropertySubnav.tsx");
const packageJson = JSON.parse(read("package.json"));
const css = read("app/globals.css");

assert.match(property, /unit\.property\.name} – \{use\.unit\.label/);
assert.match(property, /orderBy: \[\{ unit: \{ property: \{ name: "asc"/);
assert.match(unit, /\/banka\$\{ownershipPaymentAccount\?`#ucet-/);
assert.match(ownerAccess, /user\.role !== "OWNER_VIEWER"/);
assert.match(ownerAccess, /email: \{ not: null \}/);
assert.match(ownerAccess, /userAccesses: \{ some: \{ userId \} \}/);
assert.match(ownerAccess, /memberships: \{ some: \{ userId \} \}/);
assert.match(ownerAccess, /exact\.length !== 1/);
assert.match(ownerAccess, /assignedAccountIds/);
assert.match(ownerAccess, /id: \{ in: assignedAccountIds \}, ownerId: owner\.id/);
assert.match(ownerRoute, /requireOwnedAccount\(user, propertyId, accountId\)/);
assert.match(ownerRoute, /form\.getAll\("unitIds"\)/);
assert.match(ownerRoute, /!accountId && !selectedUnitIds\.length/);
assert.match(ownerRoute, /selectedUnitIds\.some\(\(unitId\) => !authorizedByUnitId\.has\(unitId\)\)/);
assert.doesNotMatch(ownerRoute, /unitOwnership\.updateMany/);
assert.match(ownerRoute, /for \(const unitId of selectedUnitIds\)/);
assert.match(ownerRoute, /ownership\.ownerId !== scope\.id/);
assert.match(ownerRoute, /leaseStatusAt\(lease\) !== "ENDED"/);
assert.match(ownerRoute, /assertUniqueVariableSymbol\(tx, savedAccount\.id, lease\.variableSymbol, lease\.id\)/);
assert.ok(ownerRoute.indexOf("assertUniqueVariableSymbol") < ownerRoute.indexOf("tx.unitOwnership.update"));
assert.match(ownerRoute, /ownerBankAccountId: savedAccount\.id/);
assert.match(ownerRoute, /notificationVerifiedAt: null/);
assert.match(ownerRoute, /normalizeAccountNumber\(previous\.accountNumber\)/);
assert.match(ownerRoute, /normalizeBankCode\(previous\.bankCode\)/);
assert.match(ownerRoute, /normalizeIban\(previous\.iban\)/);
assert.doesNotMatch(ownerRoute, /previous\.label !== account\.label/);
assert.match(property, /name="unitIds"/);
assert.match(property, /defaultChecked=\{ownerScope\.unitOwnerships\.length===1\}/);
assert.match(property, /section === "banka" && !ownerBankView/);
assert.match(property, /Pokročilá pravidla/);
assert.match(property, /Česká spořitelna/);
assert.match(property, /několik minut/);
assert.match(property, /platby@flatcloud\.cz/);

const irrelevant = parseBankNotification({ subject: "Pozvánka", from: "office@example.com", text: "Dobrý den, posíláme zápis ze schůzky." });
assert.equal(irrelevant.bankLike, false);
const incompleteBank = parseBankNotification({ subject: "Fwd: notifikace", from: "owner@example.com", text: "Příchozí platba, částka 2 500,00 Kč, VS 12345" });
assert.equal(incompleteBank.recognizedPayment, false);
assert.equal(incompleteBank.bankLike, true);
assert.match(sync, /parsedPayment\.bankLike \? "ERROR" : "IGNORED"/);
assert.match(sync, /Nerelevantní e-mail: zpráva neobsahuje/);
assert.match(reprocess, /parsed\.recognizedPayment \? "RECEIVED" : forceReview \|\| parsed\.bankLike \? "ERROR" : "IGNORED"/);
assert.match(reprocess, /!parsed\.recognizedPayment && !parsed\.bankLike && !forceReview/);
assert.match(reprocess, /Nerelevantní e-mail: zpráva neobsahuje/);
assert.match(ignore, /parseBankNotification/);
assert.match(ignore, /const bankLike = parsed\.bankLike \|\| row\.bank !== "UNKNOWN"/);
assert.match(ignore, /bankLike \? manualNote : `Nerelevantní e-mail:/);
assert.match(queue, /status: \{ in: \["RECEIVED", "UNMATCHED", "ERROR"\] \}/);
assert.match(queue, /Nerelevantní e-maily/);
assert.match(queue, /take: 100/);
assert.match(queue, /transactions\.length \+ inbox\.length/);
assert.match(detail, /Znovu zpracovat \/ vrátit ke kontrole/);

assert.match(property, /google\.com\/maps\/search\/\?api=1&query=\$\{encodeURIComponent/);
assert.match(property, /Správce budovy/);
assert.doesNotMatch(property, /compact-manager[\s\S]{0,300}\/uzivatele\//);
assert.match(property, /contact-preview-card/);
assert.match(css, /\.contact-preview-card/);
assert.match(property, /activity-thread/);
assert.match(property, /COLLECTION_TASK_CREATED:"Vytvořen úkol pro vymáhání"/);
assert.match(css, /\.activity-content p\{font-size:13px/);
assert.match(css, /\.archived-property-row td:nth-child\(3\)/);
assert.match(subnav, /\["banka","Bankovní účet"\]/);
assert.equal(packageJson.scripts["verify:v21.3.5"], "tsx scripts/verify-v21-3-5.ts");
assert.equal(packageJson.scripts["verify:v21.3.6"], "tsx scripts/verify-v21-3-6.ts");
assert.match(css, /\.contact-preview-card strong\{font-size:13px\}/);
assert.match(css, /\.contact-preview-card small,\.contact-preview-card span\{font-size:11px/);
assert.match(css, /\.contact-preview-card a\{[^}]*font-size:11px/);
assert.equal((property.match(/<BankNotificationGuide mailbox=\{bankSettings/g) || []).length, 2);
assert.doesNotMatch(property, /bank-guide-update/);

console.log("V21.3.6 verification passed.");
