import assert from "node:assert/strict";import {readFileSync} from "node:fs";import {parseDistributionReportPeriod} from "../lib/distribution/reporting";
const read=(path:string)=>readFileSync(path,"utf8");let checks=0;function check(name:string,run:()=>void){run();checks++;console.log(`✓ ${checks}. ${name}`)}
check("quarter and annual periods have deterministic Prague business boundaries",()=>{const quarter=parseDistributionReportPeriod("2025-Q2");assert.equal(quarter.key,"2025-Q2");assert.equal(quarter.from.toISOString(),"2025-03-31T22:00:00.000Z");assert.equal(quarter.to.toISOString(),"2025-06-30T21:59:59.999Z");const year=parseDistributionReportPeriod("2025");assert.equal(year.quarter,null);assert.equal(year.label,"Rok 2025");assert.equal(parseDistributionReportPeriod("bad",new Date("2026-09-04T12:00:00Z")).key,"2026-Q3")});
check("loader is internal and consolidated-scope only",()=>{const source=read("lib/distribution/reporting.ts");for(const marker of ["canSeeAll(actor.role)","flatcloudConsolidationBasisPoints:{gt:0}","scopeLabel:\"Potvrzená aktiva FlatCloud · LIVE stav\""])assert.match(source,new RegExp(marker.replace(/[()]/g,"\\$&")))});
check("period activity and live stage are not conflated",()=>{const source=read("lib/distribution/reporting.ts"),page=read("app/distribuce/reporting/page.tsx");assert.match(source,/createdAt>=period\.from&&item\.createdAt<=period\.to/);for(const marker of ["Stav ratingů, valuací a pipeline je LIVE","období omezuje nově založené příležitosti","Bez PII a bez historizace fáze"])assert.match(page,new RegExp(marker))});
check("shareholder CSV contains aggregates without prospect PII",()=>{const route=read("app/api/distribution/report.csv/route.ts");for(const marker of ["requireUser()","loadDistributionReport","LIVE fáze pipeline","export bez osobních údajů","private, no-store"])assert.match(route,new RegExp(marker.replace(/[()]/g,"\\$&")));assert.doesNotMatch(route,/\.email|\.phone|prospect\.name/)});
check("quality gaps remain visible by property",()=>{const source=read("lib/distribution/reporting.ts"),page=read("app/distribuce/reporting/page.tsx");for(const marker of ["Chybí rating","Chybí valuace","Připraveno bez valuace"])assert.match(source,new RegExp(marker));assert.match(page,/mezer v ratingu, valuaci nebo připravenosti/)});
check("pipeline methodology browser smoke and CI cover R6D",()=>{assert.match(read("UX-REMODEL-PIPELINE.md"),/R6D implementováno bez migrace/);assert.match(read("lib/methodology.ts"),/slug: "reporting-distribuce"/);assert.match(read("e2e/flatcloud.smoke.spec.ts"),/distribuční podklad odděluje LIVE stav/);assert.match(read(".github/workflows/ci.yml"),/verify:ux-remodel-r6d/)});
console.log(`UX remodel R6D ověřen: ${checks} kontrol.`);
