import assert from "node:assert/strict";
import { crmToday, filterProspectOverview, nextActionState, prospectFilters, type OverviewOpportunity, type OverviewProspect } from "../lib/distribution/prospect-overview";
const today = "2026-09-21";
const opportunity = (id: string, property: string, stage: OverviewOpportunity["stage"], day: string | null): OverviewOpportunity => ({ id, stage, nextActionAt: day ? new Date(`${day}T00:00:00Z`) : null, unit: { id, label: id, property: { id: property, name: property } } });
const prospect = (id: string, opportunities: OverviewOpportunity[]): OverviewProspect => ({ id, name: `Žaneta ${id}`, email: `${id}@example.test`, phone: null, source: "Doporučení", note: "Zavolat", opportunities });
const contacts = [prospect("multi", [opportunity("a", "house-a", "VIEWING", "2026-09-21"), opportunity("b", "house-b", "OFFER", "2026-09-20"), opportunity("closed", "house-a", "WON", "2026-09-20"), opportunity("no-date", "house-a", "NEW", null), opportunity("next-week", "house-a", "NEW", "2026-09-28"), opportunity("later", "house-a", "NEW", "2026-09-29")]), prospect("empty", [])];
const filter = (query: Record<string, string>) => filterProspectOverview(contacts, prospectFilters(query), today);
assert.equal(filter({ q: "zaneta" }).length, 2);
assert.deepEqual(filter({ propertyId: "house-a", stage: "OFFER" }), [], "different opportunities must not satisfy different predicates");
assert.deepEqual(filter({ propertyId: "house-b", unitId: "a" }), []);
assert.deepEqual(filter({ unassigned: "1" }).map(p => p.id), ["empty"]);
assert.deepEqual(filter({ unassigned: "1", stage: "NEW" }), [], "filtering must not manufacture unassigned contacts");
assert.deepEqual(filter({ due: "today" })[0].opportunities.map(o => o.id), ["a"]);
assert.deepEqual(filter({ due: "overdue" })[0].opportunities.map(o => o.id), ["b"]);
assert.deepEqual(filter({ due: "missing" })[0].opportunities.map(o => o.id), ["no-date"]);
assert.deepEqual(filter({ due: "week" })[0].opportunities.map(o => o.id), ["next-week"]);
assert.equal(filter({ stage: "WON" })[0].opportunities.length, 1);
assert.deepEqual(filter({ due: "unknown" }), []);
assert.deepEqual(filter({ q: "does not exist" }), []);
assert.equal(contacts[0].opportunities.length, 6, "filter leaves original summaries unchanged");
assert.equal(nextActionState(contacts[0].opportunities[0], today), "today");
assert.equal(crmToday(new Date("2026-09-20T22:30:00Z")), today, "Czech day can already be tomorrow in UTC");
assert.equal(crmToday(new Date("2026-12-31T23:30:00Z")), "2027-01-01");
assert.equal(prospectFilters({q:["a","b"]}).q, "");
console.log("P07A: combined filters, independent contacts, closed stages and Czech calendar boundaries passed (17 checks).");
