import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
import { validateSource,emptySourceLine,lineReadiness } from '../lib/settlement-source-rules';
import { createSettlementSource,confirmSettlementSource,sourceAccess } from '../lib/settlement-sources';
const base={schemaVersion:1,mode:'HOUSE',kind:'INVOICE',vendor:'R24_AGENT_QA_2026_09 Dodavatel',reference:'INV-1',from:'2025-01-01',to:'2025-12-31',supplyAmount:'120000',supplierAdvances:'100000',unitId:'',creditForId:'',propertyCostId:'',revisionReason:'',lines:[{...emptySourceLine('2025-01-01','2025-12-31'),amount:'120000'}]};
let checks=0;async function check(name:string,run:()=>unknown|Promise<unknown>){await run();console.log(`✓ ${++checks}. ${name}`);}
async function main(){
 await check('supply cost is preserved before supplier advances',()=>assert.equal(validateSource(base).supplyAmount,'120000'));
 await check('invoice remainder cannot substitute line cost',()=>assert.throws(()=>validateSource({...base,supplyAmount:'20000'}),/Součet/));
 await check('summary and component figures are not double counted',()=>{const line={...base.lines[0],base:'60000',consumptionComponent:'59999',rounding:'1',componentsComplete:true};assert.equal(validateSource({...base,lines:[line,{...line,key:'Summary',role:'SUMMARY',amount:'999999',base:'',consumptionComponent:'',rounding:'',componentsComplete:false}]}).lines.length,2);assert.throws(()=>validateSource({...base,lines:[{...line,rounding:'2'}]}),/složka/);assert.doesNotThrow(()=>validateSource({...base,lines:[{...line,consumptionComponent:'',componentsComplete:false}]}));});
 await check('duplicate row identifiers and invalid periods are rejected',()=>{assert.throws(()=>validateSource({...base,lines:[base.lines[0],base.lines[0]]}),/Duplicitní/);assert.throws(()=>validateSource({...base,from:'2025-02-30'}),/datum/);assert.throws(()=>validateSource({...base,lines:[{...base.lines[0],from:'2024-12-31'}]}),/uvnitř/);});
 await check('cross-period allocation needs evidence',()=>{assert.throws(()=>validateSource({...base,lines:[{...base.lines[0],from:'2025-06-01'}]}),/odůvodnění/);});
 await check('owner costs default to owner, pest control requires assessment, heat waits',()=>{for(const [service,label] of [['INSURANCE','Hradí vlastník'],['PEST_CONTROL','Čeká na individuální posouzení'],['HEATING','Čeká na externí rozúčtování']]){const p=validateSource({...base,lines:[{...base.lines[0],service}]});assert.equal(lineReadiness(p,p.lines[0]),label);}assert.throws(()=>validateSource({...base,lines:[{...base.lines[0],service:'INSURANCE',ownerOverride:true}]}),/odůvodnění/);});
 if(process.argv.includes('--rules-only'))return;
 const url=process.env.DATABASE_URL;if(!url||!['localhost','127.0.0.1','postgres'].includes(new URL(url).hostname))throw new Error('Isolated local/CI database required');
 const db=new PrismaClient();try{
 const tag=`R24_AGENT_QA_2026_09 R26B ${crypto.randomUUID()}`;const user=await db.user.create({data:{name:tag,email:`${crypto.randomUUID()}@example.test`,passwordHash:'test',role:'SUPER_ADMIN',allProperties:true}}),actor={id:user.id,role:user.role,allProperties:true};
 const owner=await db.owner.create({data:{name:tag}}),property=await db.property.create({data:{ownerId:owner.id,name:tag,address:'Syntetická 26',city:'Praha'}});const unit=await db.unit.create({data:{propertyId:property.id,label:tag}});
 const asset=await db.fileAsset.create({data:{storageKey:tag,originalName:'synthetic.pdf',mimeType:'application/pdf',sizeBytes:10,sha256:tag,uploadedById:user.id}});const doc=await db.document.create({data:{propertyId:property.id,fileAssetId:asset.id,title:tag,category:'OTHER',createdById:user.id}});
 const s=await createSettlementSource(actor,property.id,base,doc.id);
 await check('unconfirmed draft cannot be used as confirmed evidence',async()=>{assert.equal(s.confirmedAt,null);await assert.rejects(()=>confirmSettlementSource(actor,property.id,s.id,false,false),/Potvrďte/);});
 await check('confirmation is audited without financial writes',async()=>{await confirmSettlementSource(actor,property.id,s.id,true,false);assert.equal(await db.charge.count({where:{lease:{unit:{propertyId:property.id}}}}),0);assert.equal(await db.leaseCredit.count({where:{lease:{unit:{propertyId:property.id}}}}),0);assert.equal(await db.auditLog.count({where:{entityId:s.id,action:'SETTLEMENT_SOURCE_CONFIRMED'}}),1);});
 await check('confirmed source and draft content are immutable',async()=>{await assert.rejects(()=>db.settlementSource.update({where:{id:s.id},data:{payload:{}}}),/immutable/);await assert.rejects(()=>db.settlementSource.delete({where:{id:s.id}}),/immutable/);});
 await check('duplicate original/reference and simultaneous submissions are protected',async()=>{await assert.rejects(()=>createSettlementSource(actor,property.id,base,doc.id),/Duplicitní/);const results=await Promise.allSettled([1,2].map(()=>createSettlementSource(actor,property.id,{...base,reference:'CONCURRENT'},null)));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const alias=await createSettlementSource(actor,property.id,{...base,reference:'ALIAS'},doc.id);await assert.rejects(()=>confirmSettlementSource(actor,property.id,alias.id,true,false),/originál/);});
 await check('append-only revision preserves previous evidence',async()=>{const revision=await createSettlementSource(actor,property.id,{...base,revisionReason:'Oprava přepisu podle originálu'},doc.id,s.id);assert.equal(revision.version,2);await confirmSettlementSource(actor,property.id,revision.id,true,false);assert.ok((await db.settlementSource.findUniqueOrThrow({where:{id:s.id}})).confirmedAt);});
 await check('missing original, foreign scopes and view-only account fail closed',async()=>{const noDoc=await createSettlementSource(actor,property.id,{...base,reference:'MISSING'},null);await assert.rejects(()=>confirmSettlementSource(actor,property.id,noDoc.id,true,false),/originál/);await assert.rejects(()=>createSettlementSource(actor,property.id,{...base,reference:'FOREIGN',unitId:'other-unit'},null),/Jednotka/);await assert.rejects(()=>sourceAccess({id:'stranger',role:'VIEWER'},property.id),/oprávnění/);});
 await check('owner override requires separate explicit warning acknowledgement',async()=>{const ownerAsset=await db.fileAsset.create({data:{storageKey:tag+'owner',originalName:'owner.pdf',mimeType:'application/pdf',sizeBytes:10,sha256:tag+'owner',uploadedById:user.id}});const ownerDoc=await db.document.create({data:{propertyId:property.id,fileAssetId:ownerAsset.id,title:tag+'owner',category:'OTHER',createdById:user.id}});const source=await createSettlementSource(actor,property.id,{...base,reference:'OWNER',lines:[{...base.lines[0],service:'INSURANCE',ownerOverride:true,ownerReason:'Syntetické individuální posouzení titulu'}]},ownerDoc.id);await assert.rejects(()=>confirmSettlementSource(actor,property.id,source.id,true,false),/Náklad vlastníka/);await confirmSettlementSource(actor,property.id,source.id,true,true);});
 await check('external unit results retain components and exclude house summary',async()=>{const ext=await createSettlementSource(actor,property.id,{...base,kind:'EXTERNAL',mode:'EXTERNAL_UNIT',unitId:unit.id,reference:'ISTA',lines:[{...base.lines[0],service:'HEATING',base:'60000',consumptionComponent:'60000',componentsComplete:true}]},null);assert.equal((ext.payload as any).lines[0].base,'60000');});
 await check('credit notes require negative reconciled amounts and a confirmed invoice',async()=>{const c=await createSettlementSource(actor,property.id,{...base,kind:'CREDIT_NOTE',reference:'CREDIT',creditForId:s.id,supplyAmount:'-100',lines:[{...base.lines[0],amount:'-100'}]},null);assert.equal((c.payload as any).supplyAmount,'-100');});
 await check('archived history remains readable and no longer writable',async()=>{await db.property.update({where:{id:property.id},data:{active:false}});assert.ok(await sourceAccess(actor,property.id));await assert.rejects(()=>createSettlementSource(actor,property.id,{...base,reference:'ARCHIVED'},null),/aktivní/);});
 }finally{await db.$disconnect();}
}
main().then(()=>console.log(`R26B: ${checks} kontrol prošlo.`)).catch(e=>{console.error(e);process.exitCode=1;});
