import Link from "next/link";
import { AlertTriangle, CheckCircle2, Download, FileSpreadsheet, Landmark, ReceiptText, WalletCards } from "lucide-react";
import { Shell } from "@/components/Shell";
import { MethodologyCallout } from "@/components/MethodologyCallout";
import { requireUser } from "@/lib/auth";
import { date, money } from "@/lib/format";
import { loadAnnualOwnerPackage, normalizeAnnualPackageYear } from "@/lib/reporting/annual-owner-package";
import { propertyCostCategories, propertyCostKinds } from "@/lib/asset-finance";

export const dynamic = "force-dynamic";
export default async function AnnualOwnerPackagePage({searchParams}:{searchParams:Promise<{ownerId?:string;year?:string}>}){
  const[user,query]=await Promise.all([requireUser(),searchParams]);const year=normalizeAnnualPackageYear(query.year);const data=await loadAnnualOwnerPackage(user,{ownerId:query.ownerId,year});const exportHref=data.selectedOwner?`/api/reports/annual-owner-package.csv?ownerId=${encodeURIComponent(data.selectedOwner.id)}&year=${year}`:null;
  return <Shell user={user}><div className="page annual-package-page"><div className="breadcrumb">Reporty › Roční podklady vlastníka</div><div className="page-title"><div><h1>Roční podklady vlastníka</h1><p>Příjmy, skutečné výdaje, doklady a kontrola úvěrů za uzavřený kalendářní rok.</p></div>{exportHref&&<Link className="primary" href={exportHref}><Download size={16}/> Stáhnout CSV</Link>}</div>
    <nav className="report-tabs" aria-label="Report Center views"><Link href="/reporty">Zpět na reporty</Link><Link className="active" href="/reporty/rocni-podklady">Roční podklady</Link></nav>
    <form className="card annual-package-filter" method="get"><label className="field"><span>Vlastník *</span><select name="ownerId" defaultValue={data.selectedOwner?.id||""} required><option value="">Vyberte vlastníka</option>{data.owners.map((owner)=><option value={owner.id} key={owner.id}>{owner.name}</option>)}</select></label><label className="field"><span>Rok *</span><input type="number" name="year" min="2000" max={new Date().getUTCFullYear()} defaultValue={year} required/></label><button className="primary" type="submit">Načíst podklady</button></form>
    {!data.selectedOwner?<div className="empty-state annual-package-empty"><FileSpreadsheet size={28}/><h2>Nejprve vyberte vlastníka</h2><p>Rozsah se skládá pouze z nemovitostí a jednotek, ke kterým máte přístup. Balíček nepoužívá konsolidační podíl FlatCloud.</p></div>:<>
      <div className={`notice annual-readiness ${data.ready?"ok":"warn"}`}>{data.ready?<CheckCircle2 size={20}/>:<AlertTriangle size={20}/>}<div><strong>{data.ready?"Podklady nemají blokátor":"Podklady vyžadují doplnění"}</strong><span>{data.ready?"Před předáním účetnímu ještě proveďte odbornou kontrolu kategorizace.":"CSV lze stáhnout jako pracovní seznam, ale nesmí působit jako hotové daňové přiznání."}</span></div></div>
      <div className="stat-grid v21-stat-grid annual-package-kpis"><Stat label="Přijaté úhrady" value={money(data.totals.incomeCents)} icon={<WalletCards/>}/><Stat label="Z toho nájemné" value={money(data.totals.rentIncomeCents)} icon={<Landmark/>}/><Stat label="Skutečné výdaje" value={money(data.totals.expenseCents)} icon={<ReceiptText/>}/><Stat label="Pracovní rozdíl" value={money(data.totals.differenceCents)} icon={<FileSpreadsheet/>}/></div>
      <div className="notice"><strong>Co čísla znamenají</strong><span>Cash příjmy vycházejí z data bankovní transakce a přiřazené částky. Kauce ({money(data.totals.depositIncomeCents)}) jsou z pracovního rozdílu vyloučené. Výdaje obsahují jen stav Skutečnost. Nejde o automatické stanovení základu daně.</span></div>
      {data.issues.length>0&&<section className="card annual-issues"><div className="card-head"><div><h2>Kontrola úplnosti</h2><p className="muted-copy">{data.issues.filter((issue)=>issue.severity==="BLOCKER").length} blokátorů · {data.issues.filter((issue)=>issue.severity==="WARNING").length} upozornění</p></div></div><div className="stack-list">{data.issues.map((issue)=><div className={`annual-issue ${issue.severity==="BLOCKER"?"bad":"warn"}`} key={issue.code}><AlertTriangle size={17}/><span><strong>{issue.severity==="BLOCKER"?"Blokátor":"Ověřit"}</strong>{issue.message}</span>{issue.href&&<Link className="table-link" href={issue.href}>Doplnit</Link>}</div>)}</div></section>}
      <section className="card portfolio-table-card"><div className="table-toolbar"><div><h2>Přijaté úhrady</h2><p>Částky jsou rozdělené podle skladby předpisu a současného podílu vlastníka.</p></div></div><div className="table-wrap"><table><thead><tr><th>Datum</th><th>Nemovitost / jednotka</th><th>Nájemník</th><th>Přijato</th><th>Podíl vlastníka</th><th>Nájemné</th><th>Služby</th><th>Kauce</th><th>Ostatní</th></tr></thead><tbody>{data.incomeRows.length?data.incomeRows.map((row)=><tr key={row.id}><td>{date(row.bookedAt)}</td><td><strong>{row.propertyName} · {row.unitLabel}</strong><span className="owner-sub">VS {row.variableSymbol||"—"}</span></td><td>{row.tenantName}</td><td>{money(row.receivedCents)}</td><td><strong>{money(row.ownerAmountCents)}</strong><span className="owner-sub">{row.allocationNote}</span></td><td>{money(row.rentCents)}</td><td>{money(row.servicesCents)}</td><td>{money(row.depositCents)}</td><td>{money(row.otherCents)}</td></tr>):<tr><td colSpan={9} className="table-empty">Bez přiřazených úhrad v tomto roce.</td></tr>}</tbody></table></div></section>
      <section className="card portfolio-table-card"><div className="table-toolbar"><div><h2>Skutečné výdaje</h2><p>Doklady pokrývají {money(data.totals.documentedExpenseCents)} z {money(data.totals.expenseCents)} přiřazených výdajů.</p></div></div><div className="table-wrap"><table><thead><tr><th>Datum</th><th>Nemovitost</th><th>Náklad</th><th>Typ / kategorie</th><th>Zdrojová částka</th><th>Podíl vlastníka</th><th>Doklad</th></tr></thead><tbody>{data.expenseRows.length?data.expenseRows.map((row)=><tr key={row.id}><td>{date(row.effectiveAt)}</td><td>{row.propertyName}</td><td><Link className="entity-link" href={`/nemovitosti/${row.propertyId}/naklady/${row.id}`}>{row.title}</Link><span className="owner-sub">{row.allocationNote}</span></td><td>{propertyCostKinds[row.kind as keyof typeof propertyCostKinds]} · {propertyCostCategories[row.category as keyof typeof propertyCostCategories]}</td><td>{money(row.sourceAmountCents)}</td><td><strong>{money(row.ownerAmountCents)}</strong></td><td><span className={`status ${row.documentCount?"ok":"warn"}`}>{row.documentCount?`${row.documentCount} souborů`:row.documentNumber||"Chybí"}</span></td></tr>):<tr><td colSpan={7} className="table-empty">Bez skutečných výdajů přiřazených tomuto vlastníkovi.</td></tr>}</tbody></table></div></section>
      <section className="card portfolio-table-card"><div className="table-toolbar"><div><h2>Úvěry a úroky</h2><p>Sazba a jistina slouží jen ke kontrole úplnosti. Skutečně zaplacený úrok musí mít samostatný účetní zdroj.</p></div></div><div className="table-wrap"><table><thead><tr><th>Nemovitost</th><th>Úvěr</th><th>Věřitel</th><th>Jistina dle evidence</th><th>Sazba</th><th>Stav k</th><th>Úrok zaplacený za rok</th></tr></thead><tbody>{data.loanRows.length?data.loanRows.map((row)=><tr key={row.id}><td>{row.propertyName}</td><td><strong>{row.label}</strong></td><td>{row.lender}</td><td>{money(row.outstandingPrincipalCents)}</td><td>{(row.annualInterestRateBps/100).toLocaleString("cs-CZ",{minimumFractionDigits:2})} %</td><td>{row.asOfDate?date(row.asOfDate):"Aktuální karta"}</td><td><span className="status warn">Nedoloženo</span><span className="owner-sub">{row.evidence}</span></td></tr>):<tr><td colSpan={7} className="table-empty">Bez aktivních úvěrů v dostupném rozsahu.</td></tr>}</tbody></table></div></section>
      <MethodologyCallout slug="rocni-podklady" compact/>
    </>}</div></Shell>;
}
function Stat({label,value,icon}:{label:string;value:string;icon:React.ReactNode}){return <div className="card stat"><div className="stat-icon blue">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}
