import { hasAllPropertyAccess } from "../auth";
import { businessDateKey } from "../calendar";

export type ReportingUser = { id: string; role: string; allProperties?: boolean; memberships?: Array<{ propertyId: string }>; unitMemberships?: Array<{ unitId: string; unit?: { propertyId: string } }>; reportingGroupMemberships?: Array<{ reportingGroupId: string; permission: string }> };
export type ReportingScope = { propertyIds: string[]; unitIds?: string[] };
export function reportingGroupsForUser(user: ReportingUser) { return user.reportingGroupMemberships || []; }
export function canViewReportingGroup(user: ReportingUser, groupId: string) { return user.role === "SUPER_ADMIN" || reportingGroupsForUser(user).some((membership) => membership.reportingGroupId === groupId); }
export function canEditReportingGroup(user: ReportingUser, groupId: string) { return user.role === "SUPER_ADMIN" || reportingGroupsForUser(user).some((membership) => membership.reportingGroupId === groupId && ["EDIT", "ADMIN"].includes(membership.permission)); }
export function reportingGroupPropertiesAt(group: { properties: Array<{ propertyId: string; effectiveFrom: Date; effectiveTo?: Date | null }> }, asOf: Date) { const asOfKey = businessDateKey(asOf); return group.properties.filter((property) => businessDateKey(property.effectiveFrom) <= asOfKey && (!property.effectiveTo || businessDateKey(property.effectiveTo) >= asOfKey)); }
export function availableAppContexts(user: ReportingUser): Array<"RENT" | "SHAREHOLDER_REPORTING"> { const contexts: Array<"RENT" | "SHAREHOLDER_REPORTING"> = []; if (hasAllPropertyAccess(user) || user.memberships?.length || user.unitMemberships?.length) contexts.push("RENT"); if (user.role === "SUPER_ADMIN" || user.reportingGroupMemberships?.length) contexts.push("SHAREHOLDER_REPORTING"); return contexts; }
/** A requested property is always an intersection with, never an expansion of, the user's Rent grants. */
export function reportingScopeForUser(user: ReportingUser, requestedPropertyId?: string): ReportingScope { if (hasAllPropertyAccess(user)) return { propertyIds: requestedPropertyId ? [requestedPropertyId] : [] }; const propertyIds = [...new Set((user.memberships || []).map((membership) => membership.propertyId))]; const unitAccess = (user.unitMemberships || []).filter((membership) => !requestedPropertyId || membership.unit?.propertyId === requestedPropertyId); const allowedProperties = requestedPropertyId ? propertyIds.filter((id) => id === requestedPropertyId) : propertyIds; return { propertyIds: allowedProperties, ...(unitAccess.length ? { unitIds: unitAccess.map((membership) => membership.unitId) } : {}) }; }
