import { hasAllPropertyAccess } from "../auth";
import { businessDateKey } from "../calendar";
import type { Prisma } from "@prisma/client";

export type ReportingUser = { id: string; role: string; allProperties?: boolean; memberships?: Array<{ propertyId: string }>; unitMemberships?: Array<{ unitId: string; unit?: { propertyId: string } }>; reportingGroupMemberships?: Array<{ reportingGroupId: string; permission: string }> };
export type ReportingScope = { mode: "ALL" } | { mode: "SCOPED"; wholePropertyIds: string[]; unitIds: string[] };
export function reportingGroupsForUser(user: ReportingUser) { return user.reportingGroupMemberships || []; }
export function canViewReportingGroup(user: ReportingUser, groupId: string) { return user.role === "SUPER_ADMIN" || reportingGroupsForUser(user).some((membership) => membership.reportingGroupId === groupId); }
export function canEditReportingGroup(user: ReportingUser, groupId: string) { return user.role === "SUPER_ADMIN" || reportingGroupsForUser(user).some((membership) => membership.reportingGroupId === groupId && ["EDIT", "ADMIN"].includes(membership.permission)); }
export function canAdminReportingGroup(user: ReportingUser, groupId: string) { return user.role === "SUPER_ADMIN" || reportingGroupsForUser(user).some((membership) => membership.reportingGroupId === groupId && membership.permission === "ADMIN"); }
export function reportingGroupPropertiesAt<T extends { propertyId: string; effectiveFrom: Date; effectiveTo?: Date | null }>(group: { properties: T[] }, asOf: Date): T[] { const asOfKey = businessDateKey(asOf); return group.properties.filter((property) => businessDateKey(property.effectiveFrom) <= asOfKey && (!property.effectiveTo || businessDateKey(property.effectiveTo) >= asOfKey)); }
export function availableAppContexts(user: ReportingUser): Array<"RENT" | "SHAREHOLDER_REPORTING"> { const contexts: Array<"RENT" | "SHAREHOLDER_REPORTING"> = []; if (hasAllPropertyAccess(user) || user.memberships?.length || user.unitMemberships?.length) contexts.push("RENT"); if (user.role === "SUPER_ADMIN" || user.reportingGroupMemberships?.length) contexts.push("SHAREHOLDER_REPORTING"); return contexts; }
/** A requested property is always an intersection with, never an expansion of, the user's Rent grants. */
export function reportingScopeForUser(user: ReportingUser, requestedPropertyId?: string): ReportingScope { if (hasAllPropertyAccess(user) && !requestedPropertyId) return { mode: "ALL" }; if (hasAllPropertyAccess(user)) return { mode: "SCOPED", wholePropertyIds: [requestedPropertyId!], unitIds: [] }; const wholePropertyIds = [...new Set((user.memberships || []).map((membership) => membership.propertyId))].filter((propertyId) => !requestedPropertyId || propertyId === requestedPropertyId); const unitIds = [...new Set((user.unitMemberships || []).filter((membership) => !requestedPropertyId || membership.unit?.propertyId === requestedPropertyId).map((membership) => membership.unitId))]; return { mode: "SCOPED", wholePropertyIds, unitIds }; }

/** ALL deliberately returns no filter; empty SCOPED deliberately returns a match-nothing predicate. */
export function reportingUnitAccessWhere(scope: ReportingScope): Prisma.UnitWhereInput | undefined { if (scope.mode === "ALL") return undefined; const OR: Prisma.UnitWhereInput[] = []; if (scope.wholePropertyIds.length) OR.push({ propertyId: { in: scope.wholePropertyIds } }); if (scope.unitIds.length) OR.push({ id: { in: scope.unitIds } }); return OR.length ? { OR } : { id: { in: [] } }; }
export function reportingPropertyAccessWhere(scope: ReportingScope): Prisma.PropertyWhereInput | undefined { if (scope.mode === "ALL") return undefined; const OR: Prisma.PropertyWhereInput[] = []; if (scope.wholePropertyIds.length) OR.push({ id: { in: scope.wholePropertyIds } }); if (scope.unitIds.length) OR.push({ units: { some: { id: { in: scope.unitIds } } } }); return OR.length ? { OR } : { id: { in: [] } }; }
