import { prisma } from "@/lib/db";
import { hasAllPropertyAccess, previewContext } from "@/lib/auth";
import { guardKpiInputs } from "./kpi-completeness";
import { loadAssetFinanceKpis } from "./asset-finance-kpis";
import type { loadLiveReport } from "./live-service";
import { loadPortfolioSaleBenchmarks } from "./sale-benchmark";
import { csuDistrictForCity, selectCsuAverage } from "./csu-location";
function ratioBps(numerator:number|null,denominator:number|null){return numerator==null||denominator==null||denominator<=0?null:Math.round(numerator*10_000/denominator)}
/** Operational ownership scope only. FlatCloud consolidation is not used here. */
export async function loadGeneralKpis(user:{id:string;role:string;allProperties?:boolean}, data:Awaited<ReturnType<typeof loadLiveReport>>, asOf:Date, unitId?:string) {
  const permitted=new Set(data.memberships.map(row=>row.propertyId));
  const rows=unitId?[]:data.propertyRows.filter(row=>hasAllPropertyAccess(user)||permitted.has(row.property.id));
  const propertyIds=rows.map(row=>row.property.id);
  const inPreview=(await previewContext()).requested;
  const [finance,missingLoans,benchmarks,personalCheckpoints,csuAverages,csuIndex]=await Promise.all([loadAssetFinanceKpis(rows.map(row=>({...row,property:{...row.property,flatcloudConsolidationBasisPoints:10000}})),asOf),prisma.propertyLoan.findMany({where:{propertyId:{in:propertyIds},active:true,snapshots:{none:{asOfDate:{lte:asOf}}}},select:{propertyId:true}}),loadPortfolioSaleBenchmarks(propertyIds),inPreview?Promise.resolve([]):prisma.personalValueCheckpoint.findMany({where:{userId:user.id,unit:{propertyId:{in:propertyIds}},asOfDate:{lte:asOf}},orderBy:[{asOfDate:"desc"},{createdAt:"desc"}],select:{unitId:true,kind:true,valueCents:true}}),prisma.csuApartmentAverage.findMany({where:{territoryCode:{in:["CZ",...rows.flatMap(row=>{const district=csuDistrictForCity(row.property.city);return district?[district,district.slice(0,5)]:[]})]}},select:{territoryCode:true,sourcePeriod:true,pricePerSqmCents:true}}),prisma.csuApartmentPriceIndex.findFirst({where:{territoryCode:"CZ",OR:[{marketYear:{lt:asOf.getUTCFullYear()}},{marketYear:asOf.getUTCFullYear(),marketQuarter:{lte:Math.floor(asOf.getUTCMonth()/3)+1}}]},orderBy:[{marketYear:"desc"},{marketQuarter:"desc"}],select:{marketYear:true,marketQuarter:true,indexBasisPoints:true}})]);
  const missing=new Set(missingLoans.map(loan=>loan.propertyId));
  const missingRent = new Set(rows.filter(row => row.rentRoll.monthlyNetRentCents === null || row.units.unknownOperationalStatus > 0 || row.quality.some(issue => issue.code === "MISSING_RENT_SOURCE")).map(row => row.property.id));
  const benchmarkByProperty=new Map(benchmarks.map(row=>[row.propertyId,row]));
  const personalByUnit=new Map<string,{kind:string;valueCents:bigint}>();
  for(const checkpoint of personalCheckpoints){const existing=personalByUnit.get(checkpoint.unitId);if(!existing||existing.kind!=="OFFICIAL_APPRAISAL"&&checkpoint.kind==="OFFICIAL_APPRAISAL")personalByUnit.set(checkpoint.unitId,checkpoint)}
  const propertyRows = finance.propertyRows.map(row => {const guarded=guardKpiInputs(row,!missingRent.has(row.propertyId),!missing.has(row.propertyId)),benchmark=benchmarkByProperty.get(row.propertyId),benchmarkValueCents=benchmark?.benchmarkValueCents??null,benchmarkEquityCents=benchmarkValueCents==null||guarded.outstandingPrincipalCents==null?null:benchmarkValueCents-guarded.outstandingPrincipalCents;
    const property=rows.find(candidate=>candidate.property.id===row.propertyId)!;
    const district=csuDistrictForCity(property.property.city);
    const csu=selectCsuAverage(csuAverages,district,asOf.getUTCFullYear());
    const officialUnits=benchmark?.unitRows.map(unit=>unit.areaM2&&csu?Math.round(unit.areaM2*Number(csu.pricePerSqmCents)):null)||[];
    const csuValueCents=officialUnits.length&&officialUnits.every(value=>value!=null)&&Number.isSafeInteger(officialUnits.reduce((sum,value)=>sum+(value||0),0))?officialUnits.reduce((sum,value)=>sum+(value||0),0):null;
    const personalUnits=benchmark?.unitRows.map((unit,index)=>{const personal=personalByUnit.get(unit.id);return personal?Number(personal.valueCents):officialUnits[index]})||[];
    const personalValueCents=personalUnits.length&&personalUnits.every(value=>value!=null)&&Number.isSafeInteger(personalUnits.reduce((sum,value)=>sum+(value||0),0))?personalUnits.reduce((sum,value)=>sum+(value||0),0):null;
    return {...guarded,benchmarkValueCents,csuValueCents,csuSourcePeriod:csu?.sourcePeriod||null,csuTerritoryCode:csu?.territoryCode||null,personalValueCents,personalYieldBps:ratioBps(guarded.noiCents,personalValueCents),personalLtvBps:ratioBps(guarded.outstandingPrincipalCents,personalValueCents),personalOverrideCount:benchmark?.unitRows.filter(unit=>personalByUnit.has(unit.id)).length||0,benchmarkYieldBps:ratioBps(guarded.noiCents,benchmarkValueCents),benchmarkRoeBps:ratioBps(guarded.cashflowCents,benchmarkEquityCents),benchmarkLtvBps:ratioBps(guarded.outstandingPrincipalCents,benchmarkValueCents),benchmarkQoqBps:benchmark?.qoqBps??null,benchmarkConfidence:benchmark?.realized?.confidence??null,benchmarkMappingQuality:benchmark?.realized?.mappingQuality??null,benchmarkBaselinePartial:benchmark?.realized?.baselinePartial??false,benchmarkQuarter:benchmark?.realized?`${benchmark.realized.marketYear} Q${benchmark.realized.marketQuarter}`:null,benchmarkCoveredUnits:benchmark?.coveredUnits??0,benchmarkTotalUnits:benchmark?.totalUnits??0};});
  const guarded=guardKpiInputs(finance,missingRent.size===0,missing.size===0),benchmarkComplete=propertyRows.length>0&&propertyRows.every(row=>row.benchmarkValueCents!=null),benchmarkValueCents=benchmarkComplete?propertyRows.reduce((sum,row)=>sum+row.benchmarkValueCents!,0):null,benchmarkEquityCents=benchmarkValueCents==null||guarded.outstandingPrincipalCents==null?null:benchmarkValueCents-guarded.outstandingPrincipalCents;
  const personalComplete=propertyRows.length>0&&propertyRows.every(row=>row.personalValueCents!=null);
  const personalValueCents=personalComplete?propertyRows.reduce((sum,row)=>sum+row.personalValueCents!,0):null;
  const csuComplete=propertyRows.length>0&&propertyRows.every(row=>row.csuValueCents!=null);
  return {...guarded,propertyRows,benchmarkValueCents,csuValueCents:csuComplete?propertyRows.reduce((sum,row)=>sum+row.csuValueCents!,0):null,csuIndex,csuCoverageCount:propertyRows.filter(row=>row.csuValueCents!=null).length,personalValueCents,personalYieldBps:ratioBps(guarded.noiCents,personalValueCents),personalLtvBps:ratioBps(guarded.outstandingPrincipalCents,personalValueCents),personalOverrideCount:propertyRows.reduce((sum,row)=>sum+row.personalOverrideCount,0),benchmarkYieldBps:ratioBps(guarded.noiCents,benchmarkValueCents),benchmarkRoeBps:ratioBps(guarded.cashflowCents,benchmarkEquityCents),benchmarkLtvBps:ratioBps(guarded.outstandingPrincipalCents,benchmarkValueCents),benchmarkCoverageCount:propertyRows.filter(row=>row.benchmarkValueCents!=null).length,benchmarkComplete};
}
