import { prisma } from "../db";
import { businessDateKey, businessQuarter, quarterStartKey } from "../calendar";
import { applyPortfolioSelection, liveSelectedPropertyIds, type PortfolioSelection } from "../portfolio-selection";
import { effectiveLeaseEnd, leaseStatusAt } from "../lease-lifecycle-core";
import { securityDepositSnapshot } from "../security-deposit";
import { reportingPropertyAccessWhere, reportingScopeForUser, reportingUnitAccessWhere } from "./access";
import { calculatePropertySnapshot } from "./snapshot-calculator";
import { overdueDebtCentsAsOf, paidCentsAsOf } from "./finance";
import { rentRollAmountsAt } from "./rent-roll";

type User = { id: string; role: string; allProperties?: boolean };
const known = (value: number | null) => value ?? 0;
function recentPeriods(asOf: Date, count = 12) { const key = businessDateKey(asOf), [year, month] = key.split("-").map(Number); return Array.from({ length: count }, (_, index) => { const value = new Date(Date.UTC(year, month - count + index, 1, 12)); return value.toISOString().slice(0, 7); }); }

export async function loadLiveReport(user: User, selection: PortfolioSelection, asOf = new Date()) {
  const [memberships, unitMemberships] = await Promise.all([
    prisma.userProperty.findMany({ where: { userId: user.id }, select: { propertyId: true } }),
    prisma.userUnit.findMany({ where: { userId: user.id }, select: { unitId: true, unit: { select: { propertyId: true } } } }),
  ]);
  const baseScope = reportingScopeForUser({ ...user, memberships, unitMemberships });
  const unitPropertyIds = Object.fromEntries(unitMemberships.map((membership) => [membership.unitId, membership.unit.propertyId]));
  const availableProperties=await prisma.property.findMany({ where: reportingPropertyAccessWhere(baseScope), select: { id: true, name: true, address: true, city: true, active: true }, orderBy: { name: "asc" } });
  const livePropertyIds=liveSelectedPropertyIds(selection,availableProperties);
  const scope = applyPortfolioSelection(baseScope, {mode:"SELECTED",propertyIds:livePropertyIds}, unitPropertyIds);
  const [properties, units] = await Promise.all([
    prisma.property.findMany({ where: reportingPropertyAccessWhere(scope), select: { id: true, name: true, address: true, city: true, active: true }, orderBy: { name: "asc" } }),
    prisma.unit.findMany({ where: reportingUnitAccessWhere(scope), include: { property: { select: { id: true, name: true } }, operationalStatusEvents: { orderBy: [{ effectiveAt: "asc" }, { createdAt: "asc" }] }, leases: { include: { tenant: true, paymentItems: true, charges: { include: { items: true, allocations: { include: { transaction: true } }, securityDepositOffsets: true, creditApplications: true } }, securityDepositTerms: true, securityDepositMovements: true } } }, orderBy: [{ property: { name: "asc" } }, { label: "asc" }] }),
  ]);
  const propertyRows = properties.map((property) => { const propertyUnits = units.filter((unit) => unit.propertyId === property.id); const snapshot = calculatePropertySnapshot({ propertyId: property.id, asOf, units: propertyUnits }); return { property, ...snapshot.data, quality: snapshot.quality.issues }; });
  const allLeases = units.flatMap((unit) => unit.leases.map((lease) => ({ ...lease, unit })));
  const q = businessQuarter(asOf), quarterStart = quarterStartKey(q.year, q.quarter), asOfKey = businessDateKey(asOf), yearStart = `${q.year}-01-01`;
  const tenancyRows = allLeases.filter((lease) => leaseStatusAt(lease, asOf) === "ACTIVE").map((lease) => { const rent = rentRollAmountsAt(lease, asOf); const deposit = securityDepositSnapshot(lease, asOf); const debt = lease.charges.reduce((sum, charge) => sum + overdueDebtCentsAsOf(charge, asOf), 0); return { leaseId: lease.id, tenantId: lease.tenantId, tenantName: lease.tenant.name, propertyId: lease.unit.propertyId, propertyName: lease.unit.property.name, unitId: lease.unitId, unitLabel: lease.unit.label, areaM2: lease.unit.areaM2, startDate: lease.startDate, endDate: effectiveLeaseEnd(lease), netRentCents: rent.rent.amountCents, servicesCents: rent.services.amountCents, rentPerM2Cents: lease.unit.areaM2 && lease.unit.areaM2 > 0 ? Math.round(rent.rent.amountCents / lease.unit.areaM2) : null, agreedDepositCents: deposit.agreedAmountCents, heldDepositCents: deposit.heldPrincipalCents, debtCents: debt }; });
  const depositRows = allLeases.map((lease) => ({ lease, status: leaseStatusAt(lease, asOf), deposit: securityDepositSnapshot(lease, asOf) })).filter((row) => row.status === "ACTIVE" || row.deposit.status === "TO_SETTLE").map(({lease,status,deposit}) => ({ leaseId: lease.id, tenantName: lease.tenant.name, propertyName: lease.unit.property.name, unitLabel: lease.unit.label, leaseStatus: status, agreedCents: status === "ACTIVE" ? deposit.agreedAmountCents : 0, heldCents: deposit.heldPrincipalCents, missingCents: status === "ACTIVE" ? deposit.missingDepositCents : 0, depositStatus: deposit.status, amountToReturnCents: deposit.amountToReturnCents }));
  const contractRows = allLeases.map((lease) => { const status = leaseStatusAt(lease, asOf), end = effectiveLeaseEnd(lease); const endKey = end ? businessDateKey(end) : null; return { leaseId: lease.id, propertyName: lease.unit.property.name, propertyId: lease.unit.propertyId, unitLabel: lease.unit.label, unitId: lease.unitId, tenantName: lease.tenant.name, contractNumber: lease.contractNumber, startDate: lease.startDate, effectiveEnd: end, status, rentCents: rentRollAmountsAt(lease, asOf).rent.amountCents, depositCents: securityDepositSnapshot(lease, asOf).heldPrincipalCents, expiring90Days: status === "ACTIVE" && Boolean(endKey && endKey > asOfKey && endKey <= new Date(new Date(`${asOfKey}T12:00Z`).getTime() + 90 * 86_400_000).toISOString().slice(0,10)), endedYtd: status === "ENDED" && !lease.cancelledAt && Boolean(endKey && endKey >= yearStart && endKey <= asOfKey) }; });
  const periods = recentPeriods(asOf), trend = periods.map((period) => { const charges = allLeases.flatMap((lease) => lease.charges).filter((charge) => charge.active && charge.period === period); return { label: period, expected: charges.reduce((sum, charge) => sum + charge.amountCents, 0), paid: charges.reduce((sum, charge) => sum + paidCentsAsOf(charge, asOf), 0) }; });
  const aggregate = propertyRows.reduce((sum, row) => ({ rentable: sum.rentable + known(row.units.rentable), occupied: sum.occupied + known(row.units.occupied), vacant: sum.vacant + known(row.units.vacant), renovation: sum.renovation + known(row.units.renovation), inactive: sum.inactive + known(row.units.inactive), unknown: sum.unknown + row.units.unknownOperationalStatus, netRentCents: sum.netRentCents + known(row.rentRoll.monthlyNetRentCents), quarterExpectedCents: sum.quarterExpectedCents + known(row.collections.quarterExpectedCents), quarterPaidCents: sum.quarterPaidCents + known(row.collections.quarterPaidCents), overdueDebtCents: sum.overdueDebtCents + known(row.collections.overdueDebtCents), heldDepositCents: sum.heldDepositCents + known(row.deposits.heldPrincipalCents), agreedDepositCents: sum.agreedDepositCents + known(row.deposits.agreedCents), missingDepositCents: sum.missingDepositCents + known(row.deposits.missingCents), toSettleLeases: sum.toSettleLeases + known(row.deposits.toSettleLeases), activeLeases: sum.activeLeases + known(row.leases.active), futureLeases: sum.futureLeases + known(row.leases.future), expiring90Days: sum.expiring90Days + known(row.leases.expiring90Days), endedYtd: sum.endedYtd + known(row.leases.endedYtd) }), { rentable:0,occupied:0,vacant:0,renovation:0,inactive:0,unknown:0,netRentCents:0,quarterExpectedCents:0,quarterPaidCents:0,overdueDebtCents:0,heldDepositCents:0,agreedDepositCents:0,missingDepositCents:0,toSettleLeases:0,activeLeases:0,futureLeases:0,expiring90Days:0,endedYtd:0 });
  const validAreaTenancies = tenancyRows.filter((row) => row.areaM2 && row.areaM2 > 0), totalArea = validAreaTenancies.reduce((sum,row)=>sum+(row.areaM2||0),0);
  const qualityIssues = propertyRows.flatMap((row) => row.quality),newLeasesYtd=countNewLeasesYtd(allLeases,asOf);
  return { asOfDate: asOfKey, scope, availableProperties, properties, aggregate: { ...aggregate, occupancyBps: aggregate.rentable ? Math.round(aggregate.occupied * 10000 / aggregate.rentable) : null, collectionRateBps: aggregate.quarterExpectedCents ? Math.round(aggregate.quarterPaidCents * 10000 / aggregate.quarterExpectedCents) : null, weightedRentPerM2Cents: totalArea ? Math.round(validAreaTenancies.reduce((sum,row)=>sum+row.netRentCents,0)/totalArea) : null, averageActiveDays: tenancyRows.length ? Math.round(tenancyRows.reduce((sum,row)=>sum+Math.max(0,(new Date(`${asOfKey}T12:00Z`).getTime()-row.startDate.getTime())/86_400_000),0)/tenancyRows.length) : null, newLeasesYtd }, propertyRows, tenancyRows, depositRows, contractRows, trend, quality: qualityIssues, quarterStart };
}
export function countNewLeasesYtd(leases:Array<{startDate:Date;cancelledAt?:Date|null}>,asOf:Date){const asOfKey=businessDateKey(asOf),yearStart=`${asOfKey.slice(0,4)}-01-01`;return leases.filter(lease=>{const start=businessDateKey(lease.startDate);return start>=yearStart&&start<=asOfKey&&!(lease.cancelledAt&&lease.cancelledAt.getTime()<lease.startDate.getTime())}).length}
