import { businessDateKey, businessMonthKey, businessQuarter, quarterStartKey } from "../calendar";
import { leaseStatusAt } from "../lease-lifecycle-core";
import { securityDepositSnapshot } from "../security-deposit";
import { operationalStatusAt } from "../unit-operational-history";
import { paidCentsAsOf, overdueDebtCentsAsOf } from "./finance";
import type { ReportingQualityIssue } from "./data-quality";
import type { QuarterSnapshotData } from "./snapshot-schema";

type UnitInput = { id:string; areaM2:number|null; operationalStatusEvents:Array<{status:string;effectiveAt:Date;createdAt?:Date}>; leases:any[] };
export function calculatePropertySnapshot(input:{propertyId:string;asOf:Date;units:UnitInput[]}):{data:QuarterSnapshotData;quality:{issues:ReportingQualityIssue[]}} {
 const issues:ReportingQualityIssue[]=[]; let rentable=0,occupied=0,renovation=0,inactive=0,unknown=0,missingArea=0,net=0,services=0,rentableArea=0,occupiedArea=0,weightedRent=0,weightedArea=0;
 const activeLeases:any[]=[];
 for(const unit of input.units){const op=operationalStatusAt(unit.operationalStatusEvents,input.asOf);if(op.kind==="UNKNOWN_BEFORE_HISTORY"){unknown++;issues.push({code:"UNKNOWN_OPERATIONAL_HISTORY",severity:"WARNING",message:"Operational status is unknown at as-of date.",propertyId:input.propertyId,unitId:unit.id});continue} if(op.status==="RENOVATION"){renovation++;continue} if(op.status==="INACTIVE"){inactive++;continue} rentable++; const lease=unit.leases.find(l=>leaseStatusAt(l,input.asOf)==="ACTIVE");if(lease){occupied++;activeLeases.push(lease)} if(!unit.areaM2||unit.areaM2<=0){missingArea++;issues.push({code:"MISSING_UNIT_AREA",severity:"WARNING",message:"Unit has no usable area.",propertyId:input.propertyId,unitId:unit.id})}else{rentableArea+=unit.areaM2;if(lease)occupiedArea+=unit.areaM2}
  if(lease){const charge=lease.charges?.find((c:any)=>c.active&&c.period===businessMonthKey(input.asOf));const items=charge?.items?.length?charge.items:lease.paymentItems?.filter((i:any)=>i.active&&businessDateKey(i.validFrom)<=businessDateKey(input.asOf)&&(!i.validTo||businessDateKey(i.validTo)>=businessDateKey(input.asOf)));let rentItems=items?.filter((i:any)=>i.category==="RENT")||[];let serviceItems=items?.filter((i:any)=>i.category==="SERVICES")||[];let r=rentItems.reduce((s:number,i:any)=>s+i.amountCents,0),sv=serviceItems.reduce((s:number,i:any)=>s+i.amountCents,0);if(!items?.length){r=lease.rentCents;sv=lease.servicesCents;issues.push({code:"RENT_SOURCE_LEGACY_FALLBACK",severity:"WARNING",message:"Legacy current lease rent used as fallback.",propertyId:input.propertyId,unitId:unit.id,leaseId:lease.id})} if(!r)issues.push({code:"MISSING_RENT_SOURCE",severity:"WARNING",message:"No rent source at as-of date.",propertyId:input.propertyId,unitId:unit.id,leaseId:lease.id});net+=r;services+=sv;if(unit.areaM2&&unit.areaM2>0){weightedRent+=r;weightedArea+=unit.areaM2}}
 }
 if(!rentable)issues.push({code:"NO_RENTABLE_UNITS",severity:"INFO",message:"Property has no known rentable units.",propertyId:input.propertyId});
 const q=businessQuarter(input.asOf), qs=quarterStartKey(q.year,q.quarter);const charges=activeLeases.flatMap(l=>l.charges||[]).filter((c:any)=>c.active&&`${c.period}-01`>=qs&&`${c.period}-01`<=businessDateKey(input.asOf));const expected=charges.reduce((s:number,c:any)=>s+c.amountCents,0),paid=charges.reduce((s:number,c:any)=>s+paidCentsAsOf(c,input.asOf),0),overdue=activeLeases.flatMap(l=>l.charges||[]).reduce((s:number,c:any)=>s+overdueDebtCentsAsOf(c,input.asOf),0);
 let agreed=0,held=0,missing=0,funded=0,partial=0,unpaid=0,toSettle=0;for(const lease of activeLeases){const d=securityDepositSnapshot(lease,input.asOf);agreed+=d.agreedAmountCents;held+=d.heldPrincipalCents;missing+=d.missingDepositCents;if(d.status==="FUNDED")funded++;if(d.status==="PARTIAL")partial++;if(d.status==="UNPAID")unpaid++;if(d.status==="TO_SETTLE")toSettle++;if(d.status==="NOT_CONFIGURED")issues.push({code:"DEPOSIT_CONFIGURATION_WARNING",severity:"INFO",message:"Deposit is not configured.",propertyId:input.propertyId,leaseId:lease.id})}
 const data={source:"CALCULATED" as const,schemaVersion:1 as const,asOfDate:businessDateKey(input.asOf),units:{total:input.units.length,rentable,occupied,vacant:rentable-occupied,renovation,inactive,unknownOperationalStatus:unknown},rentRoll:{monthlyNetRentCents:net,monthlyServicesCents:services,monthlyTotalCents:net+services,rentableAreaM2:rentableArea,occupiedAreaM2:occupiedArea,weightedNetRentPerM2Cents:weightedArea?Math.round(weightedRent/weightedArea):0,missingAreaUnits:missingArea},collections:{quarterExpectedCents:expected,quarterPaidCents:paid,collectionRateBps:expected?Math.round(paid*10000/expected):null,overdueDebtCents:overdue},deposits:{agreedCents:agreed,heldPrincipalCents:held,missingCents:missing,fundedLeases:funded,partialLeases:partial,unpaidLeases:unpaid,toSettleLeases:toSettle},leases:{active:activeLeases.length,future:input.units.flatMap(u=>u.leases).filter(l=>leaseStatusAt(l,input.asOf)==="FUTURE").length,expiring90Days:0,endedYtd:0}} satisfies QuarterSnapshotData;return {data,quality:{issues}};
}
