import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { requirePropertyAccess } from "@/lib/access";
import { Shell } from "@/components/Shell";
import { Field, Flash, FormCard, FormPage, Select, Textarea } from "@/components/FormUi";
import { tenantTypes } from "@/lib/labels";
import { dateInput } from "@/lib/forms";

export const dynamic="force-dynamic";
export default async function NewTenant({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{ok?:string;error?:string}>}){const user=await requireUser();const {id}=await params;const [property,query]=await Promise.all([requirePropertyAccess(user,id),searchParams]);if(!property)notFound();const freeUnits=property.units.filter(unit=>!unit.leases.some(lease=>lease.status==="ACTIVE"));return <Shell user={user}><FormPage title="Nový nájemník a smlouva" description="Nájemník bude rovnou přiřazen ke konkrétní jednotce." backHref={`/nemovitosti/${id}/najemnici`}><Flash ok={query.ok} error={query.error}/>{freeUnits.length?<FormCard action={`/api/properties/${id}/tenants`} cancelHref={`/nemovitosti/${id}/najemnici`} submitLabel="Vytvořit nájemníka a smlouvu"><h2 className="form-section-title field-full">Nájemník</h2><Select label="Typ nájemníka" name="tenantType" options={Object.entries(tenantTypes)}/><Field label="Jméno / název firmy" name="name" required/><Field label="E-mail" name="email" type="email"/><Field label="Telefon" name="phone"/><Field label="Kontaktní adresa" name="tenantAddress" full/><Textarea label="Známé účty plátce" name="payerAccounts" placeholder="Jeden účet na řádek nebo oddělený čárkou"/><Textarea label="Poznámka k nájemníkovi" name="tenantNote"/><h2 className="form-section-title field-full">Nájemní smlouva</h2><Select label="Jednotka" name="unitId" required options={freeUnits.map(unit=>[unit.id,`${unit.label}${unit.floor?` · ${unit.floor}`:""}`])}/><Field label="Číslo smlouvy" name="contractNumber"/><Field label="Platnost od" name="startDate" type="date" defaultValue={dateInput(new Date())} required/><Field label="Platnost do" name="endDate" type="date"/><Select label="Stav smlouvy" name="leaseStatus" options={[["ACTIVE","Aktivní"],["FUTURE","Budoucí"]]}/><Field label="Den splatnosti" name="dueDay" type="number" min={1} max={31} defaultValue={5} required/><Field label="Variabilní symbol" name="variableSymbol" required/><Field label="Nájemné Kč / měsíc" name="rent" type="number" step="0.01" min={0} required/><Field label="Zálohy na služby Kč / měsíc" name="services" type="number" step="0.01" min={0}/><Field label="Kauce Kč" name="deposit" type="number" step="0.01" min={0}/><Textarea label="Poznámka ke smlouvě" name="leaseNote"/></FormCard>:<div className="card empty-state"><h2>Nejprve přidejte volnou jednotku</h2><p>V objektu není jednotka bez aktivní smlouvy.</p></div>}</FormPage></Shell>}
